# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Enabling Distributed Spatial Audio
#+SUBTITLE: Thesis Committee: Year 1
#+AUTHOR: Thomas Rushton
#+DATE: May 2024

#+EXPORT_FILE_NAME: out/report
#+OPTIONS: toc:nil ':t ^:{} num:1
#+LATEX_CLASS: report
#+BIBLIOGRAPHY: references.bib
#+CITE_EXPORT: biblatex
#+LATEX_HEADER: \RequirePackage[]{report-style}

* Latex Setup                                                      :noexport:
:PROPERTIES:
:HEADER-ARGS: :tangle out/report-style.sty :results silent
:END:

** Basics

#+begin_src latex
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{report-style}[2024/05/13 v0.1 Bundling Report LaTeX style]
#+end_src

** Packages

#+begin_src latex
\RequirePackage{subfig}
\RequirePackage[
  subfig,
  beramono,
  eulermath,
  pdfspacing
]{classicthesis}
\RequirePackage{arsclassica}
\RequirePackage{hyperref}
\RequirePackage[scale=0.95]{ebgaramond} % Probably not a good idea to override the font, but whatever.
\RequirePackage[T1]{fontenc} % Use 8-bit encoding that has 256 glyphs
\RequirePackage[utf8]{inputenc} % Required for including letters with accents
\RequirePackage{enumitem} % Required for manipulating the whitespace between and within lists
\RequirePackage{subfig} % Required for creating figures with multiple parts (subfigures)
\RequirePackage{amsmath,amssymb,amsthm} % For including math equations, theorems, symbols, etc
\RequirePackage{varioref} % More descriptive referencing
%% \RequirePackage{inconsolata}
#+end_src

** Typography

#+begin_src latex
%% \linespread{1.5}
\setkomafont{date}{\normalsize}
#+end_src

** Bibliography

#+begin_src latex
\PassOptionsToPackage{%
  %backend=biber,bibencoding=utf8, %instead of bibtex
%   backend=bibtex8,bibencoding=ascii,%
  language=auto,
  style=numeric-comp,
  %style=authoryear-comp, % Author 1999, 2010
  %bibstyle=authoryear,dashed=false, % dashed: substitute rep. author with ---
  % sorting=nyt, % name, year, title
  sorting=none,
  maxbibnames=10, % default: 3, et al.
  natbib=true, % natbib compatibility mode (\citep and \citet still work)
  url=false,
  doi=false,
  isbn=false
}{biblatex}
#+end_src

* Work Conducted

At the conclusion of my master's degree, I had developed a UDP
multicast server for audio and control data, running on a
general-purpose computer, and an accompanying ethernet network of
microcontroller based clients, running a distributed Wave Field
Synthesis algorithm written in the [[https://faust.grame.fr/][Faust]] programming language. Though
facing significant synchronicity challenges in the absence of an
authoritative source of time, the system gave the impression, under
experimentation, of producing perceptually plausible virtual sound
sources.

** Exploration of Raspberry Pi as an Alternative Hardware Platform
:PROPERTIES:
:CUSTOM_ID: rpi
:END:

The implementation upon which my master's thesis was based used the
[[https://www.pjrc.com/store/teensy41.html][Teensy 4.1]] microcontroller development board as its hardware
platform. While compuationally powerful, low-cost, and supported as a
Faust compilation target, teensy is limited in terms of on-board
memory --- a crucial resource in audio algorithms, particularly those
involving many or long delay lines --- and its audio add-on is only
capable of producing 16-bit audio output.

A platform not given serious consideration during work on my master's
thesis is the Raspberry Pi. Though typically run as a single-board
computer with a Linux operating system, it can be programmed to act as
something more akin to a microcontroller board via the /bare-metal/
C++ development environment, [[https://circle-rpi.readthedocs.io/en/46.0/][Circle]]. This potentially facilitates the
deployment of the Raspberry Pi, with its high-quality, I^{2}S sound
output, in timing-critical audio spatialisation applications.

Using the utility classes provided by Circle, I developed a
proof-of-concept networked audio client, similar to the JackTrip
client described in [cite:@rushton_microcontroller-based_2023]. The
choice to use JackTrip, and thus unicast UDP transmission, was
motivated by the fact that, at the time of writing, Circle does not
offer functionality for configuring multicast network sockets.

Limitations of this sort are inherent to the Circle environment, which
also, unlike Teensy, does not offer C++ standard library support. It
has also proven to be somewhat /fragile/, responding unstably to
attempts to perform diagnostic logging during audio processing for
example. Given the computing power of the Raspberry Pi, however, its
availability (something far from guaranteed amongst single-board
computers and microcontrollers, particularly over the past few years)
and the low-level control over its hardware permitted by Circle, I
feel a solution based on this platform is worth pursuing.

** Account of Master's Research Submitted as Journal Article

In November 2023, I was afforded the opportunity to submit a
manuscript summary to the journal [[https://www.frontiersin.org/journals/virtual-reality][Frontiers in Virtual Reality]] based
on the work I conducted for my master's thesis. I was subsequently
invited to write an article, which I submitted on February 26^{th}. The
current version of the article, pending the feedback of the review
panel, is included with this file.

* Outlook & Prospects

** In Pursuit of Sample-Synchronous Audio Output

I am in the process of establishing the viability of achieving greater
inter-client synchronicity than exhibited by the system produced for
my master's thesis. For that system, in the absence of a shared clock,
asynchronicity is minimised via a combination a small audio buffer
(and thus networked audio packet) size of 32 frames, an adaptive
resampling algorithm at the client side, and a clock-adjustment
strategy based on the rate of packet reception.

Under such a strategy, the network itself becomes the shared clock,
but with packets arriving on the order of every 726 \micro{}s, the resolution
of that clock is far too coarse for reliable, accurate adjustments to
be made. One possible approach to achieving clock-synchronicity
between the server and all clients is to run one client as a USB audio
device, thus becoming the /master clock/ for the system, and sharing
its clock with the other clients over a hard link. One drawback to
this approach is the need to run an additional cable in parallel with
the ethernet cables linking the server and clients, making an already
cable-heavy system less attractive from an accessibility
point-of-view. Additionally, high-frequency clock signals would need
to be amplified at intervals to maintain their integrity, further
increasing the complexity of the system and increasing costs.

State of the art networked audio systems typically use Precision Time
Protocol (PTP) as a clock synchronisation mechanism. PTP in its most
accurate form is underpinned by packet timestamping performed at the
hardware level, something that affordable networking equipment does
not provide. Software-only implementations of PTP are possible,
however, and may support microsecond-order synchronisation
[cite:@correll_design_2005]; in the short term, this is the approach
that I wish to explore.

** The Problem of Jitter

Further complicating matters, though, is the influence of transmission
jitter. For the Teensy-based system, reporting inter-packet intervals
at the client side revealed high levels of jitter, with some packets
taking as long as three times the expected interval to
arrive. Conservative client-side buffering could compensate for this
phenomenon, but ultimately, an investigation of the influence of
unmanaged network switches, USB-C ethernet dongles, etc. on packet
transmission will likely be necessary. It could be that compromises
have to be made in terms of the /frugality/ of the proposed system to
make it truly viable for high quality spatial audio
applications. Recent Raspberry Pi versions support hardware
timestamping, so a change of approach to costlier PTP-enabled switches
may prove favourable.

** Audio Spatialisation Algorithms

Subsequent to drawing meaningful conclusions about client
synchronicity, my wish is to return to the design of distributed audio
spatialisation algorithms. The WFS algorithm demonstrated for my
master's thesis is a relatively rudimentary one, and it does not
extend to /focused/ virtual sources sources[cite:@ahrens_analytic_2012
ch. 5.6] or the production of plane waves, for example. And though not
as readily-parallelisable as WFS, ambisonics also represents an
attractive target implementation.

* Other Activities

** Co-supervision of PIR Project Group

With my co-supervisor, Romain Michon, I have been assisting a group of
fourth year computer science students at INSA Lyon with a /projet
d'initiation à la recherche/ (PIR). For this project, the group have
been working on producing a Faust architecture for the Circle
environment. If successful, this work has the potential to be of great
use in facilitating the compilation of audio spatialisation algorithms
written in Faust for use on bare-metal Raspberry Pi.

** Google Summer of Code Mentorship

I served as a contributor for the 2023 edition of [[https://summerofcode.withgoogle.com/][Google Summer of
Code]], working on a project entitled "[[https://github.com/grame-cncm/faust/pull/939][Automatic Differentiation in
the Faust Compiler]]." Having subsequently developed this project
further, writing an [[https://github.com/hatchjaw/faust-ddsp][exploratory automatic differentiation library]] in
the Faust language (directly, rather than focusing on its compiler),
this year I will act as a project mentor, overseeing the work of a
contributor in expanding upon the exploratory library. This will
entail weekly-meetings and provision of support to the contributor
throughout the summer.

** Training

- [[https://sites.google.com/site/rsdwinterschool/home][GDR RSD / ASF Winter School on Distributed Systems & Networks]],
  5-9 February 2024, Le Pleynet.

- [[https://www.fun-mooc.fr/en/courses/reproducible-research-methodological-principles-transparent-scie/][Reproducible
  research: methodological principles for transparent science]], MOOC.

** Reviews

*** Conferences

- [[https://www.nime2024.org/][New Interfaces for Music Expression]] (NIME) 2024.

- [[https://smcnetwork.org/smc2024/][Sound and Music Computing]] (SMC) 2024.

*** Journals

- [[https://link.springer.com/journal/779][Personal and Ubiquitous Computing]] (PAUC).

#+PRINT_BIBLIOGRAPHY:

* Emacs Setup                                                      :noexport:

# Local Variables:
# eval:   (add-to-list 'org-latex-classes '("report"
# "\\documentclass[a4paper,oneside,
# headinclude,footinclude,BCOR=5mm,
# numbers=noenddot,cleardoublepage=empty,
# tablecaptionabove]{scrartcl}
# [NO-DEFAULT-PACKAGES]"
# ("\\section{%s}" . "\\section*{%s}")
# ("\\subsection{%s}" . "\\subsection*{%s}")
# ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
# ("\\paragraph{%s}" . "\\paragraph*{%s}")
# ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# End:
