# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Curriculum Vitæ
#+AUTHOR: Thomas Rushton

#+EXPORT_FILE_NAME: out/cv
#+OPTIONS: toc:nil num:nil ':t ^:{}

#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: cv

* Description                                                      :noexport:

Adapted from vitæ by [[https://github.com/kjhealy/kjh-vita/tree/master][Kieran Healy]] and [[https://github.com/xgarrido/org-resume/tree/master][Xavier Garrido]].

Tangle, then export.

For the future, there are also some nice ideas [[https://titan-c.gitlab.io/org-cv/][here]].

* Latex style                                                      :noexport:
:PROPERTIES:
:HEADER-ARGS: :tangle out/cv-style.sty :results silent
:END:

** Basics

#+begin_src latex
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{cv-style}[2024/05/12 v0.1 Bundling CV LaTeX style]
#+end_src

** Packages

Gosh, I probably don't need all of these...

#+begin_src latex
\RequirePackage{fontspec}
\RequirePackage[babel]{csquotes}
\RequirePackage{titlesec}
\RequirePackage{enumitem}
\RequirePackage{a4wide}
\RequirePackage{xcolor}
\RequirePackage{fontawesome5}
\RequirePackage{hyperref}
%% \RequirePackage{graphicx}
%% \RequirePackage{longtable}
%% \RequirePackage{wrapfig}
%% \RequirePackage{rotating}
%% \RequirePackage[normalem]{ulem}
%% \RequirePackage{amsmath}
%% \RequirePackage{amssymb}
%% \RequirePackage{capt-of}
#+end_src

Include the package generated by tangling (=C-c C-v t=) this file:

#+LATEX_HEADER: \RequirePackage[]{cv-style}

One could alternatively include this in local variables, as Xavier
Garrido [[https://github.com/xgarrido/org-resume/blob/029c74f73dbd20b603da0dfc6af8dae0f621a8ab/README.org?plain=1#L746][does]].

** Variables

A non-exhaustive selection, but enough for this vita.

#+begin_src latex
\newcommand{\myphone}{+33 (0)7 66 73 24 06}
\newcommand{\myemail}{thomas.rushton@inria.fr}
\newcommand{\myweb}{https://github.com/hatchjaw/}
#+end_src

** Cosmetics

*** Colours, links

#+begin_src latex
\definecolor{red}{RGB}{221,42,43}
\definecolor{green}{RGB}{105,182,40}
\definecolor{blue}{RGB}{0,51,153}
\definecolor{gray}{RGB}{25,25,25}
\colorlet{theMainColor}{blue}
\colorlet{theRefColor}{blue!90}
\newcommand{\globalcolor}[1]{%
  \color{#1}\global\let\default@color\current@color
}

\hypersetup{
  xetex,
  colorlinks=true,
  urlcolor=theRefColor,
  filecolor=theRefColor,
  linkcolor=theRefColor,
  plainpages=false,
  pdfpagelabels,
  bookmarksnumbered,
  pagebackref
}
#+end_src

*** Fonts

All available for download (Minion and Myriad are "widely available,
from Adobe" says Healy; Minion can be found [[https://font.download/font/minion-pro][here]], for example). names
may have to be changed to match what you have in
=~/.local/share/fonts=.

#+begin_src latex
\setromanfont[Mapping={tex-text}, 
	Numbers={OldStyle},
	Ligatures={Common}]{MinionPro-Regular}

\setsansfont[Mapping=tex-text,
	Ligatures={Common}, 
	Colour=AA0000]{FF Unit Pro Medium}

\setmonofont[Mapping=tex-text,Scale=0.9]{Iosevka Comfy Motion}

\newfontface\scheader[SmallCapsFont={Minion
    Pro},SmallCapsFeatures={Letters=SmallCaps}]{Minion Pro}

\newfontface\addressblock[Mapping={tex-text}, 
	Numbers={OldStyle},
	Ligatures={Common}]{MinionPro-MediumCapt}
#+end_src

** Layout
*** Paragraphs

#+begin_src latex
\setlength{\parindent}{0cm}
\setlength{\parskip}{.175cm}
#+end_src

*** Title

Swap the title out for a couple of minipages with my work address and
contact details.

#+begin_src latex
\newcommand{\mytitle}{}

\renewcommand{\mytitle}{\Large\scheader\textsc\@author\\\footnotesize
  \href{https://team.inria.fr/emeraude/}{Emeraude Research Team, Inria}
  \\ CITI Laboratory \\ 6 av. des Arts \\ \vspace{-0.05in}
  69100 Villeurbanne, France}

\renewcommand*{\maketitle}{%
  \globalcolor{gray}
  \begin{minipage}[t]{2.95in}
    \flushleft {\mytitle}
  \end{minipage}
  \hfill
  \hfill
  \begin{minipage}[t]{1.7in}
    \flushright \footnotesize \addressblock \myphone \, \faPhone \\
                {\scriptsize  \texttt{\href{mailto:\myemail}{\myemail}} \, \faEnvelope} \\
                {\scriptsize  \texttt{\href{\myweb}{\myweb}} \, \faGithub}
  \end{minipage}
  \vspace{10pt}
}
#+end_src

*** Section names

Shift ~\section~ headings into the left margin.

Again, [[https://github.com/xgarrido/org-resume/blob/029c74f73dbd20b603da0dfc6af8dae0f621a8ab/README.org?plain=1#L636][indebted]] to X. G. here.

#+begin_src latex
\titleformat{\section} %command
            [leftmargin] %shape
            {\footnotesize\bfseries\sffamily\raggedleft} %format
            {} %label
            {0pt} %sep
            {\lowercase} %before
            [] %after
            \titlespacing{\section}{90pt}{10pt}{15pt}
#+end_src

*** Lists

Don't show bullets.

#+begin_src latex
\renewcommand{\labelitemi}{~}
\renewcommand{\labelitemii}{~}
#+end_src

Alter itemize spacing.

#+begin_src latex
\let\saveditemize=\itemize%
\let\savedenditemize=\enditemize%
%% \makeatletter
\renewenvironment{itemize}
{\vspace{-1mm}\footnotesize\saveditemize}
{\savedenditemize\vspace{0mm}}
#+end_src

X. G. has more on overriding the ~itemize~ environment [[https://github.com/xgarrido/org-resume/blob/029c74f73dbd20b603da0dfc6af8dae0f621a8ab/README.org?plain=1#L675][here]].

** VC Status

Get the hash of the latest commit. Use it to construct the post-footer
text.

#+NAME: vc-status
#+BEGIN_SRC sh :results output :tangle no
  if [ -d ../.git ]; then
      log=$(LC_MESSAGES=en git --no-pager log -1 HEAD --date=short --pretty=format:"\href{https://github.com/hatchjaw/org/commit/%H}{\color{gray!50}\footnotesize\texttt{%h --- %ad}}")
      echo "\renewcommand*{\PrelimText}{${log}}"
  fi
#+END_SRC

Then use [[https://orgmode.org/manual/Noweb-Reference-Syntax.html][noweb]] to insert it.

#+BEGIN_SRC latex :noweb yes
\RequirePackage{prelim2e}
<<vc-status()>>
#+END_SRC

Update it by tangling; best done immediately after a commit.

* Education

MSc Sound and Music Computing, Aalborg University (Copenhagen), 2023.

BMus Music Technology, The University of Edinburgh, 2009.

* Employment

PhD Researcher, [[https://inria.fr][Inria]], Villeurbanne, France, 2023-present.
- Member of the Emeraude Research Team, conducting research on a
  doctorate entitled /Enabling Distributed Spatial Audio/.

Internship, [[https://inria.fr][Inria]], Villeurbanne, France, 2022.
- Developing a microcontroller-based networked audio client for
  distributed audio spatialisation. Work presented at 2022
  [[https://paw.grame.fr/2022/#rushton-talk][Programmable Audio Workshop]].

Web Developer, freelance, 2016-2022.
- Full-stack web development, specialising in software licensing and
  eCommerce. Clients including [[https://www.physicalaudio.co.uk][PhysicalAudio]] and
  [[https://krotosaudio.com][Krotos]].

Software Developer, [[https://sci-telligent.co.uk/][Sci-telligent]], Macclesfield, UK, 2014-2016.
- Development of web applications for scientific and pharmaceutical
  clients; contracted support for financial services clients.

Print Output Developer, DST Output, Manchester, UK, 2012-2014.
- Print output application development; business intelligence systems.

Music/Drama Technician, Parrs Wood High School, Manchester, UK,
2010-2011.
- Technical support; classroom assistance.

* Publications

T. A. Rushton, Y. Orlarey, R. Michon, T. Risset, S. Letz, 2025, [[https://aes.org/publications/elibrary-page/?id=23017][Faust
Autodiff: Towards Audio Domain-Specific Machine Learning]], /Proceedings
of the 2025 AES International Conference on Artifical Intelligence and
Machine Learning for Audio/.

T. A. Rushton, R. Michon, T. Risset, 2025, [[https://smc25.iem.at/contributions/all-together-now/][All Together Now: A
Synchronous Platform for Distributed Spatial Audio]], /Proceedings of the
22^{nd} Sound and Music Computing Conference/ (SMC2025).

T. A. Rushton, 2024, [[https://hal.science/hal-04846518/document#page=17][Differentiable DSP In Faust]], /Proceedings of the
International Faust Conference (IFC-24)/.

T. A. Rushton, R. Michon, S. Serafin, T. Risset, S. Letz, 2024, [[https://www.frontiersin.org/journals/virtual-reality/articles/10.3389/frvir.2024.1391987/][Networked
Microcontrollers for Accessible, Distributed Spatial Audio]],
/Frontiers in Virtual Reality, 5/.

T. A. Rushton, R. Michon, S. Letz, 2023, [[https://inria.hal.science/hal-04169238/document][A Microcontroller-Based
Network Client Towards Distributed Spatial Audio]], /Proceedings of
the 2023 Sound and Music Computing Conference (SMC-23)/.

T. A. Rushton, P. R. Kantan, 2022, [[https://seafile.zfn.uni-bremen.de/f/94b7758744164b4e9988/][A Real-time Embodied Sonification
Model to Convey Temporal Asymmetry During Running]], /Proceedings of
the 7th Interactive Sonification Workshop (ISon)/.
- Winner: /Best Student Paper/.

T. A. Rushton, D. Overholt, 2022, [[https://vbn.aau.dk/files/497197288/d20.pdf][The Springamajig: A Flexible Digital
Musical Instrument]], /Proceedings of the 19th Sound and Music Computing
Conference, SMC 2022/.

G. V. K. Gustafsson, M. Timossi, T. A. Rushton, 2022, [[https://vbn.aau.dk/en/publications/kuplen-a-hands-on-physical-model][Kuplen: A
Hands-On Physical Model]], /Proceedings of the 19th Sound and Music
Computing Conference, SMC 2022/.

* Emacs setup                                                      :noexport:

# Local Variables:
# org-latex-classes: (("cv" "\\documentclass[11pt]{scrartcl}
# [NO-DEFAULT-PACKAGES]"
# ("\\section{%s}" . "\\section*{%s}")
# ("\\subsection{%s}" . "\\subsection*{%s}")
# ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
# ("\\paragraph{%s}" . "\\paragraph*{%s}")
# ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# End:
