# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+title: Enabling Distributed Spatial Audio
#+subtitle: Individual Follow-up Committee: Year 2
#+author: Thomas Rushton
#+date: May 2025

#+options: toc:nil num:2
#+bibliography: references.bib

# LaTeX
#+export_file_name: out/report-latex
#+cite_export: biblatex
#+latex_class: report
#+latex_header: \RequirePackage[]{report-style}
#+latex_compiler: xelatex

# Typst
# #+export_file_name: out/report-typst
# #+cite_export: typst ieee

#+begin_src shell :results none :exports none
ln -s ../../../references.bib out/references.bib
#+end_src

#+begin_export typst
#import "@preview/ilm:1.4.1": *

#set text(lang: "en", font: "Minion Pro", number-type: "old-style")

#context [
  #show: ilm.with(
    title: text(hyphenate: false)[#document.title],
    author: document.author.first(),
    date: datetime(year: 2025, month: 05, day: 01),
    date-format: "[month repr:long] [year repr:full]",
    abstract: "Individual Follow-up Committee: Year 2",
    table-of-contents: none,
    external-link-circle: false,
  )
]

#show link: set text(fill: rgb("#880000"))

#set par(justify: true)
#+end_export

* Latex Setup                                                      :noexport:
:PROPERTIES:
:HEADER-ARGS: :tangle out/report-style.sty :results silent
:END:

** Basics

#+begin_src latex
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{report-style}[2025/05/04 v0.1 Bundling Report LaTeX style]
#+end_src

** Packages

Hm. Looks like these packages come from the example [[https://www.latextemplates.com/template/arsclassica-article][here]].

#+begin_src latex
\RequirePackage{subfig}
\RequirePackage[
  subfig,
  beramono,
  eulermath,
  pdfspacing
]{classicthesis}
\RequirePackage{arsclassica}
\RequirePackage{hyperref}
\RequirePackage{fontspec}
\RequirePackage{enumitem} % Required for manipulating the whitespace between and within lists
\RequirePackage{subfig} % Required for creating figures with multiple parts (subfigures)
\RequirePackage{amsmath,amssymb,amsthm} % For including math equations, theorems, symbols, etc
\RequirePackage{varioref} % More descriptive referencing
\RequirePackage{cleveref}
#+end_src

** Typography

Reduce the default font size by half a point.

#+begin_src latex
\KOMAoptions{fontsize=10pt}
#+end_src

Reduce the size of the date.

#+begin_src latex
\setkomafont{date}{\normalsize}
#+end_src

Use Minion for both main and "sans" fonts.

#+begin_src latex
\setmainfont[Mapping={tex-text}, 
  Numbers={OldStyle},
  Ligatures={Common},
  %% Extension=.otf,
  %% UprightFont=*-Regular,
  %% ItalicFont= *-It,
  %% BoldFont= *-Bold,
  %% BoldItalicFont = *-BoldIt
]{MinionPro-Regular}

\setsansfont[Mapping=tex-text,
  Ligatures={Common},
  Numbers={OldStyle},
  %% Extension=.otf,
  %% UprightFont=MyriadPro-Regular,
  %% ItalicFont=MyriadPro-CondIt,
  %% BoldFont=MyriadPro-Semibold,
  %% BoldItalicFont=MyriadPro-SemiboldIt,
]{MinionPro-Regular}
#+end_src

Scale Iosevka to more-or-less match Minion.

#+begin_src latex
\setmonofont[Mapping=tex-text,Scale=0.9]{Iosevka Comfy Motion}
#+end_src

** Bibliography

#+begin_src latex
\PassOptionsToPackage{%
  %backend=biber,bibencoding=utf8, %instead of bibtex
%   backend=bibtex8,bibencoding=ascii,%
  language=auto,
  style=numeric-comp,
  %style=authoryear-comp, % Author 1999, 2010
  %bibstyle=authoryear,dashed=false, % dashed: substitute rep. author with ---
  % sorting=nyt, % name, year, title
  sorting=none,
  maxbibnames=10, % default: 3, et al.
  natbib=true, % natbib compatibility mode (\citep and \citet still work)
  url=false,
  doi=false,
  isbn=false,
  giveninits=true,
}{biblatex}
#+end_src

#+begin_src latex :tangle out/biblatex.cfg
\AtEveryBibitem{
  \clearfield{eventtitle}
  %% \clearfield{pages}
}
#+end_src

* Work Undertaken

In preparation for last year's individual follow-up committee, I
expressed the intention to continue work with the Raspberry Pi (RPi)
hardware platform in preference to the Teensy 4.1 (T41), to explore a
software-based Precision Time Protocol (PTP, IEEE 1588)
implementation, and to return to the design of distributed spatial
audio algorithms. Perhaps unsurprisingly, the first two of these
intentions fell victim to changes of circumstance and understanding of
the problem space, and the third has lain unexplored.

Shortly after last year's committee, I had two key meetings. The
first, with [[https://christofressi.com/][Christof Ressi]], maintainer of [[https://github.com/essej/aoo][Audio Over OSC]] (AOO),
provided some ideas regarding the structure and operation of my
system's networked audio server. It is a pity that, beyond a
decade-old paper on /message based audio/\nbsp[cite:@ritschMessage2014],
no significant literature has emerged from the AOO project. The second
meeting was with [[https://www.femto-st.fr/fr/personnel-femto/jeanmichelfriedt][Jean-Michel Friedt]], researcher at the FEMTO-ST
laboratory in Besançon and an expert in time-sensitive computing. He
discouraged my supervisors and I from pursuing another of our
potential lines of investigation --- that of sharing a clock signal
over a physical link in parallel with the network link --- and shared
an article that he had written on the topic of synchronising RPi
Compute Modules via PTP\nbsp[cite:@friedtNetwork2023]. It emerged,
however, that Jean-Michel's approach entailed making physical
modifications to the devices, which I deemed a barrier to
accessibility.

** Development of a Sample-Synchronous, Distributed Audio Platform

Following the meeting with Jean-Michel, I was of the understanding
that PTP-compliant hardware was prohibitively expensive, that the T41
--- or rather its NXP IMXRT1062 microcontroller (MCU) --- did not
provide PTP support, and that the T41 and RPi audio clocks, though
adjustable at runtime, were of resolution too coarse for accurate
sampling frequency exchange.

Seeking ideas, I posted on the Teensy forum, yielding a response
pointing me toward a project called /[[https://github.com/ddrown/teensy-ntp][teensy-ntp]]/, which (though
dealing primarily with the lower-resolution /Network Time Protocol/)
revealed that the IMXRT1060 series features a configurable IEEE 1588
hardware timer. The functionality of this timer is unused in the core
T41 codebase, and examples provided by NXP use FreeRTOS (as opposed to
the bare-metal, Arduino-like Teensy libraries). I had the exceedingly
good fortune, while searching for an NXP application note on using the
MCU's PTP timer, to discover a conference paper, published just months
prior, demonstrating a bare-metal
implementation\nbsp[cite:@schleusnerSubMicrosecond2024].

Adapting this implementation to condition audio timing, I
reverse-engineered the existing T41 audio subsystem code and,
comparing with the MCU reference manual, I established a means to take
PTP timer adjustments and apply these to the device's I^{2}S
clock. Crucially, I discovered that, unlike the RPi, whose Broadcom
system-on-chip provides 12-bit GPIO clock divider registers
(resolution of around 1/14 Hz at a sampling frequency of 48 kHz), the
T41's MCU features a dedicated audio clock with 30-bit resolution
(1/600,000 Hz). I determined appropriate conditions for synchronous,
distributed audio startup, and reduced relative clock drift by three
orders of magnitude, to within 2 parts per billion (\sim1.7
nanoseconds-per-second).

Initially, devices were connected directly, limiting the network to
two nodes --- one /clock authority/ and one /clock subscriber/. Via a
[[https://github.com/jclark/rpi-cm4-ptp-guide/blob/main/switches.md][guide to PTP]] for the RPi CM4 I found a suitable €199, 24-port ethernet
switch, and discussions with Nils Tonnat and Fernando Lopez-Lezcano at
the Centre for Computer Research in Music and Acoustics (CCRMA) at
Stanford University led me toward a €30 USB ethernet adapter with PTP
support. With these devices in hand, I was able to use a general
purpose computer as both an audio server and as an authoritative
source of PTP time --- the irony being that the computer's audio
system timing remained /unconditioned/, the computer drifting relative
to itself, essentially. Doing away with the ethernet adapter, I now
run one MCU as a USB audio device[fn:1] --- dictating audio timing on
the general purpose computer --- /and/ as the PTP clock authority ---
dictating audio timing to other MCUs on the network.

*** Journal Article Published

In parallel with the above, I was readying an article based on my
master's thesis (and the basis for my current work) for publication in
the journal /Frontiers in Virtual Reality/. A successful outcome was
reached in November 2024 [cite:@rushtonNetworked2024].

** Differentiable DSP in Faust

An initiative upon which I began work as a contributor to Faust's
involvement in the 2023 edition of Google Summer of Code, provision
for the means to write differentiable code in Faust, has proven to be
a fruitful, if time-consuming side-project. Having the aim of
providing support for tackling gradient-based optimisation problems,
including those under the broad banner of machine learning, it has
been the basis for one conference
publication\nbsp[cite:@rushtonDifferentiable2024] and one further paper
that is currently under review (see cref:sec:papers).

* Outlook & Prospects

To date, the vast majority of my work has been on the synchronous,
distributed audio aspect of the technical side of my thesis topic. I
am now at the stage where we have a potentially useful, accessible
platform for practical applications and evaluation.

** Spatial Audio & Virtual Acoustics

A distributed Wave Field Synthesis implementation, developed as part
of the internship that preceded work on my master's thesis, remains
the only spatial audio application of my work. It has been my wish for
over two years now to attempt a distributed ambisonics algorithm; the
extent to which such an algorithm can in fact be parallelised remains
unknown to me, as does the T41 platform's capacity for acting as a
real-time ambisonics decoder. On the subject of parallelisation, the
development of an /autoparallelisation/ option for the Faust compiler
would be more elegant than the manual approach taken for the WFS
implementation, and may have applications to other signal processing
algorithms.

Perhaps the ultimate goal from a technical standpoint is to introduce
virtual acoustics techniques as a complement to the spatial audio
component. This will entail establishing the capabilities of the
memory-constrained MCU platform for performing real-time
impulse-response convolutions. Memory on the T41 can be extended by
up to 16 MB, enough to store a couple of minutes' worth of 16-bit IRs;
whether this additional memory is performant enough to support
audio-rate processing remains to be seen.

** Mitigation for Remaining Clock Drift

As alluded to above, some ppb. clock drift remains. Technical
evaluation has revealed (for one quartet of T41 devices) a maximum
asynchronicity of around 1 \micro{}s after ten minutes; assuming linear
drift, that suggests one sample (\sim20 \micro{}s) in around three hours. That
order of drift is a vast improvement over the unconditioned case, but
it remains troublesome and its cause and a suitable remediation must
be sought.

** Evaluation

The technical nature of my work to-date places limits on its scholarly
value. To address this shortcoming, I am conscious of the need to
devise an appropriate scheme for perceptual or usability
evaluation. The aim should not be to evaluate the effectiveness of a
given spatial audio or auralisation algorithm primarily, but rather to
establish whether such an algorithm running on the proposed
distributed system compares favourably with something operating on its
centralised counterpart. This could be in terms of perceived sound
field integrity, or, given the likely complexity of the system when
deployed on a large scale, ease of use. I am attracted to the
accessibility aspect of the project, so finding a suitable way to
gauge this formally is something to which I intend to pay further
attention.

** Paper/Article Submission Targets
:PROPERTIES:
:CUSTOM_ID: sec:papers
:END:

Subject to minor revisions, I will be presenting a paper, entitled
/All Together Now: A Synchronous Platform for Distributed Spatial
Audio/ at the 22^{nd} Sound and Music Computing Conference ([[https://smc25.iem.at/][SMC]], July
10th-12th, Graz, Austria).

I await a verdict on a submission to the 2025 AES International
Conference on Artificial Intelligence and Machine Learning for Audio
([[https://aes2.org/event-extra/2025-aes-international-conference-on-artificial-intelligence-and-machine-learning-for-audio/][AES AIMLA]], September 8th-10th, London, UK), entitled /Faust Autodiff:
Towards Audio Domain-Specific Machine Learning/.

Upcoming submission opportunities include:

- EURASIP Journal on Audio, Speech and Music Processing, collection on
  [[https://www.springeropen.com/collections/spios][Signal Processing for the Internet of Sounds]] --- deadline *June
  11^{th} 2025*.
- International Conference on Immersive and 3D Audio ([[https://www.i3da2025.org/][I3DA]]) ---
  abstract accepted under the title /Virtual Acoustics in a
  Distributed Setting: A Feasibility Study/; full paper deadline *June
  15^{th} 2025*.
- Internet of Sounds Symposium ([[https://internetofsounds2025.ieee-is2.org/][IS^{2}]]) --- deadline *July 1^{st}
  2025*. This event also features a satellite workshop on /Networked
  Immersive Audio/, and I have been encouraged (by a member of the
  organising committee) to propose a tutorial on Faust DDSP.
    
* Other Activities

** Google Summer of Code (GSoC)

I co-mentored all four of Faust's 2024 GSoC projects, including one
concerned with building on my initial work on Faust DDSP. This level
of involvement was greater than I ought to have committed to; I intend
to take a less active role this year.

** CCRMA Visit

Romain Michon and I visited CCRMA the end of October 2024. For CCRMA's
[[https://ccrma.stanford.edu/events/faust-day-2024][Faust Day 2024]], I had the honour of delivering an introductory Faust
workshop and, as part of Romain's broader Faust presentation, I gave
an overview of the DDSP project. I also had the opportunity to
demonstrate my synchronous, distributed audio system to interested
parties at CCRMA, stakeholders in the MIRAGES associate research
team. I have since maintained correspondence with Prof. Lopez-Lezcano,
who has a particular interest in networked and time-sensitive audio
applications.

*** Visiting Student Researcher application

In early March of this year, I submitted an application for a Visiting
Student Researcher position at CCRMA for the three months April-June
2026; department Chair, Prof. Chris Chafe, has agreed to act as
sponsor. A positive outcome hinges on financial support; a funding
application to the [[https://francestanford.stanford.edu/][France-Stanford Institute for Interdisciplinary
Studies]] is currently under consideration and I expect to receive a
response at some point over the coming month.

** Training

I have undertaken sixty-eight hours of doctoral training to-date,
including the following, completed since last year's committee
meeting:

- [[https://www.fun-mooc.fr/en/courses/reproducible-research-methodological-principles-transparent-scie/][Reproducible
  research: methodological principles for transparent science]], MOOC
  (24 hours).
  
- French as a Foreign Language, June-November 2024 (20
  hours). Courtesy of Inria, I received lessons with an instructor
  from the agency /Wissen International/.

This year's SMC summer school, /[[https://smc25.iem.at/summer-school/][The auditory gardener: creating
Ambisonic landscapes]]/, appears to be of significant relevance to my
work; I hope to have the opportunity to attend.
  
** Reviews

I served as a reviewer for this year's New Interfaces for Music
Expression ([[https://nime2025.org/][NIME]]) and SMC conferences, and the journal [[https://link.springer.com/journal/779][Personal and
Ubiquitous Computing]] (Springer).

** Teaching

I completed 20 hours' teaching assistance for /Traitement de Signal
pour le Son / Audio Signal Processing/, a 3TC (undergraduate, final
year) course at INSA.

#+print_bibliography:


* Footnotes

[fn:1] This entailed modifying T41's USB driver to permit running at
48 kHz, a much more convenient frequency for time-sensitive audio than
T41's default 44.1 kHz, since power-of-two audio block sizes of 128
and below, are divisors of 48,000.

* Emacs Setup                                                      :noexport:

# Local Variables:
# org-latex-classes: (("report" "\\documentclass[
# a4paper,oneside,headinclude,footinclude,BCOR=5mm,
# numbers=noenddot,cleardoublepage=empty,tablecaptionabove
# ]{scrartcl}
# [NO-DEFAULT-PACKAGES]"
# ("\\section{%s}" . "\\section*{%s}")
# ("\\subsection{%s}" . "\\subsection*{%s}")
# ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
# ("\\paragraph{%s}" . "\\paragraph*{%s}")
# ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# org-cite-global-bibliography: nil
# End:
