# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+title: Differentiable DSP in Faust
#+author: Thomas Rushton

#+startup: overview
#+options: num:nil toc:nil ^:{} ':t
#+options: reveal_width:1500 reveal_height:1000 reveal_slider_number:c/t
#+export_file_name: index

#+REVEAL_ROOT: ../reveal.js
#+REVEAL_THEME: simple
#+reveal_highlight_css: %r/plugin/highlight/monokai.css
#+reveal_trans: slide
#+REVEAL_PLUGINS: (highlight)
# Prevent org-re-reveal from loading MathJax automatically!
#+REVEAL_MATHJAX_URL:
#+REVEAL_MIN_SCALE: 1.0
#+REVEAL_MAX_SCALE: 1.0
#+REVEAL_EXTRA_OPTIONS: hash: true, fragmentInURL: true
#+REVEAL_TITLE_SLIDE: <h1>%t</h1><h2>%a</h2><h3>Inria, Emeraude Team --- INSA Lyon</h3>
#+reveal_extra_scripts: ("./node_modules/mathjax/es5/tex-svg.js" "./dist/ifc24.js")
#+reveal_extra_css: style.css

* About This Presentation                                          :noexport:

This =org= file describes my presentation for the 2024 International
Faust Conference.

** Dependencies

- =org-re-reveal= ([[https://gitlab.com/oer/org-re-reveal/-/tree/main][gitlab]]), which enables export support from Org to [[https://revealjs.com/][Reveal.js]].
- Vite.js. Here's the config:

#+begin_src js :results none :tangle ./vite.config.js
import { resolve } from 'path'
import { defineConfig } from 'vite'

export default defineConfig({
    build: {
        minify: false,
        lib: {
            entry: resolve(__dirname, "src/main.js"),
            name: "ifc24",
            // formats: ["iife"],
            // formats: ["es", "umd"]
            fileName: () => "ifc24.js",
        },
        sourcemap: true,
    }
});
#+end_src

** Running the Presentation

Tangle, =C-c C-v t=, then export as a Reveal.js presentation, =C-c C-e
v v=, which will trigger the =npm= build.

Then, from the reveal.js directory (=../reveal.js=), run:

#+begin_src shell :noeval :exports code
npm start -- --root=../
#+end_src

Finally, navigate to [[http://localhost:8000/ifc-2024]].

* Agenda

#+ATTR_REVEAL: :frag (appear)
- Differentiation
- Dual Number arithmetic
- Automatic Differentiation
- Differentiable Programming in Faust
- Gradient-based Parameter Optimisation

* Differentiation

#+REVEAL: split

#+attr_html: :class big-eqn
\begin{equation}
f'(x) = \lim_{h\to0}\frac{f(x + h) - f(x)}{h}
\end{equation}

#+begin_src css :exports none :results none :tangle style.css
.big-eqn {
    font-size: 1.66em;
}
#+end_src

#+REVEAL: split

#+begin_export html
<div id="xSquaredContainer">
  <div>
    <div>
      <canvas id="xSquaredCanvas"></canvas>
      <canvas id="secantCanvas"></canvas>
    </div>
    <div>
      <label for="xSquared-xValue">\(x\)</label>
      <input type="range" id="xSquared-x" min=-2 max=2 value=0 step=.01 />
      <span id="xSquared-xValue" class="sliderValue"></span>
    </div>
    <div>
      <label for="xSquared-hValue">\(h\)</label>
      <input type="range" id="xSquared-h" min=.01 max=3 value=2 step=.01 />
      <span id="xSquared-hValue" class="sliderValue"></span>
    </div>
  </div>
  <div id="xSquaredMath">
    <p style="padding-bottom: 2em;">\(f(x) = x^{2}\)</p>
    <div id="xSquaredDynamicMath">
    </div>
  </div>
</div>
#+end_export

** JS & CSS for the xSquared Plot                                  :noexport:

Some CSS. Just tangle this to the current directory.

#+begin_src css :results none :tangle style.css
#xSquaredContainer {
    display: flex;
    justify-content: space-evenly;
}

#xSquaredContainer> div:nth-child(2) {
    width: 45%;
}

#xSquaredCanvas {
    position: absolute;
}

.sliderValue {
    display: inline-block;
    width: 2.5em;
    text-align: right;
}    
#+end_src

Tangle JS to the =src= directory to be processed by Vite.

Some display constants:

#+begin_src js :results none :tangle src/xsquared.js
const SVG = {};

const CANVAS = {
    WIDTH: 600,
    HEIGHT: 600,
    PADDING: 25
};

const AXES = {
    X: {
        ZERO: CANVAS.WIDTH / 2,
        INDICATOR: {
            WIDTH: 3,
            HEIGHT: 10
        }
    },
    Y: {
        ZERO: CANVAS.HEIGHT - CANVAS.PADDING - 50,
    }
};

const X = {
    MIN: -2,
    MAX: 2,
    LEN: 1000
};

X.STEP = (X.MAX-X.MIN)/X.LEN;
#+end_src

A vector for the independent variable \(x\):

#+begin_src js :results none :tangle src/xsquared.js
const xVec = Array.from({length: X.LEN + 1}, (_,x) => X.MIN + x * X.STEP);
#+end_src

Prepare to plot \(f(x) = x^{2}\):

#+begin_src js :results none :tangle src/xsquared.js
export default async () => {
    const f = x => x * x;
    const yVec = xVec.map(x => ({x: x, y: f(x)}));
    const yMax = Math.max(...yVec.map(y => y.y));

    await MathJax.startup.promise;
    const xml = new XMLSerializer();
    const tex2imageSrc = tex => "data:image/svg+xml;base64, " +
          window.btoa(unescape(encodeURIComponent(
              xml.serializeToString(MathJax.tex2svg(tex).firstElementChild)
          )));
#+end_src

Define the axes and the static plot of \(f(x)\):

#+begin_src js :results none :tangle src/xsquared.js
    const staticLayer = {
        canvas: document.getElementById("xSquaredCanvas"),

        visualiser: ctx => ({
            drawAxis: {
                x: () => {
                    ctx.beginPath();
                    ctx.moveTo(CANVAS.PADDING, AXES.Y.ZERO);
                    ctx.lineTo(CANVAS.WIDTH - CANVAS.PADDING, AXES.Y.ZERO);
                    ctx.stroke();
                    // Arrow
                    ctx.beginPath();
                    ctx.moveTo(CANVAS.WIDTH - CANVAS.PADDING, AXES.Y.ZERO);
                    ctx.lineTo(CANVAS.WIDTH - CANVAS.PADDING - 10, AXES.Y.ZERO - 5);
                    ctx.lineTo(CANVAS.WIDTH - CANVAS.PADDING - 10, AXES.Y.ZERO + 5);
                    ctx.closePath();
                    ctx.fill();
                },
                y: () => {
                    ctx.beginPath();
                    ctx.moveTo(AXES.X.ZERO, CANVAS.PADDING);
                    ctx.lineTo(AXES.X.ZERO, CANVAS.HEIGHT - CANVAS.PADDING);
                    ctx.stroke();
                    // Arrow
                    ctx.beginPath();
                    ctx.moveTo(AXES.X.ZERO, CANVAS.PADDING);
                    ctx.lineTo(AXES.X.ZERO - 5, CANVAS.PADDING + 10);
                    ctx.lineTo(AXES.X.ZERO + 5, CANVAS.PADDING + 10);
                    ctx.closePath();
                    ctx.fill();
                    // Label
                    ctx.drawImage(SVG.FX, AXES.X.ZERO - 60, CANVAS.PADDING,
                                 SVG.FX.naturalWidth * 1.5,
                                 SVG.FX.naturalHeight * 1.5);
                }
            },

            drawFunction: () => {
                ctx.beginPath();
                ctx.moveTo(
                    CANVAS.PADDING + (yVec[0].x + X.MAX) * (CANVAS.WIDTH - CANVAS.PADDING * 2) / (X.MAX - X.MIN),
                    CANVAS.PADDING + (yMax - yVec[0].y) * (AXES.Y.ZERO - CANVAS.PADDING) / yMax
                );
                yVec.forEach(p => ctx.lineTo(
                    CANVAS.PADDING + (p.x + X.MAX) * (CANVAS.WIDTH - CANVAS.PADDING * 2) / (X.MAX - X.MIN),
                    CANVAS.PADDING + (yMax - p.y) * (AXES.Y.ZERO - CANVAS.PADDING) / yMax
                ));
                ctx.strokeStyle = "blue";
                ctx.lineWidth = 2;
                ctx.stroke();
            },
        }),

        async init() {
            if (this.canvas.getContext) {
                this.canvas.setAttribute("width", CANVAS.WIDTH);
                this.canvas.setAttribute("height", CANVAS.HEIGHT);

                let img = new Image();
                img.src = tex2imageSrc("f(x)");
                await img.decode();
                SVG.FX = img;

                const v = this.visualiser(this.canvas.getContext("2d"));
                v.drawAxis.x();
                v.drawAxis.y();
                v.drawFunction();
            }
        }
    };
#+end_src

Define the dynamic part of the plot --- the secant and axis
indicators. Slope \(m\) found as \(m = \frac{f(x + h) - f(x)}{h}\);
secant line found as \(m(x - x_{1}) + y_{1}\).

#+begin_src js :results none :tangle src/xsquared.js
    const dynamicLayer = {
        canvas: document.getElementById("secantCanvas"),
        xSlider: {
            element: document.getElementById("xSquared-x"),
            valSpan: document.getElementById("xSquared-xValue")
        },
        hSlider: {
            element: document.getElementById("xSquared-h"),
            valSpan: document.getElementById("xSquared-hValue"),
            prevValue: 0
        },
        math: document.getElementById("xSquaredDynamicMath"),

        visualiser: ctx => ({
            drawIndicators: (x, h) => {
                const drawXIndicator = (x, y) => ctx.fillRect(
                    CANVAS.PADDING - (AXES.X.INDICATOR.WIDTH / 2) + (x + X.MAX) * (CANVAS.WIDTH - CANVAS.PADDING * 2) / (X.MAX - X.MIN),
                    y - AXES.X.INDICATOR.HEIGHT / 2,
                    AXES.X.INDICATOR.WIDTH,
                    AXES.X.INDICATOR.HEIGHT
                );

                const drawFxIndicator = (x, y) => {
                    const indicatorWidth = 6;
                    ctx.beginPath();
                    ctx.arc(
                        CANVAS.PADDING + (x + X.MAX) * (CANVAS.WIDTH - CANVAS.PADDING * 2) / (X.MAX - X.MIN),
                        CANVAS.PADDING + (yMax - y) * (AXES.Y.ZERO - CANVAS.PADDING) / yMax,
                        indicatorWidth,
                        0, 2 * Math.PI
                    );
                    ctx.fill();
                };

                const drawSVG = (img, x, y, scale) => {
                    const w = img.naturalWidth * scale;
                    const h = img.naturalHeight * scale;
                    const xPos = CANVAS.PADDING - w / 2 +
                          (x + X.MAX) * (CANVAS.WIDTH - CANVAS.PADDING * 2) / (X.MAX - X.MIN);
                    const yPos = CANVAS.PADDING + (yMax - y) * (AXES.Y.ZERO - CANVAS.PADDING) / yMax;
                    ctx.drawImage(img, xPos, yPos, w, h);
                };

                drawXIndicator(x, AXES.Y.ZERO);
                drawXIndicator(x + h, AXES.Y.ZERO);

                drawFxIndicator(x, f(x));
                drawFxIndicator(x + h, f(x + h));

                drawSVG(SVG.X, x, -.08, 1.5);
                drawSVG(SVG.XPLUSH, x + h, -.2, 1.5);
            },

            drawSecant: (x, h) => {
                const slope = (f(x + h) - f(x)) / h;
                const ySecVec = xVec.map(xVal => ({x: xVal, y: slope * (xVal - x) + f(x)}));
                ctx.beginPath();
                ctx.moveTo(
                    CANVAS.PADDING + (ySecVec[0].x + X.MAX) * (CANVAS.WIDTH - CANVAS.PADDING * 2) / (X.MAX - X.MIN),
                    CANVAS.PADDING + (yMax - ySecVec[0].y) * (AXES.Y.ZERO - CANVAS.PADDING) / yMax
                );
                ySecVec.forEach(p => ctx.lineTo(
                    CANVAS.PADDING + (p.x + X.MAX) * (CANVAS.WIDTH - CANVAS.PADDING * 2) / (X.MAX - X.MIN),
                    CANVAS.PADDING + (yMax - p.y) * (AXES.Y.ZERO - CANVAS.PADDING) / yMax
                ));
                ctx.strokeStyle = "green";
                ctx.lineWidth = 2;
                ctx.stroke();
            },

            clear: () => ctx.clearRect(0, 0, CANVAS.WIDTH, CANVAS.HEIGHT),
            
            draw(x, h) {
                this.drawIndicators(x, h);
                this.drawSecant(x, h);
            },
            
            redraw(x, h) {
                this.clear();
                this.draw(x, h)
            }
        }),

        async init() {
            if (this.canvas.getContext) {
                this.canvas.setAttribute("width", CANVAS.WIDTH);
                this.canvas.setAttribute("height", CANVAS.HEIGHT);
                
                let img = new Image();
                img.src = tex2imageSrc("x");
                await img.decode();
                SVG.X = img;
                
                img = new Image();
                img.src = tex2imageSrc("x + h");
                await img.decode();
                SVG.XPLUSH = img;

                const x = Number(this.xSlider.element.value);
                const h = Number(this.hSlider.element.value);                
                const v = this.visualiser(this.canvas.getContext("2d"));
                v.draw(x, h);

                const updateMath = async () => {
                    const x = Number(this.xSlider.element.value);
                    const h = Number(this.hSlider.element.value);
                    const xx = f(x);
                    const xhxh = f(x + h);
                    const fprimex = (xhxh - xx) / h;
                    const mx = fprimex / x;

                    MathJax.typesetClear([this.math, this.xSlider.valSpan, this.hSlider.valSpan]);
                    this.math.innerHTML = `$$
    \\begin{align}
        f'(x) &\\approx \\frac{f(x + h) - f(x)}{h} \\\\[10pt]
          &\\approx \\frac{${xhxh.toFixed(2)} - ${xx.toFixed(2)}}{${h}} = ${fprimex.toFixed(2)} \\\\[10pt]
          &\\approx ${isFinite(mx) ? mx.toFixed(2) + "x" : "\\infty{}"}
    \\end{align}
    $$`;
                    this.xSlider.valSpan.innerHTML = `\\(${x.toFixed(2)}\\)`;
                    this.hSlider.valSpan.innerHTML = `\\(${h.toFixed(2)}\\)`;
                    await MathJax.typesetPromise([this.math, this.xSlider.valSpan, this.hSlider.valSpan]);
                };

                updateMath();

                this.xSlider.element && this.xSlider.valSpan &&
                    this.xSlider.element.addEventListener("input", async ({target: {value: val}}) => {
                        v.redraw(Number(this.xSlider.element.value), Number(this.hSlider.element.value));
                        await updateMath();
                    });

                this.hSlider.element && this.hSlider.valSpan &&
                    this.hSlider.element.addEventListener("input", async ({target: {value: val}}) => {
                        // Avoid division by zero!
                        if (val == 0) {
                            val = this.hSlider.prevValue > val ? -.01 : .01;
                            this.hSlider.element.value = val;
                        }
                        this.hSlider.prevValue = val;
                        v.redraw(Number(this.xSlider.element.value), Number(this.hSlider.element.value));
                        await updateMath();
                    });
            }
        }
    };
#+end_src

Initialise the layers:

#+begin_src js :results none :tangle src/xsquared.js
    await staticLayer.init();
    await dynamicLayer.init();
}
#+end_src

* Infinitessimal Jest

#+REVEAL: split

\begin{equation}
\textrm{Let}\; h = \varepsilon\dot{x}
\end{equation}

#+ATTR_REVEAL: :frag t
\(\dot{x}\) is Newton's notation for the derivative.

#+ATTR_REVEAL: :frag t
\(\varepsilon\) is a /nilpotent symbol/: \(\quad\varepsilon \neq
0\;,\quad\varepsilon^{2} = 0\)

#+attr_html: :class big-eqn
#+ATTR_REVEAL: :frag t
\begin{equation}
f'(x) = \frac{f(x + \varepsilon\dot{x}) - f(x)}{\varepsilon\dot{x}}
\end{equation}

#+attr_html: :class big-eqn
#+ATTR_REVEAL: :frag t
\begin{equation}
{\color{darkred} f(x + \varepsilon\dot{x}) = f(x) + \varepsilon\dot{x}f'(x)}
\end{equation}

#+attr_html: :style font-size: .5em
#+begin_quote
Baydin, Pearlmutter, Radul, and Siskind. 2018. ‘Automatic
Diﬀerentiation in Machine Learning: A Survey’. Journal of Machine
Learning Research 18.

Rall. 1986. ‘The Arithmetic of Differentiation’. Mathematics
Magazine 59 (5): 275–82.
#+end_quote

#+REVEAL: split

\begin{equation}
\textrm{Let}\; f(x) = x
\end{equation}

#+attr_html: :class big-eqn
\begin{equation}
f(x) + \varepsilon\dot{x}f'(x) = {\color{blue} x} + {\color{green} \varepsilon\dot{x}}
\end{equation}

#+begin_export html
<p class="fragment">This is a <span style="color:blue;">DUAL</span> <span style="color:green;">NUMBER</span>.</p>
<p class="fragment">The first component is the <span style="color:blue;">PRIMAL</span> expression; the second is the <span style="color:green;">TANGENT</span>.</p>
#+end_export

#+ATTR_REVEAL: :frag t
/Possible interpretation/ --- truncated Taylor series expansion at
\(\varepsilon\dot{x} = 0\):

#+ATTR_REVEAL: :frag t
\begin{equation}
f(x + \varepsilon\dot{x}) = x + \varepsilon\dot{x}f'(x) +
  \cancel{(\varepsilon\dot{x})^{2}\frac{f''(x)}{2}} + \cancel{(\varepsilon\dot{x})^{3}\frac{f'''(x)}{6}} + \cdots
\end{equation}

* Dual Number Arithmetic

#+REVEAL: split

The basic rules of differentiation arithmetic arise from application
of dual numbers.

\begin{align}
(u + \varepsilon\dot{u}) + (v + \varepsilon\dot{v}) &= {\color{blue} u + v} + {\color{green} \varepsilon(\dot{u} + \dot{v})} \\[.5em]
(u + \varepsilon\dot{u}) - (v + \varepsilon\dot{v}) &= {\color{blue} u - v} + {\color{green} \varepsilon(\dot{u} - \dot{v})} \\[.5em]
(u + \varepsilon\dot{u}) \times (v + \varepsilon\dot{v}) &= {\color{blue} uv} + {\color{green} \varepsilon(u\dot{v} + v\dot{u})} \\[.5em]
(u + \varepsilon\dot{u}) \div (v + \varepsilon\dot{v}) &= (u + \varepsilon\dot{u})\frac{1}{(v + \varepsilon\dot{v})} \\
  &= (u + \varepsilon\dot{u})\left(\frac{1}{v} - \varepsilon\frac{\dot{v}}{v^{2}}\right) \\
  &= {\color{blue} \frac{u}{v}} + {\color{green} \varepsilon\left(\frac{v\dot{u} - u\dot{v}}{v^{2}}\right)}
\end{align}

#+REVEAL: split

The truncated Taylor series gives us some other useful results.

\begin{align}
\sin(u + \varepsilon\dot{u}) &= {\color{blue} \sin(u)} + {\color{green} \varepsilon\dot{u}\cos(u)} \\[.5em]
\ln(u + \varepsilon\dot{u}) &= {\color{blue} \ln(u)} + {\color{green} \varepsilon\dot{u}\frac{1}{u}} \\[.5em]
e^{(u + \varepsilon\dot{u})} &= {\color{blue} e^{u}} + {\color{green} \varepsilon\dot{u}e^{u}} \\[.5em]
(u + \varepsilon\dot{u})^{(v + \varepsilon\dot{v})} &= {\color{blue} u^{v}} + {\color{green} \varepsilon{}u^{v-1}(\dot{v}u\ln(u) + \dot{u}v)}
\end{align}

#+REVEAL: split

Multiple applications of \(f(x + \varepsilon\dot{x})\) give us the chain rule.

\begin{align}
f(g(x + \varepsilon\dot{x})) &= f(g(x) + \varepsilon\dot{x}g'(x)) \\
  &= f(w + \varepsilon\dot{w})\;,\quad w = g(x)\;,\quad \dot{w} = \dot{x}g'(x) \\
  &= f(w) + \varepsilon\dot{w}f'(w) \\
  &= {\color{blue} f(g(x))} + {\color{green} \varepsilon\dot{x}g'(x)f'(g(x))}
\end{align}

#+ATTR_REVEAL: :frag t
#+attr_html: :style padding-top: 1em
E.g. let \(g(x) = \sin(x)\) and \(f(v) = v^{2}\):

#+ATTR_REVEAL: :frag t
\begin{align}
\sin^{2}(x + \varepsilon\dot{x}) &= \sin^{2}(x) + \varepsilon\dot{x}\cos(x)2v \\
  &= {\color{blue} \sin^{2}(x)} + {\color{green} \varepsilon2\sin(x)\cos(x)}
\end{align}

** A Change of Notation

#+ATTR_REVEAL: :frag t
#+attr_html: :class big-eqn
\begin{equation}
({\color{blue} u} + {\color{green} \varepsilon\dot{u}}) \to \langle {\color{blue} u}, {\color{green} u'} \rangle
\end{equation}

#+ATTR_REVEAL: :frag t
\begin{equation}
UV = \langle {\color{blue} u}, {\color{green} u'} \rangle\langle {\color{blue} v}, {\color{green} v'} \rangle
  = \langle {\color{blue} uv}, {\color{green} uv' + vu'} \rangle
\end{equation}

@@html: <div class="fragment">@@
Possible implementation:

#+attr_html: :style width: 1050px;
#+begin_src c++
class Dual {
  //...
  float primal, tangent;
  //....
  Dual operator*(Dual& d) {
    Dual result;
    result.primal = this->primal * d.primal;
    result.tangent = this->primal * d.tangent + d.primal * this->tangent;
    return result;
  }
}
#+end_src
@@html: </div>@@

#+attr_html: :style font-size: .5em
#+begin_quote
Yu and Blair. 2013. ‘DNAD, a Simple Tool for Automatic Differentiation of Fortran Codes Using Dual Numbers’. Computer Physics Communications 184 (5): 1446–52.
#+end_quote

#+begin_src css :exports none :results none :tangle style.css
pre code.hljs {
    padding: 1em;
}
#+end_src

** A Numerical Example

Compute the primal and tangent of \((x + 1)(x - 2)\).

#+ATTR_REVEAL: :frag t
Independent variable, \(X = \langle {\color{blue} x}, {\color{green} 1}
\rangle\). Constant, \(C = \langle {\color{blue} c}, {\color{green} 0} \rangle\).

#+begin_export html
<div id="dualExample" class="fragment">
  <div>
    <label for="dualX">\(x\)</label>
    <input type="range" id="dualX" min=-2 max=2 value=0 step=.01 />
  </div>
  <div id="dualNumerical">
  </div>
  <canvas id="dualPlotStatic"></canvas>
  <canvas id="dualPlotDynamic"></canvas>
</div>
#+end_export

#+ATTR_REVEAL: :frag t
What we've achieved here is /*AUTOMATIC DIFFERENTIATION*/.

*** JS for the numerical example                                   :noexport:

#+begin_src js :results none :tangle src/dualnumber.js
export default class Dual {
    constructor(primal, tangent) {
        this.primal = primal;
        this.tangent = tangent;
    }

    toString() {
        return `\\langle{\\color{blue}${this.primal.toFixed(2)}},{\\color{green}${this.tangent.toFixed(2)}}\\rangle`;
    }

    add(d) {
        return new Dual(this.primal + d.primal, this.tangent + d.tangent);
    }

    sub(d) {
        return new Dual(this.primal - d.primal, this.tangent - d.tangent);
    }

    mul(d) {
        return new Dual(this.primal * d.primal, this.primal * d.tangent + d.primal * this.tangent);
    }
};
#+end_src

#+begin_src js :results none :tangle src/numerical.js
import Dual from "./dualnumber";

const CANVAS = { WIDTH: 550, HEIGHT: 550, PADDING: 0 };
const AXES = { X: { ZERO: CANVAS.WIDTH / 2 },
               Y: { ZERO: CANVAS.HEIGHT - 250 } };
const X = { LEN: 1000, MIN: -2.5, MAX: 2.5};
X.STEP = (X.MAX - X.MIN) / X.LEN;
const xVec = Array.from({length: X.LEN + 1}, (_,x) => X.MIN + x * X.STEP);
const C1 = new Dual(1, 0);
const C2 = new Dual(2, 0);
const f = x => x.add(C1).mul(x.sub(C2));
const yVec = xVec.map(x => ({x: x, y: f(new Dual(x, 1)).primal}));
const yMax = 3.5;//Math.max(...yVec.map(y => y.y));

export default async () => {
    const math = document.getElementById("dualNumerical");
    const slider = document.getElementById("dualX");

    const plot = {
        staticLayer: {
            canvas: document.getElementById("dualPlotStatic"),

            drawAxis: {
                x: ctx => {
                    ctx.beginPath();
                    ctx.moveTo(0, AXES.Y.ZERO);
                    ctx.lineTo(CANVAS.WIDTH, AXES.Y.ZERO);
                    ctx.stroke();
                    // Arrow
                    ctx.beginPath();
                    ctx.moveTo(CANVAS.WIDTH, AXES.Y.ZERO);
                    ctx.lineTo(CANVAS.WIDTH - 10, AXES.Y.ZERO - 5);
                    ctx.lineTo(CANVAS.WIDTH - 10, AXES.Y.ZERO + 5);
                    ctx.closePath();
                    ctx.fill();
                },
                y: ctx => {
                    ctx.beginPath();
                    ctx.moveTo(AXES.X.ZERO, 0);
                    ctx.lineTo(AXES.X.ZERO, CANVAS.HEIGHT);
                    ctx.stroke();
                    // Arrow
                    ctx.beginPath();
                    ctx.moveTo(AXES.X.ZERO, 0);
                    ctx.lineTo(AXES.X.ZERO - 5, 10);
                    ctx.lineTo(AXES.X.ZERO + 5, 10);
                    ctx.closePath();
                    ctx.fill();
                }
            },

            drawFunction: ctx => {
                ctx.beginPath();
                ctx.moveTo(
                    CANVAS.PADDING + (yVec[0].x + X.MAX) * (CANVAS.WIDTH - CANVAS.PADDING * 2) / (X.MAX - X.MIN),
                    CANVAS.PADDING + (yMax - yVec[0].y) * (AXES.Y.ZERO - CANVAS.PADDING) / yMax
                );
                yVec.forEach(p => ctx.lineTo(
                    CANVAS.PADDING + (p.x + X.MAX) * (CANVAS.WIDTH - CANVAS.PADDING * 2) / (X.MAX - X.MIN),
                    CANVAS.PADDING + (yMax - p.y) * (AXES.Y.ZERO - CANVAS.PADDING) / yMax
                ));
                ctx.strokeStyle = "blue";
                ctx.lineWidth = 2;
                ctx.stroke();
            },

            init() {
                if (this.canvas.getContext) {
                    this.canvas.setAttribute("width", CANVAS.WIDTH);
                    this.canvas.setAttribute("height", CANVAS.HEIGHT);

                    const ctx = this.canvas.getContext("2d");
                    this.drawAxis.x(ctx);
                    this.drawAxis.y(ctx);
                    this.drawFunction(ctx);
                }
            }
        },

        dynamicLayer: {
            canvas: document.getElementById("dualPlotDynamic"),

            artist: ctx => ({
                clear: () => ctx.clearRect(0, 0, CANVAS.WIDTH, CANVAS.HEIGHT),

                drawTangent: x => {
                    const slope = f(new Dual(x, 1)).tangent;
                    const yTanVec = xVec.map(xVal => ({x: xVal, y: slope * (xVal - x) + f(new Dual(x, 1)).primal}));
                    ctx.beginPath();
                    ctx.moveTo(
                        CANVAS.PADDING + (yTanVec[0].x + X.MAX) * (CANVAS.WIDTH - CANVAS.PADDING * 2) / (X.MAX - X.MIN),
                        CANVAS.PADDING + (yMax - yTanVec[0].y) * (AXES.Y.ZERO - CANVAS.PADDING) / yMax
                    );
                    yTanVec.forEach(p => ctx.lineTo(
                        CANVAS.PADDING + (p.x + X.MAX) * (CANVAS.WIDTH - CANVAS.PADDING * 2) / (X.MAX - X.MIN),
                        CANVAS.PADDING + (yMax - p.y) * (AXES.Y.ZERO - CANVAS.PADDING) / yMax
                    ));
                    ctx.strokeStyle = "green";
                    ctx.lineWidth = 2;
                    ctx.stroke();
                },

                drawIntersection: x => {
                    const indicatorWidth = 6;
                    ctx.beginPath();
                    ctx.arc(
                        CANVAS.PADDING + (x + X.MAX) * (CANVAS.WIDTH - CANVAS.PADDING * 2) / (X.MAX - X.MIN),
                        CANVAS.PADDING + (yMax - f(new Dual(x, 1)).primal) * (AXES.Y.ZERO - CANVAS.PADDING) / yMax,
                        indicatorWidth,
                        0, 2 * Math.PI
                    );
                    ctx.fill();
                },
                
                draw(x) {
                    this.drawTangent(x);
                    this.drawIntersection(x);
                },
                
                redraw(x) {
                    this.clear();
                    this.draw(x);
                }
            }),

            async init() {
                if (this.canvas.getContext) {
                    this.canvas.setAttribute("width", CANVAS.WIDTH);
                    this.canvas.setAttribute("height", CANVAS.HEIGHT);

                    return this.artist(this.canvas.getContext("2d"));
                }
            }
        }
    };

    const updateMath = async () => {
        const x = new Dual(Number(slider.value), 1);
        
        MathJax.typesetClear([math]);
        math.innerHTML = `\\begin{align}
& ( ${x} + ${C1} )( ${x} - ${C2} ) \\\\[.5em]
=& ${x.add(C1)} ${x.sub(C2)} \\\\[.5em]
=& ${f(x)}
\\end{align}`
        await MathJax.typesetPromise([math]);
    };

    await MathJax.startup.promise;
    
    await updateMath();
    plot.staticLayer.init();
    const d = await plot.dynamicLayer.init();
    d.draw(Number(slider.value));

    slider.addEventListener("input", async ({target: {value}}) => {
        await updateMath();
        await d.redraw(Number(value));
    });
}
#+end_src

And some CSS

#+begin_src css :results none :tangle style.css
#dualExample {
    position: relative;
    padding-bottom: 1em;
}

#dualExample > canvas {
    position: absolute;
    top: -10%;
    opacity: .4;
    z-index: -100;
}
#+end_src

** Multivariate Dual Numbers

#+attr_html: :class big-eqn
\begin{equation}
\langle {\color{blue} u},{\color{green} u'} \rangle \to \langle {\color{blue} u}, {\color{green} \nabla{}u} \rangle
\end{equation}

#+ATTR_REVEAL: :frag t
#+attr_html: :class big-eqn
\begin{equation}
\nabla{}u = \begin{bmatrix}\frac{\partial{}u}{\partial{}x_{1}} \\ \vdots \\ \frac{\partial{}u}{\partial{}x_{N}}\end{bmatrix}
\end{equation}

#+REVEAL: split

\begin{equation}
f(x_{1},x_{2}) = \sin(x_{1})(x_{1} + x_{2})
\end{equation}

#+begin_export html
<div id="graphMathContainer">
  <canvas id="graphStatic"></canvas>
  <canvas id="graphDynamic"></canvas>
  <input type="range" id="graphX1" min=-5 max=5 value=0 step=.01 />
  <input type="range" id="graphX2" min=-5 max=5 value=0 step=.01 />
  <div id="graphx1" class="graphMath graphMathC1 graphMathR1 smallGraphMath"></div>
  <div id="graphx2" class="graphMath graphMathC1 graphMathR2 smallGraphMath"></div>
  <div id="graphSin" class="graphMath graphMathC2 graphMathR1 smallGraphMath"></div>
  <div id="graphAdd" class="graphMath graphMathC2 graphMathR2 smallGraphMath"></div>
  <div id="graphOutput" class="graphMath"></div>
</div>
#+end_export

*** CSS & JS for the graph                                         :noexport:

#+begin_src css :results none :tangle style.css
#graphMathContainer {
    position: relative;
}

input#graphX1 {
    position: absolute;
    left: 0;
    top: 68px;
}

input#graphX2 {
    position: absolute;
    left: 0;
    top: 410px;
}

div.graphMath {
    position: absolute;
}

div.smallGraphMath {
    font-size: .66em;
}

.graphMathC1 {
    left: 320px;
}

.graphMathC2 {
    left: 720px;
}

.graphMathR1 {
    top: 70px;
}

.graphMathR2 {
    top: 420px;
}

div#graphOutput {
    left: 1200px;
    top: 160px;
}
#+end_src

#+begin_src js :results none :tangle src/dualN.js
export default class DualN {
    constructor(primal, gradients) {
        this.primal = primal;
        this.gradients = gradients;
    }

    toString() {
        return `$$\\left\\langle{\\color{blue}${this.primal.toFixed(2)}},{\\color{green}\\begin{bmatrix}${this.gradients.map(g => g.toFixed(2)).join(" \\\\ ")}\\end{bmatrix}}\\right\\rangle$$`;
    }

    variable(x, N, i) {
        this.primal = x;
        this.gradients = Array(N).fill(0);
        this.gradients[i] = 1;
        return this;
    }

    add(d) {        
        return new DualN(this.primal + d.primal, this.gradients.map((g,i) => g + d.gradients[i]));
    }

    mul(d) {
        return new DualN(this.primal * d.primal,
                         this.gradients.map((g,i) => this.primal * d.gradients[i]  + d.primal * g));
    }

    sin() {
        return new DualN(Math.sin(this.primal), this.gradients.map((g,i) => g * Math.cos(this.primal)));
    }
};
#+end_src

#+begin_src js :results none :tangle src/graph.js
import DualN from "./dualN";

const CANVAS = { WIDTH: 1200, HEIGHT: 500, PADDING: 0 };
const OPRADIUS = 75;

const f = x => x[0].add(x[1]).mul(x[0].sin());

export default async () => {
    const sliders = [
        document.getElementById("graphX1"),
        document.getElementById("graphX2")
    ];

    const math = {
        x1: document.getElementById("graphx1"),
        x2: document.getElementById("graphx2"),
        sin: document.getElementById("graphSin"),
        add: document.getElementById("graphAdd"),
        output: document.getElementById("graphOutput"),
    };
    
    const graph = {
        staticLayer: {
            canvas: document.getElementById("graphStatic"),

            drawOp: (ctx, x, y, svg) => {
                ctx.beginPath();
                ctx.arc(
                    x, y, OPRADIUS, 0, 2 * Math.PI
                );
                ctx.stroke();

                ctx.drawImage(svg,
                              x - svg.naturalWidth,
                              y - svg.naturalHeight,
                              svg.naturalWidth * 2,
                              svg.naturalHeight * 2);
            },
            
            async init() {
                if (this.canvas.getContext) {
                    this.canvas.setAttribute("width", CANVAS.WIDTH);
                    this.canvas.setAttribute("height", CANVAS.HEIGHT);

                    const xml = new XMLSerializer();
                    const tex2imgSrc = tex => "data:image/svg+xml;base64, " +
                          window.btoa(unescape(encodeURIComponent(
                              xml.serializeToString(MathJax.tex2svg(tex).firstElementChild)
                          )));

                    const ctx = this.canvas.getContext("2d");
                    
                    let img = new Image();
                    img.src = tex2imgSrc("x_{1}");
                    await img.decode();
                    this.drawOp(ctx, 100, OPRADIUS + 5, img);

                    ctx.beginPath();
                    ctx.moveTo(100 + OPRADIUS, OPRADIUS + 5);
                    ctx.lineTo(500 - OPRADIUS, OPRADIUS + 5);
                    ctx.stroke();

                    ctx.beginPath();
                    ctx.moveTo(500 - OPRADIUS, OPRADIUS + 5);
                    ctx.lineTo(500 - OPRADIUS - 10, OPRADIUS + 5 + 5);
                    ctx.lineTo(500 - OPRADIUS - 10, OPRADIUS + 5 - 5);
                    ctx.closePath();
                    ctx.fill();

                    ctx.beginPath();
                    ctx.moveTo(100 + OPRADIUS - 4, OPRADIUS + 5 + 25);
                    ctx.lineTo(500 - OPRADIUS + 3, CANVAS.HEIGHT - (OPRADIUS + 5) - 25);
                    ctx.stroke();

                    ctx.beginPath();
                    ctx.moveTo(500 - OPRADIUS + 3, CANVAS.HEIGHT - (OPRADIUS + 5) - 25);
                    ctx.lineTo(500 - OPRADIUS + 3 - 10, CANVAS.HEIGHT - (OPRADIUS + 5) - 25 - 4);
                    ctx.lineTo(500 - OPRADIUS + 3 - 5, CANVAS.HEIGHT - (OPRADIUS + 5) - 25 - 13);
                    ctx.closePath();
                    ctx.fill();
                    
                    img = new Image();
                    img.src = tex2imgSrc("x_{2}");
                    await img.decode();
                    this.drawOp(ctx, 100, CANVAS.HEIGHT - (OPRADIUS + 5), img);

                    ctx.beginPath();
                    ctx.moveTo(100 + OPRADIUS, CANVAS.HEIGHT - (OPRADIUS + 5));
                    ctx.lineTo(500 - OPRADIUS, CANVAS.HEIGHT - (OPRADIUS + 5));
                    ctx.stroke();

                    ctx.beginPath();
                    ctx.moveTo(500 - OPRADIUS, CANVAS.HEIGHT - (OPRADIUS + 5));
                    ctx.lineTo(500 - OPRADIUS - 10, CANVAS.HEIGHT - (OPRADIUS + 5) + 5);
                    ctx.lineTo(500 - OPRADIUS - 10, CANVAS.HEIGHT - (OPRADIUS + 5) - 5);
                    ctx.closePath();
                    ctx.fill();

                    img = new Image();
                    img.src = tex2imgSrc("\\sin");
                    await img.decode();
                    this.drawOp(ctx, 500, OPRADIUS + 5, img);

                    ctx.beginPath();
                    ctx.moveTo(500 + OPRADIUS, OPRADIUS + 5);
                    ctx.lineTo(900 - OPRADIUS + 3, CANVAS.HEIGHT / 2 - 25);
                    ctx.stroke();

                    ctx.beginPath();
                    ctx.moveTo(900 - OPRADIUS + 3, CANVAS.HEIGHT / 2 - 25);
                    ctx.lineTo(900 - OPRADIUS + 3 - 11, CANVAS.HEIGHT / 2 - 25);
                    ctx.lineTo(900 - OPRADIUS + 3 - 8, CANVAS.HEIGHT / 2 - 25 - 10);
                    ctx.closePath();
                    ctx.fill();

                    img = new Image();
                    img.src = tex2imgSrc("+");
                    await img.decode();
                    this.drawOp(ctx, 500, CANVAS.HEIGHT - (OPRADIUS + 5), img);

                    ctx.beginPath();
                    ctx.moveTo(500 + OPRADIUS, CANVAS.HEIGHT - (OPRADIUS + 5));
                    ctx.lineTo(900 - OPRADIUS + 3, CANVAS.HEIGHT / 2 + 25);
                    ctx.stroke();

                    ctx.beginPath();
                    ctx.moveTo(900 - OPRADIUS + 3, CANVAS.HEIGHT / 2 + 25);
                    ctx.lineTo(900 - OPRADIUS + 3 - 11, CANVAS.HEIGHT / 2 + 25);
                    ctx.lineTo(900 - OPRADIUS + 3 - 8, CANVAS.HEIGHT / 2 + 25 + 10);
                    ctx.closePath();
                    ctx.fill();

                    img = new Image();
                    img.src = tex2imgSrc("*");
                    await img.decode();
                    this.drawOp(ctx, 900, CANVAS.HEIGHT / 2, img);

                    ctx.beginPath();
                    ctx.moveTo(900 + OPRADIUS, CANVAS.HEIGHT / 2);
                    ctx.lineTo(900 + OPRADIUS + 50, CANVAS.HEIGHT / 2);
                    ctx.stroke();

                    ctx.beginPath();
                    ctx.moveTo(900 + OPRADIUS + 50, CANVAS.HEIGHT / 2);
                    ctx.lineTo(900 + OPRADIUS + 40, CANVAS.HEIGHT / 2 + 5);
                    ctx.lineTo(900 + OPRADIUS + 40, CANVAS.HEIGHT / 2 - 5);
                    ctx.closePath();
                    ctx.fill();
                }
            }
        },

        dynamicLayer: {
            canvas: document.getElementById("graphDynamic"),
            
            artist: ctx => ({
                redraw(X) {

                }
            }),
            
            async init() {
                if (this.canvas.getContext) {
                    return this.artist(this.canvas.getContext("2d"));
                }
            }
        }
    };

    const updateMath = async () => {
        const X = [
            new DualN(0, []).variable(Number(sliders[0].value), sliders.length, 0),
            new DualN(0, []).variable(Number(sliders[1].value), sliders.length, 1)
        ];

        MathJax.typesetClear([math.output, math.x1, math.x2, math.sin, math.add]);
        math.x1.innerHTML = `${X[0]}`;
        math.x2.innerHTML = `${X[1]}`;
        math.sin.innerHTML = `${X[0].sin()}`;
        math.add.innerHTML = `${X[0].add(X[1])}`;
        math.output.innerHTML = `${f(X)}`;
        await MathJax.typesetPromise([math.output, math.x1, math.x2, math.sin, math.add]);
    };

    await MathJax.startup.promise;

    await graph.staticLayer.init();
    const d = await graph.dynamicLayer.init();
    await updateMath();

    sliders.forEach(s => s.addEventListener("input", async e => {
        await d.redraw(sliders.map(s => s.value));
        await updateMath();
    }));
};
#+end_src

** Why Would We Want To Do Any Of This?

#+ATTR_REVEAL: :frag (appear)
- /End-to-end differentiability/ is fundamental to *gradient-based*
  optimisation methods.
- Gradient descent is fundamental to contemporary approaches to
  machine learning.
- /Automatic Differentiation/ and /Differentiable Programming/ ensure
  end-to-end differentiability.

* What Does This Have To Do With Faust?

#+ATTR_REVEAL: :frag (appear)
- Many of Faust's primitive operators are trivially differentiable.
- Dual-number automatic differentiation can be implemented in Faust.
- Pattern matching can be used to /override/ Faust's primitives with
  differentiable implementations.

** Gradient-based Parameter Optimisation

#+ATTR_REVEAL: :frag t
Take ground truth circuit producing target output signal \(y\), and
optimisable circuit producing estimate output \(\hat{y}\).

#+ATTR_REVEAL: :frag t
Compare \(y\) and \(\hat{y}\) via a loss function.

#+ATTR_REVEAL: :frag t
\begin{equation}
\mathcal{L}(y,\hat{y})[n] = ||\hat{y}[n] - y[n]||
\end{equation}

#+ATTR_REVEAL: :frag t
Partial derivatives of the loss function are the *gradients* in the
direction that minimises its value.

#+ATTR_REVEAL: :frag t
/Backpropagating/ the gradients, we can update the parameters of the
optimisable circuit.

* Examples
#+ATTR_HTML: :target _blank
[[https://faustide.grame.fr][🚀]]

* Provisos, Caveats

#+ATTR_REVEAL: :frag (appear)
- Automatic Differentiation has a reverse mode too --- and it may be
  more efficient.
- Some of Faust's primitives don't have well-defined derivatives.
- The derivative of a variable delay defies a closed-form solution.
- Pattern matching has its limitations.
- Loss taken in time-domain; only works for deterministic input, not
  perceptually-informed.
- Optimisation \neq generalisation.

* Thank you

[[https://github.com/hatchjaw/faust-ddsp]]

* Set up Javascript components                                     :noexport:

#+begin_src js :results none :tangle src/main.js
import xSquared from "./xsquared.js";
import numerical from "./numerical.js";
import graph from "./graph.js";

// Waiting for this callback doesn't appear to help with MathJax
// issues.
Reveal.on("ready", async e => {
    await MathJax.startup.promise;
    xSquared();
    numerical();
    graph();
});
#+end_src

* Emacs Setup                                                      :noexport:

Add a hook to run =npm= before export:

# Local Variables:
# eval: (add-hook 'org-export-before-processing-functions
# (lambda (backend)
# (interactive)
# (message "building js...")
# (shell-command-to-string "npm run build")))
# End:
