# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Duelling Signals: Differentiable DSP in Faust
#+AUTHOR: Thomas Rushton

#+OPTIONS: num:nil toc:nil reveal_width:1200

#+REVEAL_ROOT: ./reveal.js
# #+REVEAL_THEME: white
#+REVEAL_PLUGINS: (math)
#+REVEAL_EXTRA_CSS: phd-day-2024.css
#+REVEAL_MIN_SCALE: 1.0
#+REVEAL_MAX_SCALE: 1.0
# #+REVEAL_HIGHLIGHT_CSS: %r/plugin/highlight/monokai.css
# #+REVEAL_HIGHLIGHT_CSS: %r/node_modules/highlight.js/styles/zenburn.css
# #+REVEAL_EXTRA_SCRIPTS: <script src="https://cdn.jsdelivr.net/npm/@grame/faust-web-component@0.3.2/dist/faust-web-component.js" defer></script>
#+REVEAL_EXTRA_SCRIPTS: ("faust-web-component.js" "faust-stop-on-slidechanged.js")
#+REVEAL_TITLE_SLIDE: <h1>%t</h1><h2>%s</h2><h3>%a</h3>

* About This Presentation                                          :noexport:

This =org= file describes my presentation for the 2024 CITI lab PhD Day.

** Dependencies

- =org-re-reveal= ([[https://gitlab.com/oer/org-re-reveal/-/tree/main][gitlab]]), which enables export support from Org to [[https://revealjs.com/][Reveal.js]];
- =faust-web-component.js=, which provides a customised version of the
  ~<faust-editor>~ [[https://github.com/grame-cncm/faust-web-component][web component]] with support for specifying
  attributes and styling the content area of the component;
- =ob-faust= ([[https://github.com/hatchjaw/ob-faust][github]]), which adds (basic) support for Faust to Org Babel;

** Running the Presentation

From the reveal.js directory (=../reveal.js=), run:

#+begin_src shell :noeval :exports code
npm start -- --root=../
#+end_src

Then navigate to [[localhost:8000/phd-day-2024.html]].

* Differentiable Programming

- Differentiate a program (analytically) with respect to its inputs
  + Automatic differentiation
- Compute the sensitivity of a program's outputs to changes in its
  inputs
  
\begin{equation*}
\frac{\partial y}{\partial\mathbf{x}} = \begin{bmatrix}\frac{\partial y}{\partial x_1} \\
\vdots \\
\frac{\partial y}{\partial x_N}\end{bmatrix}
\end{equation*}

#+REVEAL: split

- Key to gradient-based optimisation problems
- Native support in some languages, e.g. Swift
- Support via libraries in Python, Julia, etc.

* Differentiable DSP

- Application of differentiable programming to audio tasks
  + Source separation
  + Timbre transfer
  + Parameter estimation, etc.
- Possible in Faust via the DawDreamer project
  + Transpilation of Faust to Python
  + AD via JAX

* The Faust Programming Language

Faust is a domain-specific, functional programming language for
digital signal processing and audio synthesis.

- Syntax describes a /circuit/ through which /signals/ propagate
- (Almost) everything in Faust is a signal, or something that operates
  on signals

** A basic Faust program

- Two input signals — implicit
- One output signal: the sum of the inputs

#+begin_src faust :results html :exports both :tab svg :sizes 0,100 :class add
process = +;
#+end_src

#+RESULTS:
#+begin_export html
<faust-editor sizes="[0,100]" tab="svg">
<!--
process = +;
-->
</faust-editor>
#+end_export

** A basic Faust synthesiser

#+begin_src faust :results html :exports both :tab ui :sizes 0,100 :class synth
import("stdfaust.lib");
process = sum(i, 10, os.osc(220*((i+1)^1.8)) : *(1/(i+1))) 
    : *(en.ar(.025, 2.5, button("gate")))
    : *(.5)
    <: _,_;
#+end_src

#+RESULTS:
#+begin_export html
<faust-editor sizes="[0,100]" tab="ui">
<!--
import("stdfaust.lib");
process = sum(i, 10, os.osc(220*((i+1)^1.8)) : *(1/(i+1))) 
    : *(en.ar(.025, 2.5, button("gate")))
    : *(.5)
    <: _,_;
-->
</faust-editor>
#+end_export

** A recursive Faust program

- One input
- One output: the sum of the input and scaled, delayed copy of the output

#+begin_src faust :results html :exports both :tab svg :sizes 0,100 :class echo
process = +~(@(10000) : *(.5));
#+end_src

#+RESULTS:
#+begin_export html
<faust-editor sizes="[0,100]" tab="svg">
<!--
process = +~(@(10000) : *(.5));
-->
</faust-editor>
#+end_export

* DDSP in Faust

** A Differentiable Primitive

#+begin_src faust :results silent
process = +;
#+end_src

#+ATTR_REVEAL: :frag t
$y = u + v$

#+ATTR_REVEAL: :frag t
Differentiate wrt. $x$:
\[
\frac{dy}{dx} = \frac{d}{dx}\left(u + v\right) = \frac{du}{dx} +
\frac{dv}{dx}
\]

#+REVEAL: split

- We can represent the addition and its derivative in parallel

#+begin_src faust :results html :exports both :tab svg :sizes 0,100 :class dual-add
process = +,+;
#+end_src

#+RESULTS:
#+begin_export html
<faust-editor sizes="[0,100]" tab="svg" class="dual-add">
<!--
process = +,+;
-->
</faust-editor>
#+end_export

#+ATTR_REVEAL: :frag t
\begin{align*}
\langle y, \frac{dy}{dx} \rangle
&= \langle u, \frac{du}{dx} \rangle + \langle v, \frac{dv}{dx} \rangle \\
&= \langle u + v, \frac{du}{dx} + \frac{dv}{dx} \rangle
\end{align*}

Dual number \rightarrow */Dual signal/*

** /Where's the derivative?/

#+REVEAL: split
It's assumed that each derivative has been calculated elsewhere

#+begin_src faust :results html :exports both :tab svg :sizes 0,100 :class dual-add-again
x = hslider("x", 0, -1, 1, .1);
u = _;
v = x;
dudx = 0;
dvdx = 1;
process = u,v,dudx,dvdx : +,+;
#+end_src

#+RESULTS:
#+begin_export html
<faust-editor sizes="[0,100]" tab="svg" class="dual-add-again">
<!--
x = hslider("x", 0, -1, 1, .1);
u = _;
v = x;
dudx = 0;
dvdx = 1;
process = u,v,dudx,dvdx : +,+;
-->
</faust-editor>
#+end_export

** Making it /Automatic/

#+begin_src faust :results silent
diffInput = _,0;
diffSlider = hslider("x", 0, -1, 1, .1),1;
#+end_src

#+ATTR_REVEAL: :frag t
#+begin_src faust :results silent
diffAdd = route(4,4,(1,1),(2,3),(3,2),(4,4)) : +,+;
#+end_src

#+REVEAL: split

#+begin_src faust :results html :exports results :tab svg :sizes 0,100 :class dual-add-again
diffInput = _,0;
diffSlider = hslider("x", 0, -1, 1, .1),1;
diffAdd = route(4,4,(1,1),(2,3),(3,2),(4,4)) : +,+;
process = diffInput,diffSlider : diffAdd;
#+end_src

#+RESULTS:
#+begin_export html
<faust-editor sizes="[0,100]" tab="svg" class="dual-add-again">
<!--
diffInput = _,0;
diffSlider = hslider("x", 0, -1, 1, .1),1;
diffAdd = route(4,4,(1,1),(2,3),(3,2),(4,4)) : +,+;
process = diffInput,diffSlider : diffAdd;
-->
</faust-editor>
#+end_export

** Multivariate Problems

*** Variable gain and DC offset

#+begin_src faust :results html :exports both :tab svg :sizes 0,100 :class multivariate
x1 = hslider("gain", .5, 0, 1, .1);
x2 = hslider("dc", 0, -1, 1, .1);
process = _,x1 : *,x2 : +;
#+end_src

#+RESULTS:
#+begin_export html
<faust-editor sizes="[0,100]" tab="svg" class="multivariate">
<!--
x1 = hslider("gain", .5, 0, 1, .1);
x2 = hslider("dc", 0, -1, 1, .1);
process = _,x1 : *,x2 : +;
-->
</faust-editor>
#+end_export

\[y = uv + w, \quad v = x_1, \quad w = x_2\]

#+ATTR_REVEAL: :frag t
\[
y' = \frac{\partial y}{\partial \mathbf{x}}
= \begin{bmatrix}\frac{\partial y}{\partial x_1} \\
\frac{\partial y}{\partial x_2}\end{bmatrix}
\]

*** Dual Signal Representation

\begin{align*}
\langle y,y' \rangle &=
\langle u,u' \rangle \langle v,v' \rangle + \langle w,w' \rangle \\
&= \langle uv,u'v + v'u \rangle + \langle w,w' \rangle \\
&= \langle uv + w,u'v + v'u + w'\rangle
\end{align*}

*** Implementation in Faust

#+begin_src faust :results html :exports results :tab svg :sizes 0,100 :class gain-dc
NVARS = 2;
x1 = diffSlider(NVARS,1,.5,0,1,.1);
x2 = diffSlider(NVARS,2,0,-1,1,.1);
process = diffInput(NVARS),x1 : diffMul(NVARS),x2 : diffAdd(NVARS);

diffInput(nvars) = _,par(i,nvars,0);

diffSlider(nvars,I,init,lo,hi,step) = hslider("x%I",init,lo,hi,step),par(i,nvars,i==I-1);

diffAdd(nvars) = route(nIN,nOUT,
        (u,1),(v,2), // u + v
        par(i,nvars,
            (u+i+1,dx),(v+i+1,dx+1) // du/dx_i + dv/dx_i
            with {
                dx = 2*i+3; // Start of derivatives wrt ith var
            }
        )
    ) with {
        nIN = 2+2*nvars;
        nOUT = nIN;
        u = 1;
        v = u+nvars+1;
    } : +,par(i, nvars, +);

diffMul(nvars) = route(nIN,nOUT,
        (u,1),(v,2), // u * v
        par(i,nvars,
            (u,dx),(dvdx,dx+1),   // u * dv/dx_i
            (dudx,dx+2),(v,dx+3)  // du/dx_i * v
            with {
                dx = 4*i+3; // Start of derivatives wrt ith var
                dudx = u+i+1;
                dvdx = v+i+1;
            }
        )
    ) with {
        nIN = 2+2*nvars;
        nOUT = 2+4*nvars;
        u = 1;
        v = u+nvars+1;
    } : *,par(i, nvars, *,* : +);
#+end_src

** Gradient Descent



* Outlook

- More loss functions, optimisers, momentum, parameter normalisation...
- Frequency-domain loss
- Reverse mode...
- Weight computation; real-time inference
- To be developed further as a Google Summer of Code project

* How I made this presentation...

** Literate programming is kind of cool, don't you think?

