#+title:      Automatic Differentiation
#+date:       [2024-08-12 lun. 14:06]
#+filetags:   :autodiff:
#+identifier: 20240812T140652

Automatic Differentiation (AD, autodiff) [cite:@baydinAutomatic2018]
is a method for computing derivatives with particular application to
computer programming. It is the computational/mathematical backbone
supporting contemporary approaches to machine learning and parameter
optimisation via gradient descent.

Autodiff has two main modes, [[denote:20240812T142629][forward mode]] and [[denote:20240813T115157][reverse mode]]. In forward
mode, derivatives are propagated from inputs to outputs through the
computation graph, one per input variable; in reverse mode,
derivatives are propagated backwards, one per output. A combination of
forward and backward modes --- so-called /cross-country mode/
[cite:@laueSimple2020] --- may prove more efficient in certain
contexts.

* Autodiff-related topics

- [[denote:20240813T191939][Differentiable Delay]]
- [[denote:20240813T191958][Differentiable Recursion]]
