#+title:      Libmapper
#+date:       [2024-10-13 dim. 19:05]
#+filetags:   :nime:
#+identifier: 20241013T190559

"A library for connecting things"

Libmapper is presented as a comprehensive control data mapping
solution.

#+begin_quote
libmapper is an open-source, cross-platform software library for
declaring data signals on a shared network and enabling arbitrary
connections to be made between them. libmapper creates a distributed
mapping system/network, with no central points of failure, the
potential for tight collaboration and easy parallelization of media
synthesis. The main focus of libmapper development is to provide tools
for creating and using systems for interactive control of media
synthesis.
#+end_quote

The T-Stick is listed as a project that uses =libmapper=.

=mapperd= [[[https://github.com/libmapper/mapperd][github]]], a tool for providing access to the libmapper API
in the browser (or other sandboxed environments), was presented at
[[denote:20241013T170234][IS2]] 2024.

* Resources

- GitHub team [[https://github.com/libmapper][page]]
- Libmapper GitHub [[https://github.com/libmapper/libmapper][repo]]
