:PROPERTIES:
:CUSTOM_ID: h:4d282945-0024-4fd7-a670-080c0377734e
:END:
#+title:      Differentiable Delay
#+date:       [2024-08-13 mar. 19:19]
#+filetags:   :autodiff:ddsp:faust:
#+identifier: 20240813T191939

Let's consider the case of delaying a function \(f(v)\), \(v = v(x)\),
by some fixed time \(\tau\):

#+NAME: eq:fixed-delay
\begin{align}
y = f(v) &= v(t - \tau).
\end{align}

The derivative of the above, via the [[denote:20240819T095042][The Chain Rule]], is:

#+NAME: eq:diff-delay-1
\begin{equation}
\frac{dy}{\partial{}x} = \frac{dy}{dv}\frac{dv}{dx} \\
\end{equation}

But what is \(\frac{dy}{dv}\), i.e. the derivative of a delayed
signal?  First, the impulse response the ideal delay system is a
time-shifted impulse:

#+NAME: eq:ideal-delay-ir
\begin{equation}
h(t) = \delta(t - \tau),
\end{equation}

and we can represent eqref:eq:fixed-delay as a convolution of \(v(t)\)
and that impulse response:

#+NAME: eq:conv
\begin{equation}
v(t - \tau) = v(t) \ast h(t).
\end{equation}

Next, recall the convolution property of the Fourier transform:

#+NAME: eq:fourier-conv
\begin{equation}
x(t) \ast h(t) \quad\xleftrightarrow{\mathcal{F}}\quad X(j\omega)H(j\omega),
\end{equation}

which we could also notate as:

#+NAME: eq:conv-mult
\begin{equation}
\mathcal{F}[x(t) \ast h(t)] = \mathcal{F}[x(t)]\cdot\mathcal{F}[h(t)] = X(j\omega)H(j\omega),
\end{equation}

and the [[denote:20240819T103529][derivative property]]:

#+NAME: eq:fourier-diff
\begin{equation}
\frac{d}{dt}x(t) \quad\xleftrightarrow{\mathcal{F}}\quad j\omega{}X(j\omega),
\end{equation}

from which it can be deduced that:

#+NAME: eq:fourier-conv-diff
\begin{equation}
  \begin{rcases}
    \frac{d}{dt}(x(t) \ast h(t)) \\
    \frac{d}{dt}(x(t)) \ast h(t) \\
    x(t) \ast \frac{d}{dt}(h(t))
  \end{rcases} \quad\xleftrightarrow{\mathcal{F}}\quad j\omega{}X(j\omega)H(j\omega).
\end{equation}

To put it another way, using the notation from eqref:eq:conv-mult:

#+NAME: eq:diff-conv
\begin{align}
\mathcal{F}\left[\frac{d}{dt}(x(t) \ast h(t))\right]
  &= \mathcal{F}\left[\left(\frac{d}{dt}x(t)\right)\right]\cdot\mathcal{F}[h(t)] \\
  &= \mathcal{F}[x(t)]\cdot\mathcal{F}\left[\left(\frac{d}{dt}h(t)\right)\right] \\
  &= j\omega{}X(j\omega)H(j\omega)
\end{align}

Anyway, thus:

#+NAME: eq:diff-delay
\begin{align}
\frac{dy}{dx} &= \frac{dv}{dx}\frac{d}{dv}(v(t) \ast h(t)) \\
  &= \frac{dv}{dx}\frac{d}{dv}(v(t)) \ast h(t) \\
  &= \frac{dv}{dx} \ast h(t) \\
  &= v'(t - \tau).
\end{align}

Or as a dual number, in discrete time:

#+NAME: eq:diff-delay-dual
\begin{equation}
\langle v,v' \rangle[n - k] = \langle v[n - k], v'[n - k] \rangle
\end{equation}

And in Faust:

#+begin_src faust :results none
diff(mem) = mem,par(i, N, mem);
#+end_src

* Variable Delay



* Resources

- [[https://www.youtube.com/watch?v=pkL7cuy29XU][YouTube video]]: Convolution & Derivatives
- Maths Stack Exchange: [[https://math.stackexchange.com/questions/177239/derivative-of-convolution][Derivative of Convolution]]
