#+title:      MIDIWeave: A Gesture-Based Controller for Fluid and Intuitive MIDI Expression in Music Creation
#+date:       [2025-03-04 mar. 09:36]
#+filetags:   :bib:nime:review:
#+identifier: 20250304T093640
#+reference:  anonMIDIWeave2025

* Summary

This paper describes a gesture-based computer vision system for MIDI
control. The work is situated in the context of the search for
intuitive MIDI control by way of alternatives to traditional physical
interfaces, and includes a respectable exploration of related work in
gestural and touch-free interfaces. The importance of gesture in
musical practice is alluded to, as is that of responsiveness and
effective mapping strategies. An accessible system, it uses a standard
webcam for capture, and maps three distinct hand gestures to musical
control parameters, essentially "stop MIDI transmission", "start MIDI
Transmission", and an assignable, open-hand gesture for use with MIDI
CC messages, the particular control change message being assignable
via a slider. The proposed system was subjected to technical
evaluation of its latency, and informal user testing.

The authors do not make a strong case for the novelty of their
work. Computer vision-based controllers have been demonstrated
previously, and are in fact referenced in this paper ([11, 18], the
latter from last year's NIME conference). MIDIWeave prioritises the
transmission of MIDI data over MuGeVI's OSC, but since OSC is widely
supported and more flexible, and in light of MuGeVI's variety of
use-cases, it is difficult to view MIDIWeave as an advancement of the
idea. The addition of a latency evaluation is a welcome addition, and
the system does indeed appear responsive in the supplementary
video; the user evaluation is undermined, however, by the fact that
although a Likert scale questionnaire was used, none of the associated
quantitative results are shared.

The implementation appears solid, but, for want of an original take on
the topic, I cannot recommend it for inclusion.

* Notes

- The 50 ms perceptual limit on latency (§4.2) is in need of a source,
  and any such limit varies with the target application. For
  percussive interfaces it can be lower than 10 ms.
- The link associated with reference [7] appears to be invalid.
