#+title:      Is Music in the Air? Evaluating 4G and 5G Support for the Internet of Musical Things
#+date:       [2025-01-17 ven. 10:28]
#+filetags:   :bib:networkedaudio:
#+identifier: 20250117T102838
#+reference:  vignatiMusic2024

* Summary

Vignati et al. discuss the viability of 4G/5G for [[denote:20250117T104518][Networked Music
Performance]] and [[denote:20250117T104824][IoMusT]] stuff. Authors state that the potential of
cellular networks for IoMusT remains largely unexplored.

* Discussion

** Is 5G new?

They repeatedly make the strange assertion that 5G is a new
thing. "[S]everal companies have been installing their first 5G cell
towers," etc. 5G has been around for years, hasn't it? They're basing
their assertions on a 2019 Cisco white paper that estimated 5G making
up 3.5% of connections by 2022; in 2023, in North America, it was
29%, [[https://www.5gamericas.org/global-5g-connections-surge-to-1-76-billion-66-percent-growth-year-over-year-as-north-america-leads-charge/][apparently]]. I guess they might've started writing their paper a
fair while before it was published.

** /Inconceivable!/

They do some heavy (and unreferenced) straw-manning in §1.D with
"common misconceptions" about the intersection of 5G and IoMusT. It's
weird.

** Infinite Grift

Naturally, they're shilling for Elk OS in §2.A.
