#+title:      ESP-NOW MIDI Protocol and Enomik (ESP-NOW MIDI Toolkit): Wired and Wireless MIDI Devices with an Optional Code-free Workflow
#+date:       [2026-04-16 jeu. 09:13]
#+filetags:   :bib:review:smc:
#+identifier: 20260416T091359
#+reference:  geisslESPNOW2026

* Summary

The author presents a system for wireless communication between
devices in musical instruments and interactive systems. Enomik
(ESP-NOW MIDI Toolkit) uses the ESP-NOW protocol as a transmission
medium for wireless MIDI data and provides a browser-based
configuration interface.

The work appears solid and novel and the system is evaluated via a
collection of round-trip latency benchmarks; it has also been put to
use in a performance scenario, though this was not formally
evaluated. Latency measurements appear to compare favourably with
equivalent transmission over Wi-Fi and Bluetooth.

A well-written paper, I have only a handful of minor suggestions for
improvement (see below). In all I believe the work represents a
valuable contribution to this year's conference and I recommend it for
acceptance.

* Observations

- Though elucidated in the paper's title, a clarification in the body
  of the text that Enomik is an acronym for ESP-NOW MIDI Toolkit would
  be a good idea.
- Figure 1: It is not clear which of the two devices pictured is the
  wireless MIDI dongle and which the client device.
- An explanation of the acronym IDC16 would have been appreciated.
- It is not made clear what the "obstacles" are in the reported
  tests. Are these human bodies, walls, etc.?
