#+title:      Harmonic Care and Embodied Interplay in a Participatory Audiovisual Instrument
#+date:       [2026-04-16 jeu. 09:13]
#+filetags:   :bib:review:smc:
#+identifier: 20260416T091320
#+reference:  kaufmanHarmonic2026

* Summary

This paper presents /Somatic Continuum/, an installation for
audio-visual interaction based on the author's concept of /harmonic
care/, i.e. constraint of generated sonic material to a D minor
tonality. The system tracks facial landmarks and hand positions using
FaceMesh and a Leap Motion controller respectively and maps the
signals generated by these tools to various sonic and visual
characteristics of the output of the interface. Based on the
supplementary video, it appears to be a well-realised work, combining
interesting, artful visuals with a coherent auditory
accompaniment. The author makes a good case for the work's relevance
to the theme of this year's conference.

The text occasionally reads like promotional or advertising copy,
e.g. §1 "The system remains open enough to feel alive, but constrained
enough to remain playable and sound beautiful." Even the term
"harmonic care" strikes this reviewer as a grandiose way of describing
a constraint on the harmonic context of the sonic output. There are no
figures to illustrate the structure of the system, no systematic
description of the purported four-hundred iterations through which the
installation was developed, and no formal evaluation beyond some
anecdotal remarks in section 6. It is difficult, based on these
omissions, in light of the near-absence of bibliographical references
(see my remark below), and despite the apparent strength of the
implementation, to recommend this paper for inclusion, therefore I
submit an evaluation of /reject/.

* Observations

It is strange, jarring even, that the author chose not to use the
standard SMC conference template for their paper, choosing instead
white sans-serif text on a black background without line numbers. If
accepted, I would expect the author to transfer their work to the
approved template.

To the best of my knowledge, only one of the ten bibliographical
entries is referenced in the text ([6], Magnusson). This is highly
unusual to say the least, and calls into question the scientific
rigour of the work.

In section 6 it is announced that "AI was used". Although not "the
paper's main contribution", this is in important aspect of the system
and would be best announced in the abstract

* Proofreading

- §2, paragraph 2: The acronym "ML" is used having not previously been
introduced. Presumably this stands for "machine learning".
- §4, paragraph 5, §6, paragraph 1: "Kaufman" -> "The author".
