# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Differentiable DSP in Faust
# #+AUTHOR: Thomas Rushton

#+EXPORT_FILE_NAME: out/ifc24
#+OPTIONS: toc:nil ':t ^:{} num:3
# #+LATEX_COMPILER: latexmk
#+LATEX_CLASS: ifc24
#+BIBLIOGRAPHY: IFC-24.bib
#+CITE_EXPORT: bibtex
#+LATEX_HEADER: \RequirePackage[]{ifc24-style}

#+begin_abstract
This is the template file for the proceedings of the third \F{}
International Conference (IFC-24).
This template has been derived from IFC-20 templates and aims at producing
conference proceedings in electronic form.
The format is essentially the one used for ICASSP conferences. Please use
either this \LaTeX{} or the accompanying Word formats when preparing your
submission.

Using the ~environment~ expression and pattern matching abstraction,
it is possible to write \F{} code that is differentiable end-to-end,
facilitating the computation and propagation of gradients, and in turn
supporting the creation of parameter optimisation
algorithms. Differentiable programming in Faust could serve as a
platform for a \F{}-native approach to machine learning problems.
#+end_abstract

* Latex Setup                                                      :noexport:
:PROPERTIES:
:HEADER-ARGS: :tangle out/ifc24-style.sty :results silent
:END:

Remember to tangle =C-c C-v t= before exporting.

** Basics

#+begin_src latex
\ProvidesPackage{ifc24-style}[2024/07/12 v0.1 Bundling IFC24 LaTeX style]
#+end_src

** Author(s)

Title is taken from the title attribute.

#+begin_src latex
%% \def\papertitle{Differentiable DSP in Faust}
\def\paperauthorA{Thomas Albert Rushton}
#+end_src

Authors' affiliations have to be set below.

** Packages
#+begin_src latex
\usepackage{IFC-24}
\usepackage{amsmath,amssymb,amsfonts,amsthm}
\usepackage{euscript}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{ifpdf}

\usepackage{color}
\usepackage{listings}
\definecolor{mygrey}{rgb}{0.96,0.96,0.96}
\lstset{
  tabsize=4,
  basicstyle=\ttfamily,
  backgroundcolor=\color{mygrey},
  captionpos=b,
  breaklines=true
}

\usepackage[english]{babel}
\usepackage{caption}
\usepackage{subfig, color}

\setcounter{page}{1}
\ninept

\usepackage{times}
\usepackage{inconsolata}

\usepackage[inkscapelatex=false]{svg}
#+end_src

** LaTeX vs PDFLaTeX

#+begin_src latex
% pdf-tex settings: detect automatically if run by latex or pdflatex
\newif\ifpdf
\ifx\pdfoutput\relax
\else
   \ifcase\pdfoutput
      \pdffalse
   \else
      \pdftrue
\fi

\ifpdf % compiling with pdflatex
  \usepackage[pdftex,
    pdftitle={\papertitle},
    pdfauthor={\paperauthorA, \paperauthorB, \paperauthorC, \paperauthorD},
    colorlinks=false, % links are activated as colror boxes instead of color text
    bookmarksnumbered, % use section numbers with bookmarks
    pdfstartview=XYZ % start with zoom=100% instead of full screen; especially useful if working with a big screen :-)
  ]{hyperref}
  \pdfcompresslevel=9
  \usepackage[pdftex]{graphicx}
  \usepackage[figure,table]{hypcap}
\else % compiling with latex
  \usepackage[dvips]{epsfig,graphicx}
  \usepackage[dvips,
    colorlinks=false, % no color links
    bookmarksnumbered, % use section numbers with bookmarks
    pdfstartview=XYZ % start with zoom=100% instead of full screen
  ]{hyperref}
  % hyperrefs are active in the pdf file after conversion
  \usepackage[figure,table]{hypcap}
\fi
#+end_src

** Macros
#+begin_src latex
% Special Macros
\newcommand{\F}{\textsc{Faust}}
#+end_src

** Author affiliations

Single author affiliation:

#+begin_src latex
\affiliation{\paperauthorA}
{\href{https://inria.fr}{Inria} \\ Villeurbanne, France\\
{\tt \href{mailto:thomas.rushton@inria.fr}{thomas.rushton@inria.fr}}
}
#+end_src

** Bibliography

#+begin_src latex
\bibliographystyle{IEEEbib}
#+end_src

* Adding Image Attributes                                          :noexport:

You've generated some image output from a source block; now you want
to add attributes like ~#+CAPTION:~, etc. There are a few approaches,
none of which is perfectly lovely. To suggest a couple:

- Generate an image result, then add attributes between the source
  block or ~CALL~ statement and the results.
#+begin_example
#+begin_src
...
#+end_src
#+CAPTION: A delightful caption
#+ATTR_LATEX: :width .5\linewidth
#+RESULTS:...
#+end_example

- Use [[https://orgmode.org/manual/Evaluating-Code-Blocks.html#How-to-evaluate-source-code-1][inline call]] syntax
#+begin_example
#+NAME: faust_code
#+begin_src faust
...
#+end_src

#+ATTR_LATEX: :width .75\linewidth
call_faust_code()[:results svg file :file image.svg :output-dir images
:exports results]
#+end_example

The latter doesn't provide a preview, but less manual intervention is
necessary.

One more thing: for regular source blocks, ~output-dir:~ and ~file:~
are combined into ~file:~ to produce =<outputdir>/<file>=. For
~#+CALL:~ this isn't the case; best to just use ~file:
<outputdir>/<file>~.

* More potentially useful syntax                                   :noexport:

This is a link to section [[*Conclusion]]

This template can be found on the conference website.

Here's a ref: [cite:@Smith2012]

Here's some code:

#+begin_src faust
  process = _;
#+end_src

And some inline code ~process = !;~

And floating code?

#+CAPTION: this code should float, because it has a caption
#+begin_src faust
process = 1;
#+end_src

* Introduction

Differentiable programming is "a programming paradigm in which complex
computer programs\dots can be differentiated end-to-end automically"

[Differentiable programming] may be supported by operator overloading...

There is a sense in which the block-diagram algebra of \F{} lends the
language intuitively to the problem of automatic differentiation. As
we will see, the language itself presents certain limitations in this
respect, but nonetheless we can achieve a great deal\dots

* Differentiable Programming in Faust

The possibility of writing differentiable code in any programming
language is contingent on the availability of derivative expressions
for the primitive operations in that language.

** Defining a Differentiable Primitive

As a basic example, consider the addition primitive; in \F{} one can
write:

#+NAME: faust_add
#+begin_src faust
  process = +;
#+end_src

which yields the block diagram:

#+CALL: faust_add() :results svg file :file images/add.svg :exports results
#+ATTR_LATEX: :width .5\linewidth
#+RESULTS:
[[file:add.svg]]

This signal processor, \(f\), takes two input signals, \(u\) and \(v\), and
produces one output signal, \(y\):

\begin{equation}
y = f(u, v) = u + v.
\end{equation}

Now, imagine that \(y\) is dependent on some variable \(x\), and that
we wish to know how sensitive \(y\) is to changes in \(x\). We can
produce an analytic expression for this sensitivity by differentiating
\(y\) with respect to \(x\):

\begin{equation}
\frac{dy}{dx} = \frac{d}{dx}(u + v) = \frac{du}{dx} + \frac{dv}{dx}.
\end{equation}

The addition rule of differentiation states that the derivative of an
addition is another addition, albeit one whose operands are the
derivatives of the operands to the original addition with respect to
the variable of interest. In \F{} we could express this as follows:

#+begin_src faust :results svg file :file images/dualadd.svg :exports both
  process = +,+;
#+end_src
#+ATTR_LATEX: :width .5\linewidth
#+RESULTS:
[[file:images/dualadd.svg]]

That being the case, we would be describing, in parallel, the /primal/
output signal \(y\), and its /tangent/ \(\frac{dy}{dx}\), which we
could in turn represent as follows:

#+NAME: eq:dualadd
\begin{align}
\langle y, \frac{dy}{dx} \rangle
&= \langle u, \frac{du}{dx} \rangle + \langle v, \frac{dv}{dx} \rangle \nonumber \\
&= \langle u + v, \frac{du}{dx} + \frac{dv}{dx} \rangle.
\end{align}

This is a /dual number/ representation, or, more accurately since \F{}
deals exclusively with signals, a /dual signal/ representation. Having
acces to the primal and tangent signals in parallel in this manner
lays the foundation for forward mode automatic differentiation in the
\F{} language.



* Conclusion

Don't know yet; working on it.

#+begin_export latex
%%\nocite{*}
#+end_export
#+PRINT_BIBLIOGRAPHY:

* Emacs Setup                                                      :noexport:

# Local Variables:
# eval:   (add-to-list 'org-latex-classes '("ifc24"
# "\\documentclass[twoside,a4paper]{article}
# [NO-DEFAULT-PACKAGES]"
# ("\\section{%s}" . "\\section*{%s}")
# ("\\subsection{%s}" . "\\subsection*{%s}")
# ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
# ("\\paragraph{%s}" . "\\paragraph*{%s}")
# ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# eval:   (setq org-latex-pdf-process '("latexmk -f -pdf -%latex \
# -interaction=nonstopmode -shell-escape -output-directory=%o %f"))
# eval:   (setq org-latex-src-block-backend 'listings)
# End:
