# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Differentiable DSP in Faust
# #+AUTHOR: Thomas Rushton

#+EXPORT_FILE_NAME: out/ifc24
#+OPTIONS: toc:nil ':t ^:{} num:3
#+LATEX_CLASS: ifc24
#+BIBLIOGRAPHY: IFC-24.bib
#+CITE_EXPORT: bibtex
#+LATEX_HEADER_EXTRA: \RequirePackage[]{./out/ifc24-style}
#+refproc: :abbreviate nil

#+begin_abstract
Differentiable programming is\dots

Using the ~environment~ expression and pattern matching abstraction,
it is possible to write \F{} code that is differentiable end-to-end,
facilitating the computation and propagation of gradients, and in turn
supporting the creation of parameter optimisation
algorithms. Differentiable programming in \F{} could serve as a
platform for a \F{}-native approach to machine learning problems.
#+end_abstract

* About                                                            :noexport:

Org file describing a paper for the 2024 International Faust
Conference.

Uses =org-ref= for cross references (and it was a real bugger to set
up), and =citar=/=org-cite= for citations.

* Latex Setup                                                      :noexport:
:PROPERTIES:
:HEADER-ARGS: :tangle out/ifc24-style.sty :results silent
:END:

Remember to tangle =C-c C-v t= before exporting.

** Basics

#+begin_src latex
\ProvidesPackage{ifc24-style}[2024/07/12 v0.1 Bundling IFC24 LaTeX style]
#+end_src

** Author(s)

Title is taken from the title attribute.

#+begin_src latex
%% \def\papertitle{Differentiable DSP in Faust}
\def\paperauthorA{Thomas Albert Rushton}
#+end_src

Authors' affiliations have to be set below.

** Packages
#+begin_src latex
\usepackage{IFC-24}
\usepackage{amsmath,amssymb,amsfonts,amsthm,mathtools}
\usepackage{euscript}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{ifpdf}

\usepackage{color}
\usepackage{listings}
\definecolor{mygrey}{rgb}{0.96,0.96,0.96}
\lstset{
  tabsize=4,
  basicstyle=\ttfamily,
  backgroundcolor=\color{mygrey},
  captionpos=b,
  breaklines=true
}

\usepackage[english]{babel}
\usepackage{caption}
\usepackage{subfig, color}

\setcounter{page}{1}
\ninept

\usepackage{times}
\usepackage{inconsolata}

\usepackage{microtype}
\usepackage[inkscapelatex=false]{svg}
#+end_src

** LaTeX vs PDFLaTeX

#+begin_src latex
% pdf-tex settings: detect automatically if run by latex or pdflatex
\newif\ifpdf
\ifx\pdfoutput\relax
\else
   \ifcase\pdfoutput
      \pdffalse
   \else
      \pdftrue
\fi

\ifpdf % compiling with pdflatex
  \usepackage[pdftex,
    pdftitle={\papertitle},
    pdfauthor={\paperauthorA, \paperauthorB, \paperauthorC, \paperauthorD},
    colorlinks=false, % links are activated as colror boxes instead of color text
    bookmarksnumbered, % use section numbers with bookmarks
    pdfstartview=XYZ % start with zoom=100% instead of full screen; especially useful if working with a big screen :-)
  ]{hyperref}
  \pdfcompresslevel=9
  \usepackage[pdftex]{graphicx}
  \usepackage[figure,table]{hypcap}
\else % compiling with latex
  \usepackage[dvips]{epsfig,graphicx}
  \usepackage[dvips,
    colorlinks=false, % no color links
    bookmarksnumbered, % use section numbers with bookmarks
    pdfstartview=XYZ % start with zoom=100% instead of full screen
  ]{hyperref}
  % hyperrefs are active in the pdf file after conversion
  \usepackage[figure,table]{hypcap}
\fi
#+end_src

** Cleveref must be loaded last\dots

...otherwise =hyperref= throws a wobbler and won't link equations, etc.

#+begin_src latex
\usepackage[noabbrev]{cleveref}
#+end_src

Coupled with the ~#+refproc:~ directive above, =cleveref= should not
abbreviate cross-reference names... maybe for HTML, but not for LaTeX.

** Macros
#+begin_src latex
% Special Macros
\newcommand{\F}{\textsc{Faust}}
#+end_src

** Author affiliations

Single author affiliation:

#+begin_src latex
\affiliation{\paperauthorA}
{\href{https://inria.fr}{Inria} \\ Villeurbanne, France\\
{\tt \href{mailto:thomas.rushton@inria.fr}{thomas.rushton@inria.fr}}
}
#+end_src

** Bibliography

#+begin_src latex
\bibliographystyle{IEEEbib}
#+end_src

* Adding Image Attributes                                          :noexport:

You've generated some image output from a source block; now you want
to add attributes like ~#+CAPTION:~, etc. There are a few approaches,
none of which is perfectly lovely. To suggest a couple:

- Generate an image result, then add attributes between the source
  block or ~CALL~ statement and the results.
#+begin_example
#+begin_src
...
#+end_src
#+CAPTION: A delightful caption
#+ATTR_LATEX: :width .5\linewidth
#+RESULTS:...
#+end_example

- Use [[https://orgmode.org/manual/Evaluating-Code-Blocks.html#How-to-evaluate-source-code-1][inline call]] syntax
#+begin_example
#+NAME: faust_code
#+begin_src faust
...
#+end_src

#+ATTR_LATEX: :width .75\linewidth
call_faust_code()[:results svg file :file image.svg :output-dir images
:exports results]
#+end_example

The latter doesn't provide a preview, but less manual intervention is
necessary.

One more thing: for regular source blocks, ~:output-dir~ and ~:file~
are combined into ~:file~ to produce =<outputdir>/<file>=. For
~#+CALL:~ this isn't the case; best to just use ~:file
<outputdir>/<file>~.

* More potentially useful syntax                                   :noexport:

This is an =org-ref= cross-reference: [[cref:sec:intro]]

Here's an =org-cite= citation: [cite:@rallArithmetic1986]

Here's some code:

#+begin_src faust
process = _;
#+end_src

And some inline code ~process = !;~

And floating code?

#+CAPTION: this code should float, because it has a caption
#+begin_src faust
process = 1;
#+end_src

* Introduction
:PROPERTIES:
:CUSTOM_ID: sec:intro
:END:

Differentiable programming is a programming paradigm whereby a
computer program can be differentiated end-to-end
[cite:@blondelElements2024]. The sensitivity of a differentiable
program's outputs to perturbations of its inputs can be computed via
automatic differentiation (AD, autodiff)
[cite:@rallArithmetic1986;@baydinAutomatic2018;], producing a partial
derivative with respect to each input parameter. End-to-end
differentiability is a desirable quality in the creation of computer
programs that perform gradient-based optimization.

This paper introduces a /differentiation arithmetic/ to \F{},
facilitating the creation of differentiable algorithms 

There is a sense in which the block-diagram algebra of \F{} lends the
language intuitively to the problem of automatic differentiation. As
we will see, the language itself presents certain limitations in this
respect, but nonetheless we can achieve a great deal\dots

* Algorithmic Differentiation

What does it entail to write differentiable code? As stated, the aim
of differentiable programming is to compute the sensitivity of a
program's outputs to purturbations to its inputs.
Computational approaches to differentiation are typically
characterised as falling into one of three camps: /numerical/,
/symbolic/, and /automatic/. Numerical differentiation produces
numerical values for derivatives via approximation by finite
differences, and will be familiar to those acquainted with
finite-difference time-domain audio synthesis methods
[cite:@bilbaoNumerical2009]. Symbolic differentiation takes a
computational expression and generates the corresponding expression
for its derivative; this approach may resonate with users of MATLAB's
Symbolic Math Toolbox [cite:@molerSymbolic1997] or the Maple
programming language [cite:@monaganGRADIENT1993]. Automatic
differentiation describes an arithmetic for accumulating both the
numerical output of a computational expression and the numerical value
of its derivative; it is an arithmetic of this kind that underpins the
current crop of Python libraries for machine learning
[cite:@harrisonBrief2021].

A certain ambiguity abounds with regard to how automatic and symbolic
differentiation relate to each other[cite:@laueEquivalence2022], and
partisan views have been expressed over which is more
efficient[cite:@guenterEfficient2007]. The ambiguity may be ascribed
in part to the former's nature as "partly symbolic and partly
numerical" [cite:@harrisonBrief2021], and perhaps also to the fact
that programs composed symbolically may be differentiated
automatically [cite:@villardADrien1999]. Dismissal of symbolic
differentiation over the purported problem of "expression swell"
[cite:@harrisonBrief2021; @baydinAutomatic2018] may be driven by
implementation-specific assumptions and historical lack of available
computing power. For our purposes, we shall defer to Rall, who,
writing in the mid-1980's, before the waters were muddied by legions
of machine learning researchers, observed (to paraphrase): /symbolic
approaches produce formulas whereas automatic approaches produce
numerical outputs/ [cite:@rallArithmetic1986]. The latter do so,
however, by implementing differentiation rules, symbolically, at the
level, as we will see, of the primitive operations of the programming
language upon which they are based.

** The Arithmetic of Automatic Differentiation

Two main /modes/ of automatic differentiation are typically alluded to
in scholarly works on the topic: forward (or /tangent/) mode, and
reverse (or /adjoint/) mode [cite:]. These modes describe, in effect,
two directions of derivative propagation through a computation graph;
in tangent mode, derivatives propagate forward, from inputs to
outputs; in adjoint mode, propagation occurs backwards, from outputs
to inputs. What does it mean, however, for a derivative to propagate?
And is that propagation numerical or symbolic? As we will see, the
answer to the second question is /"both"/; the answer to the first is
less concise, but, irrespective of the direction of propagation, it
lies in the chain rule of differentiation.

*** The Chain Rule

The chain rule is fundamental to both the forward and reverse modes of
automatic differentiation, and it is pertinent at this point to offer
its definition. Consider a function, \(y = f(\mathbf{v})\), of \(m\)
independent variables; for each \(j \in 1, \dots, m\), let \(v_{j} =
v_{j}(\mathbf{w})\) be a differentiable function of \(n\) independent
variables:

#+NAME: eq:diff-functions-1
\begin{align}
y &= f(\mathbf{v}) = f(v_{1}, v_{2}, \dots, v_{m}), \\
v_{j} &= v_{j}(\mathbf{w}) = v_{j}(w_{1}, w_{2}, \dots, w_{n}).
\end{align}

The chain rule states that, for any \(k \in 1, \dots, n\), the derivative of
\(y\) with respect to \(w_{k}\) is:

#+NAME: eq:chain-rule-1
\begin{equation}
\frac{\partial{}y}{\partial{}w_{k}} = \sum_{j=1}^{m}\frac{\partial{}y}{\partial{}v_{j}}\frac{\partial{}v_{j}}{\partial{}w_{k}}
\end{equation}

We can also imagine a situaion in which \(w_{k} = w_{k}(\mathbf{x})\) is, in
turn, a function of \(p\) independent variables:

#+NAME: eq:diff-functions-2
\begin{equation}
w_{k} &= w_{k}(\mathbf{x}) = w_{k}(x_{1}, x_{2}, \dots, x_{p}),
\end{equation}
in which case, for any \(i \in 1, \dots, p\), the derivative of \(y\)
with respect to \(x_{i}\) is:

#+NAME: eq:chain-rule-2
\begin{equation}
\frac{\partial{}y}{\partial{}x_{i}} = \sum_{j=1}^{m}\frac{\partial{}y}{\partial{}v_{j}}\left(
  \sum_{k=1}^{n}\frac{\partial{}v_{j}}{\partial{}w_{k}}\frac{\partial{}w_{k}}{\partial{}x_{i}}
\right)
\end{equation}

To give an audio-relevant example, imagine the case of a gain control,
\(x_{1}\), and a DC offset, \(x_{2}\), applied to an input signal,
\(s\). With some knowledge of elementary calculus, one could observe
that \(y = sx_{1} + x_{2}\) and find \(\frac{\partial{}y}{\partial{}x_{1}} = s\), and
\(\frac{\partial{}y}{\partial{}x_{2}} = 1\). This entails having an overview of the
expression as a whole, however, which works for this simple example,
but may not be feasible for more complex audio processes. Using the
chain rule, we can break our expression down into its fundamental,
/primitive/ operations, and differentiate each separately:

#+NAME: eq:chainrule-example
\begin{align*}
y &= f(v_{1}, v_{2}) = v_{1} + v_{2} \\
  & v_{1}(w_{1}, w_{2}, w_{3}) = w_{1}w_{2},\quad v_{2}(w_{1}, w_{2}, w_{3}) = w_{3},\\
  & w_{1}(x_{1}, x_{2}) = s_{}, \quad w_{2}(x_{1}, x_{2}) = x_{1}, \quad w_{3}(x_{1}, x_{2}) = x_{2},\\
\frac{\partial{}y}{\partial{}x_{i}} &= \sum_{j=1}^{2}\frac{\partial{}y}{\partial{}v_{j}}\left(
  \sum_{k=1}^{3}\frac{\partial{}v_{j}}{\partial{}w_{k}}\frac{\partial{}w_{k}}{\partial{}x_{i}}
\right) \\
  &= \frac{\partial{}y}{\partial{}v_{1}}\left(
  \frac{\partial{}v_{1}}{\partial{}w_{1}}\frac{\partial{}w_{1}}{\partial{}x_{i}} +
  \frac{\partial{}v_{1}}{\partial{}w_{2}}\frac{\partial{}w_{2}}{\partial{}x_{i}} +
  \frac{\partial{}v_{1}}{\partial{}w_{3}}\frac{\partial{}w_{3}}{\partial{}x_{i}}
\right) + \\
  &\quad\,\,\frac{\partial{}y}{\partial{}v_{2}}\left(
  \frac{\partial{}v_{2}}{\partial{}w_{1}}\frac{\partial{}w_{1}}{\partial{}x_{i}} +
  \frac{\partial{}v_{2}}{\partial{}w_{2}}\frac{\partial{}w_{2}}{\partial{}x_{i}} +
  \frac{\partial{}v_{2}}{\partial{}w_{3}}\frac{\partial{}w_{3}}{\partial{}x_{i}}
\right), \\
i = 1, &= 1\left(w_{2}\cdot0 + w_{1}\cdot1 + 0\cdot0\right) + 1\left(0\cdot0 + 0\cdot1 + 1\cdot0\right) \\
  &= w_{1} \\
  &= s, \\
i = 2, &= 1\left(w_{2}\cdot0 + w_{1}\cdot0 + 0\cdot1\right) + 1\left(0\cdot0 + 0\cdot0 + 1\cdot1\right) \\
  &= 1.
\end{align*}
The above may look awfully fussy on paper, but note that the correct
solutions have been reached without us having to consider anything
more complicated at any one time than the derivative of the product of
a variable by a constant (e.g. \(\frac{\partial{}v_{1}}{\partial{}w_{2}}\)). The answers
emerged /automatically/, in a sense; indeed, this fastidious
decomposition of an exression into its differentiable, primitive
operations is the essence of automatic differentiation.

*** Forward Mode Automatic Differentiation
:PROPERTIES:
:CUSTOM_ID: subsubsec:forward-mode
:END:

To approach forward mode, we can use an example \F{} program with the
following block diagram:

#+begin_src faust :results file svg :file (org-babel-temp-file "faust-" ".svg") :exports results
N = 5;
// Just create something that the compiler will bundle into an
// abstraction in the block diagram.
S(j) = sum(i,N,((i+j) : sqrt)/N);
process = (v0 <: _,_),v1 : v2,v3 : v4
with {
    v0 = S(0);
    v1 = S(1);
    v2 = _,S(2) : +;
    v3 = +,S(3) : +;
    v4 = +,S(4) : +;
};
#+end_src
#+CAPTION: Block diagram of a \F{} program consisting of primitive
#+CAPTION: operators, \(v_{j}\).
#+NAME: fig:block-diag-forward-mode
#+RESULTS:
[[file:/tmp/babel-25ewEB/faust-RhquEY.svg]]

This program consists of a number of primitive operations \(v_{j}\). \(N
= 2\) of these we will consider to be parameter primitives, each
taking its value from a vector, \(\mathbf{x} = \begin{bmatrix}x_{1} &
x_{2}\end{bmatrix}\), of input variables:

\begin{align}
v_{0} &= x_{1}_{}, \label{eq:v0} \\
v_{1} &= x_{2}. \label{eq:v1}
\end{align}

These parameters are passed to two further primitives:

#+NAME: eq:v2-v3
\begin{align}
v_{2} &= v_{2}(v_{0}), \\
v_{3} &= v_{3}(v_{0}, v_{1}),
\end{align}
and the program produces one output signal, the output of the final
primitive in the graph, which we can refer to as the /primal/ output
of the program:

#+NAME: eq:output
\begin{equation}
y = v_{4} = v_{4}(v_{2}, v_{3}).
\end{equation}

In forward mode, differentiating each primitive is a case of computing
the sensitivity of each to changes in the program's inputs, producing
a /tangent/ vector of partial derivatives, each with respect to an
element in the parameter vector \(\mathbf{x}\). For example, the input
primitive \(v_{0}\) returns as its derivative:

#+NAME: eq:dv0-dx
\begin{equation}
\frac{\partial{}v_{0}}{\partial{}\mathbf{x}} = \begin{bmatrix}\frac{\partial{}v_{0}}{\partial{}x_{1}} \\ \frac{\partial{}v_{0}}{\partial{}x_{2}}\end{bmatrix}.
\end{equation}
On paper, per [[cref:eq:v0]], this simplifies to \(\begin{bmatrix}1 &
0\end{bmatrix}^{T}\), but in the context of automatic differentiation no
such simplification takes place; rather, derivatives emerge
automatically via differentiation rules provided by each primitive.

By that token, stepping forward through the graph, the partial
derivatives of primitive \(v_{2}\) are, via the chain rule:

#+NAME: eq:dv2-dx
\begin{equation}
\frac{\partial{}v_{2}}{\partial{}\mathbf{x}} = \begin{bmatrix}
  \frac{\partial{}v_{0}}{\partial{}x_{1}}\frac{\partial{}v_{2}}{\partial{}v_{0}} \\
  \frac{\partial{}v_{0}}{\partial{}x_{2}}\frac{\partial{}v_{2}}{\partial{}v_{0}}
\end{bmatrix},
\end{equation}
notwithstanding the fact that \(v_{0}\) (and by extension \(v_{2}\)) does
not depend on \(x_{2}\).

\(v_{3}\) is a multivariate primitive, so the chain rule for multivariate
functions comes into play:

#+NAME: eq:dv3-dx
\begin{equation}
\frac{\partial{}v_{3}}{\partial{}\mathbf{x}} = \begin{bmatrix}
  \frac{\partial{}v_{0}}{\partial{}x_{1}}\frac{\partial{}v_{3}}{\partial{}v_{0}} + \frac{\partial{}v_{1}}{\partial{}x_{1}}\frac{\partial{}v_{3}}{\partial{}v_{1}} \\
  \frac{\partial{}v_{0}}{\partial{}x_{2}}\frac{\partial{}v_{3}}{\partial{}v_{0}} + \frac{\partial{}v_{1}}{\partial{}x_{2}}\frac{\partial{}v_{3}}{\partial{}v_{1}}
\end{bmatrix}.
\end{equation}

Combining and extending [[cref:eq:dv2-dx,eq:dv3-dx]] we can produce a
derivative expression for \(v_{4}\):

#+NAME: eq:dv4-dx
\begin{equation}
\frac{\partial{}v_{4}}{\partial{}\mathbf{x}} = \begin{bmatrix}
  \left(
    \frac{\partial{}v_{0}}{\partial{}x_{1}}
    \frac{\partial{}v_{2}}{\partial{}v_{0}}
    \frac{\partial{}v_{4}}{\partial{}v_{2}}
  \right) +
  \left(
    \frac{\partial{}v_{0}}{\partial{}x_{1}}
    \frac{\partial{}v_{3}}{\partial{}v_{0}}
    \frac{\partial{}v_{4}}{\partial{}v_{3}} +
    \frac{\partial{}v_{0}}{\partial{}x_{1}}
    \frac{\partial{}v_{3}}{\partial{}v_{1}}
    \frac{\partial{}v_{4}}{\partial{}v_{3}}
  \right) \\
  \left(
    \frac{\partial{}v_{0}}{\partial{}x_{2}}
    \frac{\partial{}v_{2}}{\partial{}v_{0}}
    \frac{\partial{}v_{4}}{\partial{}v_{2}}
  \right) +
  \left(
    \frac{\partial{}v_{0}}{\partial{}x_{2}}
    \frac{\partial{}v_{3}}{\partial{}v_{0}}
    \frac{\partial{}v_{4}}{\partial{}v_{3}} +
    \frac{\partial{}v_{0}}{\partial{}x_{2}}
    \frac{\partial{}v_{3}}{\partial{}v_{1}}
    \frac{\partial{}v_{4}}{\partial{}v_{3}}
  \right)
\end{bmatrix},
\end{equation}
and that, in effect, gives us an expression for
\(\frac{\partial{}y}{\partial{}\mathbf{x}}\), a \(2\times1\) Jacobian matrix.

The ultimate aim of automatic differentiation is not, however, to
produce derivative expressions, but numerical outputs. To calculate
the numerical value of the derivative of \(y\) with respect to \(x_{i}\),
we begin by differentiating \(\mathbf{x}\) with respect to \(x_{i}\):

#+NAME: eq:partial-x1
\begin{equation}
\frac{\partial{}\mathbf{x}}{\partial{}x_{i}}
= \begin{bmatrix}\frac{\partial{}x_{1}}{\partial{}x_{i}} & \frac{\partial{}x_{2}}{\partial{}x_{i}}\end{bmatrix}.
\end{equation}

We then propagate this tangent vector through the graph, producing the
/forward tangent output/ of the program. On paper this looks like a
vector product (a /Jacobian vector product/ in fact
[cite:@baydinAutomatic2018]), and simply extracts the first element of
the vector in [[cref:eq:dv4-dx]]; for example:

#+NAME: eq:vec-prod
\begin{align}
\frac{\partial{}y}{\partial{}x_{1}} &= \frac{\partial{}\mathbf{x}}{\partial{}x_{1}}\frac{\partial{}y}{\partial{}\mathbf{x}} \nonumber \\
&= \begin{bmatrix}1 & 0\end{bmatrix}\frac{\partial{}y}{\partial{}\mathbf{x}} \nonumber \\
&= \left(
    \frac{\partial{}v_{0}}{\partial{}x_{1}}
    \frac{\partial{}v_{2}}{\partial{}v_{0}}
    \frac{\partial{}v_{4}}{\partial{}v_{2}}
  \right) +
  \left(
    \frac{\partial{}v_{0}}{\partial{}x_{1}}
    \frac{\partial{}v_{3}}{\partial{}v_{0}}
    \frac{\partial{}v_{4}}{\partial{}v_{3}} +
    \frac{\partial{}v_{0}}{\partial{}x_{1}}
    \frac{\partial{}v_{3}}{\partial{}v_{1}}
    \frac{\partial{}v_{4}}{\partial{}v_{3}}
  \right).
\end{align}
To compute \(\frac{\partial{}y}{\partial{}x_{2}}\), we find \(\frac{\partial{}\mathbf{x}}{\partial{}x_{2}}
= \begin{bmatrix}0 & 1\end{bmatrix}\) and proceed similarly.

To give an example, let's assign some concrete functions to \(v_{n}\):

#+NAME: eq:funcs
\begin{equation}
v_{2} = \sin(v_{0}), \quad v_{3} = v_{0} + v_{1}, \quad v_{4} = v_{2}v_{3},
\end{equation}
and substitute these into [[cref:eq:vec-prod]] (and the equivalent for
\(x_{2}\)):

\begin{align}
\frac{\partial{}y}{\partial{}x_{1}} &= \left(1\cdot\cos(v_{0})\cdot{}v_{3}\right) + \left(1\cdot1\cdot{}v_{2} + 0\cdot1\cdot{}v_{2}\right) \nonumber \\
  &= v_{3}\cos(v_{0}) + v_{2} \nonumber \\
  &= (x_{1} + x_{2})\cos(x_{1}) + \sin(x_{1}), \label{eq:concrete-fwd-x1} \\
\frac{\partial{}y}{\partial{}x_{2}} & = \left(0\cdot\cos(v_{0})\cdot{}v_{3}\right) + \left(0\cdot1\cdot{}v_{2} + 1\cdot1\cdot{}v_{2}\right) \nonumber \\
  &= v_{2} \nonumber \\
  &= \sin(x_{1}). \label{eq:concrete-fwd-x2}
\end{align}
Providing numerical values for \(x_{1}\) and \(x_{2}\) would of course yield
numerical values for the above derivatives.

One potential drawback of forward mode concerns computational
efficiency --- to compute all of the partial derivatives of \(y\),
\(N\) passes are required. For programs with more outputs than inputs,
this would not be a problem, but in the audio domain, where inputs
will likely outnumber outputs, it is potentially a concern.

*** Reverse Mode Automatic Differentiation

For reverse mode, consider a very similar \F{} program to the one
described in cref:fig:block-diag-forward-mode:

#+begin_src faust :results file svg :file (org-babel-temp-file "faust-" ".svg") :exports results
N = 5;
// Just create something that the compiler will bundle into an
// abstraction in the block diagram.
S(j) = sum(i,N,((i+j) : sqrt)/N);
process = (v00 <: _,_),v01 : v10,v11 : v20
with {
    v00 = S(0);
    v01 = S(1);
    v10 = _,S(2) : +;
    v11 = +,S(3) : +;
    v20 = +,S(4) : +;
};
#+end_src
#+CAPTION: Block diagram of a \F{} program with primitives
#+CAPTION: organised into layers in preparation for reverse mode
#+CAPTION: automatic differentiation.
#+NAME: fig:block-diag-reverse-mode
#+RESULTS:
[[file:/tmp/babel-25ewEB/faust-vN3e6l.svg]]

As with forward mode, we have an input vector \(\mathbf{x}\) of length
\(N = 2\). This time, however, we group our primitives, \(v_{p,q}\), into
layers, \(p\), and identify them by their index, \(q\), within each
layer:


#+NAME: eq:primitives
\begin{align*}
v_{0,0} &= x_{1,} \\
v_{0,1} &= x_{2}, \\
v_{1,0} &= v_{1,0}(v_{0,0}) = v_{1,0}(x_{1}), \\
v_{1,1} &= v_{1,1}(v_{0,0}, v_{0,1}) = v_{1,1}(x_{1}, x_{2}), \\
v_{2,0} &= v_{2,0}(v_{1,0}, v_{1,1}) = v_{2,0}(v_{1,0}(x_{1}), v_{1,1}(x_{1}, x_{2})).
\end{align*}
As before, we have a single output, \(y = v_{2,0}\).

Whereas in forward mode the primal and tangent outputs of the program
are computed in parallel during the forward pass, in reverse mode we
complement the forward primal pass with a /reverse adjoint pass/;
instead of computing the /sensitivity/ of each primitive with respect to
its inputs, we compute the /influence/ of a given primitive on the
output of the program (or the sensitivity of the output with respect
to a given primitive):

#+NAME: eq:adjoint
\begin{equation}
\bar{v_{}}_{j} = \frac{\partial{}y}{\partial{}v_{j}}.
\end{equation}

Rather than propagate successive tangent vectors forward through the
computation graph, we instead compute the adjoint of the program's
output (i.e. the influence of the output over itself):

#+NAME: eq:y-adjoint
\begin{equation}
\bar{y} = \bar{v}_{2,0} = \frac{\partial{}y}{\partial{}v_{2,0}} = 1,
\end{equation}
and propagate that backward though the graph. Adjoints for layer \(p =
1\) are:

#+NAME: eq:v1-adjoints
\begin{equation}
\bar{v}_{1,q} &= \bar{v}_{2,0}\frac{\partial{}v_{2,0}}{\partial{}v_{1,q}} = \frac{\partial{}y}{\partial{}v_{2,0}}\frac{\partial{}v_{2,0}}{\partial{}v_{1,q}}.
\end{equation}

In general, the adjoint for primitive \(v_{p,q}\) is found as the sum of
the derivatives of the \(M\) primitives in the \((p+1)\)^{th} layer:

#+NAME: eq:general-adjoint
\begin{align}
\bar{v}_{p,q} &= \frac{\partial{}y}{\partial{}v_{p,q}} = \sum^{M-1}_{m=0}\frac{\partial{}y}{\partial{}v_{p+1,m}}\frac{\partial{}v_{p+1,m}}{\partial{}v_{p,q}} \\
  &= \sum^{M-1}_{m=0}\bar{v}_{p+1,m}\frac{\partial{}v_{p+1,m}}{\partial{}v_{p,q}},
\end{align}
so adjoints for the input layer, \(p = 0\), emerge as follows:

#+name: eq:v0-adjoint
\begin{align}
\bar{v}_{0,q} &= \bar{v}_{1,0}
  \frac{\partial{}v_{1,0}}{\partial{}v_{0,q}} +
  \bar{v}_{1,1}
  \frac{\partial{}v_{1,1}}{\partial{}v_{0,q}} \nonumber \\
&= \bar{v}_{2,0}
  \frac{\partial{}v_{2,0}}{\partial{}v_{1,0}}
  \frac{\partial{}v_{1,0}}{\partial{}v_{0,q}} +
  \bar{v}_{2,0}
  \frac{\partial{}v_{2,0}}{\partial{}v_{1,1}}
  \frac{\partial{}v_{1,1}}{\partial{}v_{0,q}} \nonumber \\
&= \frac{\partial{}y}{\partial{}v_{2,0}}
  \frac{\partial{}v_{2,0}}{\partial{}v_{1,0}}
  \frac{\partial{}v_{1,0}}{\partial{}v_{0,q}} +
  \frac{\partial{}y}{\partial{}v_{2,0}}
  \frac{\partial{}v_{2,0}}{\partial{}v_{1,1}}
  \frac{\partial{}v_{1,1}}{\partial{}v_{0,q}},
\end{align}
giving us:

#+NAME: eq:xi-adjoint
\begin{equation}
\bar{x}_{i} = \frac{\partial{}y}{\partial{}x_{i}} = \bar{v}_{0,i-1}.
\end{equation}

Expanding the terms above isn't really necessary, and
[[cref:eq:v0-adjoint]] could end at the first line; we have definitions
for \(\bar{v}_{1,0}\) and \(\bar{v}_{1,1}\) and these propagate
backward through the graph without any need for them to be
recomputed. In effect, though the graph may branch as adjoints
propagate, we achieve both \(\frac{\partial{}y}{\partial{}x_{1}} =
\bar{v}_{0,0}\) and \(\frac{\partial{}y}{\partial{}x_{2}} =
\bar{v}_{0,1}\) in a single pass, unlike in tangent mode, where two
passes are required.

As with the forward mode example, let's assign some functions to
\(v_{p,q}\) to verify our implementation:

#+NAME: eq:concrete-funcs
\begin{equation}
v_{1,0} = \sin(v_{0,0}), \quad v_{1,1} = v_{0,0} + v_{0,1}, \quad v_{2,0} = v_{1,0}v_{1,1,}
\end{equation}
and substitute these into [[cref:eq:v0-adjoint]]:

\begin{align}
\frac{\partial{}y}{\partial{}x_{1}} &= 1\cdot{}v_{1,1}\cdot\cos(v_{0,0}) + 1\cdot{}v_{1,0}\cdot1 \nonumber \\
  &= (v_{0,0} + v_{0,1})\cos(v_{0,0}) + v_{1,0} \nonumber \\
  &= (x_{1} + x_{2})\cos(x_{1}) + \sin(x_{1}), \label{eq:concrete-rev-x1} \\
\frac{\partial{}y}{\partial{}x_{2}} &= 1\cdot{}v_{1,1}\cdot0 + 1\cdot{}v_{1,0}\cdot1 \nonumber \\
  &= v_{1,0} \nonumber \\
  &= \sin(v_{0,0}) \nonumber \\
  &= \sin(x_{1}), \label{eq:concrete-rev-x2}
\end{align}
which are entirely the same results achieved in
cref:eq:concrete-fwd-x1,eq:concrete-fwd-x2 via tangent mode.

For reverse mode to work in practice, however, some knowledge of a
program's structure is required. Whether this is achived via a
bookkeeping mechanism [cite:@baydinAutomatic2018] such as a /tape/
[cite:@pearlmutterReversemode2008;@radulYou2023], or by organising the
program into layers as we have here, a degree of complexity is
introduced that tangent mode, with its more brute-force approach, does
not.

*** Dual Number Arithmetic

One interesting property of forward mode autodiff lies in the
possibility of formulating differentiation in a manner similar to the
complex numbers [cite:@rallArithmetic1986;@yuDNAD2013]. Where complex
arithmetic uses the imaginary unit \(i\) to designate the imaginary
part of a complex number \(z = x + iy\), with \(i^{2} = -1\),
differentiable arithmetic uses the /nilpotent symbol/, \(\varepsilon\)
[cite:@yuDNAD2013;@baydinAutomatic2018]:

#+NAME: eq:nilpotent
\begin{equation}
U = u + \varepsilon{}u',
\end{equation}
where \(u' = \frac{du}{dx}\) is the derivative of \(u\) with respect
to some variable \(x\)  and \(\varepsilon^{2}\) = 0.

Using this arithmetic, the addition rule of differentiation emerges
quite naturally as the sum of \(U\) and \(V = v + \varepsilon{}v'\):

#+NAME: eq:addition-rule
\begin{equation}
(u + \varepsilon{}u') + (v + \varepsilon{}v') = u + v + \varepsilon(u' + v').
\end{equation}
Similarly, the product rule, via a simple polynomial expansion:

#+NAME: eq:product-rule
\begin{align}
(u + \varepsilon{}u')(v + \varepsilon{}v') &= uv + u\varepsilon{}v' + v\varepsilon{}u' + \varepsilon^{2}u'v' \nonumber \\
                   &= uv + \varepsilon(uv' + vu'),
\end{align}
the final term cancelling due to the presence of \(\varepsilon^{2}\).

This arithmetic may be more conviently expressed, for computational
purposes, as one of /ordered
pairs/[cite:@rallArithmetic1986;@kalmanDoubly2002] or /dual numbers/
[cite:@yuDNAD2013;@sigalAutomatic2021;@revelsForwardMode2016]:

#+NAME: eq:dual
\begin{equation}
U = \langle u, u' \rangle.
\end{equation}
The addition and product rules now take the following forms:

\begin{align}
U+V &= \langle u, u' \rangle + \langle v, v' \rangle = \langle u + v, u' + v' \rangle, \label{eq:addition-rule-dual}\\
UV &= \langle u, u' \rangle\langle v, v' \rangle = \langle uv, uv' + vu' \rangle. \label{eq:product-rule-dual}
\end{align}
The first component of each dual number is the rule for evaluation of
the operation; the second is the rule for differentiation
[cite:@rallArithmetic1986]. These components may be referred to as the
/primal/ and /tangent/ respectively
[cite:@baydinAutomatic2018;@radulYou2023]. In dual number
differentiation arithmetic, an independent variable can be expressed
as \(X = \langle x,\frac{dx}{dx} \rangle\), and a constant \(C = \langle c,\frac{dc}{dx}
\rangle\). If we wish, for example, to compute the primal and tangent of a
polynomial \((x + 1)(x - 2)\) at \(x = 2\), we set \(X = \langle 2,1 \rangle\) and
supply appropriate values for the constants:

#+NAME: eq:product-example
\begin{equation}
(\langle 2,1 \rangle + \langle 1,0 \rangle)(\langle 2,1 \rangle - \langle 2,0 \rangle) = \langle 3,1 \rangle\langle 0,1 \rangle = \langle 0,3 \rangle. \nonumber
\end{equation}
We find that our arithmetic produces the expected numerical results
/automatically/ via composition of the fundamental operations
described in [[cref:eq:addition-rule-dual,eq:product-rule-dual]].

Differentiation arithmetic of this sort is a special case of a more
general /gradient arithmetic/ [cite:@rallArithmetic1986], which comes
into effect when multiple variables are present, and thus multiple
partial derivatives must be calculated:

#+NAME: eq:dual-gradient
\begin{equation}
U = \langle u, \nabla{}u \rangle.
\end{equation}

** Extending \F{}'s Arithmetic

One quality generally possessed by automatic differentiation
implementations is that of allowing the programmer to write
differentiable programs with minimal changes to the syntax of their
code. This is typically achieved either by source code transformation
or operator overloading [cite:@yuDNAD2013;@baydinAutomatic2018]
--- neither of which is available in the \F{} language.[fn:1] We could
take an approach similar to Wengert's 1964 demonstration of the
composition of differentiable functions in Fortran
[cite:@wengertSimple1964] and define differentiable functions
~diffAdd~, ~diffMul~, etc. each accepting and returning dual numbers;
thanks to \F{}'s pattern matching abstraction, however, we can go one
better, achieving something akin to, albeit slightly more verbose
than, operator overloading.

Pattern matching has been used extensively in the Faust libraries. The
=basics.lib= library, for example, provides a function with a
recursive pattern matching definition for taking an element from a
list:

#+begin_src faust :results none
// Take the first element, the head;
take(1, (head, rest)) = head;
// Take the only element;
take(1, head)         = head;
// Take the n-1th element from the rest.
take(n, (head, rest)) = take(n-1, rest);
#+end_src

The =physmodels.lib= library provides ~pm.chain~ for creating chains
of bidirectional signal blocks [cite:@michonFaust2018]. ~chain(A)~
simply returns the signal block ~A~; ~chain(A:As)~ creates a recursive
structure containing ~A~ and ~chain(As)~. Similarly, =wdmodels.lib=
facilitates the creation of wave digital filter models via primitive
elements, resistors, capacitors, etc. [cite:@roosenburgWave2021],
whose behaviour is described with pattern matching syntax. Both
libraries extend \F{}'s arithmetic with their own rules, with the aim
of achievening a particular goal within the syntax provided by \F{}.

If one's particular goal was to be able to compose reciprocal
expressions, one could create an arithmetic of the following form,
using pattern matching to avoid division by zero:

#+begin_src faust :results file svg :file images/arithmetic.svg :exports both
import("stdfaust.lib");
recip(0) = recip(ma.EPSILON);
recip(0.0) = recip(0);
recip(op) = 1,op : /;
process = recip(log(1)),recip((_,2 : ^))
  : recip(-);
#+end_src
#+ATTR_LATEX: :width 1\linewidth
#+RESULTS:
[[file:images/arithmetic.svg]]
Wrapping our expressions in ~recip~ gives us automatic reciprocals
without affecting the fundamental composability of \F{}'s
primitives. Note that if we were to insert the expression ~recip(-) =
+;~ at the top of the program, the final operation, rather than
returning \(1/(x_{1} - x_{2})\) would be /overridden/, in a manner of
speaking, returning \((x_{1} + x_{2})\) instead. An approach along these
lines will form the basis for the creation of differentiable \F{}
primitives.

* Differentiable Programming in \F{}

As described in cref:subsubsec:forward-mode, in forward mode, primal
and tangent outputs are found during a forward pass through the
computation graph, which fits neatly with the left-to-right
propagation of signals through a \F{} block diagram. Reverse
propagation of signals is entirely possible in \F{} (indeed forward
mode demands it as a final, backpropagation step --- see
cref:subsec:param-opt), and it is by way of nested recursive
composition that the =physmodels.lib= library accomplishes simulated
bidirectional wave propagation; the structures described by
=physmodels.lib= are purely linear, however, and, at the time of
writing, no general scheme for the creation of /branching/
bidirectional structures, such as reverse mode requires, has been
found.

Consequently, this section is concerned with the description of an
approach to differentiable programming in \F{} based on forward mode
automatic differentiation. End-to-end differentiability is predicated
on the availability of derivative expressions for the primitive
operations of the language; described, in the subsections that follow,
is an approach to definining \F{} primitives that are differentiable
in forward mode.

** Defining a Differentiable Primitive

As a basic example, consider the addition primitive; in \F{} one can
write:

#+NAME: faust_add
#+begin_src faust
process = +;
#+end_src
which yields the block diagram:

#+CALL: faust_add() :results svg file :file images/add.svg :exports results
#+ATTR_LATEX: :width .5\linewidth
#+RESULTS:
[[file:add.svg]]
This signal processor takes two input signals, \(u\) and \(v\), and
produces one output signal, \(y\):

\begin{equation}
y = u + v.
\end{equation}
Note that \F{}'s addition primitive has no special knowledge of its
arguments, their history, provenance, etc., it just consumes them and
returns their sum. In \F{}'s arithmetic, the addition of two signals is
simply well-defined.

Suppose that \(y\) is dependent on some variable \(x\), and that we
wish to know how sensitive \(y\) is to perturbations in \(x\). We can
produce an analytic expression for this sensitivity by differentiating
\(y\) with respect to \(x\). Recall, from [[cref:eq:addition-rule-dual]],
that a dual-number addition takes the form of two additions in
parallel; in \F{}, that could be expressed as follows:

#+begin_src faust :results svg file :file images/dualadd.svg :exports both
diffAdd = +,+;
process = diffAdd;
#+end_src
#+ATTR_LATEX: :width .5\linewidth
#+RESULTS:
[[file:images/dualadd.svg]]
Since \F{} deals exclusively with the propagation of signals, we shall
refer to this as a /dual signal/ representation.

Just as the addition primitive has no special knowledge of its input
signals, nor does ~diffAdd~, but at this stage the notion of
differentiable addition is not well-defined. In order for this new
primitive to behave as it should, it is necessary to supplement \F{}'s
arithmetic with the following rule:

#+begin_quote
Supply \(\langle u, u' \rangle\) and \(\langle v, v' \rangle\) to the differentiable addition
primitive, in that order, and it should return \(\langle u+v, u'+v' \rangle\).
#+end_quote
To satisfy this rule, ~diffAdd~ needs to be modified, otherwise it
will produce the nonsensical result \(\langle y, y' \rangle = \langle u + u', v + v'
\rangle\); this can be remedied with \F{}'s ~route~ primitive:

#+begin_src faust :results svg file :file images/dualaddroute.svg :exports both
diffAdd = route(4, 4,
    (1, 1), (2, 3), (3, 2), (4, 4)) : +,+;
process = diffAdd;
#+end_src
#+ATTR_LATEX: :width .66\linewidth
#+RESULTS:
[[file:images/dualaddroute.svg]]
~diffAdd~ now satisfies the rule, implementing
cref:eq:addition-rule-dual, and describing a dual-signal
differentiable addition primitive.

Let's define some more differentiable primitives for ~diffAdd~ to act
upon. For \(u\) we can use an arbitrary input signal, which we will
describe with \F{}'s identity function, ~_~. Such a signal has no
relationship with \(x\), so \(u' = 0\). To \(v\) we assign the
variable \(x\); one possible analogy to a variable in \F{} is a
slider, so that is what we shall use; \(v = x\), so \(v' = 1\).

#+begin_src faust :results none
diffInput = _,0;
diffSlider = hslider("x", 0, -1, 1, .1),1;
#+end_src
Now we can compose these with our differentiable addition primitive:

#+begin_src faust :results none
u = diffInput;
v = diffSlider;
process = u,v : diffAdd;
#+end_src

#+begin_src faust :results file svg :file images/dc.svg :exports results
diffAdd = route(4, 4,
    (1, 1), (2, 3), (3, 2), (4, 4)) : +,+;
diffInput = _,0;
diffSlider = hslider("x", 0, -1, 1, .1),1;
process = diffInput,diffSlider : diffAdd;
#+end_src
#+ATTR_LATEX: :width 1\linewidth
#+RESULTS:
[[file:images/dc.svg]]
The primal output signal of this program is the result of an
expression describing an input signal with a DC offset \(x\) applied;
the tangent output, the derivative with respect to \(x\), is a
constant signal of value \(1\). By composing primitives with
well-defined derivatives, the derivative of the entire program has
been found /automatically/; the above program is a rudimentary
implementation of forward-mode automatic differentiation in \F{}.

** Multivariate Differentiable Primitives

What if a program has more than one variable? Consider the following
(non-differentiable) example consisting of a DC offset and a gain
control applied to an input signal:

#+CAPTION: A \F{} program that applies gain and DC offset parameters
#+CAPTION: to an input signal.
#+NAME: lst:gain-dc
#+begin_src faust
x1 = hslider("gain", .5, 0, 1, .1);
x2 = hslider("dc", 0, -1, 1, .1);
process = _,x1 : *,x2 : +;
#+end_src
which can be notated thus:

#+NAME: eq:gain-dc
\begin{equation}
y = uv + w, \quad v = x_1, \quad w = x_2.
\end{equation}
Once again \(u\) is an arbitrary input signal, for which we have no
analytic expression. Now, rather than being a lone ordinary derivative
\(\frac{dy}{dx}\), we have \(\nabla{}y\), a matrix of partial derivatives:

#+NAME: eq:pds
\begin{equation}
\nabla{}y = \frac{\partial y}{\partial \mathbf{x}}
= \begin{bmatrix}\frac{\partial y}{\partial x_1} \\
\frac{\partial y}{\partial x_2}\end{bmatrix}.
\end{equation}
Our algorithm takes two parameter inputs, and produces one output
signal, so the resulting Jacobian matrix is of dimension \(2 \times
1\). Returning to dual signal representation and applying the chain,
product and addition rules of differentiation, we have:

#+NAME: eq:dual-gain-dc
\begin{align}
\langle y,\nabla{}y \rangle &=
\langle u,\nabla{}u \rangle \langle v,\nabla{}v \rangle + \langle w,\nabla{}w \rangle \nonumber \\
&= \langle uv,\nabla{}uv + \nabla{}vu \rangle + \langle w,\nabla{}w \rangle \nonumber \\
&= \langle uv + w,\nabla{}uv + \nabla{}vu + \nabla{}w\rangle,
\end{align}

To implement the above in \F{} calls for the creation of multivariate
differentiable primitives. One approach to achieving this would be to
implement ~diffInput~, ~diffSlider~, and ~diffAdd~ as functions, each
taking as a parameter ~NVARS~, the number of variables in the program,
and thus partial derivatives that they should produce. Using \F{}'s
~environment~ expression, however it is possible to approach the
problem in a more general, and syntactically succinct fashion.

*** A Differentiable Environment

First, we can define a function for collecting, counting, and
retrieving variables and their partial derivatives:

#+NAME: lst:var-env
#+CAPTION: A \F{} function for defining an environment of
#+CAPTION: differentiable variables.
#+begin_src faust
vars(V) = environment {
  // Count the variables.
  N = outputs(V);
  // Retrieve a variable by index i.
  var(i) = ba.take(i, V),pds(N, i)
  with {
    // Compute partial derivatives of
    // variable x_i.
    pds(N, i) = par(j, N, i-1==j);
  };
};
#+end_src
~vars~ receives a list of variables, expressed via parallel
composition, e.g. ~X = vars((gain,dc));~, where ~gain~ and ~dc~ are
defined as ~hslider~ instances.

Next, we can define a function that takes the variable environment
produced by ~vars~ as its sole argument, and returns a /differentiable
environment/, containing a collection of multivariate differentiable
primitives. As a further improvement, we can use \F{}'s pattern
matching syntax to simplify the nomenclature of the differentiable
primitives; instead of exposing the name ~diffAdd~, for example, the
differentiable addition primitive can be named ~diff(+)~:

#+NAME: lst:diff-env
#+CAPTION: Extract from the definition of a \F{} environment for
#+CAPTION: differentiable programming.
#+begin_src faust
env(vars) = environment {
  diff(+) = diffAdd with {
    diffAdd = route(nIN, nOUT,
      (u, 1), (v, 2), // u + v
      par(i, vars.N,
        // du/dx_i + dv/dx_i
        (u+i+1, dx), (v+i+1, dx+1)
        with {
          // Start of derivatives wrt x_i
          dx = 2*i+3;
        }
      )
    ) with {
      nIN = 2+2*vars.N;
      nOUT = nIN;
      u = 1;
      v = u+vars.N+1;
    }
    : +,par(i, vars.N, +);
  };

  // ...definitions of other
  // differentiable primitives...
};
#+end_src

As before, the primal signal output of the differentiable addition
primitive is the sum of the primal inputs, \(u+v\); now, however, the
differentiable primitive produces ~vars.N~ tangent outputs, each
corresponding to a derivative with respect to \(x_{i}\). As before, the
~route~ primitive ensures that incoming signals are delivered to the
parallel additions in the correct order.

Encapsulating [[cref:lst:var-env,lst:diff-env]] as a library in a file
named =diff.lib=, we can use ~vars~ and ~env~ to write a
differentiable version of the gain-plus-DC-offset program encountered
earlier:

#+CAPTION: Differentiable counterpart to the \F{} program described
#+CAPTION: in [[cref:lst:gain-dc]].
#+NAME: lst:gain-dc-diff
#+begin_src faust :results file svg :file images/gain-dc.svg :exports both
df = library("diff.lib");

X = df.vars((gain,dc)) with {
  gain = hslider("gain", .5, 0, 1, .01);
  dc = hslider("dc", 0, -1, 1, .01);
};

d = df.env(X);

process = d.input,X.var(1)
  : d.diff(*),X.var(2)
  : d.diff(+);
#+end_src
#+NAME: fig:gain-dc
#+ATTR_LATEX: :float multicolumn :placement [ht!]
#+CAPTION: Block diagram of a differentiable \F{} program consisting
#+CAPTION: of differentiable gain and DC parameters applied to an
#+CAPTION: input signal (see [[cref:lst:gain-dc-diff]]).
#+RESULTS: lst:gain-dc-diff
[[file:images/gain-dc.svg]]
See [[cref:fig:gain-dc]] for the block diagram of this program. Note that
while the routing for each primitive --- particularly ~diff(*)~ ---
may be quite complex (and would only become more involved with the
addition of further variables) the ~df~ library abstracts this
complexity away.

** Parameter Optimisation via Gradient Descent
:PROPERTIES:
:CUSTOM_ID: subsec:param-opt
:END:

Armed with the means to write end-to-end differentiable \F{} programs,
it is possible, with a few modifications (and additions to
=diff.lib=), to combine the code in
[[cref:lst:gain-dc,lst:gain-dc-diff]], to create a demonstrative
parameter optimisation algorithm. An algorithm of this kind describes
a target output, governed by parameters that are /hidden/ with respect
to some /estimated/ output, which itself depends on parameters that we
wish to optimise.

The algorithm in [[cref:lst:gain-dc]] is dependent on hidden parameters
\(\mathbf{x}\) and produces a ground truth output signal \(y\); we
assign this algorithm to a variable named ~target~. Its differentiable
equivalent in [[cref:lst:gain-dc-diff]] is dependent on estimated
parameters \(\mathbf{\hat{x}}\) and produces the dual output signal,
\(\langle \hat{y}, \nabla\hat{y} \rangle\); we assign this to a variable named
~estimate~. The output signals produced by ~target~ and ~estimate~ can
now be compared by way of a loss function; to this end, we can employ
time-domain L1-norm loss of the form:

#+NAME: eq:l1-loss
\begin{equation}
\mathcal{L}(y,\hat{y}) = ||\hat{y} - y||.
\end{equation}

Our aim is to minimise the value returned by the loss function,
i.e. to reach the point at which \(y\) and \(\hat{y}\) (and by
extension \(\mathbf{x}\) and \(\mathbf{\hat{x}}\)) most closely
approximate one-another. The sensitivity of \(\mathcal{L}\) to
perturbations in \(\mathbf{\hat{x}}\) can again be found by automatic
differentiation, subject to the definition of a differentiable
absolute value function in ~df.env~. The loss function can then be
implemented as follows:

#+NAME: lst:loss-function
#+CAPTION: Implementation of a differentiable loss function
#+CAPTION: (L1-norm) using differentiable ~abs~ primitive.
#+begin_src faust
env(vars) = environment {
  // ...
  lossL1(learningRate, y, yHat) = 
    error,par(i, vars.N, _)
    : diff(abs)
    : _,scaleGrads
  with {
    error = yHat,y : -;
    scaleGrads = par(i, vars.N,
      _,learningRate : *);
  };
  // ...
#+end_src

The loss function's derivatives are the /gradients/ associated with
each variable in \(\mathbf{\hat{x}}\). In our two-parameter example,
\(\mathcal{L}\) will describe a three-dimensional surface, and
\(\frac{\partial\mathcal{L}}{\partial x_{i}}\) its slope in the direction of
\(x_{i}\). Variables at time \(t+1\) are found by scaling gradients by a
learning rate, \(\alpha\), and subtracting the result from variable values
at time \(t\):

#+NAME: eq:gradient-descent
\begin{equation}
\mathbf{\hat{x}}_{t+1} = \mathbf{\hat{x}}_t - \alpha\frac{\partial\mathcal{L}}{\partial \mathbf{\hat{x}}_t}
\end{equation}
In \F{}, this can be achieved via recursion, and by changing the
definition of the variables delivered to ~df.env~. Since values will
be updated automatically via gradient descent, the sliders used in
[[cref:lst:gain-dc-diff]] are no longer appropriate; instead, a bargraph
instance can be used to display the value of each variable, with
recursive subtractions accumulating the incoming gradients.

#+begin_src faust
X = df.vars((gain,dc)) with {
  gain = -~_
    <: attach(hbargraph("Gain", 0, 1));
  dc = -~_
    <: attach(hbargraph("DC", -1, 1));
};
#+end_src

Finally, we can create a program that takes white noise as input,
encapsulates ~target~, ~estimate~, and the loss function, and recurses
gradients produced by the latter back to ~estimate~. 

#+NAME: lst:backprop
#+CAPTION: Excerpt from a parameter optimisation algorithm. See
#+CAPTION: [[cref:lst:gain-dc,lst:gain-dc-diff,lst:loss-function]]
#+CAPTION: respectively for definitions of ~target~,
#+CAPTION: ~estimate~, and ~d.lossL1~.
#+begin_src faust :results none
process = no.noise <: (
    route(nvars+nInputs, nvars+nInputs,
      // Route gradients to estimate.
      par(i, nvars, (i+1, i+3)),
      // Route input to target & estimate.
      (nvars+1, 1), (nvars+2, 2))
    : target,estimate : d.lossL1(1e-3)
    // Recurse the gradients.
  ) ~ (!,si.bus(nvars))
  // Block the gradients, post-recursion.
  : _,si.block(nvars)
with {
  nvars = inputs(estimate),
    inputs(target) : -;
  nInputs = inputs(target),2 : *;
// ...
#+end_src

This delivery of gradients from the outputs of the program back to its
inputs is commonly (and particularly in material from the field of
machine learning) referred to as /backpropagation/ [cite:]. Whereas in
reverse mode gradients arrive at the inputs as a result of passing
backwards through the graph, in forward mode something like the
recursion described in ref:lst:backprop is required.

[link to example files]

** Differentiation of Audio-specific Primitives

We have established that we can write differentiable counterparts to
some of the fundamental primitive operators in \F{}'s arithmetic. But
what about the more domain-specific operators of the language? Two
particularly interesting examples are \F{}'s delay operators and
recursive composition operation.

*** Differentiable Delay

What is the derivative of a delayed expression? To explore this idea,
consider the case of delaying a function \(f(v)\), \(v = v(x)\), by
some fixed time \(\tau\):

#+NAME: eq:fixed-delay
\begin{align}
y = f(v) &= v(t - \tau).
\end{align}
The derivative of the above, via the chain rule, is:

#+NAME: eq:diff-delay-1
\begin{equation}
\frac{dy}{dx} = \frac{dy}{dv}\frac{dv}{dx}. \\
\end{equation}
But what is \(\frac{dy}{dv}\)? To proceed, recall that the impulse
response of the ideal delay system is a time-shifted impulse:

#+NAME: eq:ideal-delay-ir
\begin{equation}
h(t) = \delta(t - \tau),
\end{equation}
and we can represent cref:eq:fixed-delay as a convolution of \(v(t)\)
and that impulse response:

#+NAME: eq:conv
\begin{equation}
v(t - \tau) = v(t) \ast h(t).
\end{equation}
Next, we can use the convolution and differentiation properties of the
Fourier transform [cite:@mcclellanSignal2003]:

#+NAME: eq:fourier-properties
\begin{align}
x(t) \ast h(t) \quad&\xleftrightarrow{\mathcal{F}}\quad X(j\omega)H(j\omega), \\
\frac{d}{dt}x(t) \quad&\xleftrightarrow{\mathcal{F}}\quad j\omega{}X(j\omega),
\end{align}
which, when combined, tell us that the Fourier transform of the
derivative of a convolution takes the following form:

#+NAME: eq:diff-conv
\begin{align}
\mathcal{F}\left[\frac{d}{dt}(x(t) \ast h(t))\right]
  &= \mathcal{F}\left[\left(\frac{d}{dt}x(t)\right)\right]\cdot\mathcal{F}[h(t)] \\
  &= \mathcal{F}[x(t)]\cdot\mathcal{F}\left[\left(\frac{d}{dt}h(t)\right)\right] \\
  &= j\omega{}X(j\omega)H(j\omega),
\end{align}
and this tells us that, to differentiate a convolution, we only have
to differentiate /one/ of the functions being convolved. Now we can
solve cref:eq:diff-delay-1:

#+NAME: eq:diff-delay
\begin{align}
\frac{dy}{dx} &= \frac{dv}{dx}\frac{d}{dv}(v(t) \ast h(t)) \nonumber \\
  &= \frac{dv}{dx}\frac{d}{dv}(v(t)) \ast h(t) \nonumber \\
  &= \frac{dv}{dx} \ast h(t) \nonumber \\
  &= v'(t - \tau).
\end{align}
This proves that the ideal differentiator is a time-invariant system.

Differentiable delay in discrete time, by some fixed time \(k\), can
be represented with dual numbers:

#+NAME: eq:diff-delay-dual
\begin{equation}
\langle v,\nabla{}v \rangle[n - k] = \langle v[n - k], \nabla{}v[n - k] \rangle
\end{equation}
and in Faust:

#+begin_src faust :results none
diff(mem) = mem,par(i, vars.N, mem);
#+end_src

*** Variable Delay

A thornier matter is the case where the length of the delay is itself
a differentiable parameter, e.g.:

#+NAME: eq:variable-delay
\begin{equation}
y = f(\mathbf{v}) = v_{1}(t - v_{2}(t)), \quad v_{j}(\mathbf{x}) = v_{j}(x_{1}, x_{2}).
\end{equation}
It's derivative, via the chain rule, with respect to \(x_{i}\) is:

#+NAME: eq:variable-delay-deriv
\begin{equation}
\frac{\partial{}y}{\partial{}x_{i}} = \frac{\partial{}y}{\partial{}v_{1}}\frac{\partial{}v_{1}}{\partial{}x_{i}} + \frac{\partial{}y}{\partial{}v_{2}}\frac{\partial{}v_{2}}{\partial{}x_{i}}.
\end{equation}
Courtesy of cref:eq:diff-delay we know that the first term reduces to
\(\frac{\partial{}v_{1}}{\partial{}x_{i}} \ast h(t) = v_{1}'(t - v_{2}(t))\). We have nothing in
particular to fear from \(\frac{\partial{}v_{2}}{\partial{}x_{i}} = v_{2}'\). Let's tackle the
remaining term, \(\frac{\partial{}y}{\partial{}v_{2}}\). By the chain rule, we have:

#+NAME: eq:chain-rule-dydv2
\begin{align}
\frac{\partial{}y}{\partial{}v_{2}} &= \frac{\partial{}y}{\partial{}u}\frac{\partial{}u}{\partial{}v_{2}}, \quad u = t - v_{2}(t) \nonumber \\
  &= \frac{\partial{}}{\partial{}u}v_{1}(u)\frac{\partial{}}{\partial{}v_{2}}(t - v_{2}(t)) \nonumber \\
  &= \frac{\partial{}}{\partial{}u}v_{1}(u)\cdot(-1) \nonumber \\
  &= -\frac{\partial{}}{\partial{}u}v_{1}(u).
\end{align}
Disappointingly, it feels like we're back to where we started (albeit
having introduced a negative sign), and that is essentially the nature
of the beast in this instance. Nevertheless, our complete expression
for \(\frac{\partial{}y}{\partial{}x_{i}}\), expanding cref:eq:variable-delay-deriv, is:

#+NAME: eq:dydxi-via-chain-rule
\begin{align}
\frac{\partial{}y}{\partial{}x_{i}} &= 1\cdot{}v_{1}'(t - v_{2}(t)) - \frac{\partial{}}{\partial{}u}v_{1}(u)\cdot{}v_{2}'(t) \nonumber \\
  &= v_{1}'(t - v_{2}(t)) - v_{2}'(t)\frac{\partial{}}{\partial{}u}v_{1}(u),
\end{align}
where \(u = t - v_{2}(t)\). In the general case, that of \F{}'s ~@~
operator, we need an expression that will handle both fixed and
variable delays, and, at the time of writing, this has entailed taking
a numerical derivative of \(v_{1}\) with respect to time. This approach
is able to support parameter optimisation for increasing delays, but,
for reasons of causality, for /decreasing/ ones it is of limited use.

*** Variable Delay as a Differentiable Filterbank

Perhaps a better approach, in parameter optimisation scenarios
involving variable-length delay lines, is to model the variable delay
as a differentiable FIR filterbank. The general FIR filter, with
coefficients \(x_{i}\) and input signal \(s\), can be described by the
difference equation [cite:@mcclellanSignal2003]:

#+NAME: eq:general-fir-1
\begin{equation}
y[n] = \sum_{k=0}^{M-1}x_{k}s[n-k]
\end{equation}
We can express \(y = y[n]\) as a function of a vector of independent
variables \(\mathbf{v}\):

#+NAME: eq:general-fir-2
\begin{equation}
y &= f(\mathbf{v}) = \sum_{k=1}^{M}v_{2k-1}v_{2k},
\end{equation}
where \(v_{j}\) is a function of a vector of filter coefficients
\(\mathbf{x}\):

#+NAME: eq:vees
\begin{align*}
v_{2k-1}(\mathbf{x}) &= x_{k} \\
v_{2k}(\mathbf{x}) &= s[n - (k - 1)].
\end{align*}
To differentiate \(y\) with respect to a filter coefficient \(x_{i}\),
use the chain rule:

#+NAME: eq:diff-fir
\begin{align*}
\frac{\partial{}y}{\partial{}x_{i}} &= \sum_{j=1}^{2M}\frac{\partial{}y}{\partial{}v_{j}}\frac{\partial{}v_{j}}{\partial{}x_{i}} \\
  &= \frac{\partial{}y}{\partial{}v_{1}}\frac{\partial{}v_{1}}{\partial{}x_{i}} + \cdots + \frac{\partial{}y}{\partial{}v_{2M}}\frac{\partial{}v_{2M}}{\partial{}x_{i}} \\
  &= v_{2i} \\
  &= s[n - (i - 1)].
\end{align*}
Thus, differentiating the general FIR filter with respect to \(x_{i}\)
has the effect of isolating the \((i-1)\)^{th} tap. Consequently,
optimising against a (hidden) variable delay will have the effect of
plucking out the closest filter tap.

*** Differentiable Recursion

Thus far it has not been necessary to define derivative expressions
for any of \F{}'s /composition operations/; this is because for
parallel and sequential types of composition we have encountered so
far have no arithmetical impact on the signals they act upon, and thus
no impact on derivative computation in forward mode. Of \F{}'s five
composition operators, only merge composition, ~:>~, has such an
effect, that of summation; consequently differentiable merge
composition could be defined as something like the following:

#+begin_src faust :results none
diff((A,B)) = diff(A),diff(B);
diff(A :> B) = diff(A) : diff(+) : diff(B);
#+end_src
assuming that ~A~ consists of exactly two parallel signals.[fn:3]

Cref:fig:block-diag-forward-mode demonstrates visually that split,
parallel, and sequential composition do not alter the signals they act
upon, and are thus analogous to application of the identity function,
whose partial derivatives are in turn identity functions, i.e.:

#+begin_src faust :results none
diff(_) = par(i, vars.N+1, _);
#+end_src
For the case of recursive composition, this is perhaps not as clear;
fortunately we can prove it to be so via the chain rule.

A simple (and undifferentiated) \F{} program that produces a ramp of
varying slope can be defined like so:

#+begin_src faust :results none
process = hslider("x", 0, -1, 1, .01)
    : +~_;
#+end_src
This can be notated, in discrete time, as:

#+NAME: eq:ramp-1
\begin{equation}
y[n] = x[n] + y[n-1].
\end{equation}
As usual, we can express \(y = y[n]\) as a function of independent
variables, \(v_{j}\), which are in turn functions of \(x\):

#+NAME: eq:ramp-2
\begin{align}
y &= f(v_{1},v_{2}) = v_{1} + v_{2}, \nonumber\\
v_{1}(x) &= x, \quad v_{2}(x) = y[n - 1],
\end{align}
and find find its derivative with respect to \(x\):

#+NAME: eq:ramp-diff
\begin{align}
\frac{dy}{dx} &= \frac{dy}{dv_{1}}\frac{dv_{1}}{dx} + \frac{dy}{dv_{2}}\frac{dv_{2}}{dx} \nonumber \\
  &= 1\cdot{}1 + 1\cdot\frac{dy}{dx}[n-1] \nonumber \\
  &= 1 + \frac{dy}{dx}[n-1].
\end{align}
If the presence of the recurrence relation in the result seems
surprising, recall that \(y = y[n]\), so \(\frac{dy}{dx} =
\frac{dy}{dx}[n]\).

* Discussion
:PROPERTIES:
:CUSTOM_ID: sec:discussion
:END:

** Limitations

- derivative of delay
- deterministic input
- overfitting...
- dimensionality; reverse mode
- pattern matching generalisation...
- widget modulation
- compiler-based transformations

# [[Cref:sec:conclusion]]

* Conclusion
:PROPERTIES:
:CUSTOM_ID: sec:conclusion
:END:
** Acknowledgements

#+begin_export latex
%%\nocite{*}
#+end_export
#+PRINT_BIBLIOGRAPHY:

* Footnotes
[fn:3] Alternatively, for the case where ~A~ consists of an arbitrary
number of parallel signals, it could simply be the responsibility of
the programmer to make appropriate use of the differentiable addition
primitive instead of merge composition.

[fn:2]  See [cite:@radulYou2023], figure 1, for an illustration of
the sort of structure that would be required in order to support
reverse mode automatic differentiation.

[fn:1] Various transformations /are/ in fact possible at the level of
the \F{} compiler. See [[cref:sec:discussion]] for further exploration of
this idea.

* Emacs Setup                                                      :noexport:

- Set up =ifc24= document class.
- Add =-shell-escape= flag to latex process, so =svg= works.
- Use =listings= package for exported source blocks.

# Local Variables:
# eval:   (add-to-list 'org-latex-classes '("ifc24"
# "\\documentclass[twoside,a4paper]{article}
# [NO-DEFAULT-PACKAGES]"
# ("\\section{%s}" . "\\section*{%s}")
# ("\\subsection{%s}" . "\\subsection*{%s}")
# ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
# ("\\paragraph{%s}" . "\\paragraph*{%s}")
# ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# eval:   (setq org-latex-pdf-process '("latexmk -f -pdf -%latex \
# -interaction=nonstopmode -shell-escape -output-directory=%o %f"))
# eval:   (setq org-latex-src-block-backend 'listings)
# End:
