# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Differentiable DSP in Faust
# #+AUTHOR: Thomas Rushton

#+EXPORT_FILE_NAME: out/ifc24
#+OPTIONS: toc:nil ':t ^:{} num:3
#+LATEX_CLASS: ifc24
#+BIBLIOGRAPHY: IFC-24.bib
#+CITE_EXPORT: bibtex
#+LATEX_HEADER_EXTRA: \RequirePackage[]{./out/ifc24-style}
#+refproc: :abbreviate nil

#+begin_abstract
Differentiable Digital Signal Processing is the application of
differentiable programming, whereby a computer program may be
differentiated end-to-end, to audio tasks. Coupled with gradient-based
optimisation methods, differentiable signal processors are central to
a variety of audio problems and can be incorporated into machine
learning architectures.

In this paper it is shown that, using the ~environment~ expression and
pattern matching abstraction, it is possible to write \F{} code that
is differentiable end-to-end. A system for writing \F{} programs that
are automatically differentiable in the forward-mode is developed and
a parameter optimisation example presented. Differentiable programming
in \F{} could serve as a platform for native approaches to
machine learning problems in the audio domain.
#+end_abstract

* About                                                            :noexport:

Org file describing a paper for the 2024 International Faust
Conference.

Uses =org-ref= for cross references (which was a real bugger to set
up), and =citar=/=org-cite= for citations.

* Latex Setup                                                      :noexport:
:PROPERTIES:
:HEADER-ARGS: :tangle out/ifc24-style.sty :results silent
:END:

Remember to tangle =C-c C-v t= before exporting.

** Basics

#+begin_src latex
\ProvidesPackage{ifc24-style}[2024/07/12 v0.1 Bundling IFC24 LaTeX style]
#+end_src

** Author(s)

Title is taken from the title attribute.

#+begin_src latex
%% \def\papertitle{Differentiable DSP in Faust}
\def\paperauthorA{Thomas Albert Rushton}
#+end_src

Authors' affiliations have to be set below.

** Packages
#+begin_src latex
\usepackage{IFC-24}
\usepackage{amsmath,amssymb,amsfonts,amsthm,mathtools}
\usepackage{euscript}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{ifpdf}

\usepackage{color}
\usepackage{listings}
\definecolor{mygrey}{rgb}{0.96,0.96,0.96}
\lstset{
  tabsize=4,
  basicstyle=\ttfamily,
  backgroundcolor=\color{mygrey},
  captionpos=b,
  breaklines=true
}

\usepackage[english]{babel}
\usepackage{caption}
\usepackage{subfig, color}

\setcounter{page}{1}
\ninept

\usepackage{times}
\usepackage{inconsolata}

\usepackage{microtype}
\usepackage[inkscapelatex=false]{svg}
#+end_src

** LaTeX vs PDFLaTeX

#+begin_src latex
% pdf-tex settings: detect automatically if run by latex or pdflatex
\newif\ifpdf
\ifx\pdfoutput\relax
\else
   \ifcase\pdfoutput
      \pdffalse
   \else
      \pdftrue
\fi

\ifpdf % compiling with pdflatex
  \usepackage[pdftex,
    pdftitle={\papertitle},
    pdfauthor={\paperauthorA, \paperauthorB, \paperauthorC, \paperauthorD},
    colorlinks=false, % links are activated as colror boxes instead of color text
    bookmarksnumbered, % use section numbers with bookmarks
    pdfstartview=XYZ % start with zoom=100% instead of full screen; especially useful if working with a big screen :-)
  ]{hyperref}
  \pdfcompresslevel=9
  \usepackage[pdftex]{graphicx}
  \usepackage[figure,table]{hypcap}
\else % compiling with latex
  \usepackage[dvips]{epsfig,graphicx}
  \usepackage[dvips,
    colorlinks=false, % no color links
    bookmarksnumbered, % use section numbers with bookmarks
    pdfstartview=XYZ % start with zoom=100% instead of full screen
  ]{hyperref}
  % hyperrefs are active in the pdf file after conversion
  \usepackage[figure,table]{hypcap}
\fi
#+end_src

** Cleveref must be loaded last\dots

...otherwise =hyperref= throws a wobbler and won't link equations, etc.

#+begin_src latex
\usepackage[noabbrev]{cleveref}
#+end_src

Coupled with the ~#+refproc:~ directive above, =cleveref= should not
abbreviate cross-reference names... maybe for HTML, but not for LaTeX.

** Macros
#+begin_src latex
% Special Macros
\newcommand{\F}{\textsc{Faust}}
#+end_src

** Author affiliations

Single author affiliation:

#+begin_src latex
\affiliation{\paperauthorA}
{Inria, INSA Lyon, CITI, EA3720 \\ 69621 Villeurbanne, France\\
{\tt \href{mailto:thomas.rushton@inria.fr}{thomas.rushton@inria.fr}}
}
#+end_src

** Bibliography

#+begin_src latex
\bibliographystyle{IEEEbib}
#+end_src

** Page numbers

Don't display them:

#+begin_src latex
\pagenumbering{gobble}
#+end_src

* Adding Image Attributes                                          :noexport:

You've generated some image output from a source block; now you want
to add attributes like ~#+CAPTION:~, etc. There are a few approaches,
none of which is perfectly lovely. To suggest a couple:

- Generate an image result, then add attributes between the source
  block or ~CALL~ statement and the results.
#+begin_example
#+begin_src
...
#+end_src
#+CAPTION: A delightful caption
#+ATTR_LATEX: :width .5\linewidth
#+RESULTS:...
#+end_example

- Use [[https://orgmode.org/manual/Evaluating-Code-Blocks.html#How-to-evaluate-source-code-1][inline call]] syntax
#+begin_example
#+NAME: faust_code
#+begin_src faust
...
#+end_src

#+ATTR_LATEX: :width .75\linewidth
call_faust_code()[:results svg file :file image.svg :output-dir images
:exports results]
#+end_example

The latter doesn't provide a preview, but less manual intervention is
necessary.

One more thing: for regular source blocks, ~:output-dir~ and ~:file~
are combined into ~:file~ to produce =<outputdir>/<file>=. For
~#+CALL:~ this isn't the case; best to just use ~:file
<outputdir>/<file>~.

* More potentially useful syntax                                   :noexport:

This is an =org-ref= cross-reference: [[cref:sec:intro]]

Here's an =org-cite= citation: [cite:@rallArithmetic1986]

Here's some code:

#+begin_src faust
process = _;
#+end_src

And some inline code ~process = !;~

And floating code?

#+CAPTION: this code should float, because it has a caption
#+begin_src faust
process = 1;
#+end_src

* Introduction
:PROPERTIES:
:CUSTOM_ID: sec:intro
:END:

Differentiable programming is a programming paradigm whereby a
computer program can be differentiated end-to-end
[cite:@blondelElements2024]. The sensitivity of a differentiable
program's outputs to perturbations of its inputs can be computed via
automatic differentiation (AD, autodiff)
[cite:@rallArithmetic1986;@baydinAutomatic2018;], producing a partial
derivative with respect to each input parameter. End-to-end
differentiability is a desirable quality in the creation of computer
programs that perform gradient-based optimization, and differentiable
programming via automatic differentiation is the foundation for
contemporary approaches to machine learning [cite:@harrisonBrief2021].

Differentiable Digital Signal Processing (DDSP) is the application of
differentiable programming to DSP operations
[cite:@hayesReview2023]. The acronym /DDSP/ was coined by Engel et
al. [cite:@engelDifferentiable2020], who used it to refer to the
specific case of combining differentiable signal processors with a
neural network architecture, but in principle any DSP system featuring
recursive optimisation using gradients found as partial derivatives of
a loss function fits this label [cite:@hayesReview2023], including
work dating as far back as the late 1980's
[cite:@shynkAdaptive1989]. In addition to Engel et al.'s timbre
transfer implementation via a differentiable spectral modelling
synthesiser, DDSP has been applied to audio tasks such as source
separation [cite:@schulze-forsterUnsupervised2023], filter
optimisation [cite:@kuznetsovDifferentiable2020], and echo
cancellation [cite:@casebeerAutoDSP2021] --- see
[cite:@hayesReview2023] for a comprehensive review.

This paper introduces the concept of a /differentiation
arithmetic/ [cite:@rallArithmetic1986] to \F{}, facilitating the
creation of differentiable audio algorithms in the \F{}
language. Following a detailed account of the arithmetic of automatic
differentiation, the development of an automatic differentiation
framework in \F{} is outlined, and applied to a simple, but
illustrative, parameter optimisation problem. There is a sense in
which the block-diagram algebra of \F{} lends itself intuitively to
the problem of automatic differentiation (in its forward mode at
least), and the possibility of writing differentiable code in an audio
domain specific language paves the way for novel approaches to
problems at the intersection of DSP and machine learning.

* Algorithmic Differentiation
:PROPERTIES:
:CUSTOM_ID: sec:algorithmic-diff
:END:

Methods for computational differentiation are typically characterised
as falling into one of three camps: /numerical/, /symbolic/, and
/automatic/. Numerical differentiation produces numerical values for
derivatives via approximation by finite differences, and will be
familiar to those acquainted with finite-difference time-domain audio
synthesis methods [cite:@bilbaoNumerical2009]. Symbolic
differentiation takes a computational expression and generates the
corresponding expression for its derivative; this approach may
resonate with users of MATLAB's Symbolic Math Toolbox
[cite:@molerSymbolic1997] or the Maple programming language
[cite:@monaganGRADIENT1993]. Automatic differentiation describes an
arithmetic for accumulating both the numerical output of a
computational expression and the numerical value of its derivative; it
is an arithmetic of this kind that underpins the current crop of
Python libraries for machine learning [cite:@harrisonBrief2021].

A certain ambiguity abounds with regard to how automatic and symbolic
differentiation relate to each other [cite:@laueEquivalence2022], and
partisan views have been expressed over which is more efficient
[cite:@guenterEfficient2007]. The ambiguity may be ascribed in part to
the former's nature as "partly symbolic and partly numerical"
[cite:@harrisonBrief2021], and perhaps also to the fact that programs
composed symbolically may be differentiated automatically
[cite:@villardADrien1999]. For our purposes, we shall defer to Rall,
who, writing in the mid-1980's, before the waters were muddied by
legions of machine learning researchers, observed (to paraphrase):
/symbolic approaches produce formulas whereas automatic approaches
produce numerical outputs/ [cite:@rallArithmetic1986]. The latter do
so, however, by implementing differentiation rules, symbolically, at
the level, as we will see, of the primitive operations of the
programming language upon which they are based.

** The Arithmetic of Automatic Differentiation

Two main /modes/ of automatic differentiation are typically alluded to
in scholarly works on the topic: forward (or /tangent/) mode, and
reverse (or /adjoint/) mode [cite:@blondelElements2024;
@baydinAutomatic2018; @harrisonBrief2021]. These modes describe, in
effect, two directions of derivative propagation through a computation
graph; in tangent mode, derivatives propagate forward, from inputs to
outputs; in adjoint mode, propagation occurs backwards, from outputs
to inputs. What does it mean, however, for a derivative to propagate?
And is that propagation numerical or symbolic? As we will see, the
answer to the second question is /"both"/; the answer to the first is
less concise, but, irrespective of the direction of propagation, it
lies in the chain rule of differentiation.

*** The Chain Rule

The chain rule is fundamental to both the forward and reverse modes of
automatic differentiation, and it is pertinent at this point to offer
its definition. Consider a differentiable function, \(y :
\mathbf{v}\mapsto{}f(\mathbf{v})\), of \(m\) independent variables;
for each \(j \in 1, \dots, m\), let \(v_{j}\) be a differentiable function of \(n\)
independent variables:

#+NAME: eq:diff-functions-1
\begin{align}
y &: \mathbf{v} \mapsto f(v_{1}, v_{2}, \dots, v_{m}) \\
v_{j} &: \mathbf{w} \mapsto v_{j}(w_{1}, w_{2}, \dots, w_{n})\;.
\end{align}
The chain rule states that, for any \(k \in 1, \dots, n\), the derivative of
\(y\) with respect to \(w_{k}\) is

#+NAME: eq:chain-rule-1
\begin{equation}
\frac{\partial{}y}{\partial{}w_{k}} = \sum_{j=1}^{m}\frac{\partial{}y}{\partial{}v_{j}}\frac{\partial{}v_{j}}{\partial{}w_{k}}\;.
\end{equation}
We can also imagine a situation in which each \(w_{k}\) is, in turn, a
function of \(p\) independent variables,

#+NAME: eq:diff-functions-2
\begin{equation}
w_{k} : \mathbf{x} \mapsto w_{k}(x_{1}, x_{2}, \dots, x_{p})\;,
\end{equation}
in which case, for any \(i \in 1, \dots, p\), the derivative of \(y\)
with respect to \(x_{i}\) is

#+NAME: eq:chain-rule-2
\begin{equation}
\frac{\partial{}y}{\partial{}x_{i}} = \sum_{j=1}^{m}\frac{\partial{}y}{\partial{}v_{j}}\left(
  \sum_{k=1}^{n}\frac{\partial{}v_{j}}{\partial{}w_{k}}\frac{\partial{}w_{k}}{\partial{}x_{i}}
\right)\;.
\end{equation}

To give an audio-relevant example, imagine the case of a gain control,
\(x_{1}\), and a DC offset, \(x_{2}\), applied to an input signal,
\(s\). With some knowledge of elementary calculus, one could observe
that \(y = sx_{1} + x_{2}\) and find \(\frac{\partial{}y}{\partial{}x_{1}} = s\), and
\(\frac{\partial{}y}{\partial{}x_{2}} = 1\). This entails having an overview of the
expression as a whole, however, which works for this simple example,
but may not be feasible for more complex audio processes. Using the
chain rule, we can break our expression down into its fundamental,
/primitive/ operations, and differentiate each separately:

#+NAME: eq:chainrule-example
\begin{align*}
y &= f(v_{1}, v_{2}) = v_{1} + v_{2} \\
  & v_{1}(w_{1}, w_{2}, w_{3}) = w_{1}w_{2}\;,\quad v_{2}(w_{1}, w_{2}, w_{3}) = w_{3}\\
  & w_{1}(x_{1}, x_{2}) = s\;, \quad w_{2}(x_{1}, x_{2}) = x_{1}\;, \quad w_{3}(x_{1}, x_{2}) = x_{2}\\
\frac{\partial{}y}{\partial{}x_{i}} &= \sum_{j=1}^{2}\frac{\partial{}y}{\partial{}v_{j}}\left(
  \sum_{k=1}^{3}\frac{\partial{}v_{j}}{\partial{}w_{k}}\frac{\partial{}w_{k}}{\partial{}x_{i}}
\right) \\
  &= \frac{\partial{}y}{\partial{}v_{1}}\left(
  \frac{\partial{}v_{1}}{\partial{}w_{1}}\frac{\partial{}w_{1}}{\partial{}x_{i}} +
  \frac{\partial{}v_{1}}{\partial{}w_{2}}\frac{\partial{}w_{2}}{\partial{}x_{i}} +
  \frac{\partial{}v_{1}}{\partial{}w_{3}}\frac{\partial{}w_{3}}{\partial{}x_{i}}
\right) + \\
  &\quad\,\,\frac{\partial{}y}{\partial{}v_{2}}\left(
  \frac{\partial{}v_{2}}{\partial{}w_{1}}\frac{\partial{}w_{1}}{\partial{}x_{i}} +
  \frac{\partial{}v_{2}}{\partial{}w_{2}}\frac{\partial{}w_{2}}{\partial{}x_{i}} +
  \frac{\partial{}v_{2}}{\partial{}w_{3}}\frac{\partial{}w_{3}}{\partial{}x_{i}}
\right) \\
i = 1, &= 1\left(w_{2}\cdot0 + w_{1}\cdot1 + 0\cdot0\right) + 1\left(0\cdot0 + 0\cdot1 + 1\cdot0\right) \\
  &= w_{1} \\
  &= s \\
i = 2, &= 1\left(w_{2}\cdot0 + w_{1}\cdot0 + 0\cdot1\right) + 1\left(0\cdot0 + 0\cdot0 + 1\cdot1\right) \\
  &= 1\;.
\end{align*}
The above may look awfully fussy on paper, but note that the correct
solutions have been reached without us having to consider anything
more complicated at any one time than the derivative of the product of
a variable by a constant
(e.g. \(\frac{\partial{}v_{1}}{\partial{}w_{2}}\)). The answers
emerged /automatically/, in a sense; indeed, this fastidious
decomposition of an expression into its differentiable, primitive
operations is the essence of automatic differentiation.

*** Forward Mode Automatic Differentiation
:PROPERTIES:
:CUSTOM_ID: subsubsec:forward-mode
:END:

To investigate forward mode automatic differentiation, we can use an
example \F{} program with the following block diagram:

#+begin_src faust :results file svg :file (org-babel-temp-file "faust-" ".svg") :exports results
N = 5;
// Just create something that the compiler will bundle into an
// abstraction in the block diagram.
S(j) = sum(i,N,((i+j) : sqrt)/N);
process = (v1 <: _,_),v2 : v3,v4 : v5
with {
    v1 = S(0);
    v2 = S(1);
    v3 = _,S(2) : +;
    v4 = +,S(3) : +;
    v5 = +,S(4) : +;
};
#+end_src
#+CAPTION: /Block diagram of a \F{} program consisting of primitive/
#+CAPTION: /operations, \(v_{j}\)./
#+NAME: fig:block-diag-forward-mode
#+RESULTS:
[[file:/tmp/babel-opgpxN/faust-tKVbw0.svg]]

This program consists of a number of what we will consider to be
primitive operations \(v_{j}\). \(N = 2\) of these we will designate as
parameter primitives, each taking its value from a vector,
\(\mathbf{x} = \begin{bmatrix}x_{1} & x_{2}\end{bmatrix}\), of input
variables:

\begin{align}
v_{1} &: \mathbf{x} \mapsto x_{1} \label{eq:v1} \\
v_{2} &: \mathbf{x} \mapsto x_{2}\;. \label{eq:v2}
\end{align}
These parameters are passed to two further primitives,

#+NAME: eq:v3-v4
\begin{align}
v_{3} &: v_{1} \mapsto v_{3}(v_{1}) \\
v_{4} &: \begin{pmatrix}v_{1}\\v_{2}\end{pmatrix} \mapsto v_{4}(v_{1}, v_{2})\;,
\end{align}
and the program produces one output signal, the output of the final
primitive in the graph, which we can refer to as the /primal/ output
of the program,

#+NAME: eq:output
\begin{align}
v_{5} : \begin{pmatrix}v_{3}\\v_{4}\end{pmatrix} &\mapsto v_{5}(v_{3}, v_{4}) \\
y &= v_{5}\;.
\end{align}

In forward mode, differentiating a given primitive is a case of
computing its sensitivity to changes in the program's inputs,
producing a /tangent/ vector of partial derivatives, each with respect
to an element in the parameter vector \(\mathbf{x}\). For example, the
input primitive \(v_{1}\) returns as its derivative

#+NAME: eq:dv1-dx
\begin{equation}
\frac{\partial{}v_{1}}{\partial{}\mathbf{x}} = \begin{bmatrix}\frac{\partial{}v_{1}}{\partial{}x_{1}} \\ \frac{\partial{}v_{1}}{\partial{}x_{2}}\end{bmatrix}\;.
\end{equation}
On paper, per cref:eq:v1, this simplifies to \(\begin{bmatrix}1 &
0\end{bmatrix}^{T}\), but in the context of automatic differentiation
no such simplification takes place; rather, we take this result and
pass it to the next primitive in the graph. Stepping forward then, and
using the description of the chain rule in cref:eq:chain-rule-1, with
\(m = 1\), plus substituting \(y = v_{3}\) and \(w_{k} = x_{i}\) (and
reversing the order of multiplicative terms to better illustrate our
forward progress through the graph), the partial derivatives of
primitive \(v_{3}\) are

#+NAME: eq:dv3-dx
\begin{equation}
\frac{\partial{}v_{3}}{\partial{}\mathbf{x}} = \begin{bmatrix}
  \frac{\partial{}v_{1}}{\partial{}x_{1}}\frac{\partial{}v_{3}}{\partial{}v_{1}} \\
  \frac{\partial{}v_{1}}{\partial{}x_{2}}\frac{\partial{}v_{3}}{\partial{}v_{1}}
\end{bmatrix}\;,
\end{equation}
notwithstanding the fact that \(v_{1}\) (and by extension \(v_{3}\)) does
not depend on \(x_{2}\). \(v_{4}\) is a multivariate primitive, so the chain
rule for multivariate functions, i.e. cref:eq:chain-rule-1 with \(m =
2\), comes into play:

#+NAME: eq:dv4-dx
\begin{equation}
\frac{\partial{}v_{4}}{\partial{}\mathbf{x}} = \begin{bmatrix}
  \frac{\partial{}v_{1}}{\partial{}x_{1}}\frac{\partial{}v_{4}}{\partial{}v_{1}} + \frac{\partial{}v_{2}}{\partial{}x_{1}}\frac{\partial{}v_{4}}{\partial{}v_{2}} \\
  \frac{\partial{}v_{1}}{\partial{}x_{2}}\frac{\partial{}v_{4}}{\partial{}v_{1}} + \frac{\partial{}v_{2}}{\partial{}x_{2}}\frac{\partial{}v_{4}}{\partial{}v_{2}}
\end{bmatrix}\;.
\end{equation}

Combining and extending [[cref:eq:dv3-dx,eq:dv4-dx]] we can produce a
derivative expression for \(v_{5}\),

#+NAME: eq:dv5-dx
\begin{equation}
\frac{\partial{}v_{5}}{\partial{}\mathbf{x}} = \begin{bmatrix}
  \frac{\partial{}v_{1}}{\partial{}x_{1}}
  \frac{\partial{}v_{3}}{\partial{}v_{1}}
  \frac{\partial{}v_{5}}{\partial{}v_{3}}
  +
  \frac{\partial{}v_{1}}{\partial{}x_{1}}
  \frac{\partial{}v_{4}}{\partial{}v_{1}}
  \frac{\partial{}v_{5}}{\partial{}v_{4}}
  +
  \frac{\partial{}v_{2}}{\partial{}x_{1}}
  \frac{\partial{}v_{4}}{\partial{}v_{2}}
  \frac{\partial{}v_{5}}{\partial{}v_{4}}
  \\
  \frac{\partial{}v_{1}}{\partial{}x_{2}}
  \frac{\partial{}v_{3}}{\partial{}v_{1}}
  \frac{\partial{}v_{5}}{\partial{}v_{3}}
  +
  \frac{\partial{}v_{1}}{\partial{}x_{2}}
  \frac{\partial{}v_{4}}{\partial{}v_{1}}
  \frac{\partial{}v_{5}}{\partial{}v_{4}}
  +
  \frac{\partial{}v_{2}}{\partial{}x_{2}}
  \frac{\partial{}v_{4}}{\partial{}v_{2}}
  \frac{\partial{}v_{5}}{\partial{}v_{4}}
\end{bmatrix}\;,
\end{equation}
and that, in effect, gives us an expression for
\(\frac{\partial{}y}{\partial{}\mathbf{x}}\), a \(2\times1\) Jacobian matrix.

The ultimate aim of automatic differentiation is not, however, simply
to produce symbolic expressions, but numerical outputs. To calculate
the numerical value of the derivative of \(y\) with respect to \(x_{i}\),
we begin by differentiating \(\mathbf{x}\) with respect to \(x_{i}\):

#+NAME: eq:partial-x1
\begin{equation}
\frac{\partial{}\mathbf{x}}{\partial{}x_{i}}
= \begin{bmatrix}\frac{\partial{}x_{1}}{\partial{}x_{i}} & \frac{\partial{}x_{2}}{\partial{}x_{i}}\end{bmatrix}\;.
\end{equation}
We then propagate this tangent vector through the graph, producing the
/forward tangent output/ of the program. On paper this looks like a
vector product (a /Jacobian vector product/ in fact
[cite:@baydinAutomatic2018]), and simply extracts the first element of
the vector in [[cref:eq:dv5-dx]]; for example,

#+NAME: eq:vec-prod
\begin{align}
\frac{\partial{}y}{\partial{}x_{1}} &= \frac{\partial{}\mathbf{x}}{\partial{}x_{1}}\frac{\partial{}y}{\partial{}\mathbf{x}} \nonumber \\
&= \begin{bmatrix}1 & 0\end{bmatrix}\frac{\partial{}y}{\partial{}\mathbf{x}} \nonumber \\
&= \frac{\partial{}v_{1}}{\partial{}x_{1}}
  \frac{\partial{}v_{3}}{\partial{}v_{1}}
  \frac{\partial{}v_{5}}{\partial{}v_{3}}
  +
  \frac{\partial{}v_{1}}{\partial{}x_{1}}
  \frac{\partial{}v_{4}}{\partial{}v_{1}}
  \frac{\partial{}v_{5}}{\partial{}v_{4}}
  +
  \frac{\partial{}v_{2}}{\partial{}x_{1}}
  \frac{\partial{}v_{4}}{\partial{}v_{2}}
  \frac{\partial{}v_{5}}{\partial{}v_{4}}\;.
\end{align}
To compute \(\frac{\partial{}y}{\partial{}x_{2}}\), we find \(\frac{\partial{}\mathbf{x}}{\partial{}x_{2}}
= \begin{bmatrix}0 & 1\end{bmatrix}\) and proceed similarly.

To give an example, let's assign some concrete functions to \(v_{j}\):

#+NAME: eq:funcs
\begin{equation}
v_{3} = \sin(v_{1})\;, \quad v_{4} = v_{1} + v_{2}\;, \quad v_{5} = v_{3}v_{4}\;,
\end{equation}
and substitute these into [[cref:eq:vec-prod]] (and the equivalent for
\(x_{2}\)):

\begin{align}
\frac{\partial{}y}{\partial{}x_{1}} &= \left(1\cdot\cos(v_{1})\cdot{}v_{4}\right) + \left(1\cdot1\cdot{}v_{3} + 0\cdot1\cdot{}v_{3}\right) \nonumber \\
  &= v_{4}\cos(v_{1}) + v_{3} \nonumber \\
  &= (x_{1} + x_{2})\cos(x_{1}) + \sin(x_{1}) \label{eq:concrete-fwd-x1} \\
\frac{\partial{}y}{\partial{}x_{2}} & = \left(0\cdot\cos(v_{1})\cdot{}v_{4}\right) + \left(0\cdot1\cdot{}v_{3} + 1\cdot1\cdot{}v_{3}\right) \nonumber \\
  &= v_{3} \nonumber \\
  &= \sin(x_{1})\;. \label{eq:concrete-fwd-x2}
\end{align}
Providing numerical values for \(x_{1}\) and \(x_{2}\) would of course yield
numerical values for the above.

One potential drawback of forward mode concerns computational
efficiency --- to compute all of the partial derivatives of \(y\),
\(N\) passes are required. For programs with more outputs than inputs,
this would not be a problem, but in the audio domain, where inputs
will likely outnumber outputs, it is potentially a concern (see
ref:subsec:efficiency for more on this subject).

*** Reverse Mode Automatic Differentiation

For reverse mode, consider a very similar \F{} program to the one
depicted in cref:fig:block-diag-forward-mode:

#+begin_src faust :results file svg :file (org-babel-temp-file "faust-" ".svg") :exports results
N = 5;
// Just create something that the compiler will bundle into an
// abstraction in the block diagram.
S(j) = sum(i,N,((i+j) : sqrt)/N);
process = (v11 <: _,_),v12 : v21,v22 : v31
with {
    v11 = S(0);
    v12 = S(1);
    v21 = _,S(2) : +;
    v22 = +,S(3) : +;
    v31 = +,S(4) : +;
};
#+end_src
#+CAPTION: /Block diagram of a \F{} program with primitives/
#+CAPTION: /organised into layers in preparation for reverse mode/
#+CAPTION: /automatic differentiation./
#+NAME: fig:block-diag-reverse-mode
#+RESULTS:
[[file:/tmp/babel-opgpxN/faust-PWTlte.svg]]

\noindent
As with forward mode, we have an input vector \(\mathbf{x}\) of length
\(N = 2\). This time, however, we group our primitives, \(v_{p,q}\), into
layers, \(p\), and identify them by their index, \(q\), within each
layer:

#+NAME: eq:primitives
\begin{align}
v_{1,1} &: \mathbf{x} \mapsto x_{1} \\
v_{1,2} &: \mathbf{x} \mapsto x_{2} \\
v_{2,1} &: v_{1,1} \mapsto v_{2,1}(v_{1,1}) \\
v_{2,2} &: \begin{pmatrix}v_{1,1} \\ v_{1,2}\end{pmatrix} \mapsto v_{2,2}(v_{1,1}, v_{1,2}) \\
v_{3,1} &: \begin{pmatrix}v_{2,1} \\ v_{2,2}\end{pmatrix} \mapsto v_{3,1}(v_{2,1}, v_{2,2}) \;,
\end{align}
and, as before, we have a single output, \(y = v_{3,1}\).

Whereas in forward mode the primal and tangent outputs of the program
are computed in parallel during the forward pass, in reverse mode we
complement the forward primal pass with a /reverse adjoint pass/;
instead of computing the /sensitivity/ of each primitive with respect
to its inputs, we compute the /influence/ of a given primitive on the
output of the program:

#+NAME: eq:adjoint
\begin{equation}
\bar{v}_{p,q} = \frac{\partial{}y}{\partial{}v_{p,q}}\;.
\end{equation}

Rather than propagate successive tangent vectors forward through the
computation graph, we instead compute the adjoint of the program's
output (i.e. the influence of the output over itself),

#+NAME: eq:y-adjoint
\begin{equation}
\bar{y} = \bar{v}_{3,1} = \frac{\partial{}y}{\partial{}v_{3,1}} = 1\;,
\end{equation}
and propagate that backward through the graph. Adjoints for layer \(p =
2\) are

#+NAME: eq:v2-adjoints
\begin{equation}
\bar{v}_{2,q} &= \bar{v}_{3,1}\frac{\partial{}v_{3,1}}{\partial{}v_{2,q}} = \frac{\partial{}y}{\partial{}v_{3,1}}\frac{\partial{}v_{3,1}}{\partial{}v_{2,q}}\;.
\end{equation}

In general, the adjoint for primitive \(v_{p,q}\) is found as the sum of
the derivatives of the \(M\) primitives in the \((p+1)\)^{th} layer,

#+NAME: eq:general-adjoint
\begin{align}
\bar{v}_{p,q} &= \frac{\partial{}y}{\partial{}v_{p,q}} \nonumber \\
  &= \sum^{M}_{m=1}\frac{\partial{}y}{\partial{}v_{p+1,m}}\frac{\partial{}v_{p+1,m}}{\partial{}v_{p,q}} \nonumber \\
  &= \sum^{M}_{m=1}\bar{v}_{p+1,m}\frac{\partial{}v_{p+1,m}}{\partial{}v_{p,q}}\;,
\end{align}
so adjoints for the input layer, \(p = 1\), emerge as

#+name: eq:v1-adjoint
\begin{align}
\bar{v}_{1,q} &= \bar{v}_{2,1}
  \frac{\partial{}v_{2,1}}{\partial{}v_{1,q}} +
  \bar{v}_{2,2}
  \frac{\partial{}v_{2,2}}{\partial{}v_{1,q}} \nonumber \\
&= \bar{v}_{3,1}
  \frac{\partial{}v_{3,1}}{\partial{}v_{2,1}}
  \frac{\partial{}v_{2,1}}{\partial{}v_{1,q}} +
  \bar{v}_{3,1}
  \frac{\partial{}v_{3,1}}{\partial{}v_{2,2}}
  \frac{\partial{}v_{2,2}}{\partial{}v_{1,q}} \nonumber \\
&= \frac{\partial{}y}{\partial{}v_{3,1}}
  \frac{\partial{}v_{3,1}}{\partial{}v_{2,1}}
  \frac{\partial{}v_{2,1}}{\partial{}v_{1,q}} +
  \frac{\partial{}y}{\partial{}v_{3,1}}
  \frac{\partial{}v_{3,1}}{\partial{}v_{2,2}}
  \frac{\partial{}v_{2,2}}{\partial{}v_{1,q}}\;,
\end{align}
giving us

#+NAME: eq:xi-adjoint
\begin{equation}
\bar{x}_{i} = \frac{\partial{}y}{\partial{}x_{i}} = \bar{v}_{1,i}\;.
\end{equation}

Expanding the terms above, while illustrative, is not necessary;
indeed, [[cref:eq:v1-adjoint]] could end at the first line; we have
definitions for \(\bar{v}_{2,1}\) and \(\bar{v}_{2,2}\) and these propagate
backward through the graph without any need for them to be
recomputed. In effect, though the graph may branch as adjoints
propagate, we achieve both \(\frac{\partial{}y}{\partial{}x_{1}} = \bar{v}_{1,1}\) and
\(\frac{\partial{}y}{\partial{}x_{2}} = \bar{v}_{1,2}\) in a single pass, unlike in tangent
mode, where two passes are required.

As with the forward mode example, let's assign some functions to
\(v_{p,q}\) to verify our implementation:

#+NAME: eq:concrete-funcs
\begin{equation}
v_{2,1} = \sin(v_{1,1})\:, \quad v_{2,2} = v_{1,1} + v_{1,2}\:, \quad v_{3,1} = v_{2,1}v_{2,2}\;.
\end{equation}
Substituting these into [[cref:eq:v1-adjoint]],

\begin{align}
\frac{\partial{}y}{\partial{}x_{1}} &= 1\cdot{}v_{2,2}\cdot\cos(v_{1,1}) + 1\cdot{}v_{2,1}\cdot1 \nonumber \\
  &= (v_{1,1} + v_{1,2})\cos(v_{1,1}) + v_{2,1} \nonumber \\
  &= (x_{1} + x_{2})\cos(x_{1}) + \sin(x_{1}) \label{eq:concrete-rev-x1} \\
\frac{\partial{}y}{\partial{}x_{2}} &= 1\cdot{}v_{2,2}\cdot0 + 1\cdot{}v_{2,1}\cdot1 \nonumber \\
  &= v_{2,1} \nonumber \\
  &= \sin(v_{1,1}) \nonumber \\
  &= \sin(x_{1})\;, \label{eq:concrete-rev-x2}
\end{align}
we reach entirely the same results as achieved in
cref:eq:concrete-fwd-x1,eq:concrete-fwd-x2 via tangent mode.

For reverse mode to work in practice, however, some knowledge of a
program's structure is required. Whether this is achieved via a
bookkeeping mechanism [cite:@baydinAutomatic2018] such as a /"tape"/
[cite:@pearlmutterReversemode2008;@radulYou2023], or by organising the
program into layers as we have here, adjoint mode introduces a degree
of complexity that tangent mode, with its more brute-force approach,
does not.

*** Dual Number Arithmetic

One interesting property of forward mode lies in the possibility of
formulating differentiation in a manner similar to the complex numbers
[cite:@rallArithmetic1986;@yuDNAD2013]. Where complex arithmetic uses
the imaginary unit \(i\) to designate the imaginary part of a complex
number \(z = x + iy\), with \(i^{2} = -1\), differentiation arithmetic
uses the /nilpotent symbol/, \(\varepsilon\)
[cite:@yuDNAD2013;@baydinAutomatic2018]:

#+NAME: eq:nilpotent
\begin{equation}
U = u + \varepsilon{}u'\;,
\end{equation}
where \(u' = \frac{du}{dx}\) is the derivative of \(u\) with respect
to some variable \(x\)  and \(\varepsilon^{2}\) = 0.

Using this arithmetic, the addition rule of differentiation emerges
quite naturally as the sum of \(U\) and \(V = v + \varepsilon{}v'\),

#+NAME: eq:addition-rule
\begin{equation}
(u + \varepsilon{}u') + (v + \varepsilon{}v') = u + v + \varepsilon(u' + v')\;.
\end{equation}
Similarly, the product rule, via a simple polynomial expansion

#+NAME: eq:product-rule
\begin{align}
(u + \varepsilon{}u')(v + \varepsilon{}v') &= uv + u\varepsilon{}v' + v\varepsilon{}u' + \varepsilon^{2}u'v' \nonumber \\
                   &= uv + \varepsilon(uv' + vu')\;,
\end{align}
the final term cancelling due to the presence of \(\varepsilon^{2}\).

This arithmetic may be more conveniently expressed, for computational
purposes, as one of /ordered
pairs/ [cite:@rallArithmetic1986;@kalmanDoubly2002] or /dual numbers/
[cite:@yuDNAD2013;@sigalAutomatic2021;@revelsForwardMode2016],

#+NAME: eq:dual
\begin{equation}
U = \langle u, u' \rangle\;.
\end{equation}
The addition and product rules now take the following forms:

\begin{align}
U+V &= \langle u, u' \rangle + \langle v, v' \rangle = \langle u + v, u' + v' \rangle \label{eq:addition-rule-dual}\\
UV &= \langle u, u' \rangle\langle v, v' \rangle = \langle uv, uv' + vu' \rangle\;. \label{eq:product-rule-dual}
\end{align}
The first component of each dual number is the rule for evaluation of
the operation; the second is the rule for differentiation
[cite:@rallArithmetic1986]. These components may be referred to as the
/primal/ and /tangent/ respectively
[cite:@baydinAutomatic2018;@radulYou2023]. In dual number
differentiation arithmetic, an independent variable can be expressed
as \(X = \langle x,\frac{dx}{dx} \rangle\), and a constant \(C = \langle c,\frac{dc}{dx}
\rangle\). If we wish, for example, to compute the primal and tangent of a
polynomial \((x + 1)(x - 2)\) at \(x = 2\), we set \(X = \langle 2,1 \rangle\) and
supply appropriate values for the constants:

#+NAME: eq:product-example
\begin{equation}
(\langle 2,1 \rangle + \langle 1,0 \rangle)(\langle 2,1 \rangle - \langle 2,0 \rangle) = \langle 3,1 \rangle\langle 0,1 \rangle = \langle 0,3 \rangle\;. \nonumber
\end{equation}
We find that our arithmetic produces the expected numerical results
/automatically/ via composition of the fundamental operations
characterised by [[cref:eq:addition-rule-dual,eq:product-rule-dual]].

Differentiation arithmetic of this sort is a special case of a more
general /gradient arithmetic/ [cite:@rallArithmetic1986], which comes
into effect when multiple variables are present, and thus multiple
partial derivatives must be calculated:

#+NAME: eq:dual-gradient
\begin{equation}
U = \langle u, \nabla{}u \rangle\;.
\end{equation}

** Extending \F{}'s Arithmetic
:PROPERTIES:
:CUSTOM_ID: subsec:extend-arithmetic
:END:

One quality generally possessed by automatic differentiation
implementations is that of allowing the programmer to write
differentiable programs with minimal changes to the syntax of their
code. This is typically achieved either by source code transformation
or operator overloading [cite:@yuDNAD2013;@baydinAutomatic2018]
--- neither of which is available in the \F{} language.[fn:1] We could
take an approach similar to Wengert's 1964 demonstration of the
composition of differentiable functions in Fortran
[cite:@wengertSimple1964] and define differentiable functions
~diffAdd~, ~diffMul~, etc. each accepting and returning dual numbers;
thanks to \F{}'s pattern matching abstraction, however, we can go one
better, achieving something akin to, albeit slightly more verbose
than, operator overloading.

Pattern matching has been used extensively in the \F{} libraries. The
=basics.lib= library, for example, provides a function with a
recursive pattern matching definition for taking an element from a
list:

#+begin_src faust :results none
// Take the first element, the head;
take(1, (head, rest)) = head;
// Take the only element;
take(1, head)         = head;
// Take the n-1th element from the rest.
take(n, (head, rest)) = take(n-1, rest);
#+end_src

The =physmodels.lib= library provides ~pm.chain~ for creating chains
of bidirectional signal blocks [cite:@michonFaust2018]. ~chain(A)~
simply returns the signal block ~A~; ~chain(A:As)~ creates a recursive
structure containing ~A~ and ~chain(As)~. Similarly, =wdmodels.lib=
facilitates the creation of wave digital filter models via primitive
elements, resistors, capacitors, etc. [cite:@roosenburgWave2021],
whose behaviour is defined via pattern matching syntax. Both libraries
extend \F{}'s arithmetic with their own rules, with the aim of
achieving a particular goal within the syntax provided by \F{}.

If one's particular goal was to be able to compose reciprocal
expressions, one could create an arithmetic of the following form,
using pattern matching to avoid division by zero:

#+begin_src faust :results none
import("stdfaust.lib");
recip(0) = recip(ma.EPSILON);
recip(0.0) = recip(0);
recip(expr) = 1,expr : /;
a = log(1);
b = _,2 : ^;
c = -;
process = recip(a),recip(b) : recip(c);
#+end_src
Wrapping our expressions in ~recip~ gives us automatic reciprocals
without affecting the fundamental composability of \F{}'s
primitives. Note that if we were to insert the expression ~recip(-) =
+;~ at the top of the program, the final operation, rather than
returning \(1/(a - b)\) would be /overridden/, in a manner of
speaking, returning \(a + b\) instead. An approach along these
lines will form the basis for the creation of differentiable \F{}
primitives.

* Differentiable Programming in \F{}

As described in cref:subsubsec:forward-mode, in forward mode, primal
and tangent outputs are found during a forward pass through the
computation graph, which fits neatly with the left-to-right
propagation of signals through a \F{} block diagram. Reverse
propagation of signals is entirely possible in \F{} (indeed forward
mode demands it as a final, backpropagation step --- see
cref:subsec:param-opt), and it is by way of nested recursive
composition that the =physmodels.lib= library accomplishes simulated
bidirectional wave propagation; the structures underpinning
=physmodels.lib= are purely linear, however, and, at the time of
writing, no general scheme for the creation of /branching/
bidirectional structures, such as reverse mode requires, has been
found.

Consequently, this section is concerned with the description of an
approach to differentiable programming in \F{} based on forward mode
automatic differentiation. End-to-end differentiability is predicated
on the availability of derivative expressions for the primitive
operations of the language; presented in the subsections that follow
is an approach to defining \F{} primitives that are differentiable in
forward mode.

** Defining a Differentiable Primitive

As a basic starting point, consider the addition primitive; in \F{}
one can write:

#+NAME: faust_add
#+begin_src faust
process = +;
#+end_src
which yields the block diagram:

#+CALL: faust_add() :results svg file :file images/add.svg :exports results
#+ATTR_LATEX: :width .5\linewidth
#+caption: /Block diagram of a \F{} program consisting of a lone/
#+caption: /addition primitive./
#+RESULTS:
[[file:images/add.svg]]
This signal processor takes two input signals, \(u\) and \(v\), and
produces one output signal, \(y\):

\begin{equation}
y = u + v\;.
\end{equation}
Note that \F{}'s addition primitive has no special knowledge of its
arguments, their history, provenance, etc., it just consumes them and
returns their sum. In \F{}'s arithmetic, the addition of two signals is
simply well-defined.

Suppose that \(y\) is dependent on some variable \(x\), and that we
wish to know how sensitive \(y\) is to perturbations in \(x\). We can
produce an analytic expression for this sensitivity by differentiating
\(y\) with respect to \(x\). Recall, from [[cref:eq:addition-rule-dual]],
that a dual-number addition takes the form of two additions in
parallel; in \F{}, that could be expressed as:

#+begin_src faust :results svg file :file images/dualadd.svg :exports both
diffAdd = +,+;
process = diffAdd;
#+end_src
#+ATTR_LATEX: :width .5\linewidth
#+caption: /Block diagram of a \F{} program representing a naive/
#+caption: /implementation of a dual signal differentiable addition/
#+caption: /primitive, consisting of two parallel additions./
#+RESULTS:
[[file:images/dualadd.svg]]
Since \F{} deals exclusively with the propagation of signals, we shall
refer to this as a /dual signal/ representation.

Just as the addition primitive has no special knowledge of its input
signals, nor does ~diffAdd~, but at this stage the notion of
differentiable addition is not well-defined. In order for this new
primitive to behave as it should, it is necessary to supplement \F{}'s
arithmetic with the following rule:

#+begin_quote
Supply \(\langle u, u' \rangle\) and \(\langle v, v' \rangle\) to the differentiable addition
primitive, in that order, and it should return \(\langle u+v, u'+v' \rangle\).
#+end_quote
To satisfy this rule, ~diffAdd~ needs to be modified, otherwise it
will produce the nonsensical result \(\langle y, y' \rangle = \langle u + u', v + v'
\rangle\); this can be remedied with \F{}'s ~route~ primitive:

#+begin_src faust :results svg file :file images/dualaddroute.svg :exports both
diffAdd = route(4, 4,
    (1, 1), (2, 3), (3, 2), (4, 4)) : +,+;
process = diffAdd;
#+end_src
#+ATTR_LATEX: :width .66\linewidth
#+name: fig:dual-add
#+caption: /Block diagram of a \F{} program representing a dual signal/
#+caption: /differentiable addition primitive. Via appropriate signal/
#+caption: /routing, dual signal output \(\langle y,y' \rangle = \langle u+v, u'+v' \rangle\)/
#+caption: /is produced./
#+RESULTS:
[[file:images/dualaddroute.svg]]
~diffAdd~ now satisfies the rule, implementing
cref:eq:addition-rule-dual, and describing a dual-signal
differentiable addition primitive. As alluded to in
cref:sec:algorithmic-diff, this primitive implements its
differentiation rule symbolically, via appropriate signal routing, and
will produce the correct numerical output automatically; it is
self-contained, well-defined, and composable with other similarly
well-defined primitives.

On that note, let's define some more differentiable primitives for
~diffAdd~ to act upon. For \(u\) we can use an arbitrary input signal,
which we will represent with \F{}'s identity function, ~_~. Such a
signal has no relationship with \(x\), so \(u' = 0\). To \(v\) we
assign the variable \(x\); one possible analogy to a variable in \F{}
is a slider; \(v = x\), so \(v' = 1\).

#+begin_src faust :results none
diffInput = _,0;
diffSlider = hslider("x", 0, -1, 1, .1),1;
#+end_src
Now we can compose these with our differentiable addition primitive:

#+begin_src faust :results none
u = diffInput;
v = diffSlider;
process = u,v : diffAdd;
#+end_src

#+begin_src faust :results file svg :file images/dc.svg :exports results
diffAdd = route(4, 4,
    (1, 1), (2, 3), (3, 2), (4, 4)) : +,+;
diffInput = _,0;
diffSlider = hslider("x", 0, -1, 1, .1),1;
process = diffInput,diffSlider : diffAdd;
#+end_src
#+ATTR_LATEX: :width 1\linewidth :placement [ht!]
#+name: fig:differentiable-dc
#+caption: /Block diagram of a \F{} program consisting of application/
#+caption: /of a differentiable addition primitive (see/
#+caption: /cref:fig:dual-add) to differentiable input and ~hslider~/
#+caption: /primitives./
#+RESULTS:
[[file:images/dc.svg]]

\noindent The primal output signal of this program (see
cref:fig:differentiable-dc for its block diagram) is the result of
applying a DC offset, \(x\), to an input signal; the tangent output,
the derivative with respect to \(x\), is a constant signal of value
\(1\). By composing primitives with well-defined derivatives, the
derivative of the entire program has been found /automatically/; the
above program is a rudimentary implementation of forward-mode
automatic differentiation in \F{}.

** Multivariate Differentiable Primitives

What if a program has more than one variable? Consider the following
(non-differentiable) example consisting of a DC offset and a gain
control applied to an input signal:

#+CAPTION: /A \F{} program that applies gain and DC offset parameters/
#+CAPTION: /to an input signal./
#+NAME: lst:gain-dc
#+begin_src faust
x1 = hslider("gain", .5, 0, 1, .1);
x2 = hslider("dc", 0, -1, 1, .1);
process = _,x1 : *,x2 : +;
#+end_src
which can be notated

#+NAME: eq:gain-dc
\begin{equation}
y = uv + w, \quad v = x_1, \quad w = x_2\;.
\end{equation}
Once again \(u\) is an arbitrary input signal, for which we have no
analytic expression. Now, rather a lone ordinary derivative \(y'\), we
have \(\nabla{}y\), a matrix of partial derivatives:

#+NAME: eq:pds
\begin{equation}
\nabla{}y = \frac{\partial y}{\partial \mathbf{x}}
= \begin{bmatrix}\frac{\partial y}{\partial x_1} \\
\frac{\partial y}{\partial x_2}\end{bmatrix}\;.
\end{equation}
Our algorithm takes two parameter inputs, and produces one output
signal, so the resulting Jacobian matrix is of dimension \(2 \times
1\). Returning to dual signal representation and applying the chain,
product and addition rules of differentiation,

#+NAME: eq:dual-gain-dc
\begin{align}
\langle y,\nabla{}y \rangle &=
\langle u,\nabla{}u \rangle \langle v,\nabla{}v \rangle + \langle w,\nabla{}w \rangle \nonumber \\
&= \langle uv,\nabla{}uv + \nabla{}vu \rangle + \langle w,\nabla{}w \rangle \nonumber \\
&= \langle uv + w,\nabla{}uv + \nabla{}vu + \nabla{}w\rangle\;.
\end{align}

To implement the above in \F{} calls for the creation of multivariate
differentiable primitives. One way to achieve this would be to
implement ~diffInput~, ~diffSlider~, and ~diffAdd~ as functions, each
taking as a parameter ~NVARS~, the number of variables in the program,
and thus partial derivatives that they should produce. Using \F{}'s
~environment~ expression, however it is possible to address the
problem in a more general, and syntactically succinct fashion.

*** A Differentiable Environment

First, we can define a function for collecting, counting, and
retrieving variables and their partial derivatives:

#+NAME: lst:var-env
#+CAPTION: /A \F{} function for defining an environment of/
#+CAPTION: /differentiable variables./
#+begin_src faust
vars(V) = environment {
  // Count the variables.
  N = outputs(V);
  // Retrieve a variable by index i.
  var(i) = ba.take(i, V),pds(N, i)
  with {
    // Compute partial derivatives of
    // variable x_i.
    pds(N, i) = par(j, N, i-1==j);
  };
};
#+end_src
~vars~ receives a list of variables, expressed via parallel
composition, e.g. ~X = vars((gain,dc));~, where ~gain~ and ~dc~ are
defined as ~hslider~ instances.

Next, we can define a function that takes the variable environment
produced by ~vars~ as its sole argument, and returns a /differentiable
environment/, containing a collection of multivariate differentiable
primitives. As a further improvement, we can use \F{}'s pattern
matching syntax to simplify the nomenclature of the differentiable
primitives; instead of exposing the name ~diffAdd~, for example, the
differentiable addition primitive can be named ~diff(+)~:

#+NAME: lst:diff-env
#+CAPTION: /Extract from the definition of a \F{} environment for/
#+CAPTION: /differentiable programming./
#+begin_src faust
env(vars) = environment {
  diff(+) = diffAdd with {
    diffAdd = route(nIN, nOUT,
      (u, 1), (v, 2), // u + v
      par(i, vars.N,
        // du/dx_i + dv/dx_i
        (u+i+1, dx), (v+i+1, dx+1)
        with {
          // Start of derivatives wrt x_i
          dx = 2*i+3;
        }
      )
    ) with {
      nIN = 2+2*vars.N;
      nOUT = nIN;
      u = 1;
      v = u+vars.N+1;
    }
    : +,par(i, vars.N, +);
  };

  // ...definitions of other
  // differentiable primitives...
};
#+end_src

As before, the primal signal output of the differentiable addition
primitive is the sum of the primal inputs, \(u+v\); now, however, the
differentiable primitive produces ~vars.N~ tangent outputs, each
corresponding to a derivative with respect to \(x_{i}\). As before, the
~route~ primitive ensures that incoming signals are delivered to the
parallel additions in the correct order.

Encapsulating [[cref:lst:var-env,lst:diff-env]] as a library in a file
named =diff.lib=, we can use ~vars~ and ~env~ to write a
differentiable version of the gain-plus-DC-offset program encountered
earlier:

#+CAPTION: /Differentiable counterpart to the \F{} program described/
#+CAPTION: /in [[cref:lst:gain-dc]]./
#+NAME: lst:gain-dc-diff
#+begin_src faust :results file svg :file images/gain-dc.svg :exports both
df = library("diff.lib");

X = df.vars((gain,dc)) with {
  gain = hslider("gain", .5, 0, 1, .01);
  dc = hslider("dc", 0, -1, 1, .01);
};

d = df.env(X);

process = d.input,X.var(1)
  : d.diff(*),X.var(2)
  : d.diff(+);
#+end_src
#+NAME: fig:gain-dc
#+ATTR_LATEX: :float multicolumn :placement [ht!]
#+CAPTION: /Block diagram of a differentiable \F{} program consisting/
#+CAPTION: /of differentiable gain and DC parameters applied to an/
#+CAPTION: /input signal (see [[cref:lst:gain-dc-diff]])./
#+RESULTS: lst:gain-dc-diff
[[file:images/gain-dc.svg]]
See [[cref:fig:gain-dc]] for the block diagram of this program. Note that
while the routing for each primitive --- particularly ~diff(*)~ ---
may be quite complex (and would only become more involved with the
addition of further variables) the ~df~ library abstracts this
complexity away.

** Parameter Optimisation via Gradient Descent
:PROPERTIES:
:CUSTOM_ID: subsec:param-opt
:END:

Armed with the means to write end-to-end differentiable \F{} programs,
it is possible, with a few modifications (and additions to
=diff.lib=), to combine the code in
[[cref:lst:gain-dc,lst:gain-dc-diff]], to create a demonstrative
parameter optimisation algorithm. An algorithm of this kind consists of
a target output, governed by parameters that are /hidden/ with respect
to some /estimated/ output, which itself depends on parameters that we
wish to optimise.

The algorithm in [[cref:lst:gain-dc]] is dependent on hidden parameters
\(\mathbf{x}\) and produces a ground truth output signal \(y\); we
assign this algorithm to a variable named ~target~. Its differentiable
equivalent in [[cref:lst:gain-dc-diff]] is dependent on estimated
parameters \(\mathbf{\hat{x}}\) and produces the dual output signal,
\(\langle \hat{y}, \nabla\hat{y} \rangle\); we assign this to a variable named
~estimate~. The output signals produced by ~target~ and ~estimate~ can
now be compared by way of a loss function; to this end, we can employ
time-domain L1-norm loss of the form

#+NAME: eq:l1-loss
\begin{equation}
\mathcal{L}(y,\hat{y}) = ||\hat{y} - y||\;.
\end{equation}

Our aim is to minimise the value returned by the loss function,
i.e. to reach the point at which \(y\) and \(\hat{y}\) (and by
extension \(\mathbf{x}\) and \(\mathbf{\hat{x}}\)) most closely
approximate one-another. The sensitivity of \(\mathcal{L}\) to
perturbations in \(\mathbf{\hat{x}}\) can again be found by automatic
differentiation, subject to the definition of a differentiable
absolute value function in ~df.env~. The loss function can then be
implemented as follows:

#+NAME: lst:loss-function
#+CAPTION: /Implementation of a differentiable loss function/
#+CAPTION: /(L1-norm) using differentiable ~abs~ primitive./
#+begin_src faust
env(vars) = environment {
  // ...
  lossL1(learningRate, y, yHat) = 
    error,par(i, vars.N, _)
    : diff(abs)
    : _,scaleGrads
  with {
    error = yHat,y : -;
    scaleGrads = par(i, vars.N,
      _,learningRate : *);
  };
  // ...
#+end_src

The loss function's partial derivatives are the /gradients/ associated
with each variable in \(\mathbf{\hat{x}}\). In our two-parameter
example, \(\mathcal{L}\) will describe a three-dimensional surface,
and \(\frac{\partial\mathcal{L}}{\partial x_{i}}\) its slope relative
to \(x_{i}\). Values at time \(t+1\) are found by scaling gradients by
a learning rate, \(\alpha\), and subtracting the result from values at
time \(t\):

#+NAME: eq:gradient-descent
\begin{equation}
\mathbf{\hat{x}}_{t+1} = \mathbf{\hat{x}}_t - \alpha\frac{\partial\mathcal{L}}{\partial \mathbf{\hat{x}}_t}\;.
\end{equation}
In \F{}, this can be achieved via recursion, and by changing the
definition of the variables delivered to ~df.env~. Since values will
be updated automatically via gradient descent, the sliders used in
[[cref:lst:gain-dc-diff]] are no longer appropriate; instead, a bargraph
instance can be used to display the value of each variable, with a
recursive subtraction accumulating each parameter's incoming scaled
gradient.

#+NAME: lst:diffvars
#+caption: /Definition of differentiable variables encapsulating/
#+caption: /recursive gradient descent./
#+begin_src faust :results none
// diff.lib
var(meter) = -~_ <: attach(meter);

// gain_dc_AD.dsp
X = df.vars((gain,dc)) with {
  gain = df.var(hbargraph("Gain", 0, 1));
  dc = df.var(hbargraph("DC", -1, 1));
};
#+end_src

Finally, we can create a program that takes white noise as input,
encapsulates ~target~, ~estimate~, and the loss function, and recurses
gradients produced by the latter back to ~estimate~. 

#+NAME: lst:backprop
#+CAPTION: /Excerpt from a parameter optimisation algorithm. See/
#+CAPTION: /[[cref:lst:gain-dc,lst:gain-dc-diff,lst:loss-function]]/
#+CAPTION: /respectively for definitions of ~target~,/
#+CAPTION: /~estimate~, and ~d.lossL1~./
#+begin_src faust :results none
process = no.noise <: (
    route(nvars+nInputs, nvars+nInputs,
      // Route gradients to estimate.
      par(n, nvars, (n+1, n+1+nInputs)),
      // Route input to target & estimate.
      par(n, nInputs, (nvars+1+n, n+1))
    )
    : target,estimate : d.lossL1(1e-3)
  // Recurse the gradients.
  ) ~ (!,si.bus(nvars))
  // Block the gradients, post-recursion.
  : _,si.block(nvars)
with {
  nvars = inputs(estimate),
    inputs(target) : -;
  nInputs = inputs(target),2 : *;
  // ...
#+end_src

#+begin_src faust :results file svg :file images/backprop.svg :exports results
import("stdfaust.lib");
df = library("diff.lib");

process = no.noise <: (
    route(nvars+nInputs, nvars+nInputs,
        // Route gradients to estimate.
        par(n, nvars, (n+1, n+1+nInputs)),
        // Route input to target & estimate.
        par(n, nInputs, (nvars+1+n, n+1))
    )
    : target,estimate : d.lossL1(1e-3)
    // Recurse the gradients.
    ) ~ (!,si.bus(nvars))
    // Block the gradients, post-recursion.
    : _,si.block(nvars)
with {
    nvars = inputs(estimate),inputs(target) : -;
    nInputs = inputs(target),2 : *;

    x1 = hslider("gain", .5, 0, 1, .1);
    x2 = hslider("dc", 0, -1, 1, .1);
    target = _,x1 : *,x2 : +;
			       
    X = df.vars((gain,dc)) with {
      gain = df.var(hbargraph("Gain", 0, 1));
      dc = df.var(hbargraph("DC", -1, 1));
    };

    d = df.env(X);

    estimate = d.input,X.var(1),X.var(2)
        : d.diff(*),d.diff(_)
        : d.diff(+);				  
};
#+end_src
#+name: fig:backprop
#+ATTR_LATEX: :float multicolumn :placement [ht!]
#+caption: /Top-level block diagram for the full \F{} program of which an/
#+caption: /excerpt appears in cref:lst:backprop. ~target~ algorithm, with/
#+caption: hidden /parameters, and ~estimate~ algorithm, with two/
#+caption: optimisable /parameters, process a noise signal. Their outputs/
#+caption: /are compared via a loss function; scaled derivatives of the loss/
#+caption: /function are backpropagated such that estimated parameter values/
#+caption: /can be updated./
#+caption: /Note that the only output signal produced by this example program/
#+caption: /is the primal output signal produced by the loss function;/
#+caption: /to hear the primal signal produced by ~estimate~, one could/
#+caption: /perform additional signal routing prior to the loss function./
#+RESULTS:
[[file:images/backprop.svg]]

This delivery of gradients from the outputs of the program back to its
inputs is commonly (and particularly in material from the field of
machine learning) referred to as /backpropagation/
[cite:@baydinAutomatic2018;@casebeerAutoDSP2021;@brunelBackpropagation2020].
Whereas in reverse mode gradients arrive at the inputs inevitably as a
consequence of the reverse adjoint pass through the graph, in forward
mode something like the recursion described in cref:lst:backprop is
required; consult cref:fig:backprop for the corresponding top-level
block diagram.

Running this program[fn:2] reveals a user interface which includes
slider elements for the parameters of the ~target~ algorithm, and
bargraphs that report the values of the parameters of
~estimate~. Moving a slider results in an increase in the value
returned by the loss function, which is then minimised via gradient
descent, the estimated parameter values tracking the values of the
target.

** Differentiation of Audio-specific Primitives

We have established that we can write differentiable counterparts to
some of the fundamental primitive operators in \F{}'s arithmetic. But
what about the more domain-specific operators of the language? Two
particularly interesting examples are \F{}'s delay operators and
recursive composition operation.

*** Differentiable Delay
:PROPERTIES:
:CUSTOM_ID: subsubsec:diff-delay
:END:

What is the derivative of a delayed expression? To explore this idea,
consider the continuous-time case of delaying a function \(v\) by some
fixed time \(\tau\):

#+NAME: eq:fixed-delay
\begin{align}
y &: \begin{pmatrix}x \\ t\end{pmatrix} \mapsto v(x, t-\tau)\;.
\end{align}
It is clear enough that the delay does not depend on \(x\); indeed
\(v\) is /separable/

#+NAME: eq:v-separable
\begin{align}
v(x, t-\tau) &= v(x)w(t-\tau) \\
  w(t-\tau) &= \begin{cases}1, \quad t \geq \tau\\0, \quad\text{otherwise,}\end{cases}
\end{align}
so the derivative of \(y\) with respect to \(x\) can be expressed, via
the chain rule, as

#+NAME: eq:diff-delay-1
\begin{align}
\frac{\partial{}y}{\partial{}x}
  = \frac{\partial{}y}{\partial{}v}\frac{\partial{}v}{\partial{}x}
  = w(t-\tau)\frac{\partial{}v}{\partial{}x}\;,
\end{align}
and reversing the separation yields
\(\frac{\partial{}}{\partial{}x}v(x,t-\tau)\): /the derivative of a
delay is the delayed derivative./

Further insight may be achieved via an excursion into the frequency
domain. First consider that the impulse response of the ideal delay
system is a time-shifted impulse,

#+NAME: eq:ideal-delay-ir
\begin{equation}
h(t) = \delta(t - \tau)\;,
\end{equation}
and that cref:eq:fixed-delay can be represented as a convolution with
that impulse response,

#+NAME: eq:conv
\begin{equation}
v(x, t - \tau) = v(x,t) \ast h(t)\;.
\end{equation}
Next, we can use the convolution and differentiation properties of the
Fourier transform [cite:@mcclellanSignal2003], which, when combined,
tell us that to differentiate a convolution it is only necessary to
differentiate /one/ of the functions being convolved:

#+NAME: eq:fourier-properties
\begin{align}
v_{1}(x) \ast v_{2}(x) \quad&\xleftrightarrow{\mathcal{F}}\quad V_{1}(j\omega)V_{2}(j\omega) \\
\frac{d}{dx}v(x) \quad&\xleftrightarrow{\mathcal{F}}\quad j\omega{}V(j\omega) \\
\frac{d}{dx}\left(v_{1}(x) \ast v_{2}(x)\right)
  \quad&\xleftrightarrow{\mathcal{F}}\quad
  j\omega{}V_{1}(j\omega)V_{2}(j\omega)\;.
\end{align}
This rule holds in the two-dimensional case; for example, if we
rewrite \(h\) as \(h(x,t)\), a function that, for all \(x\), returns
\(h(t)\), then

#+NAME: eq:differentiation-is-time-invariant
\begin{align}
\mathcal{F}\left[\frac{\partial{}}{\partial{}x}\left(v(x,t) \ast h(x,t)\right)\right]
  &= j\omega_{x}V(j\omega_{x},j\omega_{t})H(j\omega_{x},\omega_{t}) \nonumber \\
  &= \mathcal{F}\left[\frac{\partial{}}{\partial{}x}v(x,t)\right]\cdot\mathcal{F}\left[h(x,t)\right] \nonumber \\
\therefore \frac{\partial{}}{\partial{}x}\left(v(x,t) \ast h(x,t)\right) &= \left(\frac{\partial{}}{\partial{}x}v(x,t)\right) \ast h(x,t) \nonumber \\
  &= \frac{\partial{}}{\partial{}x}v(x,t-\tau)\;,
\end{align}
which proves that the ideal differentiator is a time-invariant system.

The above also holds in discrete time, for which we can use the
fundamental definition of the derivative to find the equivalent
result. For delay by some fixed time \(k\),

#+NAME: eq:discrete-time-delay
\begin{align}
\frac{d}{dx}v(x)[n-k] &= \lim_{h\to0}\frac{v(x+h)[n-k] - v(x)[n-k]}{h} \nonumber \\
  &= \left(\lim_{h\to0}\frac{v(x+h) - v(x)}{h}\right)[n-k] \nonumber \\
  &= v'(x)[n-k]\;,
\end{align}
which can be represented with dual numbers as

#+NAME: eq:diff-delay-dual
\begin{equation}
\langle v,\nabla{}v \rangle[n - k] = \langle v[n - k], \nabla{}v[n - k] \rangle\;,
\end{equation}
and in \F{}:

#+begin_src faust :results none
diff(v') = diff(v) : diff(mem);
diff(mem) = mem,par(i, vars.N, mem);
#+end_src

*** Variable Delay

A thornier matter is the case where the length of the delay is itself
a differentiable parameter, e.g., returning to continuous time,

#+NAME: eq:variable-delay
\begin{align}
y &: \begin{pmatrix}x\\u\end{pmatrix} \mapsto v_{1}(x,u) \\
u &: \begin{pmatrix}v_{2}\\t\end{pmatrix} \mapsto t - v_{2} \\
v_{2} &: \begin{pmatrix}x\\t\end{pmatrix} \mapsto v_{2}(x,t)\;.
\end{align}
Having introduced the intermediate function, \(u\), the derivative,
via the chain rule, of \(y\) with respect to \(x\) is

#+NAME: eq:variable-delay-deriv
\begin{equation}
\frac{\partial{}y}{\partial{}x} = \frac{\partial{}y}{\partial{}v_{1}}\frac{\partial{}v_{1}}{\partial{}x} +
  \frac{\partial{}y}{\partial{}u}\frac{\partial{}u}{\partial{}v_{2}}\frac{\partial{}v_{2}}{\partial{}x}\;.
\end{equation}
If we imagine that, for all \(x,t\), \(v_{2}\) returns a constant
value \(\tau\), the second additive term evaluates to zero, and
cref:eq:variable-delay-deriv reduces to the fixed delay case described
by cref:eq:differentiation-is-time-invariant. More
generally, we can observe that the first additive term represents the
derivative of \(v_{1}\), delayed by the primal of
\(v_{2}\). Continuing to evaluate, we find

#+NAME: eq:variable-delay-deriv-eval
\begin{align}
\frac{\partial{}y}{\partial{}x} &= \frac{\partial{}}{\partial{}x}v_{1}(x,u) +
  \frac{\partial{}}{\partial{}u}v_{1}(x,u)\cdot(-1)\cdot\frac{\partial{}}{\partial{}x}v_{2}(x,t) \nonumber \\
  &= \frac{\partial{}}{\partial{}x}v_{1}(x,u) - \frac{\partial{}}{\partial{}u}v_{1}(x,u)\frac{\partial{}}{\partial{}x}v_{2}(x,t)\;.
\end{align}

While \(v_{1}\) and \(v_{2}\) may be trivially differentiable with
respect to \(x\), calculating \(\frac{\partial{}v_{1}}{\partial{}u}\)
--- essentially a derivative with respect to time --- appears to defy
a closed form solution. Nevertheless, in the case of \F{}'s ~@~
primitive, a discrete-time expression that will handle both fixed and
variable delays is required. At the time of writing, a compromise, in
the form of a numerical approximation, forms the basis for
implementation of the differentiable delay primitive; as a dual
signal:

#+NAME: eq:variable-delay-deriv-dual
\begin{equation}
    \begin{split}
        \langle v_{1}&,\nabla{}v_{1 }\rangle[n - \langle v_{2},\nabla{}v_{2} \rangle] = \bigl\langle v_{1}[n-v_{2}], \\
      &\nabla{}v_{1}[n-v_{2}] - \nabla{}v_{2}(v_{1}[n-v_{2}]-v_{1}[n-v_{2}-1]) \bigr\rangle\;.
    \end{split}
\end{equation}
This approach is able to support parameter optimisation for increasing
delays, but, for reasons of causality, for decreasing ones it is of
limited use.

*** Variable Delay as a Differentiable Filterbank

Perhaps a better tactic, in parameter optimisation scenarios involving
variable-length delay lines, is to model the delay as a differentiable
FIR filterbank. The general discrete-time FIR filter, with
coefficients \(x_{i}\) and input signal \(s\), is defined by the
following difference equation [cite:@mcclellanSignal2003]:

#+NAME: eq:general-fir-1
\begin{equation}
y[n] = \sum_{k=0}^{M-1}x_{k}s[n-k]\;.
\end{equation}
We can express \(y\) as a function of a vector of independent
variables \(\mathbf{v}\),

#+NAME: eq:general-fir-2
\begin{equation}
y : \mathbf{v} \mapsto f(\mathbf{v}) = \sum_{k=1}^{M}v_{2k-1}v_{2k}\;,
\end{equation}
where \(v_{j}\) is a function of a vector of filter coefficients
\(\mathbf{x}\),

#+NAME: eq:vees
\begin{align*}
v_{2k-1} &: \mathbf{x} \mapsto x_{k} \\
v_{2k} &: \mathbf{x} \mapsto s[n - (k - 1)]\;.
\end{align*}
Differentiating \(y\) with respect to filter coefficient \(x_{i}\) yields

#+NAME: eq:diff-fir
\begin{align}
\frac{\partial{}y}{\partial{}x_{i}} &= \sum_{j=1}^{2M}\frac{\partial{}y}{\partial{}v_{j}}\frac{\partial{}v_{j}}{\partial{}x_{i}} \nonumber \\
  &= \sum_{j=1}^{M}\left(\frac{\partial{}y}{\partial{}v_{2j-1}}\frac{\partial{}v_{2j-1}}{\partial{}x_{i}} + \frac{\partial{}y}{\partial{}v_{2j}}\frac{\partial{}v_{2j}}{\partial{}x_{i}} \right) \nonumber \\
  &= \sum_{j=1}^{M}\left(v_{2j}\frac{\partial{}v_{2j-1}}{\partial{}x_{i}} \right) \nonumber \\
  &= v_{2i} \nonumber \\
  &= s[n - (i - 1)]\;.
\end{align}
Thus, differentiating the general FIR filter with respect to \(x_{i}\)
has the effect of isolating the \((i-1)\)^{th} tap; optimising against a
hidden delay will result in the definition of an impulse response with
a single peak associated with the filter tap whose delay line is
closest in length to that of the hidden delay.

*** Differentiable Recursion

So far it has not been necessary to define derivative expressions
for any of \F{}'s /composition operations/; this is because the
parallel and sequential types of composition we have encountered to
this point have no arithmetical impact on the signals they act upon,
and thus no effect on derivative computation in forward mode. Of
\F{}'s five composition operators, only merge composition, ~:>~, has
such an effect, that of summation; consequently, accompanied by a
basic definition of differentiable parallel composition,
differentiable merge composition could be defined as

#+name: lst:diff-merge
#+caption: /Possible implementation of differentiable parallel and merge/
#+caption: /composition operators./
#+begin_src faust :results none
diff((A,B)) = diff(A),diff(B);
diff(A :> B) = diff(A) : diff(+) : diff(B);
#+end_src
assuming that ~A~ consists of exactly two parallel signals.[fn:3]

Cref:fig:block-diag-forward-mode demonstrates visually that split,
parallel, and sequential composition do not alter the signals they act
upon, and are thus analogous to application of the identity function,
whose partial derivatives are in turn identity functions, i.e.:

#+begin_src faust :results none
diff(_) = par(i, vars.N+1, _);
#+end_src
For the case of recursive composition, this is perhaps not as clear;
fortunately we can prove it to be so via the chain rule.

A simple (and undifferentiated) \F{} program that produces a ramp of
varying slope can be defined like so:

#+begin_src faust :results none
process = hslider("x", 0, -1, 1, .01)
    : +~_;
#+end_src
This can be notated, in discrete time,

#+NAME: eq:ramp-1
\begin{equation}
y[n] = x[n] + y[n-1]\;.
\end{equation}
As usual, we can express \(y\) as a function of independent
variables, \(v_{j}\), which are in turn functions of \(x\):

#+NAME: eq:ramp-2
\begin{align}
y &: \begin{pmatrix}v_{1}\\v_{2}\end{pmatrix} \mapsto v_{1} + v_{2} \\
v_{1} &: \begin{pmatrix}x\\n\end{pmatrix} \mapsto x[n] \\
v_{2} &: \begin{pmatrix}x\\n\end{pmatrix} \mapsto y[n-1]\;,
\end{align}
and find its derivative with respect to \(x\),

#+NAME: eq:ramp-diff
\begin{align}
\frac{\partial{}y}{\partial{}x}
  &= \frac{\partial{}y}{\partial{}v_{1}}\frac{\partial{}v_{1}}{\partial{}x} +
    \frac{\partial{}y}{\partial{}v_{2}}\frac{\partial{}v_{2}}{\partial{}x} \nonumber \\
  &= 1\cdot{}1 + 1\cdot\frac{\partial{}y}{\partial{}x}[n-1] \nonumber \\
  &= 1 + \frac{\partial{}y}{\partial{}x}[n-1]\;.
\end{align}
Thus the derivative of a recursive circuit is itself recursive. If the
presence of the recurrence relation in the result seems at all
surprising, note that \(\frac{\partial{}y}{\partial{}x}\) can be
thought of as \(\frac{\partial{}y}{\partial{}x}[n]\), /the partial
derivative of \(y\) with respect to \(x\) at time \(n\)./[fn:4]

With this insight in hand, we can differentiate an all-pole filter
with the following difference equation:

#+NAME: eq:all-pole-autodiff
\begin{equation}
y[n] = s[n] + \sum_{l=1}^{N}x_{l}y[n - l]\;.
\end{equation}
Once again, defining \(y\) as a function of a vector of
independent variables \(\mathbf{v}\),

#+NAME: eq:all-pole-2
\begin{equation}
y : \mathbf{v} \mapsto f(\mathbf{v}) = s[n] + \sum_{l=1}^{N}v_{2l-1}v_{2l}\;,
\end{equation}
where \(v_{j}\) is a function of a vector of filter coefficients
\(\mathbf{x}\),

#+NAME: eq:vees
\begin{align*}
v_{2l-1} &: \mathbf{x} \mapsto x_{l} \\
v_{2l} &: \mathbf{x} \mapsto y[n - l]\;,
\end{align*}
the derivative of \(y\) with respect to the \(i\)^{th} filter
coefficient is found in a manner comparable to that of
cref:eq:diff-fir:

#+NAME: eq:diff-one-pole
\begin{align}
\frac{\partial{}y}{\partial{}x_{i}} &= \frac{\partial{}}{\partial{}x_{i}}s[n] + \sum_{j=1}^{2N}\frac{\partial{}y}{\partial{}v_{j}}\frac{\partial{}v_{j}}{\partial{}x_{i}} \nonumber \\
  &= 0 + \sum_{j=1}^{N}\left(\frac{\partial{}y}{\partial{}v_{2j-1}}\frac{\partial{}v_{2j-1}}{\partial{}x_{i}} + \frac{\partial{}y}{\partial{}v_{2j}}\frac{\partial{}v_{2j}}{\partial{}x_{i}}\right) \nonumber \\
  &= \sum_{j=1}^{N}\left(v_{2j}\frac{\partial{}v_{2j-1}}{\partial{}x_{i}} + v_{2j-1}\frac{\partial{}v_{2j}}{\partial{}x_{i}}\right) \nonumber \\
  &= v_{2i} + \sum_{j=1}^{N}x_{j}\frac{\partial{}}{\partial{}x_{i}}y[n-j] \nonumber \\
  &= y[n - i] + \sum_{j=1}^{N}x_{j}\frac{\partial{}}{\partial{}x_{i}}y[n-j]\;.
\end{align}
Similar to the FIR filter, differentiating with respect to \(x_{i}\)
extracts the \(i\)^{th} tap; in this case, due to the all-pole filter's
recursive description, differentiating it produces, in addition,
weighted recursive derivatives numbering the length of the entire
filter (see [cite:@shynkAdaptive1989] for a more exhaustive treatment
of this topic).

* Discussion
:PROPERTIES:
:CUSTOM_ID: sec:discussion
:END:

The previous section presented an approach to differentiable
programming in \F{}, but the scheme under consideration is not free
from disadvantages. Considered in the following subsections are some
limitations of the suggested automatic differentiation strategy, plus
a selection of ideas for future development.

** Primitives With Poorly-Defined Derivatives

As observed in cref:subsubsec:diff-delay, the derivative of delay, in
the general case where the length of the delay line may itself be a
differentiable parameter, appears to defy an analytic
solution. Moreover, the suggestion of modelling a differentiable delay
as a filterbank raises questions around efficiency and feasibility; if
every instance of ~@~ has to be replaced by a cascade of delays with
differentiable coefficients, then all of those coefficients would have
to be updated at every sample; moreover, the order of the filterbank
would have to be arbitrary; and finally, such an approach might
approximate the instantaneous impulse response of the filter being
applied (albeit subject to the learning rate), but not, for example,
the frequency of an LFO governing the length of the hidden delay, such
as exhibited by audio effects such as the flanger and tremolo. It
could simply be that signal processes of this type are not suitable
candidates for parameter optimisation, but such an idea demands
further investigation.

Other primitives with problematic derivatives are those whose primal
outputs are discontinuous; the ~floor~ and ~ceil~ primitives and the
various bitwise operators, for example; the implementation of a
comprehensive automatic differentiation framework would demand the
provision of suitable definitions for these primitives.

** Frequency-Domain Loss
:PROPERTIES:
:CUSTOM_ID: subsec:freq-loss
:END:

The parameter optimisation example given in cref:subsec:param-opt
works, but with a couple of significant caveats, the first of these
being that the ~target~ and ~estimate~ algorithms receive identical
signals as input, and the second being that loss is calculated
sample-by-sample in the time domain. If decorrelated noise signals
were used instead, it is vanishingly unlikely that good parameter
estimates would be found. Some improvement may be achieved by
comparing \(y\) and \(\hat{y}\) after a short-duration application of
~ba.slidingMean~, but not if oscillators of different frequencies, or
unaligned phase, were employed instead.

One way to combat problems of this sort would be to calculate loss in
the frequency domain; indeed it is typically by way of
perceptually-informed /spectral loss/ that optimisation is conducted
in a DDSP setting [cite:@hayesReview2023]. Various functions exist in
\F{}'s =analyzers.lib= library that could be used to this end; being
based on an FFT implementation that is restricted, however, to a
single sample hop-size, at the time of writing computational expense
places limits on the calculation of magnitude spectrograms,
particularly in a real-time setting.

** Computational Efficiency
:PROPERTIES:
:CUSTOM_ID: subsec:efficiency
:END:

On that note, and as alluded to in ref:subsubsec:forward-mode, forward
mode is not, on paper at least, the most efficient choice for
automatically differentiating programs with more inputs than
outputs. Cref:fig:gain-dc shows two sets of tangent calculations
accompanying each primitive's primal operation, and a number of zero
signal paths (partial derivatives of the input signal, for
example). Not pictured in cref:fig:gain-dc, the most egregious
proliferation of zeros is caused by differentiable numerical
constants; a constant \(c\), is, in dual-signal form, \(\langle c, \nabla{}c \rangle = \langle
c, \mathbf{0} \rangle\), or in \F{}:

#+begin_src faust :results none
diff(c) = c,par(i, vars.N, 0);
#+end_src
Of course, a constant may well be followed, for instance, by a
trigonometric function --- there is no guarantee that \(\nabla{}c\) will not
contribute to a non-zero signal path, thus no scope for optimisation.

That being said, the \F{} /compiler/ is designed with this sort of
optimisation in mind, applying various rewriting rules after its
symbolic propagation phase to simplify expressions and avoid
redundancy [cite:@orlareyFAUST2009]. In effect, the compiler will
attempt to produce the most efficient possible /\F{} Imperative
Representation/ for any given \F{} program. Nevertheless, the
creation of a generalisable approach to reverse mode should be
explored, and this too would benefit from compile-time
optimisations. Moreover, forward and reverse mode can be thought of as
extremes on a continuum of derivative propagation options; a
combination of these modes (dubbed /cross-country mode/), tailored to
the structure of the program being differentiated, would be ideal,
though finding the optimal ordering is deemed a challenge
[cite:@laueSimple2020].

** A General Pattern-Matching Syntax

Although the differentiable algorithm in cref:lst:gain-dc-diff bears
the same compositional structure as its undifferentiated sibling
(cref:fig:gain-dc), the use of the differentiable environment, coupled
with pattern matching, inevitably leads to the necessity of wrapping
primitives in ~d.diff(...)~ notation. ~d.input~ too is an
unsatisfactory solution to the problem of there being no simple way,
syntactically speaking, of distinguishing an input signal from an
identity function, which, since they have different derivatives, is a
necessity.

Ideally, an approach similar to that taken in
=physmodels.lib= (as described in cref:subsec:extend-arithmetic),
or cref:lst:diff-merge, whereby expressions are recursively
/decomposed/, with a base case to handle the desired transformations,
should be employed. In that instance, it would be possible to define
~estimate~ in cref:lst:backprop via syntax along the lines of:

#+begin_src faust
estimate = forwardAD(target);
#+end_src
In addition to abstracting away calls to ~diff()~, this could permit
identifying input signals by counting the number of inputs to the
circuit passed to ~forwardAD~. Standing in the way of this idea,
however, are limitations in \F{}'s pattern matching system at the time
of writing, the principal issue being the impossibility of
pattern-matching user interface elements in the general case; i.e., to
match a ~hslider~ one needs to match its label exactly, plus the
values provided for ~init~, ~min~, ~max~ and ~step~. By way of an
alternative, a strategy based on \F{}'s /widget modulation/ syntax may
help circumvent this problem.

** Application to Machine Learning

Further to the caveats mentioned in ref:subsec:freq-loss, the success
of the parameter optimisation example presented in this paper is
contingent on the provision of deterministic input data; essentially
the example constitutes an extreme example of /overfitting/, solving
one specific problem, on one particular set of input data, very well,
but possessing no capability to generalise. Nevertheless, it shares
its basis, in the form of differentiable programming, with more
sophisticated mathematical optimisation approaches, chief amongst
these being machine learning.

Using differentiable \F{} primitives it is straightforward to create
differentiable loss functions; activation functions and artificial
neurons (the latter being based on simple linear algebra principles)
could follow without much trouble. Neural network structures, which
support the training of models capable of generalising to unseen input
data, would require significant effort to implement in a composable,
extensible fashion, but it is unlikely that they lie beyond the
capabilities of the language.

* Conclusion

In this paper, it has been shown that differentiable programming is
well within the capabilities of the \F{} language, and thus that \F{}
can be used to tackle audio problems based on principles of
mathematical optimisation. It has also been demonstrated that the
derivatives of certain audio specific primitive operations are
well-defined, though delay lines of variable length require a
sensitive approach.

The presence of a comprehensive automatic differentiation framework in
\F{} would lend the language to a multitude of DDSP problems and
applications that currently lie unexplored by \F{} programmers; in
turn, the ability to tackle such problems in a domain specific
language could foster innovation in what is a vibrant research area.

Aims for further investigation should be the implementation of
differentiation rules for all of the primitives of the language, the
development of a less intrusive syntax for automatic differentiation
transformations, and perhaps enhancements to pattern matching at the
level of the \F{} compiler. An FFT implementation of greater
efficiency, or a novel approach to perceptually-informed loss
computation, would also be of great benefit.

#+begin_export latex
%%\nocite{*}
#+end_export
#+PRINT_BIBLIOGRAPHY:

* Footnotes
[fn:4] One could imagine writing, e.g.,
\(\frac{\partial{}y}{\partial{}v_{1}}[n] = (1 + 0)[n] = 1[n]\), but,
with the aim of maintaining a familiar-looking notation, time indices
have been omitted from non-delayed terms in cref:eq:ramp-diff.

[fn:3] Alternatively, for the case where ~A~ consists of an arbitrary
number of parallel signals, it could simply be the responsibility of
the programmer to make appropriate use of the differentiable addition
primitive instead of merge composition.

[fn:2] A full code example, adapted from the excerpts in this paper,
can be found at
[[https://gist.github.com/hatchjaw/59f35d0cde7aba218d785d31f26d2d83]].

[fn:1] Transformations /are/ in fact possible at the level of the \F{}
compiler, and automatic differentiation /could/ occur as a compilation
step. For reasons of scope, this paper focuses solely on the topic of
automatic differentiation in the \F{} language itself.

* Emacs Setup                                                      :noexport:

- Set up =ifc24= document class.
- Add =-shell-escape= flag to latex process, so =svg= works.
- Use =listings= package for exported source blocks.

# Local Variables:
# eval:   (add-to-list 'org-latex-classes '("ifc24"
# "\\documentclass[twoside,a4paper]{article}
# [NO-DEFAULT-PACKAGES]"
# ("\\section{%s}" . "\\section*{%s}")
# ("\\subsection{%s}" . "\\subsection*{%s}")
# ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
# ("\\paragraph{%s}" . "\\paragraph*{%s}")
# ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# eval:   (setq org-latex-pdf-process '("latexmk -f -pdf -%latex \
# -interaction=nonstopmode -shell-escape -output-directory=%o %f"))
# eval:   (setq org-latex-src-block-backend 'listings)
# End:
