# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Differentiable DSP in Faust
# #+AUTHOR: Thomas Rushton

#+EXPORT_FILE_NAME: out/ifc24
#+OPTIONS: toc:nil ':t ^:{} num:3
#+LATEX_CLASS: ifc24
#+BIBLIOGRAPHY: IFC-24.bib
#+CITE_EXPORT: bibtex
#+LATEX_HEADER: \RequirePackage[]{ifc24-style}

#+begin_abstract
Differentiable programming is\dots

Using the ~environment~ expression and pattern matching abstraction,
it is possible to write \F{} code that is differentiable end-to-end,
facilitating the computation and propagation of gradients, and in turn
supporting the creation of parameter optimisation
algorithms. Differentiable programming in \F{} could serve as a
platform for a \F{}-native approach to machine learning problems.
#+end_abstract

* Latex Setup                                                      :noexport:
:PROPERTIES:
:HEADER-ARGS: :tangle out/ifc24-style.sty :results silent
:END:

Remember to tangle =C-c C-v t= before exporting.

** Basics

#+begin_src latex
\ProvidesPackage{ifc24-style}[2024/07/12 v0.1 Bundling IFC24 LaTeX style]
#+end_src

** Author(s)

Title is taken from the title attribute.

#+begin_src latex
%% \def\papertitle{Differentiable DSP in Faust}
\def\paperauthorA{Thomas Albert Rushton}
#+end_src

Authors' affiliations have to be set below.

** Packages
#+begin_src latex
\usepackage{IFC-24}
\usepackage{amsmath,amssymb,amsfonts,amsthm}
\usepackage{euscript}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{ifpdf}

\usepackage{color}
\usepackage{listings}
\definecolor{mygrey}{rgb}{0.96,0.96,0.96}
\lstset{
  tabsize=4,
  basicstyle=\ttfamily,
  backgroundcolor=\color{mygrey},
  captionpos=b,
  breaklines=true
}

\usepackage[english]{babel}
\usepackage{caption}
\usepackage{subfig, color}

\setcounter{page}{1}
\ninept

\usepackage{times}
\usepackage{inconsolata}

\usepackage{microtype}
\usepackage[inkscapelatex=false]{svg}
#+end_src

** LaTeX vs PDFLaTeX

#+begin_src latex
% pdf-tex settings: detect automatically if run by latex or pdflatex
\newif\ifpdf
\ifx\pdfoutput\relax
\else
   \ifcase\pdfoutput
      \pdffalse
   \else
      \pdftrue
\fi

\ifpdf % compiling with pdflatex
  \usepackage[pdftex,
    pdftitle={\papertitle},
    pdfauthor={\paperauthorA, \paperauthorB, \paperauthorC, \paperauthorD},
    colorlinks=false, % links are activated as colror boxes instead of color text
    bookmarksnumbered, % use section numbers with bookmarks
    pdfstartview=XYZ % start with zoom=100% instead of full screen; especially useful if working with a big screen :-)
  ]{hyperref}
  \pdfcompresslevel=9
  \usepackage[pdftex]{graphicx}
  \usepackage[figure,table]{hypcap}
\else % compiling with latex
  \usepackage[dvips]{epsfig,graphicx}
  \usepackage[dvips,
    colorlinks=false, % no color links
    bookmarksnumbered, % use section numbers with bookmarks
    pdfstartview=XYZ % start with zoom=100% instead of full screen
  ]{hyperref}
  % hyperrefs are active in the pdf file after conversion
  \usepackage[figure,table]{hypcap}
\fi
#+end_src

** Macros
#+begin_src latex
% Special Macros
\newcommand{\F}{\textsc{Faust}}
#+end_src

** Author affiliations

Single author affiliation:

#+begin_src latex
\affiliation{\paperauthorA}
{\href{https://inria.fr}{Inria} \\ Villeurbanne, France\\
{\tt \href{mailto:thomas.rushton@inria.fr}{thomas.rushton@inria.fr}}
}
#+end_src

** Bibliography

#+begin_src latex
\bibliographystyle{IEEEbib}
#+end_src

* Adding Image Attributes                                          :noexport:

You've generated some image output from a source block; now you want
to add attributes like ~#+CAPTION:~, etc. There are a few approaches,
none of which is perfectly lovely. To suggest a couple:

- Generate an image result, then add attributes between the source
  block or ~CALL~ statement and the results.
#+begin_example
#+begin_src
...
#+end_src
#+CAPTION: A delightful caption
#+ATTR_LATEX: :width .5\linewidth
#+RESULTS:...
#+end_example

- Use [[https://orgmode.org/manual/Evaluating-Code-Blocks.html#How-to-evaluate-source-code-1][inline call]] syntax
#+begin_example
#+NAME: faust_code
#+begin_src faust
...
#+end_src

#+ATTR_LATEX: :width .75\linewidth
call_faust_code()[:results svg file :file image.svg :output-dir images
:exports results]
#+end_example

The latter doesn't provide a preview, but less manual intervention is
necessary.

One more thing: for regular source blocks, ~:output-dir~ and ~:file~
are combined into ~:file~ to produce =<outputdir>/<file>=. For
~#+CALL:~ this isn't the case; best to just use ~:file
<outputdir>/<file>~.

* More potentially useful syntax                                   :noexport:

This is a link to section [[*Conclusion]]

This template can be found on the conference website.

Here's a ref: [cite:@rall_arithmetic_1986]

Here's some code:

#+begin_src faust
  process = _;
#+end_src

And some inline code ~process = !;~

And floating code?

#+CAPTION: this code should float, because it has a caption
#+begin_src faust
process = 1;
#+end_src

* Introduction

Differentiable programming is a programming paradigm whereby a
computer program can be differentiated end-to-end
[cite:@blondel_elements_2024]. The sensitivity of a differentiable
program's outputs to perturbations of its inputs can be computed via
automatic differentiation
(autodiff) [cite:@rall_arithmetic_1986;@baydin_automatic_2018],
producing a partial derivative with respect to each input
parameter. End-to-end differentiability is a desirable quality in the
creation of computer programs that perform gradient-based
optimization.

This paper introduces a /differentiation arithmetic/ to \F{},
facilitating the creation of differentiable algorithms 

There is a sense in which the block-diagram algebra of \F{} lends the
language intuitively to the problem of automatic differentiation. As
we will see, the language itself presents certain limitations in this
respect, but nonetheless we can achieve a great deal\dots

* Algorithmic Differentiation

What does it entail to write differentiable code? As stated, the aim
of differentiable programming is to compute the sensitivity of a
program's outputs to purturbations to its inputs.
Computational approaches to differentiation are typically
characterised as falling into one of three camps: /numerical/,
/symbolic/, and /automatic/. Numerical differentiation produces
numerical values for derivatives via approximation by finite
differences, and will be familiar to those acquainted with
finite-difference time-domain audio synthesis methods
[cite:@bilbao_numerical_2009]. Symbolic differentiation takes a
computational expression and generates the corresponding expression
for its derivative; this approach may resonate with users of MATLAB's
Symbolic Math Toolbox [cite:@moler_symbolic_1997] or the Maple
programming language[cite:@monagan_gradient_1993]. Automatic
differentiation describes an arithmetic for accumulating both the
numerical output of a computational expression and the numerical value
of its derivative; it is an arithmetic of this kind that underpins the
current crop of Python libraries for machine learning
[cite:@harrison_brief_2021].

A certain ambiguity abounds with regard to how automatic and symbolic
differentiation relate to each other[cite:@laue_equivalence_2022], and
partisan opinions have been expressed over which is more
efficient[cite:@guenter_efcient_2007]. The ambiguity may be ascribed
in part to the former's nature as "partly symbolic and partly
numerical" [cite:@harrison_brief_2021], and perhaps also to the fact
that programs composed symbolically may be differentiated
automatically [cite:@villard_adrien_1999]. Dismissal of symbolic
differentiation over the purported problem of "expression swell"
[cite:@harrison_brief_2021; @baydin_automatic_2018] may be driven by
implementation-specific assumptions and historical lack of available
computational power. For our purposes, we shall defer to Rall, who,
writing in the mid-1980's, before the waters were muddied by legions
of machine learning researchers, observed (to paraphrase): /symbolic
approaches produce formulas whereas automatic approaches produce
numerical outputs/ [cite:@rall_arithmetic_1986]. The latter do so,
however, by implementing differentiation rules, symbolically or
manually, at the level, as we will see, of the primitive operations of
the programming language upon which they are based.

** Modes of Automatic Differentiation

Forward/reverse/cross-country
Forward mode computes both the value of the function and its partial
derivatives in a forward pass; this entails 
Reverse mode computes the primal value of the function under
consideration in a forward pass,

#+begin_src faust :results file svg :file images/block.svg :exports both
N = 5;
S(j) = sum(i,N,((i+j) : sqrt)/N);
process = (v0 <: _,_),v1 : v2,v3 : v4
with {
    v0 = S(0);
    v1 = S(1);
    v2 = _,S(2) : +;
    v3 = +,S(3) : +;
    v4 = +,S(4) : +;
};
#+end_src

#+RESULTS:
[[file:images/block.svg]]

** The Arithmetic of Differentiation

The arithmetic of forward mode autodiff can be derived by formulating
differentiation in a manner similar to the complex numbers
[cite:@rall_arithmetic_1986; @yu_dnad_2013]. Where complex arithmetic
uses the imaginary unit \(i\) to designate the imaginary part of a
complex number \(z = x + iy\), with \(i^{2} = -1\), differentiable
arithmetic uses the /nilpotent
symbol/[cite:@yu_dnad_2013;@baydin_automatic_2018] \(\varepsilon\):

#+NAME: eq:nilpotent
\begin{equation}
U = u + \varepsilon{}u',
\end{equation}
where \(u' = \frac{du}{dx}\) is the derivative of \(u\) with respect
to some variable \(x\)  and \(\varepsilon^{2}\) = 0.

Using this arithmetic, the addition rule of differentiation emerges
quite naturally as the sum of \(U\) and \(V = v + \varepsilon{}v'\):

#+NAME: eq:addition-rule
\begin{equation}
(u + \varepsilon{}u') + (v + \varepsilon{}v') = u + v + \varepsilon(u' + v').
\end{equation}
Similarly, the product rule, via a simple polynomial expansion:

#+NAME: eq:product-rule
\begin{align}
(u + \varepsilon{}u')(v + \varepsilon{}v') &= uv + u\varepsilon{}v' + v\varepsilon{}u' + \varepsilon^{2}u'v' \nonumber \\
                   &= uv + \varepsilon(uv' + vu'),
\end{align}
the final term cancelling due to the presence of \(\varepsilon^{2}\).

This arithmetic may be more conviently expressed, for computational
purposes, as one of /ordered
pairs/[cite:@rall_arithmetic_1986;@kalman_doubly_2002] or /dual
numbers/
[cite:@yu_dnad_2013;@sigal_automatic_2021;@revels_forward-mode_2016]:

#+NAME: eq:dual
\begin{equation}
U = \langle u, u' \rangle.
\end{equation}
The addition and product rules now take the following forms:

#+NAME: eq:addition-rule
\begin{equation}
U+V = \langle u, u' \rangle + \langle v, v' \rangle = \langle u + v, u' + v' \rangle,
\end{equation}
#+NAME: eq:product-rule
\begin{equation}
UV = \langle u, u' \rangle\langle v, v' \rangle = \langle uv, uv' + vu' \rangle.
\end{equation}
The first component of each dual number is the rule for evaluation of
the operation; the second is the rule for differentiation
[cite:@rall_arithmetic_1986]. These components may be referred to as
the /primal/ and /tangent/ respectively
[cite:@baydin_automatic_2018;@radul_you_2023]. In dual number
differentiation arithmetic, an independent variable can be expressed
as \(X = \langle x,\frac{dx}{dx} \rangle\), and a constant \(C = \langle c,\frac{dc}{dx}
\rangle\). If we wish, for example, to compute the primal and tangent of a
polynomial \((x + 1)(x - 2)\) at \(x = 2\), we set \(X = \langle 2,1 \rangle\) and
supply appropriate values for the constants:

#+NAME: eq:product-example
\begin{equation}
(\langle 2,1 \rangle + \langle 1,0 \rangle)(\langle 2,1 \rangle - \langle 2,0 \rangle) = \langle 3,1 \rangle\langle 0,1 \rangle = \langle 0,3 \rangle. \nonumber
\end{equation}
We find that our arithmetic produces the expected numerical results
/automatically/ via composition of the fundamental operations
described in equations ([[eq:addition-rule]]) and ([[eq:product-rule]]).

** Extending \F{}'s Arithmetic

One quality generally possessed by automatic differentiation
implementations is that of allowing the programmer to write
differentiable programs with minimal changes to the syntax of their
code. This is typically achieved either by source code transformation
or operator overloading [cite:@yu_dnad_2013; @baydin_automatic_2018]
--- neither of which is available in the \F language.[fn:1] We could
take an approach similar to Wengert's 1964 demonstration of the
composition of differentiable functions in Fortran
[cite:@wengert_simple_1964] and define differentiable functions
~diffAdd~, ~diffMul~, etc. each accepting and returning dual numbers;
thanks to \F's pattern matching abstraction, however, we can go one
better, achieving something akin to, albeit slightly more verbose
than, operator overloading.

Pattern matching has been used extensively in the Faust libraries. The
=basics.lib= library, for example, provides a function with a
recursive pattern matching definition for taking an element from a
list:

#+begin_src faust :results none
// Take the first element, the head;
take(1, (head, rest)) = head;
// Take the only element;
take(1, head)         = head;
// Take the n-1th element from the rest.
take(n, (head, rest)) = take(n-1, rest);
#+end_src

The =physmodels.lib= library provides ~pm.chain~ for creating chains
of bidirectional signal blocks [cite:@michon_faust_2018]. ~chain(A)~
simply returns the signal block ~A~; ~chain(A:As)~ creates a recursive
structure containing ~A~ and ~chain(As)~. Similarly, =wdmodels.lib=
facilitates the creation of wave digital filter models via primitive
elements, resistors, capacitors, etc. [cite:@roosenburg_wave_2021],
whose behaviour is described with pattern matching syntax. Both
libraries extend \F{}'s arithmetic with their own rules, with the aim
of achievening a particular goal within the syntax provided by \F{}.

If one's particular goal was to be able to compose reciprocal
expressions, one could create an arithmetic of the following form,
using pattern matichng to avoid division by zero:

#+begin_src faust :results file svg :file images/arithmetic.svg :exports both
import("stdfaust.lib");
recip(0) = recip(ma.EPSILON);
recip(0.0) = recip(0);
recip(op) = 1,op : /;
process = recip(log(1)),recip((_,2 : ^))
  : recip(-);
#+end_src
#+ATTR_LATEX: :width 1\linewidth
#+RESULTS:
[[file:images/arithmetic.svg]]
Wrapping our expressions in ~recip~ gives us automatic reciprocals
without affecting the fundamental composability of \F{}'s
primitives. Note that if we were to insert the expression ~recip(-) =
+;~ at the top of the program, the final operation, rather than
returning \(1/(x_{1} - x_{2})\) would be /overridden/, in a manner of
speaking, returning \((x_{1} + x_{2})\) instead. An approach along these
lines will form the basis for the creation of differentiable \F{}n
primitives.

* Differentiable Programming in Faust

We implement forward mode automatic differentition based on dual
numbers/signals.

Reverse propagation of signals /is/ possible in Faust via recursive
composition (the ~~~ operator), and it is by way of nested recursions
that the =physmodels.lib= library accomplishes simulated bidirectional
wave propagation [cite:@michon_faust_2018]. The structures described
by =physmodels.lib= are purely linear, however; for branching
structures, the [fn:2]

The possibility of writing differentiable code in any programming
language is contingent on the availability of derivative expressions
for the primitive operations in that language.

** Defining a Differentiable Primitive

As a basic example, consider the addition primitive; in \F{} one can
write:

#+NAME: faust_add
#+begin_src faust
process = +;
#+end_src
which yields the block diagram:

#+CALL: faust_add() :results svg file :file images/add.svg :exports results
#+ATTR_LATEX: :width .5\linewidth
#+RESULTS:
[[file:add.svg]]
This signal processor takes two input signals, \(u\) and \(v\), and
produces one output signal, \(y\):

\begin{equation}
y = u + v.
\end{equation}
Note that \F's addition primitive has no special knowledge of its
arguments, their history, provenance, etc., it just consumes them and
returns their sum. In \F's arithmetic, the addition of two signals is
simply well-defined.

Suppose that \(y\) is dependent on some variable \(x\), and that we
wish to know how sensitive \(y\) is to perturbations in \(x\). We can
produce an analytic expression for this sensitivity by differentiating
\(y\) with respect to \(x\). Recall, from equation ([[eq:addition-rule]]),
that a dual-number addition takes the form of two additions in
parallel, which, in \F could be expressed like this:

#+begin_src faust :results svg file :file images/dualadd.svg :exports both
process = +,+;
#+end_src
#+ATTR_LATEX: :width .5\linewidth
#+RESULTS:
[[file:images/dualadd.svg]]
Such an expression could be said to describe a /differentiable
addition primitive/, taking dual-number inputs \(\langle u,u' \rangle\) and \(\langle
v,v' \rangle\) and producing output \(\langle y,y' \rangle\).  Since \F deals
exclusively with the propagation of signals, we shall refer to this as
a /dual signal/ representation. Having acces to the primal and tangent
signals in parallel in this manner lays the foundation for writing
differentiable code in the \F{} language.

*** Supplying the Derivatives

Just as the addition primitive has no knowledge of the provenance of
its input signals, nor does its differentiable counterpart. To have
the differentiable addition primitive behave as it should, it is
necessary to supplement \F{}'s arithmetic with the following rule:

#+begin_quote
Supply \(u\) and \(v\), and \(u'\) and \(v'\) to
the differentiable addition primitive, in that order, and it should
return \(y\) and \(y'\) (in that order).
#+end_quote
For \(u\) we use an arbitrary input signal, which we can represent
with \F{}'s identity function, ~_~. \(x\) is the variable of interest;
\F{}'s analogy to a variable is a slider, so one is created and assigned
to \(v\). \(u\) and \(x\) have no direct relationship, so
\(u' = 0\).  \(v\) /is/ \(x\), so \(x' = 1\).

#+NAME: lst:dc-symbolic
#+CAPTION: Symbolic differentiation of a DC offset applied to an input
#+CAPTION: signal.
#+begin_src faust :results file svg :file images/dc.svg :exports both
x = hslider("x", 0, -1, 1, .1);
u = _;
v = x;
dudx = 0;
dvdx = 1;
process = u,v,dudx,dvdx : +,+;
#+end_src

#+RESULTS: lst:dc-symbolic
[[file:images/dc.svg]]

The primal output signal of this program is the result of an
expression describing an input signal with a DC offset \(x\) applied;
the tangent output, the derivative with respect to \(x\), is a
constant signal of value \(1\).

The program in listing 1 takes a symbolic approach to
differentiation. This is fine for a basic example, but for more
complex algorithms, composed of many primitives, manually defining
derivatives symbolically in this way will quickly become unwieldy. To
generalise a little, we can define a differentiable input, and a
differentiable slider:

#+begin_src faust
diffInput = _,0;
diffSlider = hslider("x", 0, -1, 1, .1),1;
#+end_src
Simply applying the differentiable addition primitive to these new
primitives will not satisfy the new rule upon which that primitive
depends, however, nor yield a program whose structure matches that
described in equation ([[eq:addition-rule]]), as inputs to the addition
primitive will arrive out of order. This can be remedied with \F{}'s
~route~ primitive:

#+begin_src faust
diffAdd = route(4, 4,
  (1, 1), (2, 3), (3, 2), (4, 4)) : +,+;
#+end_src
Now we can write:

#+begin_src faust
process = diffInput,diffSlider : diffAdd;
#+end_src

#+begin_src faust :results file svg :file images/dcauto.svg :exports results
diffInput = _,0;
diffSlider = hslider("x", 0, -1, 1, .1),1;
diffAdd = route(4, 4, (1, 1), (2, 3), (3, 2), (4, 4)) : +,+;
process = diffInput,diffSlider : diffAdd;						 
#+end_src

#+RESULTS:
[[file:images/dcauto.svg]]

The outputs of the program are the same as before, but, by composing
primitives with well-defined derivatives, the derivative of the entire
program has been found /automatically/; to be precise, this is a
rudimentary implementation of forward-mode automatic differentiation
in \F{}.

** Multivariate Differentiable Primitives

What if a program has more than one variable? Consider the following
(non-differentiable) example consisting of a DC offset and a gain
control applied to an input signal:

#+CAPTION: A \F{} program that applies gain and DC offset parameters
#+CAPTION: to an input signal.
#+NAME: lst:gain-dc
#+begin_src faust
x1 = hslider("gain", .5, 0, 1, .1);
x2 = hslider("dc", 0, -1, 1, .1);
process = _,x1 : *,x2 : +;
#+end_src
which can be notated thus:

#+NAME: eq:gain-dc
\begin{equation}
y = uv + w, \quad v = x_1, \quad w = x_2.
\end{equation}
Once again \(u\) is an arbitrary input signal, for which we have no
analytic expression. Now, rather than being a lone ordinary derivative
\(\frac{dy}{dx}\), the derivative of \(y\) --- \(y'\) --- is a matrix
of partial derivatives:

#+NAME: eq:pds
\begin{equation}
y' = \frac{\partial y}{\partial \mathbf{x}}
= \begin{bmatrix}\frac{\partial y}{\partial x_1} \\
\frac{\partial y}{\partial x_2}\end{bmatrix}.
\end{equation}
Our algorithm takes two parameter inputs, and produces one output
signal, so the resulting /Jacobian/ matrix is of dimension \(2 \times
1\). Returning to dual signal representation and applying the chain,
product and addition rules of differentiation, we have:

#+NAME: eq:dual-gain-dc
\begin{align}
\langle y,y' \rangle &=
\langle u,u' \rangle \langle v,v' \rangle + \langle w,w' \rangle \nonumber \\
&= \langle uv,u'v + v'u \rangle + \langle w,w' \rangle \nonumber \\
&= \langle uv + w,u'v + v'u + w'\rangle,
\end{align}

To implement the above in \F{} calls for the creation of multivariate
differentiable primitives. One approach to achieving this would be to
implement ~diffInput~, ~diffSlider~, and ~diffAdd~ as functions, each
taking as a parameter ~NVARS~, the number of variables in the program,
and thus partial derivatives that they should produce. Using \F{}'s
~environment~ expression, however it is possible to approach the
problem in a more general, and syntactically succinct fashion.

*** A Differentiable Environment

First, we can define a function for collecting, counting, and
retrieving variables and their partial derivatives:

#+NAME: lst:var-env
#+CAPTION: A \F{} function for defining an environment of
#+CAPTION: differentiable variables.
#+begin_src faust
vars(V) = environment {
  // Count the variables.
  N = outputs(V);
  // Retrieve a variable by index i.
  var(i) = ba.take(i, V),pds(N, i)
  with {
    // Compute partial derivatives of
    // variable x_i.
    pds(N, i) = par(j, N, i-1==j);
  };
};
#+end_src
~vars~ receives a list of variables, expressed via parallel
composition, e.g. ~X = vars((gain,dc));~, where ~gain~ and ~dc~ are
defined as ~hslider~ instances.

Next, we can define a function that takes the variable environment
produced by ~vars~ as its sole argument, and returns a /differentiable
environment/, containing a collection of multivariate differentiable
primitives. As a further improvement, we can use \F{}'s pattern
matching syntax to simplify the nomenclature of the differentiable
primitives; instead of exposing the name ~diffAdd~, for example, the
differentiable addition primitive can be named ~diff(+)~:

#+NAME: lst:diff-env
#+CAPTION: Extract from the definition of a \F{} environment for
#+caption: differentiable programming.
#+begin_src faust
env(vars) = environment {
  diff(+) = diffAdd with {
    diffAdd = route(nIN, nOUT,
      (u, 1), (v, 2), // u + v
      par(i, vars.N,
	// du/dx_i + dv/dx_i
	(u+i+1, dx), (v+i+1, dx+1)
	with {
	  // Start of derivatives wrt x_i
	  dx = 2*i+3;
	}
      )
    ) with {
      nIN = 2+2*vars.N;
      nOUT = nIN;
      u = 1;
      v = u+vars.N+1;
    }
    : +,par(i, vars.N, +);
  };

  // ...definitions of other
  // differentiable primitives...
};
#+end_src

As before, the primal signal output of the differentiable addition
primitive is the sum of the primal inputs, \(u+v\); now, however, the
differentiable primitive produces ~vars.N~ tangent outputs, each
corresponding to a derivative with respect to \(x_{i}\). As before, the
~route~ primitive ensures that incoming signals are delivered to the
parallel additions in the correct order.

Encapsulating listings [[lst:var-env]] and [[lst:diff-env]] as a library in a
file named =diff.lib=, we can use ~vars~ and ~env~ to write a
differentiable version of the gain-plus-DC-offset program encountered
earlier:

#+CAPTION: Differentiable counterpart to the \F{} program described in
#+CAPTION: listing [[lst:gain-dc]].
#+NAME: lst:gain-dc-diff
#+begin_src faust :results file svg :file images/gain-dc.svg :exports both
df = library("diff.lib");

X = df.vars((gain,dc)) with {
  gain = hslider("gain", .5, 0, 1, .01);
  dc = hslider("dc", 0, -1, 1, .01);
};

d = df.env(X);

process = d.input,X.var(1)
  : d.diff(*),X.var(2)
  : d.diff(+);
#+end_src
#+NAME: fig:gain-dc
#+ATTR_LATEX: :float multicolumn :placement [ht!]
#+CAPTION: Block diagram of a differentiable \F{} program consisting
#+CAPTION: of differentiable gain and DC parameters applied to an
#+CAPTION: input signal
#+CAPTION: (see listing [[lst:gain-dc-diff]]).
#+RESULTS: lst:gain-dc-diff
[[file:images/gain-dc.svg]]
See figure [[fig:gain-dc]] for the block diagram of this program. Note
that while the routing for each primitive --- particularly ~diff(*)~
--- may be quite involved (and would only become more complex with the
addition of further variables) the ~df~ library abstracts this away.

** Parameter Optimisation via Gradient Descent

Armed with the means to write end-to-end differentiable \F{} programs,
it is possible, with a few modifications (and additions to
=diff.lib=), to combine the code in listings [[lst:gain-dc]] and
[[lst:gain-dc-diff]], to create a demonstrative parameter optimisation
algorithm. An algorithm of this kind describes a target output,
governed by parameters that are /hidden/ with respect to some
/estimated/ output, which itself depends on parameters that we wish to
optimise.

The algorithm in listing [[lst:gain-dc]] is dependent on hidden parameters
\(\mathbf{x}\) and produces a ground truth output signal \(y\); we
assign this algorithm to a variable named ~target~. Its differentiable
equivalent in listing [[lst:gain-dc-diff]] is dependent on estimated
parameters \(\mathbf{\hat{x}}\) and produces the dual output signal,
\(\langle \hat{y}, \hat{y}' \rangle\); we assign this to a variable named
~estimate~. The output signals produced by ~target~ and ~estimate~ can
now be compared by way of a loss function; to this end, we can employ
time-domain L1-norm loss of the form:

#+NAME: eq:l1-loss
\begin{equation}
\mathcal{L}(y,\hat{y}) = ||\hat{y} - y||.
\end{equation}

Our aim is to minimise the value returned by the loss function,
i.e. to reach the point at which \(y\) and \(\hat{y}\) (and by
extension \(\mathbf{x}\) and \(\mathbf{\hat{x}}\)) most closely
approximate one-another. The sensitivity of \(\mathcal{L}\) to
perturbations in \(\mathbf{\hat{x}}\) can again be found by automatic
differentiation, subject to the definition of a differentiable
absolute value function in ~df.env~. The loss function can then be
implemented as follows:

#+NAME: lst:loss-function
#+CAPTION: Implementation of a loss function (L1-norm) using
#+CAPTION: differentiable ~abs~ primitive.
#+begin_src faust
env(vars) = environment {
  // ...
  lossL1(learningRate, y, yHat) = 
    error,par(i, vars.N, _)
    : diff(abs)
    : _,scaleGrads
  with {
    error = yHat,y : -;
    scaleGrads = par(i, vars.N,
      _,learningRate : *);
  };
  // ...
#+end_src

The loss function's derivatives are the /gradients/ associated with
each variable in \(\mathbf{\hat{x}}\). In our two-parameter example,
\(\mathcal{L}\) will describe a two-dimensional surface, and
\(\frac{\partial\mathcal{L}}{\partial x_{i}}\) its slope in the direction of
\(x_{i}\). Variables at time \(t+1\) are found by scaling gradients by a
learning rate, \(\alpha\), and subtracting the result from variable values
at time \(t\):

#+NAME: eq:gradient-descent
\begin{equation}
\mathbf{\hat{x}}_{t+1} &= \mathbf{\hat{x}}_t - \alpha\frac{\partial\mathcal{L}}{\partial \mathbf{\hat{x}}_t}
\end{equation}
In \F{}, this can be achieved via recursion, and by changing the
definition of the variables delivered to ~df.env~. Since values will
be updated automatically via gradient descent, the sliders used in
listing [[lst:gain-dc-diff]] are no longer appropriate; instead, a
bargraph instance can be used to display the value of each variable,
with recursive subtractions accumulating the incoming gradients.

#+begin_src faust
X = df.vars((gain,dc)) with {
  gain = -~_
    <: attach(hbargraph("Gain", 0, 1));
  dc = -~_
    <: attach(hbargraph("DC", -1, 1));
};
#+end_src

Finally, we can create a program that takes white noise as input,
encapsulates ~target~, ~estimate~, and the loss function, and recurses
gradients produced by the latter back to ~estimate~.

#+NAME: lst:backprop
#+CAPTION: Excerpt from a parameter optimisation algorithm. See
#+CAPTION: listings [[lst:gain-dc]], [[lst:gain-dc-diff]] and
#+CAPTION: [[lst:loss-function]] respectively for definitions of ~target~,
#+CAPTION: ~estimate~, and ~d.lossL1~.
#+begin_src faust
process = no.noise <: (
    route(nvars+nInputs, nvars+nInputs,
      // Route gradients to estimate.
      par(i, nvars, (i+1, i+3)),
      // Route input to target & estimate.
      (nvars+1, 1), (nvars+2, 2))
    : target,estimate : d.lossL1(1e-3)
    // Recurse the gradients.
  ) ~ (!,si.bus(nvars))
  // Block the gradients, post-recursion.
  : _,si.block(nvars)
with {
  nvars = inputs(estimate),
    inputs(target) : -;
  nInputs = inputs(target),2 : *;
// ...
#+end_src

[link to example files]

* Discussion
** Limitations

- derivative of delay
- deterministic input
- overfitting...
- dimensionality; reverse mode

* Conclusion

** Acknowledgements

#+begin_export latex
%%\nocite{*}
#+end_export
#+PRINT_BIBLIOGRAPHY:

* Emacs Setup                                                      :noexport:

- Set up =ifc24= document class.
- Add =-shell-escape= flag to latex process, so =svg= works.
- Use =listings= package for exported source blocks.
- Add custom =ifc24-style= package to =org-latex-packages-alist= so
  equation previews work.

* Footnotes

[fn:2]  See [cite:@radul_you_2023], figure 1, for an illustration of
the sort of structure that would be required in order to support
reverse mode autodiff.

[fn:1] Various transformations /are/ in fact possible at the level of
the /F compiler. See section [[*Discussion]] for further exploration of
this idea.

# Local Variables:
# eval:   (add-to-list 'org-latex-classes '("ifc24"
# "\\documentclass[twoside,a4paper]{article}
# [NO-DEFAULT-PACKAGES]"
# ("\\section{%s}" . "\\section*{%s}")
# ("\\subsection{%s}" . "\\subsection*{%s}")
# ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
# ("\\paragraph{%s}" . "\\paragraph*{%s}")
# ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# eval:   (setq org-latex-pdf-process '("latexmk -f -pdf -%latex \
# -interaction=nonstopmode -shell-escape -output-directory=%o %f"))
# eval:   (setq org-latex-src-block-backend 'listings)
# eval:   (setq org-latex-packages-alist '())
# eval:   (add-to-list 'org-latex-packages-alist '("" "./out/ifc24-style" t))
# End:
