# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Differentiable DSP in Faust
# #+AUTHOR: Thomas Rushton

#+EXPORT_FILE_NAME: out/ifc24
#+OPTIONS: toc:nil ':t ^:{} num:3
# #+LATEX_COMPILER: latexmk
#+LATEX_CLASS: ifc24
#+BIBLIOGRAPHY: IFC-24.bib
#+CITE_EXPORT: bibtex
#+LATEX_HEADER: \RequirePackage[]{ifc24-style}

#+begin_abstract
This is the template file for the proceedings of the third \F{}
International Conference (IFC-24).
This template has been derived from IFC-20 templates and aims at producing
conference proceedings in electronic form.
The format is essentially the one used for ICASSP conferences. Please use
either this \LaTeX{} or the accompanying Word formats when preparing your
submission.

Using the ~environment~ expression and pattern matching abstraction,
it is possible to write \F{} code that is differentiable end-to-end,
facilitating the computation and propagation of gradients, and in turn
supporting the creation of parameter optimisation
algorithms. Differentiable programming in \F{} could serve as a
platform for a \F{}-native approach to machine learning problems.
#+end_abstract

* Latex Setup                                                      :noexport:
:PROPERTIES:
:HEADER-ARGS: :tangle out/ifc24-style.sty :results silent
:END:

Remember to tangle =C-c C-v t= before exporting.

** Basics

#+begin_src latex
\ProvidesPackage{ifc24-style}[2024/07/12 v0.1 Bundling IFC24 LaTeX style]
#+end_src

** Author(s)

Title is taken from the title attribute.

#+begin_src latex
%% \def\papertitle{Differentiable DSP in Faust}
\def\paperauthorA{Thomas Albert Rushton}
#+end_src

Authors' affiliations have to be set below.

** Packages
#+begin_src latex
\usepackage{IFC-24}
\usepackage{amsmath,amssymb,amsfonts,amsthm}
\usepackage{euscript}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{ifpdf}

\usepackage{color}
\usepackage{listings}
\definecolor{mygrey}{rgb}{0.96,0.96,0.96}
\lstset{
  tabsize=4,
  basicstyle=\ttfamily,
  backgroundcolor=\color{mygrey},
  captionpos=b,
  breaklines=true
}

\usepackage[english]{babel}
\usepackage{caption}
\usepackage{subfig, color}

\setcounter{page}{1}
\ninept

\usepackage{times}
\usepackage{inconsolata}

\usepackage{microtype}
\usepackage[inkscapelatex=false]{svg}
#+end_src

** LaTeX vs PDFLaTeX

#+begin_src latex
% pdf-tex settings: detect automatically if run by latex or pdflatex
\newif\ifpdf
\ifx\pdfoutput\relax
\else
   \ifcase\pdfoutput
      \pdffalse
   \else
      \pdftrue
\fi

\ifpdf % compiling with pdflatex
  \usepackage[pdftex,
    pdftitle={\papertitle},
    pdfauthor={\paperauthorA, \paperauthorB, \paperauthorC, \paperauthorD},
    colorlinks=false, % links are activated as colror boxes instead of color text
    bookmarksnumbered, % use section numbers with bookmarks
    pdfstartview=XYZ % start with zoom=100% instead of full screen; especially useful if working with a big screen :-)
  ]{hyperref}
  \pdfcompresslevel=9
  \usepackage[pdftex]{graphicx}
  \usepackage[figure,table]{hypcap}
\else % compiling with latex
  \usepackage[dvips]{epsfig,graphicx}
  \usepackage[dvips,
    colorlinks=false, % no color links
    bookmarksnumbered, % use section numbers with bookmarks
    pdfstartview=XYZ % start with zoom=100% instead of full screen
  ]{hyperref}
  % hyperrefs are active in the pdf file after conversion
  \usepackage[figure,table]{hypcap}
\fi
#+end_src

** Macros
#+begin_src latex
% Special Macros
\newcommand{\F}{\textsc{Faust}}
#+end_src

** Author affiliations

Single author affiliation:

#+begin_src latex
\affiliation{\paperauthorA}
{\href{https://inria.fr}{Inria} \\ Villeurbanne, France\\
{\tt \href{mailto:thomas.rushton@inria.fr}{thomas.rushton@inria.fr}}
}
#+end_src

** Bibliography

#+begin_src latex
\bibliographystyle{IEEEbib}
#+end_src

* Adding Image Attributes                                          :noexport:

You've generated some image output from a source block; now you want
to add attributes like ~#+CAPTION:~, etc. There are a few approaches,
none of which is perfectly lovely. To suggest a couple:

- Generate an image result, then add attributes between the source
  block or ~CALL~ statement and the results.
#+begin_example
#+begin_src
...
#+end_src
#+CAPTION: A delightful caption
#+ATTR_LATEX: :width .5\linewidth
#+RESULTS:...
#+end_example

- Use [[https://orgmode.org/manual/Evaluating-Code-Blocks.html#How-to-evaluate-source-code-1][inline call]] syntax
#+begin_example
#+NAME: faust_code
#+begin_src faust
...
#+end_src

#+ATTR_LATEX: :width .75\linewidth
call_faust_code()[:results svg file :file image.svg :output-dir images
:exports results]
#+end_example

The latter doesn't provide a preview, but less manual intervention is
necessary.

One more thing: for regular source blocks, ~:output-dir~ and ~:file~
are combined into ~:file~ to produce =<outputdir>/<file>=. For
~#+CALL:~ this isn't the case; best to just use ~:file
<outputdir>/<file>~.

* More potentially useful syntax                                   :noexport:

This is a link to section [[*Conclusion]]

This template can be found on the conference website.

Here's a ref: [cite:@Smith2012]

Here's some code:

#+begin_src faust
  process = _;
#+end_src

And some inline code ~process = !;~

And floating code?

#+CAPTION: this code should float, because it has a caption
#+begin_src faust
process = 1;
#+end_src

* Introduction

Differentiable programming is "a programming paradigm in which complex
computer programs\dots can be differentiated end-to-end automically"

[Differentiable programming] may be supported by operator overloading...

There is a sense in which the block-diagram algebra of \F{} lends the
language intuitively to the problem of automatic differentiation. As
we will see, the language itself presents certain limitations in this
respect, but nonetheless we can achieve a great deal\dots

* Differentiable Programming in Faust

The possibility of writing differentiable code in any programming
language is contingent on the availability of derivative expressions
for the primitive operations in that language.

** Defining a Differentiable Primitive

As a basic example, consider the addition primitive; in \F{} one can
write:

#+NAME: faust_add
#+begin_src faust
 process = +;
#+end_src
which yields the block diagram:

#+CALL: faust_add() :results svg file :file images/add.svg :exports results
#+ATTR_LATEX: :width .5\linewidth
#+RESULTS:
[[file:add.svg]]

This signal processor takes two input signals, \(u\) and \(v\), and
produces one output signal, \(y\):

\begin{equation}
y = u + v.
\end{equation}
Note that \F{}'s addition primitive has no special knowledge of its
arguments, their history, provenance, etc., it just consumes them and
returns their sum. In \F{}'s /algebra/, the addition of two signals is
simply well-defined.

Suppose that \(y\) is dependent on some variable \(x\), and that we
wish to know how sensitive \(y\) is to changes in \(x\). We can
produce an analytic expression for this sensitivity by differentiating
\(y\) with respect to \(x\). The addition rule of differentiation
states that the derivative of an addition is another addition, albeit
one whose operands are the derivatives of the operands to the original
addition with respect to the variable of interest:

\begin{equation}
\frac{dy}{dx} = \frac{d}{dx}(u + v) = \frac{du}{dx} + \frac{dv}{dx}.
\end{equation}
In \F{} we could express this as follows:

#+begin_src faust :results svg file :file images/dualadd.svg :exports both
 process = +,+;
#+end_src
#+ATTR_LATEX: :width .5\linewidth
#+RESULTS:
[[file:images/dualadd.svg]]
That being the case, we would be describing a /differentiable addition
primitive/ consisting, in parallel, of the /primal/ output signal
\(y\), and its /tangent/ \(\frac{dy}{dx}\). This could in turn be
described as follows:

#+NAME: eq:dualadd
\begin{align}
\langle y, \frac{dy}{dx} \rangle
&= \langle u, \frac{du}{dx} \rangle + \langle v, \frac{dv}{dx} \rangle \nonumber \\
&= \langle u + v, \frac{du}{dx} + \frac{dv}{dx} \rangle.
\end{align}

This is a /dual number/ representation, or, more accurately since \F{}
deals exclusively with signals, a /dual signal/ representation.
Having acces to the primal and tangent signals in parallel in this
manner lays the foundation for forward mode automatic differentiation
in the \F{} language. [But this wording is bad and I should improve
it.]

*** Supplying the Derivatives

Just as the addition primitive has no knowledge of the provenance of
its input signals, nor does its differentiable counterpart. To have
the differentiable addition primitive behave as it should, it is
necessary to supplement \F{}'s algebra with the following rule:

#+begin_quote
Supply \(u\) and \(v\), and \(\frac{du}{dx}\) and \(\frac{dv}{dx}\) to
the differentiable addition primitive, in that order, and it should
return \(y\) and \(\frac{dy}{dx}\) (in that order).
#+end_quote
For \(u\) we use an arbitrary input signal, which we can represent
with a wire, ~_~.  \(x\) is the variable of interest; \F's analogy
to a variable is a slider, so one is created and assigned to \(v\).
\(u\) and \(x\) have no direct relationship, so \(\frac{du}{dx} = 0\).
\(v\) /is/ \(x\), so \(\frac{dv}{dx} = 1\).

#+NAME: lst:dc-symbolic
#+begin_src faust :results file svg :file images/dc.svg :exports both
 x = hslider("x", 0, -1, 1, .1);
 u = _;
 v = x;
 dudx = 0;
 dvdx = 1;
 process = u,v,dudx,dvdx : +,+;
#+end_src

#+RESULTS: lst:dc-symbolic
[[file:images/dc.svg]]

The primal output signal of this program is the result of an
expression describing an input signal with a DC offset \(x\) applied;
the tangent output, the derivative with respect to \(x\), is a
constant signal of value \(1\).

The above takes a symbolic approach to differentiating the
program. This is fine for a basic example, but for more complex
algorithms, composed of many primitives, manually defining derivatives
symbolically in this way will quickly become unwieldy. To generalise a
little, we can define a differentiable input, and a differentiable
slider:

#+begin_src faust
 diffInput = _,0;
 diffSlider = hslider("x", 0, -1, 1, .1),1;
#+end_src
Simply applying the differentiable addition primitive to these new
primitives will not yield a program whose structure matches that
described in equation ([[eq:dualadd]]), however, as inputs to the addition
primitive will arrive out of order. This can be remedied with \F{}'s
~route~ primitive:

#+begin_src faust
 diffAdd = route(4, 4,
     (1, 1), (2, 3), (3, 2), (4, 4)) : +,+;
#+end_src
Now we can write:

#+begin_src faust
  process = diffInput,diffSlider : diffAdd;
#+end_src

#+begin_src faust :results file svg :file images/dcauto.svg :exports results
 diffInput = _,0;
 diffSlider = hslider("x", 0, -1, 1, .1),1;
 diffAdd = route(4, 4, (1, 1), (2, 3), (3, 2), (4, 4)) : +,+;
 process = diffInput,diffSlider : diffAdd;						 
#+end_src

#+RESULTS:
[[file:images/dcauto.svg]]

The outputs of the program are the same as before, but, by composing
primitives with well-defined derivatives, the derivative of the entire
program has been found /automatically/; to be precise, this is a
rudimentary implementation of /forward-mode automatic differentiation/
in \F{}.

** Multivariate Differentiable Primitives

What if a program has more than one variable? Consider the following
(non-differentiable) example consisting of a DC offset and a gain
control:

#+CAPTION: A \F{} program that applies gain and DC offset parameters
#+CAPTION: to an input signal.
#+NAME: lst:gain-dc
#+begin_src faust
x1 = hslider("gain", .5, 0, 1, .1);
x2 = hslider("dc", 0, -1, 1, .1);
process = _,x1 : *,x2 : +;
#+end_src
which can be notated thus:

#+NAME: eq:gain-dc
\begin{equation}
y = uv + w, \quad v = x_1, \quad w = x_2.
\end{equation}
Once again \(u\) is an arbitrary input signal, for which we have no
analytic expression. Now, rather than being a lone ordinary derivative
\(\frac{dy}{dx}\), the derivative of \(y\) --- \(y'\) --- is a matrix
of partial derivatives:

#+NAME: eq:pds
\begin{equation}
y' = \frac{\partial y}{\partial \mathbf{x}}
= \begin{bmatrix}\frac{\partial y}{\partial x_1} \\
\frac{\partial y}{\partial x_2}\end{bmatrix}.
\end{equation}

Our algorithm takes two parameter inputs, and produces one output
signal, so the resulting /Jacobian/ matrix is of dimension \(2 \times
1\). Returning to dual signal representation and applying the chain,
product and addition rules of differentiation, we have:

#+NAME: eq:dualgaindc
\begin{align}
\langle y,y' \rangle &=
\langle u,u' \rangle \langle v,v' \rangle + \langle w,w' \rangle \nonumber \\
&= \langle uv,u'v + v'u \rangle + \langle w,w' \rangle \nonumber \\
&= \langle uv + w,u'v + v'u + w'\rangle,
\end{align}

To implement the above in \F{} calls for the creation of multivariate
differentiable primitives. One approach to achieving this would be to
implement ~diffInput~, ~diffSlider~, and ~diffAdd~ as functions, each
taking as a parameter ~NVARS~, the number of variables in the program,
and thus partial derivatives that they should produce. Using \F{}'s
~environment~ expression, however it is possible to approach the
problem in a more general, and syntactically succinct fashion.

*** A Differentiable Environment

First, we can define a function for collecting, counting, and
retrieving variables and their partial derivatives:

#+begin_src faust
vars(V) = environment {
    // Count the variables.
    N = outputs(V);
    // Retrieve a variable by index i.
    var(i) = ba.take(i, V),pds(N, i)
    with {
        // Compute partial derivatives of
        // variable x_i.
        pds(N, i) = par(j, N, i-1==j);
    };
};
#+end_src
~vars~ receives a list of variables, expressed via parallel
composition, e.g. ~X = vars((gain,dc));~, where ~gain~ and ~dc~ are
defined as ~hslider~ instances.

Next, we can define a function that takes the variable environment
produced by ~vars~ as its sole argument, and returns a /differentiable
environment/, containing a collection of multivariate differentiable
primitives. As a further improvement, we can use \F{}'s pattern
matching syntax to improve the nomenclature of the differentiable
primitives; instead of exposing the name ~diffAdd~, for example, the
differentiable addition primitive can be named ~diff(+)~:

#+NAME: lst:diffenv
#+CAPTION: Extract from the definition of a \F{} environment for
#+CAPTION: differentiable programming.
#+begin_src faust
env(vars) = environment {
    // Differentiable addition primitive.
    diff(+) = diffAdd with {
        diffadd = route(nIN, nOUT,
            (u, 1), (v, 2), // u + v
            par(i, vars.N,
                // du/dx_i + dv/dx_i
                (u+i+1, dx), (v+i+1, dx+1)
                with {
                    // Start of derivatives
                    // wrt x_i
                    dx = 2*i+3;
                }
            )
        ) with {
            nIN = 2+2*vars.N;
            nOUT = nIN;
            u = 1;
            v = u+vars.N+1;
        }
        : +,par(i, vars.N, +);
    };
  
    // ...definitions of other
    // differentiable primitives...
};
#+end_src

As before, the primal signal output of the differentiable addition
primitive is the sum of the primal inputs, \(u+v\); now, however, the
differentiable primitive produces ~vars.N~ tangent outputs, each
corresponding to a derivative with respect to \(x_{i}\). As before, the
~route~ primitive ensures that incoming signals are delivered to the
parallel additions in the correct order.

Encapsulating [[lst:diffenv]] as a library in a file named =diff.lib=, we
can use ~vars~ and ~env~ to write a differentiable version of the
program in listing [[lst:gain-dc]]:

#+CAPTION: Differentiable counterpart to the \F{} program described in
#+CAPTION: listing [[lst:gain-dc]].
#+NAME: lst:gain-dc-diff
#+begin_src faust :results file svg :file images/gain-dc.svg :exports both
df = library("diff.lib");

X = df.vars((gain,dc)) with {
    gain = hslider("gain", .5, 0, 1, .01);
    dc = hslider("dc", 0, -1, 1, .01);
};

d = df.env(X);

process = d.input,X.var(1)
    : d.diff(*),X.var(2)
    : d.diff(+);
#+end_src
#+NAME: fig:gain-dc
#+ATTR_LATEX: :float multicolumn :placement [ht!]
#+CAPTION: Block diagram of a differentiable \F{} program consisting
#+CAPTION: of differentiable gain and DC parameters applied to an
#+CAPTION: input signal
#+CAPTION: (see listing [[lst:gain-dc-diff]]).
#+RESULTS: lst:gain-dc-diff
[[file:images/gain-dc.svg]]
See figure [[fig:gain-dc]] for the block diagram of this program.

** Parameter Optimisation



* Conclusion

Don't know yet; working on it.

#+begin_export latex
%%\nocite{*}
#+end_export
#+PRINT_BIBLIOGRAPHY:

* Emacs Setup                                                      :noexport:

- Set up =ifc24= document class.
- Add =-shell-escape= flag to latex process, so =svg= works.
- Use =listings= package for exported source blocks.
- Add custom =ifc24-style= package to =org-latex-packages-alist= so
  equation previews work.

# Local Variables:
# eval:   (add-to-list 'org-latex-classes '("ifc24"
# "\\documentclass[twoside,a4paper]{article}
# [NO-DEFAULT-PACKAGES]"
# ("\\section{%s}" . "\\section*{%s}")
# ("\\subsection{%s}" . "\\subsection*{%s}")
# ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
# ("\\paragraph{%s}" . "\\paragraph*{%s}")
# ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# eval:   (setq org-latex-pdf-process '("latexmk -f -pdf -%latex \
# -interaction=nonstopmode -shell-escape -output-directory=%o %f"))
# eval:   (setq org-latex-src-block-backend 'listings)
# eval:   (setq org-latex-packages-alist '())
# eval:   (add-to-list 'org-latex-packages-alist '("" "./out/ifc24-style" t))
# End:
