#+title: Ananas: A Networked Audio System for Distributed Spatial Audio Applications

#+export_file_name: out/is2-2026
#+options: toc:nil num:3 date:nil author:nil
#+latex_class: is2-2026
#+cite_export: bibtex IEEETran
#+latex_header_extra: \RequirePackage[]{./out/is2-2026}

#+begin_abstract
Spatial audio has an accessibility problem. Large-scale spatial and
immersive audio installations remain costly and exclusive, with high
barriers to entry. We propose "Ananas", a networked audio system
consisting of network protocols, control software and microcontroller
firmware, with the aim of rendering spatial audio applications
accessible to a broad cohort of potential users. Based on a network of
low-cost microcontroller development boards programmed in the Faust
programming language, synchronised via IEEE 1588 Precision Time
Protocol, and controlled by approachable, digital audio
workstation-based tooling, Ananas represents an opportunity to disrupt
and democratise the spatial audio landscape. In this paper we
demonastrate Ananas's protocols for audio and control data
transmission and device discovery, its methods for media clock and
presentation time recovery, and its applications to wave field
synthesis and higher order ambisonics in a modular, scalable form.
#+end_abstract

* About                                                            :noexport:

Org file describing a paper for submission to the 2026 Internet of
Sounds Symposium. Submit on [[https://easychair.org/conferences2/submission?a=36910236&submission=7699371][EasyChair]] by +June 30th+ July 7th 2026.

* LaTeX Setup                                                      :noexport:
:PROPERTIES:
:header-args: :tangle out/is2-2026.sty :results silent :noeval
:END:

** Provide the package

#+begin_src latex
\ProvidesPackage{is2-2026}
#+end_src

** Packages

#+begin_src latex
\IEEEoverridecommandlockouts
\RequirePackage{cite}
\RequirePackage{amsmath,amssymb,amsfonts}
\RequirePackage{algorithmic}
\RequirePackage{graphicx}
\RequirePackage{textcomp}
\RequirePackage{xcolor}
\RequirePackage{inconsolata}
\RequirePackage{siunitx}
#+end_src

*** Packet diagrams

#+begin_src latex
\RequirePackage{bytefield}
#+end_src

*** Maths typesetting

#+begin_src latex
\RequirePackage{newtxtext, newtxmath}
#+end_src

*** References

#+begin_src latex
\RequirePackage{hyperref}
\hypersetup{
  unicode,
  colorlinks,
  citecolor=black,
  filecolor=black,
  linkcolor=black,
  urlcolor=black,
  bookmarksnumbered,
  pdfstartview=XYZ
}
\RequirePackage[noabbrev]{cleveref}
#+end_src

** BibTeX stuff

#+begin_src latex
\def\BibTeX{{\rm B\kern-.05em{\sc i\kern-.025em b}\kern-.08em
    T\kern-.1667em\lower.7ex\hbox{E}\kern-.125emX}}
#+end_src

** Authors

#+begin_src latex
\author{\IEEEauthorblockN{Thomas Rushton}
  \IEEEauthorblockA{\textit{Inria, INSA Lyon} \\
    \textit{CITI, EA3720} \\
    69621 Villeurbanne, France \\
    \texttt{thomas.rushton@inria.fr}}
  \and
  \IEEEauthorblockN{Romain Michon}
  \IEEEauthorblockA{\textit{Inria, INSA Lyon} \\
    \textit{CITI, EA3720} \\
    69621 Villeurbanne, France \\
    \texttt{romain.michon@inria.fr}}
  \and
  \IEEEauthorblockN{Tanguy Risset}
  \IEEEauthorblockA{\textit{Inria, INSA Lyon} \\
    \textit{CITI, EA3720} \\
    69621 Villeurbanne, France \\
    \texttt{tanguy.risset@insa-lyon.fr}}
}
#+end_src

** Figures

#+begin_src latex
\RequirePackage{tikz}
\usetikzlibrary{positioning, arrows.meta, fit, backgrounds}
#+end_src

*** Audio Server

#+begin_src latex
\pgfdeclarelayer{background}
\pgfdeclarelayer{foreground}
\pgfsetlayers{background,main,foreground}
\tikzset{
  rounded/.style={draw, rounded corners=1mm},
  server/.pic={
    % Place procloop at origin
    \node (procloop) [draw, align=center, fill=white] at (0,0)
          {Processing\\Loop};
    \node (write) [draw, above right=2mm and 2.3cm of procloop, fill=green!20]
          {Write};
    \node (notify) [draw, below=3mm of write, fill=white] {Notify};
    \begin{pgfonlayer}{foreground}
      \node (convert) [draw, below=8mm of notify, fill=white] {Convert};
    \end{pgfonlayer}
    \node (pad1) [inner sep=0pt] at ([yshift=.3cm] convert.north) {};
    \node (read) [draw, fit=(convert)(pad1), fill=blue!20] {};
    \node [anchor=north, inner sep=1mm] at (read.north) {Read};
    \node (packet) [draw, above right=0cm and 2.3cm of notify, fill=white] {Packet};
    \begin{pgfonlayer}{foreground}
      \node (write2) [draw, below=8mm of packet, fill=red!20] {Write};
    \end{pgfonlayer}
    \node (pad2) [inner sep=0mm] at ([yshift=.3cm] write2.north) {};
    \node (socket) [draw, fit=(write2)(pad2), inner xsep=7mm, fill=white] {};
    \node [anchor=north, inner sep=1mm] at (socket.north)
          {Multicast socket};

    % Fit processor around procloop
    \begin{pgfonlayer}{background}
      \node (processor) [rounded, fit=(procloop), inner xsep=5mm, inner ysep=12mm, fill=green!20] {};
      \node [anchor=north, inner sep=1mm] at (processor.north)
            {Audio Processor};
      \node (fifo) [rounded, fit=(write)(notify)(read), inner xsep=5mm, inner ysep=5mm, fill=orange!20]
            {};
      \node [anchor=north, inner sep=1mm] at (fifo.north) {FIFO Buffer};
      \node (sender) [rounded, fit=(packet)(socket), inner ysep=8mm, fill=blue!20] {};
      \node [anchor=north, inner sep=1mm] at (sender.north)
            {Sender Thread};
    \end{pgfonlayer}

    % Outer fit
    \node (server) [fit=(processor)(fifo)(sender), draw, inner sep=5mm]
          {};
    \node [anchor=north west, inner sep=1mm] at (server.north west)
          {Audio Server};
    \node (sources) [above left=-2.875cm and .5cm of server, align=center]
          {WFS sources\\or\\ACN encoded audio};
    \node (udp) [above right=-3.35cm and 1cm of server, align=center]
          {UDP packet to\\multicast group};

    \draw [-{Triangle}] (sources.east) -- (processor.west);
    \draw [-{Triangle}] (procloop.east) -| (1.9, 0) |- (write.west);
    \draw [-{Triangle}] (write.south) -- (notify.north);
    \draw [-{Triangle}] (notify.south) -- (read.north);
    \draw [-{Triangle}] (read.east) -| (5.4, 0) |- (packet.west);
    \draw [-{Triangle}] (packet.south) -- (socket.north);
    \draw [-{Triangle}] (write2.east) -- (udp.west);

    \draw [-{Stealth}] ([yshift=12mm] sender.west) --
    ([yshift=13.35mm] fifo.east) node [midway, above=0mm] {\scriptsize{Await}};
    \draw [-{Stealth}, dashed] ([yshift=13.35mm] fifo.east) -- (notify.east);
  }
}
#+end_src

*** System overview

* Introduction

Despite significant interest in the research and commercial spheres,
access to large-scale spatial audio systems remains stubbornly out of
reach for many interested parties. Highly multichannel audio
interfaces are prohibitively expensive for all but the institutions
with the deepest pockets; implementing a spatial audio system
represents an investment in terms of money and expertise that places
the endeavour beyond the reach of many artists, researchers and other
potential users. In this paper we present Ananas --- /"Ananas
necessitates another networked audio system"/ --- a networked audio
system which, being based on a low-cost microcontroller development
board, open source software, and familiar digital audio workstation
(DAW) tools, seeks to lower the barrier to entry to spatial audio
techniques such as wave field synthesis
(WFS)\nbsp[cite:@berkhoutAcoustic1993] and higher order ambisonics
(HOA)\nbsp[cite:@zotterAmbisonics2019].

The Ananas protocol suite describes a system of protocols for audio
and control data transmission, device discovery and
synchronisation. Taking advantage of multicast user datagram protocol
(UDP) groups for audio transmission and certain elements of control
data, Ananas minimises bandwidth, and, being based on IEEE 1588
Precision Time Protocol (PTP), ensures synchronisation amongst
distributed hardware modules.

* Background

A wide array of networked audio protocols exist; why, then, create a
new one? The answer to this question lies in the time-sensitive nature
of spatial audio reproduction. In a distributed setting,
synchronisation of hardware nodes is critical, and existing protocols
are either proprietary, or do not cater to time-sensitive
applications.

Chief amongst proprietary systems is Dante\nbsp[cite:@danteWhat2022]
(Digital Audio Network Through Ethernet), which uses PTP as its
time-exchange mechanism. Dante-enabled hardware is typically very
expensive, and, being a closed-source initiative, it is not suitable
for further scholarly enquiry. Another closed-source platform can be
found in the shape of the networking component of Elk Audio OS\nbsp[cite:@turchetElk2021].

A variety of open source protocols and systems are available, such as
JackTrip\nbsp[cite:@caceresJackTrip2010a; @caceresJackTrip2010],
NetJack\nbsp[cite:@carotNetjack2009], part of the JACK audio connection
kit, message-based systems such as Audio Over
OSC\nbsp[cite:@ritschMessage2014] (the audio engine behind the audio
streaming application Sonobus[fn:2]), jamming-focused platforms such
as Jamulus\nbsp[cite:@fischerCase2015a] and
Soundjack\nbsp[cite:@renaudNetworked2007], and the audiovisual performance
streaming platform LOLA\nbsp[cite:@drioliNetworked2013]. What these
systems have in common, however, is a focus on networked music
performance and concert streaming, applications where low latency, and
not synchronicity, is of greatest concern. For time-sensitive
applications, this points to the need for a new networked audio
system, one that ensures synchronicity between distributed signal
processing modules.

** The Hardware Platform

#+name: fig:imxrt1062-clock
#+caption: iMXRT1062 audio PLL and SAI1 clock divider registers.
\begin{figure*}[t]
\centering
\begin{tikzpicture}
  \node [draw] (osc) {OSC 24M};
  \node [draw] (pll4) [right=.75cm of osc] {\(\times \left(D_{S} + \frac{D_{N}}{D_{D}}\right)\)};
  \node (pll4label) [above=0cm of pll4] {\small{PLL4}};
  \node [draw] (dp) [right=.75cm of pll4] {\(D_{p}\)};
  \node [draw] (dA) [right=.5cm of dp] {\(D_{A}\)};
  \node [draw] (dI1) [right=.75cm of dA] {\(D_{I_{1}}\)};
  \node [draw] (dI2) [right=2cm of dI1] {\(D_{I_{2}}\)};
  \node (fR) [right=1.5cm of dI2] {\(f_{R}\)};

  \draw [-{Triangle}] (osc.east) -- (pll4.west) node [above, midway] {\scriptsize{\(f_{XO}\)}};
  \draw [-{Triangle}] (pll4.east) -- (dp.west) node [above, midway] {\scriptsize{\(f_{P}\)}};
  \draw [-{Triangle}] (dp.east) -- (dA.west);
  \draw [-{Triangle}] (dA.east) -- (dI1.west) node [above, midway] {\scriptsize{\(f_{M}\)}};
  \draw [-{Triangle}] (dI1.east) -- (dI2.west) node [above, midway] {\scriptsize{\(\leq 300 \text{MHz}\)}};
  \draw [-{Triangle}] (dI2.east) -- (fR.west) node [above, midway] {\scriptsize{\(\leq 66 \text{MHz}\)}};
\end{tikzpicture}
\end{figure*}

Effective deployment of a distribtued spatial audio system is
dependent on the identification of a suitable hardware platform for
the distributed nodes. Such a platform should be low-cost and
powerful, with support for audio and ethernet. The Teensy 4.1
microcontroller development board\nbsp[cite:@michonReal2019] was
identified as satisfying these requirements, costing less than € 50
with its audio and ethernet add-ons, and sporting a \qty{600}{\MHz}
ARM Core M7 CPU. Unlike other comparable devices, such as the
Raspberry Pi, it's microcontroller, an NXP iMXRT1062 MCU, features a
dedicated audio subsystem, with high-resolution clock divider
registers for its audio phase locked loop (PLL); 30 bits are available
for the PLL's numerator and denominator registers, meaning that
nanosecond-order modifications of the audio sampling rate are
possible\nbsp[cite:@nxpsemiconductorsIMX2021].

By convention, the output frequency produced by the iMXRT1062's
synchronous audio interface ~SAI1_CLK_ROOT~, \(f_{R}\), must be 256 times oversampled with respect
to the target audio sampling rate, \(f_{s}\):

#+NAME: eq:sai1-1
\begin{equation}
f_{R} = 2^{8}f_{s}\;.
\end{equation}

The NXP MCUXpresso Config Tools software\nbsp[cite:@MCUXpresso2018]
indicates that \(f_{R}\) must be lower than or equal to
\qty{66}{\MHz}, therefore

#+begin_src emacs-lisp :exports none
(format "Fs <= %f Hz" (/ 66e6 (lsh 1 8)))
#+end_src

#+RESULTS:
: Fs <= 257812.500000 Hz

#+NAME: eq:max-fs
\begin{equation}
f_{s} \leq 257\,812.5\;\text{Hz}\;.
\end{equation}
\(f_{R}\) is found by dividing the frequency of ~PLL4_MAIN_CLK~,
\(f_{M}\), by the ~SAI1_CLK_PRED~, \(D_{I_{1}}\), and ~SAI1_CLK_PODF~,
\(D_{I_{2}}\) fields of the ~CCM_CS1CDR~ register:

#+NAME: eq:sai1-2
\begin{equation}
f_{R} = \frac{f_{M}}{D_{I_{1}}D_{I_{2}}}\;.
\end{equation}
\(f_{M}\) is found by dividing \(f_{P}\), the frequency of PLL4, by
the ~POST_DIV_SELECT~, \(D_{p}\), and ~AUDIO _DIV~, \(D_{A}\), registers:

#+NAME: eq:pll4-main
\begin{equation}
f_{M} = \frac{f_{P}}{D_{p}D_{A}}\;.
\end{equation}
\(f_{P}\) is the result of multiplying the iMXRT1062's \qty{24}{\MHz}
clock source, \(f_{XO}\), by the PLL4 divider, \(D_{P}\):

#+NAME: eq:pll4
\begin{equation}
f_{P} = f_{XO}D_{P}\;,
\end{equation}
and \(D_{P}\) is, in turn, the sum of the /PLL loop divider/, the
~DIV_SELECT~ field of the ~CCM_ANALOG_PLL_AUDIO~ register, \(D_{S}\), with
the quotient of ~CCM_ANALOG_PLL_AUDIO_NUM~, \(D_{N}\), the /PLL
fractional loop divider/ numerator register and
~CCM_ANALOG_PLL_AUDIO_DENOM~, \(D_{D}\), the denominator register:

#+NAME: eq:pll4-divider
\begin{equation}
D_{P} = D_{S} + \frac{D_{N}}{D_{D}}\;.
\end{equation}
See cref:fig:imxrt1062-clock for a diagrammatic representation of the
effect of the audio PLL and clock divider registers on the
\qty{24}{\MHz} clock source.

The ~DIV_SELECT~ field has a valid range of \(27 \leq D_{S} \leq 54\),
and \(|D_{N}| < D_{D}\), so \(D_{P}\) describes (in theory) a number in the
following range:

#+NAME: eq:divider-range
\begin{equation}
\left(26 + \frac{1}{D_{D}}\right) \leq D_{P} \leq \left(54 + \frac{D_{D}-1}{D_{D}}\right)\;,
\end{equation}
with \(1 \leq D_{D} \leq 2^{30}\); effectively, \(26 < D_{P} <
55\). MCUXpresso Config Tools, and the iMXRT1062 reference
manual\nbsp[cite:@nxpsemiconductorsIMX2021 §13.3.2.2], indicate,
however, that the output frequency range for PLL4 is:

#+NAME: eq:pll4-range
\begin{equation}
650\,\text{MHz} \leq f_{P} \leq 1\,300\,\text{MHz}\;,
\end{equation}
plus Config Tools contradicts the reference manual and states that
\(D_{N}\) must be a /positive/ 30 bit integer, so:

#+begin_src emacs-lisp :exports none
(let ((DpMin (/ 650e6 24e6))
      (DpMax (/ 1300e6 24e6)))
  (format "%f <= PLL4 divider <= %f" DpMin DpMax))
#+end_src

#+RESULTS:
: 27.083333 <= PLL4 divider <= 54.166667

#+NAME: eq:true-divider-range
\begin{equation}
\left(27 + \frac{1}{12}\right) \leq D_{P} \leq \left(54 + \frac{1}{6}\right).
\end{equation}
Setting extreme (but valid) values for the divisors, we can find the
minimal valid \(f_{s}\):

#+begin_src emacs-lisp :exports none
(let* ((postDivSelect 4)
       (audioDiv 4)
       (pll4Div (* postDivSelect audioDiv))
       (sai1ClkPred 8)
       (sai1ClkPodf 64)
       (sai1Div (* sai1ClkPred sai1ClkPodf))
       (DpMin (/ 650e6 24e6))
       (fsMin (/ (* 24e6 DpMin) (* pll4Div sai1Div (lsh 1 8))))
       (fsMax (/ 66e6 (lsh 1 8))))
  (format "%f Hz <= Fs <= %f Hz" fsMin fsMax))
#+end_src

#+RESULTS:
: 309.944153 Hz <= Fs <= 257812.500000 Hz

#+NAME: eq:fs-range
\begin{equation}
309.9\;\text{Hz} \leq f_{s} \leq 257\,812.5\;\text{Hz}\;.
\end{equation}

*** A General Expression for the Sampling Rate

Bringing all of the above together, the general expression for
achieving a target sampling rate \(\hat{f}_{s}\) is

#+NAME: eq:general-fs
\begin{align}
\hat{f}_{s} &= \frac{f_{R}}{2^{8}} \nonumber \\
  &= \frac{f_{M}}{2^{8}D_{I_{1}}D_{I_{2}}} \nonumber \\
  &= \frac{f_{XO}D_{P}}{2^{8}D_{p}D_{A}D_{I_{1}}D_{I_{2}}} \nonumber \\
  &= \frac{24\times10^{6}}{2^{8}}\frac{D_{S}+\frac{D_{N}}{D_{D}}}{D_{p}D_{A}D_{I_{1}}D_{I_{2}}}\;.
\end{align}
This reckoning alone does not take into account certain constraints on
the system, however, such as cref:eq:pll4-range and the frequency at
the input of \(D_{I_{2}}\) being less than \qty{300}{\MHz} (see
cref:fig:imxrt1062-clock). There are too many free variables to solve
for any one of them, so an iterative approach to finding appropriate
register and field values is necessary.

*** Setting the Sampling Rate
:PROPERTIES:
:CUSTOM_ID: sec:setting-the-sampling-rate
:END:

Say we wish to set a sampling rate of \(f_{s} = 48\;\text{kHz}\); our
target \(f_{R}\), \(\hat{f}_{R}\) equals, as per cref:eq:sai1-1

#+NAME: eq:sai1-clk-root
\begin{equation}
\hat{f}_{R} = 48\,000 \times 2^{8} = 12\,288\,000\;\text{Hz}\;.
\end{equation}
Strategically leaving \(D_{p}\) and \(D_{A}\) set to their default values of
1, values for \(D_{S}\), \(D_{N}\), \(D_{D}\), \(D_{I_{1}}\) and \(D_{I_{2}}\) can be
found:

- \(D_{S} = 29\)
- \(D_{N} = 184\,000\,000\)
- \(D_{D} = 1\,000\,000\,000\)
- \(D_{I_{1}} = 3\)
- \(D_{I_{2}} = 19\)

*** Fine-Tuning the Sampling Rate

Say a set of divider register values has been established and some
manner of fine adjustment is desired, e.g. to compensate for clock
drift. Cref:eq:general-fs can be rewritten to find an expression for
an unknown \(D_{N}\):

#+NAME: eq:unknown-dn
\begin{equation}
D_{N} = D_{D}\left(
  \frac{2^{8}\hat{f}_{s}D_{p}D_{A}D_{I_{1}}D_{I_{2}}}{24 \times 10^{6}} - D_{S}
\right)\;.
\end{equation}
For very large \(D_{D}\) it may be advantageous to divide by the main
oscillator's frequency in \unit{\MHz} instead of \unit{\Hz}; to do so,
multiply the contents of the parenthesis in cref:eq:unknown-dn by one
million and divide the outside by one million to compensate:

#+NAME: eq:unknown-dn-2
\begin{equation}
D_{N} = \frac{D_{D}}{1 \times 10^{6}}\left(
  \frac{2^{8}\hat{f}_{s}D_{p}D_{A}D_{I_{1}}D_{I_{2}}}{24} - 1 \times 10^{6}D_{S}
\right)\;.
\end{equation}

*** Media Clock Recovery

The Teensy's NXP iMXRT1062 MCU also features a dedicated hardware PTP
timer\nbsp[cite:@schleusnerSubMicrosecond2024] thus allowing for effective
media clock recovery via an appropriate algorithm.

* The Ananas Networked Audio System

Ananas is a system for time-sensitive networked audio for supporting
distributed approaches to sound field synthesis. In the sections that
follow we describe the various components of the Ananas system.

** The Audio Server

#+name: fig:server
#+caption: Structural overview of the Ananas audio server.
\begin{figure*}
\centering
\begin{tikzpicture}
\pic{server};
\end{tikzpicture}
\end{figure*}

The Ananas audio server is a C++ library written using the JUCE
framework.[fn:1] On startup, the library initialises a series of
threads for handling audio transmission, reading PTP timestamps and
listening for connected clients, amongst other tasks. The audio
transmission part of the server is illustrated in cref:fig:server. The
server receives a collection of input channels, either monophonic WFS
sources or ambisonics channel numbering (ACN) encoded audio channels,
and writes these to an intermediate first-in-first-out (FIFO)
buffer. When the FIFO contains enough samples to fill an outgoing
audio packet, the sender thread is notified and reads from the FIFO to
fill a packet for transmission. The sender thread delivers the packet
to a UDP multicast socket and transmits it to the network.

** The Ananas Audio Protocol

Being first and foremost concerned with the transmission of audio
data, at the heart of the Ananas system is the Ananas Audio Protocol
(AAP). A UDP multicast-based protocol, using address =224.4.224.4=, AAP
consists of a stream of sequence numbered, timestamped packets. The
structure of an AAP packet is given in cref:fig:audio-packet. It was
found that, particularly under high-bandwidth conditions, packets
sporadically arrive out of order, hence the inclusion of the sequence
number, which is used at the receiving side to ensure the integrity of
the packet stream. For timestamping, the server reads a PTP follow-up
packet, adds a small reproduction offset (for packets of 16 frames it
was found that an offset of \(1/70\) s was most appropriate) and
writes the timestamp to the outgoing packet; successive packets are
then updated with the expected inter-packet interval, e.g. for 16
frames at \qty{48}{\kHz} this is \(333\,333\frac{1}{3}\) ns.

Completing the packet header are the number of channels and number of
frames in the packet, used at the receiving side for decoding the
byte-encoded audio data that follows. At 16 frames per packet it is
possible to transmit up to 44 channels of 16-bit audio while
respecting ethernet's 1500 byte /maximum transmissible unit/.

#+name: fig:audio-packet
#+caption: Structure of an Ananas audio packet.
\begin{figure}[t]
\centering
\begin{bytefield}[bitwidth=.55cm,bitheight=.55cm]{16}
  \bitheader{0-15} \\
  \bitbox{2}{\footnotesize{Seq. num.}} & \bitbox{8}{Timestamp} & \bitbox{1}{\tiny{Num. channels}} & \bitbox{2}{\footnotesize{Num. frames}} & \bitbox[lrt]{3}{} \\
  \wordbox[lr]{1}{Audio} \\
  \skippedwords \\
  \wordbox[lrb]{1}{} \\
\end{bytefield}
\end{figure}

#+print_bibliography:

* Local Variables                                                  :noexport:

#+begin_example
Local Variables:
org-latex-classes: (("is2-2026" "\\documentclass[conference]{IEEEtran}
  [NO-DEFAULT-PACKAGES]"
  ("\\section{%s}" . "\\section*{%s}")
  ("\\subsection{%s}" . "\\subsection*{%s}")
  ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
  ("\\paragraph{%s}" . "\\paragraph*{%s}")
  ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
End:
#+end_example

* Footnotes
[fn:2] \url{https://sonobus.net}

[fn:1] JUCE v8.0.6 \url{https://juce.com}. 
