#+title: DDSP for the Internet of Sounds
#+subtitle: Tutorial proposal for the 2025 IEEE International Symposium on the Internet of Sounds
#+author: Thomas Rushton
#+date: 1 July 2025

#+options: toc:nil num:2

#+export_file_name: out/proposal
#+cite_export: biblatex
#+latex_class: proposal
#+latex_header: \RequirePackage[]{proposalIS2}
#+latex_compiler: xelatex

* Latex Setup                                                      :noexport:
:PROPERTIES:
:HEADER-ARGS: :tangle out/proposalIS2.sty :results silent
:END:

** Basics

#+begin_src latex
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{proposalIS2}
#+end_src

** Packages

Hm. Looks like these packages come from the example [[https://www.latextemplates.com/template/arsclassica-article][here]].

#+begin_src latex
\RequirePackage{subfig}
\RequirePackage[
  subfig,
  beramono,
  eulermath,
  pdfspacing
]{classicthesis}
\RequirePackage{arsclassica}
\RequirePackage{hyperref}
\RequirePackage{fontspec}
\RequirePackage{enumitem} % Required for manipulating the whitespace between and within lists
\RequirePackage{subfig} % Required for creating figures with multiple parts (subfigures)
\RequirePackage{amsmath,amssymb,amsthm} % For including math equations, theorems, symbols, etc
\RequirePackage{varioref} % More descriptive referencing
\RequirePackage{cleveref}
#+end_src

** Typography

Reduce the default font size by half a point.

#+begin_src latex
\KOMAoptions{fontsize=10pt}
#+end_src

Reduce the size of the date.

#+begin_src latex
\setkomafont{date}{\normalsize}
#+end_src

Use Minion for both main and "sans" fonts.

#+begin_src latex
\setmainfont[Mapping={tex-text}, 
  Numbers={OldStyle},
  Ligatures={Common},
  %% Extension=.otf,
  %% UprightFont=*-Regular,
  %% ItalicFont= *-It,
  %% BoldFont= *-Bold,
  %% BoldItalicFont = *-BoldIt
]{MinionPro-Regular}

\setsansfont[Mapping=tex-text,
  Ligatures={Common},
  Numbers={OldStyle},
  %% Extension=.otf,
  %% UprightFont=MyriadPro-Regular,
  %% ItalicFont=MyriadPro-CondIt,
  %% BoldFont=MyriadPro-Semibold,
  %% BoldItalicFont=MyriadPro-SemiboldIt,
]{MinionPro-Regular}
#+end_src

Scale Iosevka to more-or-less match Minion.

#+begin_src latex
\setmonofont[Mapping=tex-text,Scale=0.9]{Iosevka Comfy Motion}
#+end_src

** Bibliography

#+begin_src latex
\PassOptionsToPackage{%
  %backend=biber,bibencoding=utf8, %instead of bibtex
%   backend=bibtex8,bibencoding=ascii,%
  language=auto,
  style=numeric-comp,
  %style=authoryear-comp, % Author 1999, 2010
  %bibstyle=authoryear,dashed=false, % dashed: substitute rep. author with ---
  % sorting=nyt, % name, year, title
  sorting=none,
  maxbibnames=10, % default: 3, et al.
  natbib=true, % natbib compatibility mode (\citep and \citet still work)
  url=false,
  doi=false,
  isbn=false,
  giveninits=true,
}{biblatex}
#+end_src

#+begin_src latex :tangle out/biblatex.cfg
\AtEveryBibitem{
  \clearfield{eventtitle}
  %% \clearfield{pages}
}
#+end_src

* Presenter

- Name: Thomas Rushton
- Position: PhD Student
- Affiliation: Inria ([[https://team.inria.fr/emeraude/][Emeraude team]]), INSA Lyon
- Address: Laboratoire CITI, 6 av. des Arts, 69100 Villeurbanne, France
- Email: [[mailto:thomas.rushton@inria.fr][thomas.rushton@inria.fr]]
  
* Abstract

This tutorial introduces the concept of *differentiable digital signal
processing* (DDSP) [cite:@hayesReview2024] --- the creation of signal
processing algorithms incorporating the principles of differentiable
programming --- to the Internet of Sounds community. Differentiable
programming is the backbone of contemporary approaches to mathematical
optimisation and machine learning, and DDSP is its application to the
audio domain. With audio researchers and practitioners in mind, the
session will explore DDSP in the context of Faust, an audio
domain-specific programming language with established support for
programming embedded computing platforms [cite:@orlareyFAUST2009;
@michonReal2019; @michonFaust2020; @michonEmbedded2020]. Participants
will be assisted in the design and of a DDSP-based parameter
optimisation algorithm, and shown how they can deploy their algorithm
for use in a real time, embedded context.

[MOVE REFS TO MOTIVATION]

* Motivation

** Objectives

By the end of the tutorial, participants will have gained the
following competences:

- Understanding of DDSP, its principles and applications.
- Knowledge of the Faust language, its syntax and ecosystem, and how
  it can be used to create cross-platform signal processing
  algorithms.
- Familiarity with the process of deploying Faust code for use on an
  embedded platform; awareness of the capabilities and limitations of
  embedded audio devices for performing real-time DDSP.
- An appreciation for the trade-offs in terms of performance, latency,
  and feasibility associated with time-domain versus frequency-domain
  optimisation approaches.
  
* Detailed Outline

* Target Audience

This tutorial targets researchers, engineers, audio developers, and
may be of interest to creative individuals in the computer music
domain. Participants should ideally posses:

- Some experience of audio programming; previous exposure to
  functional paradigm languages or experience with Faust may be
  helpful to those in attendance.
- An understanding of basic DSP concepts; filters, delays, time-domain
  vs. frequency-domain processing, etc.
- Some knowledge of the mathematical concepts to be applied; ordinary
  and partial differential equations, loss functions, etc.
- An interest in deploying real-time audio systems in an embedded
  context; some familiarity with working with devices such as Arduino,
  Bela, Teensy, ESP32, etc.

* Presenter Information

* History

* Technical Requirements

#+print_bibliography:

* Local Variables                                                  :noexport:

# Local Variables:
# org-latex-classes: (("proposal" "\\documentclass[
# a4paper,oneside,headinclude,footinclude,BCOR=5mm,
# numbers=noenddot,cleardoublepage=empty,tablecaptionabove
# ]{scrartcl}
# [NO-DEFAULT-PACKAGES]"
# ("\\section{%s}" . "\\section*{%s}")
# ("\\subsection{%s}" . "\\subsection*{%s}")
# ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
# ("\\paragraph{%s}" . "\\paragraph*{%s}")
# ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# End:

#  LocalWords:  Teensy DDSP
