#+title: DDSP for the Internet of Sounds
#+subtitle: Tutorial proposal for the 2025 IEEE International Symposium on the Internet of Sounds
#+author: Thomas Rushton
#+date: 1 July 2025

#+options: toc:nil num:2

#+export_file_name: out/proposal
#+cite_export: biblatex
#+latex_class: proposal
#+latex_header: \RequirePackage[]{proposalIS2}
#+latex_compiler: xelatex

* Latex Setup                                                      :noexport:
:PROPERTIES:
:HEADER-ARGS: :tangle out/proposalIS2.sty :results silent
:END:

** Basics

#+begin_src latex
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{proposalIS2}
#+end_src

** Packages

Hm. Looks like these packages come from the example [[https://www.latextemplates.com/template/arsclassica-article][here]].

#+begin_src latex
\RequirePackage{subfig}
\RequirePackage[
  subfig,
  beramono,
  eulermath,
  pdfspacing
]{classicthesis}
\RequirePackage{arsclassica}
\RequirePackage{hyperref}
\RequirePackage{fontspec}
\RequirePackage{enumitem} % Required for manipulating the whitespace between and within lists
\RequirePackage{subfig} % Required for creating figures with multiple parts (subfigures)
\RequirePackage{amsmath,amssymb,amsthm} % For including math equations, theorems, symbols, etc
\RequirePackage{varioref} % More descriptive referencing
\RequirePackage{cleveref}
#+end_src

** Typography

Reduce the default font size by half a point.

#+begin_src latex
\KOMAoptions{fontsize=10pt}
#+end_src

Reduce the size of the date.

#+begin_src latex
\setkomafont{date}{\normalsize}
#+end_src

Use Minion for both main and "sans" fonts.

#+begin_src latex
\setmainfont[Mapping={tex-text}, 
  Numbers={OldStyle},
  Ligatures={Common},
  %% Extension=.otf,
  %% UprightFont=*-Regular,
  %% ItalicFont= *-It,
  %% BoldFont= *-Bold,
  %% BoldItalicFont = *-BoldIt
]{MinionPro-Regular}

\setsansfont[Mapping=tex-text,
  Ligatures={Common},
  Numbers={OldStyle},
  %% Extension=.otf,
  %% UprightFont=MyriadPro-Regular,
  %% ItalicFont=MyriadPro-CondIt,
  %% BoldFont=MyriadPro-Semibold,
  %% BoldItalicFont=MyriadPro-SemiboldIt,
]{MinionPro-Regular}
#+end_src

Scale Iosevka to more-or-less match Minion.

#+begin_src latex
\setmonofont[Mapping=tex-text,Scale=0.9]{Iosevka Comfy Motion}
#+end_src

** Bibliography

#+begin_src latex
\PassOptionsToPackage{%
  %backend=biber,bibencoding=utf8, %instead of bibtex
%   backend=bibtex8,bibencoding=ascii,%
  language=auto,
  style=numeric-comp,
  %style=authoryear-comp, % Author 1999, 2010
  %bibstyle=authoryear,dashed=false, % dashed: substitute rep. author with ---
  % sorting=nyt, % name, year, title
  sorting=none,
  maxbibnames=10, % default: 3, et al.
  natbib=true, % natbib compatibility mode (\citep and \citet still work)
  url=false,
  doi=false,
  isbn=false,
  giveninits=true,
}{biblatex}
#+end_src

#+begin_src latex :tangle out/biblatex.cfg
\AtEveryBibitem{
  \clearfield{eventtitle}
  %% \clearfield{pages}
}
#+end_src

* Presenter

- Name: Thomas Rushton
- Position: PhD Student
- Affiliation: Inria ([[https://team.inria.fr/emeraude/][Emeraude team]]), INSA Lyon
- Address: Laboratoire CITI, 6 av. des Arts, 69100 Villeurbanne, France
- Email: [[mailto:thomas.rushton@inria.fr][thomas.rushton@inria.fr]]
  
* Abstract

This tutorial introduces the concept of *differentiable digital signal
processing* --- the creation of signal processing algorithms
incorporating the principles of differentiable programming --- to the
Internet of Sounds community. Differentiable programming, enabled by
*automatic differentiation*, is the backbone of contemporary
approaches to mathematical optimisation and machine learning, and DDSP
is its application to the audio domain. With audio researchers and
practitioners in mind, the session will explore DDSP in the context of
Faust, an audio domain-specific programming language with established
support for programming embedded computing platforms. Participants
will be assisted in the design and of a DDSP-based parameter
optimisation algorithm, and shown how they can deploy their algorithm
for use in a real time, embedded context.

* Motivation

Mathematical optimisation approaches, particularly those pertaining to
machine learning, are of particular interest to researchers at the
present time. Gradient-based optimisation has emerged, for a wide
variety of optimisation problems, to be the preferred approach, and
the field of differentiable programming, based upon the principle of
automatic differentiation\nbsp[cite:@rallArithmetic1986;
@baydinAutomatic2018], has been paid considerable attention, forming
the mathematical basis for ubiquitous machine learning frameworks such
as PyTorch, TensorFlow, and JAX.

A wide variety of audio-specific applications of differentiable
programming exist, from filter optimisation, parameter-matching, and
acoustic control, to timbre transfer and neural audio synthesis. Being
instances of /automatic differentiation/ (autodiff) applied in a DSP
context, these constitute examples of /differentiable digital signal
processing/ (DDSP)\nbsp[cite:@hayesReview2024]. Imperative programming
languages, and established autodiff frameworks may, however, obscure
the purpose and workings of DSP systems and the mechanisms behind the
underlying processes of mathematical optimisation.

With the aim of shedding light on these matters, in this tutorial,
participants will be shown first how to describe DSP algorithms in
Faust, a functional paradigm, audio domain specific programming
language, based on an intuitive /block diagram
algebra/\nbsp[cite:@orlareySyntactical2004; @orlareyFAUST2009], then how to
perform derivative transformations on their code to produce
/differentiable signal processors/ [cite:@rushtonDifferentiable2024],
taking in an exploration of the underlying principles of
autodiff. Faust is renowned for its compilation support for a variety
of embedded devices of the /Internet of Sounds/
kind\nbsp[cite:@michonReal2019; @michonFaust2020; @michonEmbedded2020],
and participants will be guided through the process of deploying their
DDSP algorithms to an embedded platform.

In a most basic form, a participant may run an isolated DDSP
algorithm, comparing some known ground truth signal, generated on
their device, with one produced by their differentiable processor;
they may well be able to find an optimal parameter state, for an IIR
filter for example, via basic time-domain loss computation. More
advanced participants may aim to receive arbitrary or /unknown/ audio
signals over an ethernet connection, and perform frequency-domain loss
computation to find the optimal parameter state. Other participants
may wish to explore the side-effects of the optimisation process ---
the output of a loss function in a DDSP context is, in effect, an
audio signal in its own right; finding algorithms that do not optimise
well, and /sonifying/ the result, may give rise to creative
opportunities, or simply clues as to the nature of the difficulty of a
given optimisation scenario.

** Objectives

By the end of the tutorial, participants will have gained the
following insights:

- Understanding of DDSP, its principles and applications.
- Knowledge of the Faust language, its syntax and ecosystem, and how
  it can be used to create cross-platform signal processing
  algorithms.
- Familiarity with the process of deploying Faust code for use on an
  embedded platform; awareness of the capabilities and limitations of
  embedded audio devices for performing real-time DDSP.
- An appreciation for the trade-offs in terms of performance, latency,
  and feasibility associated with time-domain versus frequency-domain
  optimisation approaches.
  
* Detailed Outline

Total duration: 180 minutes

* Target Audience

This tutorial targets researchers, engineers, audio developers, and
may be of interest to creative individuals in the computer music
domain. Participants should ideally posses:

- Some experience of audio programming; previous exposure to
  functional paradigm languages or experience with Faust may be
  helpful to those in attendance.
- An understanding of basic DSP concepts; filters, delays, time-domain
  vs. frequency-domain processing, etc.
- Some knowledge of the mathematical concepts to be applied; ordinary
  and partial differential equations, loss functions, etc.
- An interest in deploying real-time audio systems in an embedded
  context; some familiarity with working with devices such as Arduino,
  Bela, Teensy, ESP32, etc.

* Presenter Information

*Thomas Rushton* is a PhD candidate at INSA Lyon, and a member of the
Emeraude (embedded, programmable audio systems) research team of the
French national institute Inria. Originally from the UK, he received
his bachelor's degree in Music Technology from the University of
Edinburgh in 2009, and following a stint in industry, a masters degree
in /Sound and Music Computing/ from Aalborg University, Copenhagen. He
is now working toward a PhD under the title /"Enabling Distributed
Spatial Audio"/. Thomas was a Google Summer of Code contributor to the
Faust project in 2023, adding automatic differentiation capabilities
to the Faust compiler, work which led directly to the implementation
of autodiff and DDSP in the Faust language. He has presented his work
on sonification, distributed spatial audio, and DDSP at a variety of
international conferences, and delivered a half-day Faust workshop at
CCRMA at Stanford University in late 2024. When not thinking about
networked audio or partial derivatives, Thomas may be found cycling in
the Monts du Lyonnais.

* History

This tutorial has not been presented previously, however the
theoretical and technical basis for it was demonstrated during a
presentation at the 2024 International Faust Conference[fn:3] to an
audience of thirty-or-so attendees.

* Technical Requirements

- Projector/screen for slides and code demonstrations.
- Internet connection for accessing the Faust Web IDE.
- Power outlets for participant laptop computers.
- Participants should have a modern web browser installed, for use of
  the Faust Web IDE, or, alternatively a local installation[fn:1] of the
  Faust compiler.
- I will be able to bring up to eight Teensy development boards, with
  ethernet and audio add-ons. Interested participants can assist by
  bringing their own audio-enabled (and preferably ethernet-enabled)
  development boards or single-board computers; supported devices
  (including Teensy, Daisy, Raspberry Pi, Bela, etc.)  may be found
  amongst the ~faust2[...]~ tools listed on the Faust documentation
  website.[fn:2]

#+print_bibliography:

* Footnotes
[fn:3] https://ifc24.soundmit.com/en 

[fn:1] https://faust.grame.fr/downloads/

[fn:2] https://faustdoc.grame.fr/manual/tools/

* Local Variables                                                  :noexport:

# Local Variables:
# org-latex-classes: (("proposal" "\\documentclass[
# a4paper,oneside,headinclude,footinclude,BCOR=5mm,
# numbers=noenddot,cleardoublepage=empty,tablecaptionabove
# ]{scrartcl}
# [NO-DEFAULT-PACKAGES]"
# ("\\section{%s}" . "\\section*{%s}")
# ("\\subsection{%s}" . "\\subsection*{%s}")
# ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
# ("\\paragraph{%s}" . "\\paragraph*{%s}")
# ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# End:

# LocalWords: Teensy DDSP INSA Inria Emeraude Rushton WFS JackTrip
# LocalWords: autodiff "Monts du Lyonnais" DSP ethernet add-ons CCRMA
# LocalWords: sonification sonifying JAX IIR
