#+title: A Sample-Synchronous Distributed Audio System for Spatial and Immersive Applications
#+author: Thomas Albert Rushton

#+options: toc:nil num:4 h:4
#+export_file_name: out/thesis
#+latex_class: thesis
#+cite_export: biblatex
#+latex_header_extra: \RequirePackage[]{./out/thesis}

#+include: "frontmatter.tex" src latex

* About                                                            :noexport:

Org file describing my PhD thesis.

* LaTeX Setup                                                      :noexport:
:PROPERTIES:
:header-args: :tangle out/thesis.sty :results silent :noeval
:END:

** Provide the package

#+begin_src latex
\ProvidesPackage{thesis}
#+end_src

** Packages

*** Geometry

#+begin_src latex
\RequirePackage[
  a4paper,
  left=3cm,
  right=3cm,
  top=3cm,
  bottom=3cm
]{geometry}
#+end_src

*** Headers/footers

#+begin_src latex
\RequirePackage{fancyhdr}
#+end_src

*** Per-chapter tables of contents

#+begin_src latex
\RequirePackage{minitoc}
#+end_src

Number minitoc sections as deep as ~\subsubsection~

#+begin_src latex
\setcounter{minitocdepth}{3}
#+end_src

*** Graphics

#+begin_src latex
\RequirePackage[dvipsnames]{xcolor}
\RequirePackage{graphicx}
#+end_src

*** Colours

#+begin_src latex
\definecolor{tabED}{rgb}{0.90, 0.87, 0.93}
\definecolor{txtED}{rgb}{0.60, 0.28, 0.02}
\definecolor{siteED}{rgb}{0.04, 0.27, 0.47}
#+end_src

*** Typography

The main serif typeface.

#+begin_src latex
\RequirePackage[cmintegrals,cmbraces]{newtxmath}
\RequirePackage{ebgaramond-maths}
\RequirePackage[T1]{fontenc}
#+end_src

A nicer sans-serif typeface.

#+begin_src latex
\RequirePackage{helvet}
#+end_src

A nicer monospaced typeface.

#+begin_src latex
\RequirePackage{inconsolata}
#+end_src

Just all-round better typography.

#+begin_src latex
\RequirePackage{microtype}
#+end_src

Fancy characters (typically) at the beginning of chapters.

#+begin_src latex
\RequirePackage{lettrine}
#+end_src

**** Quotes

#+begin_src latex
\makeatletter
\newenvironment{chapquote}[2][2em]
{\setlength{\@tempdima}{#1}%
  \def\chapquote@author{#2}%
  \parshape 1 \@tempdima \dimexpr\textwidth-2\@tempdima\relax%
\itshape}
{\par\normalfont\hfill--\ \chapquote@author\hspace*{\@tempdima}\par\bigskip}
\makeatother
#+end_src

*** Tables

#+begin_src latex
\RequirePackage{booktabs}
#+end_src

*** Maths

#+begin_src latex
\RequirePackage{amsmath}
\RequirePackage{amssymb}
\RequirePackage{amsfonts}
#+end_src

*** Units

#+begin_src latex
\RequirePackage{siunitx}
\sisetup{
  mode=match,
  per-mode=symbol
}
#+end_src

*** References

#+begin_src latex
\RequirePackage{hyperref}
\hypersetup{
  unicode,
  colorlinks,
  citecolor=black,
  filecolor=black,
  linkcolor=black,
  urlcolor=black,
  bookmarksnumbered,
  pdfstartview=XYZ
}
\RequirePackage[noabbrev]{cleveref}
#+end_src

*** Figures

#+begin_src latex
\RequirePackage{tikz}
\usetikzlibrary{positioning, arrows.meta}
#+end_src

*** Automatically include tof in contents

#+begin_src latex
%% \RequirePackage{tocbibind}
#+end_src

*** Algorithms

#+begin_src latex
\RequirePackage[ruled, vlined, linesnumbered]{algorithm2e}
\crefname{algocf}{algorithm}{algorithms}
\Crefname{algocf}{Algorithm}{Algorithms}
#+end_src

** Figures

*** PTP

#+begin_src latex
\tikzset{
  role/.style={align=center, draw, inner sep=1mm, minimum height=1cm, rounded corners=.5mm},
  authorityMsg/.style={midway, above=-1mm, rotate=-13},
  subscriberMsg/.style={midway, above=-1mm, rotate=13},
  ptp/.pic={
    \node (auth) [role] at (0, 0) {Clock\\authority};
    \draw [-{Stealth}] (auth.south) -- +(0, -6.5);
    \node (sub) [role, right = 2cm of auth] {Clock\\subscriber};
    \draw [-{Stealth}] (sub.south) -- +(0, -6.5);
    
    \node (t1) [below left=2mm and -8mm of auth] {\(t_{1}\)};
    
    \draw [-{Stealth}] ([yshift=-5.5mm]auth.south) -- ([yshift=-13.5mm]sub.south) node [authorityMsg] {\scriptsize{Sync}};
    \draw [-{Stealth}] ([yshift=-10.5mm]auth.south) -- ([yshift=-18.5mm]sub.south) node [authorityMsg] {\scriptsize{FollowUp [\(t_{1}\)]}};

    \node (t2) [below right=11mm and -8mm of sub] {\(t_{2}\)};

    \node (t3) [below right=21.5mm and -8mm of sub] {\(t_{3}\)};

    \draw [-{Stealth}] ([yshift=-24mm]sub.south) -- ([yshift=-32mm]auth.south) node [subscriberMsg] {\scriptsize{DelayReq}};

    \node (t4) [below left=29mm and -8mm of auth] {\(t_{4}\)};

    \draw [-{Stealth}] ([yshift=-36mm]auth.south) -- ([yshift=-44mm]sub.south) node [authorityMsg] {\scriptsize{DelayResp [\(t_{4}\)]}};

    \node (t11) [below left=43mm and -8mm of auth] {\(t'_{1}\)};
    
    \draw [-{Stealth}] ([yshift=-47mm]auth.south) -- ([yshift=-55mm]sub.south) node [authorityMsg] {\scriptsize{Sync}};
    \draw [-{Stealth}] ([yshift=-52mm]auth.south) -- ([yshift=-60mm]sub.south) node [authorityMsg] {\scriptsize{FollowUp [\(t'_{1}\)]}};

    \node (t21) [below right=52mm and -8mm of sub] {\(t'_{2}\)};
  }
}
#+end_src


* Acknowledgements
:PROPERTIES:
:UNNUMBERED: notoc
:END:

Unlike many of my doctoral peers, I have had the privilege of being
able to develop the work presented in this thesis for a full four
years; I began my doctorate with an internship, a master's thesis, and
a conference publication on the topic already under my belt. For this
I have my thesis co-director, Romain Michon, to thank, as well as
Stefania Serafin, who also co-supervised my master's thesis, for
inviting Romain to Aalborg University, Copenhagen twice a year to give
workshops on Faust, digitial musical instrument development, and
physical modelling.

For welcoming me as an intern and later as a /doctorant/, I must thank
Inria, the research institute that it has been an honour to be a part
of since 2023. INSA Lyon, too, for having me as a PhD student, the CITI
laboratory more specifically for being my home from home, and my
colleagues and friends there.

Beyond that, the gratitude I wish to express is more personal in
nature than it is scholarly or professional. Romain and Tanguy, my
thesis co-directors, have shown me great support and also given me the
freedom to explore my ideas, including some entirely adjacent to my
main area of research. My Emeraude teammates, past and present: Pierre
Cochard, Maxime Popoff, Orégane Desrentes, Yann Orlarey, Stéphane
Letz, Romain Bouarah, Romain Fontaine, Bastien Barbe, Florian
Rascoussier, Louis Ledoux, Benjamin Quiédeville, Anastasia Volkova,
Florent de Dinechin, Théo Cantaloube, Clemens Wegener. Other doctoral
students from other teams (/on est tous en la même galère/): Alix
Jeannerot, Guillaume Marthe, Aurélien Delarge, Makhloud Mohamed El
Mehdi, Khiem Huynh, Antoine Bonneau, Julien. Linda Soumari, Cecilia
Navarro and Anouchka Ronceray for tolerating my slowly-improving
French. Djurdjura Mehrad, Élise Denoyelle, Stéphanie Wolska and
Morgane Le Prince. Frédéric Le Mouël, Leonardo Cardoso and Jens
Ahrens; Cristoff Ressi, Shawn Silverman, and Jean-Michel Friedt.

Others, beyond the confines of the lab: Kimberly Hoole, Irène Hontang,
Myriam Boussaboua, Cristina Rottondi, Tomas Poloniecki, Julie Darnat
and Ghis, Alice Aniello, Matti Gardner, Kate Fox, Anna Percy, Judy
Knowles, Matt Rushton, Sally Rushton, Sally Catmull, Ani Cammack, Dave
Rushton, Andreas Friberg, Louise Smith, Greg Chick, Anca Diana Axinia,
Francesco Ganis, Razvan Paisa, Scott Naylor, Mike Croft, Alex Calgaro,
Laura Armstrong and Mahmoud Nadda.

I owe you all an enormous debt of gratitude.

Tommy

* Abstract
:PROPERTIES:
:UNNUMBERED: notoc
:END:

#+begin_abstract
This is what my work is about
#+end_abstract

* Introduction
:PROPERTIES:
:UNNUMBERED: t
:CUSTOM_ID: sec:intro
:END:

Hi there; let's go.

* Networked Audio
#+latex: \minitoc
#+latex: \newpage

\lettrine{A}{udio transmission} over packet-switched networks has
become the /de facto/ standard for a variety of applications over the
past three decades. Replacing the previous generation of cumbersome,
point-to-point installations, it was digital telephony and
videoconferencing that first embraced audio (and video) over the
internet protocol (IP) suite\nbsp[cite:@hardmanReliable1995;
@turlettiINRIA1994] and the broadcast industry that pioneered audio
over ethernet\nbsp[cite:@bakkerIntroduction2014].

Academic research on networked audio began with the SoundWIRE
project\nbsp[cite:@chafeSimplified2000] from which eventually emerged the
JackTrip protocol\nbsp[cite:@caceresJackTrip2010; @caceresJackTrip2009c].

** Computer Networking



*** Ethernet
Ethernet is a thing\nbsp[cite:@metcalfeEthernet1976]

*** WiFi

** The Internet Protocol Suite and the OSI Model

** Network Protocols

*** User Datagram Protocol

*** Internet Group Management Protocol

** Audio Over Computer Networks

*** JackTrip

*** NetJack

*** Audio Over OSC

*** Audio Video Bridging

*** AES67

*** Dante

*** NetJUCE

** The Need for a New Protocol

* Developing Digital Audio Systems
#+latex: \minitoc
#+latex: \newpage

** Embedded Audio Systems

*** Embedded Linux Systems

**** Raspberry Pi

**** Bela

**** Elk

*** Microcontroller Development Boards

**** ESP32

**** STM32

**** Teensy

**** PlatformIO

*** Field Programmable Gate Arrays

**** The SyFaLa Toolchain

** The Faust Programming Language

** Audio Plugins

*** Jules's Utility Class Extensions

*** The Clever Audio Plugin Format

* Time Exchange

\begin{chapquote}{Douglas Adams, \emph{The Hitchhiker's Guide to the Galaxy}}
Time is an illusion; lunchtime doubly so.
\end{chapquote}

#+begin_chapquote :by "Douglas Adams" :from "The Hitchhiker's Guide to the Galaxy"
Time is an illusion; lunchtime doubly so.
#+end_chapquote

#+latex: \minitoc
#+latex: \newpage

\lettrine{C}{onsider} a tuning fork, a steel, two-pronged resonator
which, when struck, vibrates at a reliable frequency. Just how
reliable is this frequency when all is said and done? Frequency, given
in \unit{\hertz}, can be said to describe the number of times a given
event occurs in one second. And how is a second defined? In terms of
the duration required for a caesium atom to vibrate a certain number
of times. So, frequency is defined in terms of time, and time in terms
of frequency; it appears that we have a tautology on our
hands. Indeed, this is an inescapable reality by which we are faced
when we wrestle intimately with time, that most illusory of concepts.

Returning to our tuning fork, each time it is struck, the steel from
which it is manufactured will deform ever so slightly. Some of the
physical energy imparted to it by the blow against a hard surface will
be transduced to heat, which changes the physical behaviour of its
material. Strike it on a cold day and it will vibrate more quickly
than on a hot day. And that is not even to mention the device against
which it was calibrated on the day it was manufactured. In short, a
tuning fork designed to produce a reliable \qty{440}{\hertz} frequency
/does not/, /has never/, and /will never/ produce precisely that
frequency. Indeed, given that atomic clocks are /only/ accurate to parts
per trillion,[fn:1] the very idea of the quantity \qty{440}{\hertz} is far
from perfectly-defined.

Time in computer systems is, of course, subject to the same
vagaries. It is in fact something like a tuning fork that describes
the idea of time in the vast majority of digital systems. A crystal
oscillator (XO), is a sliver of piezoelectric quartz mineral or
ceramic, and, like a tuning fork, on receiving some energy (in this
case electrical) as input, vibrates at a more-or-less reliable
frequency. How accurate this frequency is (setting aside the
fallibility of the definition of a second) is typically defined in
/parts-per-million/ (ppm); a XO with a tolerance of 10 ppm can
reasonably be expected to vibrate up to 0.001 % faster or slower than
the frequency to which it is rated. Thus a 10 ppm XO manufactured to
vibrate at \qty{1}{\mega\hertz} my be expected to produce a frequency,
\(f\), in the range

#+NAME: eq:freq-range
\begin{equation}
999\,990 \leq f \leq 1\,000\,010\;.
\end{equation}
If, to the (audio) engineer's eye, those figures suddenly don't look
so reliable after all, that is entirely understandable. What of the
purity, the /truth/ of the audio sampling rate? Indeed, an audio system
governed by a 10 ppm XO, running at a nominal sampling frequency of
\qty{48}{\kilo\hertz} may run as slow as \(f_{s_{1}} = \)
\qty{47999.52}{\hertz} or as fast as \(f_{s_{2}} = \)
\qty{48000.48}{\hertz}. Is this sort of difference perceptible? By way
of context, that difference is analogous to having two A_{4} tuning
forks, one producing a frequency of \qty{439.9956}{\hertz} and another
at \qty{440.0044}{\hertz}, so a difference of less than one hundredth
of a cycle per second (one twentieth of a cent); this falls far, far
below the /just noticeable difference/ threshold for human pitch
perception. The audio engineer notes, however, that the devices
running at \(f_{s_{1}}\) and \(f_{s_{2}}\) will, after one second, be out of
sync by almost the duration of one full audio sample
(\sim\qty{21}{\micro\second} at \qty{48}{\kilo\hertz}); the DSP engineer notes
that the sum two audio signals, \(x_{1}[n]\) and \(x_{2}[n]\), where \(x_{2}[n]
= x_{1}[n-1]\) is a one-zero low-pass filter.

This manner of /clock drift/ is inevitable in digital systems. To ensure
a sample-synchronous platform for spatial audio, it is necessary to
find a means to correct for it.

** Configuring the iMXRT1062 MCU

#+name: fig:imxrt1062-clock
#+caption: iMXRT1062 audio PLL and SAI1 clock divider registers.
\begin{figure}[t]
\centering
\begin{tikzpicture}
  \node [draw] (osc) {OSC 24M};
  \node [draw] (pll4) [right=.75cm of osc] {\(\times \left(D_{S} + \frac{D_{N}}{D_{D}}\right)\)};
  \node (pll4label) [above=0cm of pll4] {\small{PLL4}};
  \node [draw] (dp) [right=.75cm of pll4] {\(D_{p}\)};
  \node [draw] (dA) [right=.5cm of dp] {\(D_{A}\)};
  \node [draw] (dI1) [right=.75cm of dA] {\(D_{I_{1}}\)};
  \node [draw] (dI2) [right=2cm of dI1] {\(D_{I_{2}}\)};
  \node (fR) [right=1.5cm of dI2] {\(f_{R}\)};

  \draw [-{Triangle}] (osc.east) -- (pll4.west) node [above, midway] {\scriptsize{\(f_{XO}\)}};
  \draw [-{Triangle}] (pll4.east) -- (dp.west) node [above, midway] {\scriptsize{\(f_{P}\)}};
  \draw [-{Triangle}] (dp.east) -- (dA.west);
  \draw [-{Triangle}] (dA.east) -- (dI1.west) node [above, midway] {\scriptsize{\(f_{M}\)}};
  \draw [-{Triangle}] (dI1.east) -- (dI2.west) node [above, midway] {\scriptsize{\(\leq 300 \text{MHz}\)}};
  \draw [-{Triangle}] (dI2.east) -- (fR.west) node [above, midway] {\scriptsize{\(\leq 66 \text{MHz}\)}};
\end{tikzpicture}
\end{figure}

Before proceeding to a discussion of /time exchange/ mechanisms, it is
important to deal with how audio timing is configured on our target
hardware platform, the Teensy 4.1 and its NXP iMXRT1062 MCU.

The iMXRT1062 features a dedicated audio phase locked loop (PLL),
PLL4, and a /synchronous audio interface/, SAI1, the latter providing
I^{2}S output. By convention, the output frequency produced by SAI1,
~SAI1_CLK_ROOT~, \(f_{R}\), must be 256 times oversampled with respect
to the target audio sampling rate, \(f_{s}\):

#+NAME: eq:sai1-1
\begin{equation}
f_{R} = 2^{8}f_{s}\;.
\end{equation}

The NXP MCUXpresso Config Tools software\nbsp[cite:@MCUXpresso2018]
indicates that \(f_{R}\) must be lower than or equal to
\qty{66}{\MHz}, therefore

#+begin_src emacs-lisp :exports none
(format "Fs <= %f Hz" (/ 66e6 (lsh 1 8)))
#+end_src

#+RESULTS:
: Fs <= 257812.500000 Hz

#+NAME: eq:max-fs
\begin{equation}
f_{s} \leq 257\,812.5\;\text{Hz}\;.
\end{equation}
\(f_{R}\) is found by dividing the frequency of ~PLL4_MAIN_CLK~,
\(f_{M}\), by the ~SAI1_CLK_PRED~, \(D_{I_{1}}\), and ~SAI1_CLK_PODF~,
\(D_{I_{2}}\) fields of the ~CCM_CS1CDR~ register:

#+NAME: eq:sai1-2
\begin{equation}
f_{R} = \frac{f_{M}}{D_{I_{1}}D_{I_{2}}}\;.
\end{equation}
\(f_{M}\) is found by dividing \(f_{P}\), the frequency of PLL4, by
the ~POST_DIV_SELECT~, \(D_{p}\), and ~AUDIO _DIV~, \(D_{A}\), registers:

#+NAME: eq:pll4-main
\begin{equation}
f_{M} = \frac{f_{P}}{D_{p}D_{A}}\;.
\end{equation}
\(f_{P}\) is the result of multiplying the iMXRT1062's \qty{24}{\MHz}
clock source, \(f_{XO}\), by the PLL4 divider, \(D_{P}\):

#+NAME: eq:pll4
\begin{equation}
f_{P} = f_{XO}D_{P}\;,
\end{equation}
and \(D_{P}\) is, in turn, the sum of the /PLL loop divider/, the
~DIV_SELECT~ field of the ~CCM_ANALOG_PLL~ ~_AUDIO~ register, \(D_{S}\), with
the quotient of ~CCM_ANALOG_PLL_AUDIO_NUM~, \(D_{N}\), the /PLL
fractional loop divider/ numerator register and
~CCM_ANALOG_PLL_AUDIO_DENOM~, \(D_{D}\), the denominator register:

#+NAME: eq:pll4-divider
\begin{equation}
D_{P} = D_{S} + \frac{D_{N}}{D_{D}}\;.
\end{equation}
See cref:fig:imxrt1062-clock for a diagrammatic representation of the
effect of the audio PLL and clock divider registers on the
\qty{24}{\MHz} clock source.

The ~DIV_SELECT~ field has a valid range of \(27 \leq D_{S} \leq 54\),
and \(|D_{N}| < D_{D}\), so \(D_{P}\) describes (in theory) a number in the
following range:

#+NAME: eq:
\begin{equation}
\left(26 + \frac{1}{D_{D}}\right) \leq D_{P} \leq \left(54 + \frac{D_{D}-1}{D_{D}}\right)\;,
\end{equation}
with \(1 \leq D_{D} \leq 2^{30}\); effectively, \(26 < D_{P} <
55\). MCUXpresso Config Tools, and the iMXRT1062 reference
manual\nbsp[cite:@nxpsemiconductorsIMX2021 §13.3.2.2], indicate,
however, that the output frequency range for PLL4 is:

#+NAME: eq:pll4-range
\begin{equation}
650\,\text{MHz} \leq f_{P} \leq 1\,300\,\text{MHz}\;,
\end{equation}
plus Config Tools contradicts the reference manual and states that
\(D_{N}\) must be a /positive/ 30 bit integer, so:

#+begin_src emacs-lisp :exports none
(let ((DpMin (/ 650e6 24e6))
      (DpMax (/ 1300e6 24e6)))
  (format "%f <= PLL4 divider <= %f" DpMin DpMax))
#+end_src

#+RESULTS:
: 27.083333 <= PLL4 divider <= 54.166667

#+NAME: eq:
\begin{equation}
\left(27 + \frac{1}{12}\right) \leq D_{P} \leq \left(54 + \frac{1}{6}\right).
\end{equation}
Setting extreme (but valid) values for the divisors, we can find the
minimal valid \(f_{s}\):

#+begin_src emacs-lisp :exports none
(let* ((postDivSelect 4)
       (audioDiv 4)
       (pll4Div (* postDivSelect audioDiv))
       (sai1ClkPred 8)
       (sai1ClkPodf 64)
       (sai1Div (* sai1ClkPred sai1ClkPodf))
       (DpMin (/ 650e6 24e6))
       (fsMin (/ (* 24e6 DpMin) (* pll4Div sai1Div (lsh 1 8))))
       (fsMax (/ 66e6 (lsh 1 8))))
  (format "%f Hz <= Fs <= %f Hz" fsMin fsMax))
#+end_src

#+RESULTS:
: 309.944153 Hz <= Fs <= 257812.500000 Hz

#+NAME: eq:fs-range
\begin{equation}
309.9\;\text{Hz} \leq f_{s} \leq 257\,812.5\;\text{Hz}\;.
\end{equation}

*** A General Expression for the Sampling Rate

Bringing all of the above together, the general expression for
achieving a target sampling rate \(\hat{f}_{s}\) is

#+NAME: eq:general-fs
\begin{align}
\hat{f}_{s} &= \frac{f_{R}}{2^{8}} \nonumber \\
  &= \frac{f_{M}}{2^{8}D_{I_{1}}D_{I_{2}}} \nonumber \\
  &= \frac{f_{XO}D_{P}}{2^{8}D_{p}D_{A}D_{I_{1}}D_{I_{2}}} \nonumber \\
  &= \frac{24\times10^{6}}{2^{8}}\frac{D_{S}+\frac{D_{N}}{D_{D}}}{D_{p}D_{A}D_{I_{1}}D_{I_{2}}}\;.
\end{align}
This reckoning alone does not take into account certain constraints on
the system, however, such as cref:eq:pll4-range and the frequency at
the input of \(D_{I_{2}}\) being less than \qty{300}{\MHz} (see
cref:fig:imxrt1062-clock). There are too many free variables to solve
for any one of them, so an iterative approach to finding appropriate
register and field values is necessary.

*** Setting the Sampling Rate
:PROPERTIES:
:CUSTOM_ID: sec:setting-the-sampling-rate
:END:

#+name: alg:sampling-rate
#+caption: Algorithm for finding ideal divider register values for a
#+caption: given sampling rate.
\begin{algorithm}
  \tcc{Order of magnitude by which to scale calculations.}
  \(O_{m}= 1 \times 10^{6}\)

  \For{\(D_{S} \leftarrow 27\) \KwTo \(54\)}{
    \(D_{N} = 0\)

    \(D_{D} = O_{m}\)

    \(D_{I_{1}} = 1\)

    \(D_{I_{2}} = 1\)

    \(d_{e} = -1\) \tcc{Initial exact divider}
    \While{\(f_{I_{2}} \leq 300\;\text{MHz}\) and \(D_{I_{1}} < D_{I_{1},MAX}\)}{
      \(+\!+D_{I_{1}}\)
    }
    \While{\(d_{e}/O_{m} \neq D_{S}\)}{
      \(+\!+D_{I_{2}}\)

      \If{\(\hat{f}_{s} > f_{s,MAX}\) and \(D_{I_{1}} < D_{I_{1},MAX}\)}{
        \(+\!+D_{I_{1}}\)

        \(D_{I_{2}} = 1\)

        continue
      }
      \(d_{e} = 2^{8}\hat{f}_{s}D_{I_{1}}D_{I_{2}}/24\)

      \If{\(\lfloor{}d_{e}/O_{m}\rfloor \neq D_{S}\)}{
        \If{\(D_{I_{1}} < D_{I_{1},MAX}\)}{
          \(+\!+D_{I_{1}}\)

          \(D_{I_{2}} = 1\)

          continue
        } \Else {break}
      }

      \(D_{N} = d_{e} - O_{m}D_{S}\)

      \While{\(D_{N} \times 10 < D_{N,MAX}\) and \(D_{D} \times 10 < D_{D,MAX}\)}{
        \(D_{N}\;\ast\!= 10\)

        \(D_{D}\;\ast\!= 10\)
      }

      \If{\(f_{P}\) is valid and \(D_{D} = 1 \times 10^{9}\)}{
        \Return
      } \Else {break}
    }
  }
\end{algorithm}

Say we wish to set a sampling rate of \(f_{s} = 48\;\text{kHz}\); our
target \(f_{R}\), \(\hat{f}_{R}\) equals, as per cref:eq:sai1-1

#+NAME: eq:sai1-clk-root
\begin{equation}
\hat{f}_{R} = 48\,000 \times 2^{8} = 12\,288\,000\;\text{Hz}\;.
\end{equation}
Strategically leaving \(D_{p}\) and \(D_{A}\) set to their default
values of 1, cref:alg:sampling-rate can be used to find values for
\(D_{S}\), \(D_{N}\), \(D_{D}\), \(D_{I_{1}}\) and \(D_{I_{2}}\).

#+begin_src julia :results output :eval never-export :exports results
using Printf, Format

let
    # This will simplify some of the calculations, and should help
    # with getting accurate results, particularly in C++.
    MHz = 1e6
    oscMHz = 24;
    oscHz = oscMHz * MHz
    oversamplingRatio = 1 << 8
    Fs = 48000
    fR = Fs * oversamplingRatio
    # Adjustment to all figures so we can compare integer targets...
    cyclesPerOversample = oscHz/oversamplingRatio
    # Frequency limitaitions
    pll4Min = 650 * MHz
    pll4Max = 1300 * MHz
    sai1PostMaxInputFreq = 300 * MHz
    numMax = (1 << 29) - 1
    denomMax = (1 << 30) - 1

    @printf "Target sample rate:   %s Hz\n" cfmt("%'d", Fs)
    @printf "Target SAI1_CLK_ROOT: %s Hz\n\n" cfmt("%'d", fR)

    @printf "fXO * (DS + DN / DD)/(DA * Dp * DI1 * DI2) = %f Hz\n" fR

    for div in 27:54
        num = 0            # Initial numerator
        denom = 1e6        # Start with millionths
        sai1Pre = 1        # Initial SAI1 pre-divider
        sai1Post = 1       # and post-divider
        divExact = -1.0        

        pllFreq = oscHz * (div + num / denom)

        # Adjust first sai1 divider to get a valid input to the second
        # divider
        while pllFreq / sai1Pre > sai1PostMaxInputFreq && sai1Pre < 8
            sai1Pre += 1
        end

        while floor(divExact / MHz) != div
            # Adjust second sai1 divider to get a value below the target
            while cyclesPerOversample * div / (sai1Pre * sai1Post) > Fs && sai1Post < 64
                sai1Post += 1
            end

            # If target Fs is greater than the current achievable Fs,
            # try another combination of SAI1 dividers.
            if (Fs > ((div + 1)/(sai1Pre * sai1Post)) * cyclesPerOversample
                && sai1Pre < 8)
                sai1Pre += 1
                sai1Post = 1
                continue
            end

            # Divide by the main oscillator's frequency in MHz to get
            # a better-behaved number with which to calculate.
            divExact = Fs * oversamplingRatio * sai1Pre * sai1Post / oscMHz

            # If fractional and integer div don't have the same
            # integer part, something's wrong; try a different SAI1
            # predivider.
            if floor(divExact / MHz) != div
                if sai1Pre < 8
                    sai1Pre += 1
                    sai1Post = 1
                    continue
                else
                    break
                end
            end

            num = floor(divExact - div * MHz)

            # Scale num and denom to take greatest possible advantage
            # of the available numerical resolution.
            while num * 10 < numMax && denom * 10 < denomMax
                num *= 10;
                denom *= 10;
            end

            pll4Freq = oscHz * (div + num/denom)
            
            if pll4Freq > pll4Min && pll4Freq < pll4Max && denom == 1e9
                # Found a match
                @printf "24 MHz * (%d + %d/%d)" div num denom
                @printf "/(1 * 1 * %d * %d)" sai1Pre sai1Post
                @printf " = %f\n" 24e6 * (div + num / denom) / (sai1Pre * sai1Post)
            else
                break
            end
        end
    end
end
#+end_src

#+RESULTS:
#+begin_example
Target sample rate:   48,000 Hz
Target SAI1_CLK_ROOT: 12,288,000 Hz

fXO * (DS + DN / DD)/(DA * Dp * DI1 * DI2) = 12288000.000000 Hz
24 MHz * (29 + 184000000/1000000000)/(1 * 1 * 3 * 19) = 12288000.000000
24 MHz * (32 + 256000000/1000000000)/(1 * 1 * 3 * 21) = 12288000.000000
24 MHz * (35 + 328000000/1000000000)/(1 * 1 * 3 * 23) = 12288000.000000
24 MHz * (43 + 8000000/1000000000)/(1 * 1 * 4 * 21) = 12288000.000000
24 MHz * (45 + 56000000/1000000000)/(1 * 1 * 4 * 22) = 12288000.000000
24 MHz * (46 + 80000000/1000000000)/(1 * 1 * 5 * 18) = 12288000.000000
24 MHz * (47 + 104000000/1000000000)/(1 * 1 * 4 * 23) = 12288000.000000
24 MHz * (49 + 152000000/1000000000)/(1 * 1 * 4 * 24) = 12288000.000000
24 MHz * (50 + 176000000/1000000000)/(1 * 1 * 7 * 14) = 12288000.000000
24 MHz * (51 + 200000000/1000000000)/(1 * 1 * 5 * 20) = 12288000.000000
24 MHz * (52 + 224000000/1000000000)/(1 * 1 * 6 * 17) = 12288000.000000
#+end_example
In practice the first such result can be used yielding the following
values:

- \(D_{S} = 29\)
- \(D_{N} = 184\,000\,000\)
- \(D_{D} = 1\,000\,000\,000\)
- \(D_{I_{1}} = 3\)
- \(D_{I_{2}} = 19\)

*** Fine-tuning the sampling rate

Say a set of divider register values has been established using
cref:alg:sampling-rate, and some manner of fine adjustment is desired,
e.g. to compensate for clock drift. Cref:eq:general-fs can be
rewritten to find an expression for an unknown \(D_{N}\):

#+NAME: eq:unknown-dn
\begin{equation}
D_{N} = D_{D}\left(
  \frac{2^{8}\hat{f}_{s}D_{p}D_{A}D_{I_{1}}D_{I_{2}}}{24 \times 10^{6}} - D_{S}
\right)\;.
\end{equation}
For very large \(D_{D}\) it may be advantageous to divide by the main
oscillator's frequency in \unit{\MHz} instead of \unit{\Hz}; to do so,
multiply the contents of the parenthesis in cref:eq:unknown-dn by one
million and divide the outside by one million to compensate:

#+NAME: eq:unknown-dn-2
\begin{equation}
D_{N} = \frac{D_{D}}{1 \times 10^{6}}\left(
  \frac{2^{8}\hat{f}_{s}D_{p}D_{A}D_{I_{1}}D_{I_{2}}}{24} - 1 \times 10^{6}D_{S}
\right)\;.
\end{equation}

** Network Protocols for Time Exchange

*** Network Time Protocol

*** Precision Time Protocol

#+name: fig:ptp
#+caption: PTP packet flow.
\begin{figure}[t]
\centering
\begin{tikzpicture}
  \pic{ptp};
\end{tikzpicture}
\end{figure}

IEEE 1588 Precision Time Protocol (PTP) is a time exchange mechanism
consisting of the exchange of multicast network packets between a
clock authority and a clock subscriber\nbsp[cite:@leeProceedings2005;
@schleusnerSubMicrosecond2024]. PTP packet flow is illustrated in
cref:fig:ptp. Flow begins with the clock authority sending a /sync/
packet; the subscriber notes the time, \(t_{2}\), at which this packet
arrives. The authority then sends a /follow-up/ packet which is
timestamped, \(t_{1}\), with the time of transmission. With \(t_{1}\)
and \(t_{2}\) in hand, the subscriber sends a /delay request/ packet
and notes the time, \(t_{3}\) of transmission; the authority notes the
time, \(t_{4}\) of reception of this packet and sends it to the
subscriber in a final /delay response/ packet. The above process then
repeats for the next time period, typically a second, beginning with
the receipt time \(t'_{2}\)of the following sync packet and the
receipt of the next follow-up packet containing timestamp
\(t'_{1}\). Once the subscriber has the above timestamp information it
can begin to compute its drift, \(\alpha\), delay, \(\delta\), and
offset, \(\theta\) relative to the authority:

#+NAME: eq:ptp1
\begin{align}
\alpha &= 1 - \frac{t'_{2} - t_{2}}{t'_{1} - t_{1}}\;, \\
\delta &= \frac{(t_{4} - t_{1}) - (t_{3} - t_{2})}{2}\;, \\
\theta &= t_{2} - t_{1} - \delta\;.
\end{align}

Armed with the above figures, the subscriber can feed them into a
proportional integral (PI) controller to yield a number of nanoseconds
for second \(n\) by which it should adjust its internal clock,

#+NAME: eq:ptp-pi
\begin{equation}
a_{n} = \alpha - K_{P}\theta_{n} + K_{I}\sum_{t=0}^{n}\theta\;,
\end{equation}
where \(K_{P}\) and \(K_{I}\) are co-efficients to be applied to the
proportional and integral terms respectively; small co-efficients,
typically \(K_{I} < K_{P} < 1\). The adjustment value \(a_{n}\) can be used to
set, for example, the per-cycle increment of a hardware ethernet timer
register.

** Media Clock Recovery

Time exchange at the level of the ethernet subsystems of distributed
modules does not directly help us achieve audio sampling rate
parity. The time exchange information derived from PTP must be used to
condition the audio clocks of the modules such that sampling rate
parity is achieved; this is a process referred to as /media clock
recovery/\nbsp[cite:@crankshawMedia2021].

In the case of the iMXRT1062 MCU this process is achieved by using the
nanoseconds-per-second PTP-derived adjustment value at second \(n\),
\(a_{n}\), to adjust the sampling rate. For a nominal sampling rate
\(f_{s}\) (e.g. \qty{48}{\kHz}), the sampling rate, \(\hat{f}_{s,n}\) that
"matches" that of the time authority is found simply as

#+NAME: eq:sampling-rate-recovery-1
\begin{equation}
\hat{f}_{s,n} = f_{s}(1 + a_{n})\;.
\end{equation}
For example, if \(a_{n} = -1750\;\text{ns}\), we have

#+begin_src emacs-lisp :exports none
(let* ((fs 48000)
       (a -1750e-9)
       (proportion (+ 1 a))
       (fhats (* fs proportion)))
  (format "%.9f %f" proportion fhats))
#+end_src

#+RESULTS:
: 0.999998250 47999.916000

#+NAME: eq:adjust-example
\begin{align*}
\hat{f}_{s,n} &= f_{s}(1 - 1750 \times 10^{-9}) \\
  &= 48\,000 \times 0.999\,998\,25 \\
  &= 47\,999.916\;\text{Hz}\;.
\end{align*}
Inserting this value into cref:eq:general-fs, the expression for the
audio sampling rate of the iMXRT1062, yields

#+NAME: eq:adjusted-fs
\begin{equation}
47\,999.916 = \frac{24 \times 10^{6}}{2^{8}}\frac{D_{S} + \frac{D_{N,n}}{D_{D}}}{D_{p}D_{A}D_{I_{1}}D_{I_{2}}}\;,
\end{equation}
and rearranging, using cref:eq:unknown-dn-2 to find the appropriate
value for the PLL4 numerator register

#+NAME: eq:adjusted-dn
\begin{equation}
D_{N,n} = \frac{D_{D}}{1 \times 10^{6}}\left(
  \frac{2^{8} \times 47\,999.916 \times D_{p}D_{A}D_{I_{1}}D_{I_{2}}}{24} -
  1 \times 10^{6} D_{S}
\right)\;.
\end{equation}
Using the values derived in cref:sec:setting-the-sampling-rate yields

#+NAME: eq:adjusted-dn-2
\begin{align*}
D_{N,n} &= 1 \times 10^{3}\left(
  \frac{2^{8} \times 47\,999.916 \times 3 \times 19}{24} -
  29 \times 10^{6}
\right) \\
  &= 183\,948\,928\;,
\end{align*}
which can be used as a new value for the ~CCM_ANALOG_PLL_AUDIO_NUM~
register of the iMXRT1062 MCU.

In practice cref:eq:sampling-rate-recovery-1 does not suffice,
however, and some residual parts per billion drift remains (see
cref:fig:drift). The proposed solution is as follows: first, observing
that at a nominal sampling rate of \qty{48}{\kHz} for power of two
audio buffer sizes less than or equal to 128 there will be an integer
number, \(I\), of audio interrupts per second, take a representative
nanoseconds figure, \(t_{S}\), on audio system startup; second, every
\(I\) interrupts, reading the system's PTP timer, taking the
nanoseconds part, \(t_{\text{PTP}}\) and comparing with \(t_{S}\):

#+NAME: eq:audio-ptp-offset
\begin{equation}
\Delta_{n} = t_{\text{PTP}} - t_{S}\;;
\end{equation}
finally, applying another PI controller:

#+NAME: eq:sampling-rate-recovery-2
\begin{equation}
\hat{f}_{s,n} = f_{s}\left(
  1 + a_{n} + K_{P_{\Delta}}\Delta_{n} + K_{I_{\Delta}}\sum_{t=0}^{n}\Delta
\right)\;.
\end{equation}
These additional correction factors ensure reliable media clock
recovery indefinitely.

** Presentation Time Recovery

* Sound Field Synthesis
#+latex: \minitoc
#+latex: \newpage

** Psychoacoustics and Sound Localisation

*** Interaural Level Difference

*** Interaural Time Difference

** General Principles of Sound Field Synthesis

** Periphony

*** Stereo

*** Surround Sound

*** Binaural Reproduction

** Wave Field Synthesis

*** Virtual Sound Sources

*** Focused Sound Sources

*** Plane Waves

** Ambisonics

*** Higher Order Ambisonics

*** Spherical Microphone Arrays

*** Ambisonics Encoding and Decoding
** State of the Art

*** Economic and Financial Considerations

* Contribution 1: A Synchronous, Distributed Audio System
#+latex: \minitoc
#+latex: \newpage

** ???

* Contribution 2: Distributed Spatial Audio Algorithms
#+latex: \minitoc
#+latex: \newpage
** Distributed Wave Field Synthesis
** Distributed Higher Order Ambisonics
* Contribution 3: Protocol and Software Systems
#+latex: \minitoc
#+latex: \newpage
** The Ananas Protocol
*** The Ananas Audio Protocol
*** The Ananas Authority Description Protocol
*** The Ananas Client Description Protocol
** Audio Plugins
* Evaluation
#+latex: \minitoc
#+latex: \newpage
** Case Studies
* Conclusion
#+latex: \minitoc
#+latex: \newpage

This is my conclusion

#+include: "backmatter.tex" src latex

#+print_bibliography:

* Footnotes

[fn:1] Emphasis added because a one part-per-trillion clock will lose
one second on the order of once every thirty-two thousand years.

* Local Variables                                                  :noexport:

- Add the /thesis/ document class.
- Don't output the title; that's handled by =frontmatter.tex=.
- Add some export headline filters (see =.dir-locals.el=). 

#+begin_example
Local Variables:
org-latex-classes: (("thesis" "\\documentclass[a4paper, 12pt, table,
twoside]{book}
[NO-DEFAULT-PACKAGES]"
("\\chapter{%s}" . "\\chapter*{%s}")
("\\section{%s}" . "\\section*{%s}")
("\\subsection{%s}" . "\\subsection*{%s}")
("\\subsubsection{%s}" . "\\subsubsection*{%s}")
("\\paragraph{%s}" . "\\paragraph*{%s}")
("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
org-latex-title-command: nil
org-export-filter-headline-functions: (tar/acks-as-section
tar/abstract-as-section tar/intro-in-toc)
End:

LocalWords: transduced periphony ambisonics microcontroller datagram
#+end_example

