#+title: A Sample-Synchronous Distributed Audio System for Spatial and Immersive Applications
#+author: Thomas Albert Rushton

#+options: toc:nil num:4 h:4
#+export_file_name: out/thesis
#+latex_class: thesis
#+cite_export: biblatex
#+latex_header_extra: \RequirePackage[]{./out/thesis}

#+include: "frontmatter.tex" src latex

* About                                                            :noexport:

Org file describing my PhD thesis.

* LaTeX Setup                                                      :noexport:
:PROPERTIES:
:header-args: :tangle out/thesis.sty :results silent :noeval
:END:

** Provide the package

#+begin_src latex
\ProvidesPackage{thesis}
#+end_src

** Packages

*** Geometry

#+begin_src latex
\RequirePackage[
  a4paper,
  left=3cm,
  right=3cm,
  top=3cm,
  bottom=3cm
]{geometry}
#+end_src

*** Headers/footers

#+begin_src latex
\RequirePackage{fancyhdr}
#+end_src

*** Per-chapter tables of contents

#+begin_src latex
\RequirePackage{minitoc}
#+end_src

Number minitoc sections as deep as ~\subsubsection~

#+begin_src latex
\setcounter{minitocdepth}{3}
#+end_src

*** Graphics

#+begin_src latex
\RequirePackage[dvipsnames]{xcolor}
\RequirePackage{graphicx}
#+end_src

*** Colours

#+begin_src latex
\definecolor{tabED}{rgb}{0.90, 0.87, 0.93}
\definecolor{txtED}{rgb}{0.60, 0.28, 0.02}
\definecolor{siteED}{rgb}{0.04, 0.27, 0.47}
#+end_src

*** Typography

The main serif typeface.

#+begin_src latex
\RequirePackage[cmintegrals,cmbraces]{newtxmath}
\RequirePackage{ebgaramond-maths}
\RequirePackage[T1]{fontenc}
#+end_src

A nicer sans-serif typeface.

#+begin_src latex
\RequirePackage{helvet}
#+end_src

A nicer monospaced typeface.

#+begin_src latex
\RequirePackage{inconsolata}
#+end_src

Just all-round better typography.

#+begin_src latex
\RequirePackage{microtype}
#+end_src

Fancy characters (typically) at the beginning of chapters.

#+begin_src latex
\RequirePackage{lettrine}
#+end_src

**** Quotes

#+begin_src latex
\makeatletter
\newenvironment{chapquote}[2][2em]
{\setlength{\@tempdima}{#1}%
  \def\chapquote@author{#2}%
  \parshape 1 \@tempdima \dimexpr\textwidth-2\@tempdima\relax%
\itshape}
{\par\normalfont\hfill--\ \chapquote@author\hspace*{\@tempdima}\par\bigskip}
\makeatother
#+end_src

*** Tables

#+begin_src latex
\RequirePackage{booktabs}
#+end_src

*** Maths

#+begin_src latex
\RequirePackage{amsmath}
\RequirePackage{amssymb}
\RequirePackage{amsfonts}
#+end_src

*** Units

#+begin_src latex
\RequirePackage{siunitx}
\sisetup{
  mode=match,
  per-mode=symbol
}
#+end_src

*** References

#+begin_src latex
\RequirePackage[noabbrev,capitalise]{cleveref}
\RequirePackage{hyperref}
\hypersetup{
  unicode,
  colorlinks,
  citecolor=black,
  filecolor=black,
  linkcolor=black,
  urlcolor=black,
  bookmarksnumbered,
  pdfstartview=XYZ
}
#+end_src

* Export hooks                                                     :noexport:

** Lettrine at the start of each chapter

Maybe just do this as LaTeX markup... at this stage I can't see it
being useful to export to formats besides LaTeX...

# #+bind: org-export-before-parsing-functions (tar/lettrine-after-h1)
# #+begin_src emacs-lisp :results none
# (defun tar/lettrine-after-h1 (backend)
#   "Add lettrine to first paragraph after each level-1 headline."
#   (when (org-export-derived-backend-p backend 'latex)
#     (org-element-map (org-element-parse-buffer) 'headline
#       (lambda (headline)
#         (when (and (eq (org-element-property :level headline) 1)
#                    (not (org-element-property :UNNUMBERED headline)))
#           (let ((target-para
#                  (cl-loop for child in (org-element-contents
#                                         (car (org-element-contents headline)))
#                           when (eq (org-element-type child) 'paragraph)
#                           return child)))
#             (when target-para
#               (let* ((begin (org-element-property :contents-begin target-para))
#                      (end (org-element-property :contents-end target-para))
#                      (text (buffer-substring begin end))
#                      (first-char (substring text 0 1))
#                      (rest-of-word
#                       (and (string-match "^.\\([a-zA-Z]*\\)" text)
#                            (match-string 1 text)))
#                      (remainder
#                       (substring text (+ 1 (length rest-of-word)))))
#                 (goto-char begin)
#                 (delete-region begin end)
#                 (insert (format "@@latex:\\lettrine{%s}{%s}@@%s"
#                                 first-char
#                                 rest-of-word
#                                 remainder))))))))))
# #+end_src

* Acknowledgements
:PROPERTIES:
:UNNUMBERED: notoc
:END:

Unlike many of my doctoral peers, I have had the privilege of being
able to develop the work presented in this thesis for a full four
years; I began my doctorate with an internship, a master's thesis, and
a conference publication on the topic already under my belt. For this
I have my thesis co-director, Romain Michon, to thank, as well as
Stefania Serafin, who also co-supervised my master's thesis, for
inviting Romain to Aalborg University, Copenhagen twice a year to give
workshops on Faust, digitial musical instrument development, and
physical modelling.

For welcoming me as an intern and later as a /doctorant/, I must thank
Inria, the research institute that it has been an honour to be a part
of since 2023. INSA Lyon, too, for having me as a PhD student, the CITI
laboratory more specifically for being my home from home, and my
colleagues and friends there.

Beyond that, the gratitude I wish to express is more personal in
nature than it is scholarly or professional. Romain and Tanguy, my
thesis co-directors, have shown me great support and also given me the
freedom to explore my ideas, including some entirely adjacent to my
main area of research. My Emeraude teammates, past and present: Pierre
Cochard, Maxime Popoff, Orégane Desrentes, Yann Orlarey, Stéphane
Letz, Romain Bouarah, Romain Fontaine, Bastien Barbe, Florian
Rascoursier, Louis Ledoux, Benjamin Quiédeville, Anastasia Volkova,
Florent de Dinechin, Théo Cantaloube, Clemens Wegener. Other doctoral
students from other teams (/on est tous en la même galère/): Alix
Jeannerot, Guillaume, Aurélien Delarge, Mehdi, Khiem Huynh, Antoine Bonneau,
Julien. Linda Soumari, Cecilia Navarro and Anouchka Ronceray for
tolerating my slowly-improving French. Djurdjura Mehrad, Élise
Denoyelle, Stéphanie Wolska and Morgane Le Prince. Frédéric Le Mouël,
Leonardo Cardoso and Jens Ahrens; Cristoff Ressi, Shawn Silverman, and
Jean-Michel Friedt.

Others, beyond the confines of the lab: Kimberly Hoole, Irène Hontang,
Myriam Boussaboua, Cristina Rottondi, Tomas Poloniecki, Julie Darnat
and Ghis, Alice Aniello, Matti Gardner, Kate Fox, Anna Percy, Judy
Knowles, Matt Rushton, Sally Rushton, Sally Catmull, Ani Cammack, Dave
Rushton, Andreas Friberg, Louise Smith, Greg Chick, Anca Diana Axinia,
Francesco Ganis, Razvan Paisa, Scott Naylor, Mike Croft, Alex Calgaro,
Laura Armstrong and Mahmoud Nadda.

I owe you all an enormous debt of gratitude.

Tommy

* Abstract
:PROPERTIES:
:UNNUMBERED: notoc
:END:

#+begin_abstract
This is what my work is about
#+end_abstract

* Introduction
:PROPERTIES:
:UNNUMBERED: t
:CUSTOM_ID: sec:intro
:END:

Hi there; let's go.

* Networked Audio
#+latex: \minitoc
#+latex: \newpage

\lettrine{A}{udio transmission} over packet-switched networks has
become the /de facto/ standard for a variety of applications over the
past three decades. Replacing the previous generation of cumbersome,
point-to-point installations, it was digital telephony and
videoconferencing that first embraced audio (and video) over the
internet protocol (IP) suite\nbsp[cite:@turlettiINRIA1994] and the
broadcast industry that pioneered audio over
ethernet\nbsp[cite:@bakkerIntroduction2014].

** Computer Networking



*** Ethernet
Ethernet is a thing\nbsp[cite:@metcalfeEthernet1976]

*** WiFi

** The Internet Protocol Suite and the OSI Model

** Network Protocols

*** User Datagram Protocol

*** Internet Group Management Protocol

** Audio Over Computer Networks

*** JackTrip

*** NetJack

*** Audio Over OSC

*** Audio Video Bridging

*** AES67

*** Dante

*** NetJUCE

** The Need for a New Protocol

* Developing Digital Audio Systems
#+latex: \minitoc
#+latex: \newpage

** Embedded Audio Systems

*** Embedded Linux Systems

**** Raspberry Pi

**** Bela

**** Elk

*** Microcontroller Development Boards

**** ESP32

**** STM32

**** Teensy

**** PlatformIO

*** Field Programmable Gate Arrays

**** The SyFaLa Toolchain

** The Faust Programming Language

** Audio Plugins

*** Jules's Utility Class Extensions

*** The Clever Audio Plugin Format

* Time Exchange

\begin{chapquote}{Douglas Adams, \emph{The Hitchhiker's Guide to the Galaxy}}
Time is an illusion; lunchtime doubly so.
\end{chapquote}

#+begin_chapquote :by "Douglas Adams" :from "The Hitchhiker's Guide to the Galaxy"
Time is an illusion; lunchtime doubly so.
#+end_chapquote

#+latex: \minitoc
#+latex: \newpage

\lettrine{C}{onsider} a tuning fork, a steel, two-pronged resonator
which, when struck, vibrates at a reliable frequency. Just how
reliable is this frequency when all is said and done? Frequency, given
in \unit{\hertz}, can be said to describe the number of times a given
event occurs in one second. And how is a second defined? In terms of
the duration required for a caesium atom to vibrate a certain number
of times. So, frequency is defined in terms of time, and time in terms
of frequency; it appears that we have a tautology on our
hands. Indeed, this is an inescapable reality by which we are faced
when we wrestle intimately with time, that most illusory of concepts.

Returning to our tuning fork, each time it is struck, the steel from
which it is manufactured will deform ever so slightly. Some of the
physical energy imparted to it by the blow against a hard surface will
be transduced to heat, which changes the physical behaviour of its
material. Strike it on a cold day and it will vibrate more quickly
than on a hot day. And that is not even to mention the device against
which it was calibrated on the day it was manufactured. In short, a
tuning fork designed to produce a reliable \qty{440}{\hertz} frequency
/does not/, /has never/, and /will never/ produce precisely that
frequency. Indeed, given that atomic clocks are /only/ accurate to parts
per trillion, the very idea of the quantity \qty{440}{\hertz} is far
from perfectly-defined.

Time in computer systems is, of course, subject to the same
vagaries. It is in fact something like a tuning fork that describes
the idea of time in the vast majority of digital systems. A crystal
oscillator (XO), is a sliver of piezoelectric quartz mineral or
ceramic, and, like a tuning fork, on receiving some energy (in this
case electrical) as input, vibrates at a more-or-less reliable
frequency. How accurate this frequency is (setting aside the
fallibility of the definition of a second) is typically defined in
/parts-per-million/ (ppm); a XO with a tolerance of 10 ppm can
reasonably be expected to vibrate up to 0.001 % faster or slower than
the frequency to which it is rated. Thus a 10 ppm XO manufactured to
vibrate at \qty{1}{\mega\hertz} my be expected to produce a frequency,
\(f\), in the range

#+NAME: eq:freq-range
\begin{equation}
999\,990 \leq f \leq 1\,000\,010\;.
\end{equation}
If, to the (audio) engineer's eye, those figures suddenly don't look
so reliable after all, that is entirely understandable. What of the
purity, the /truth/ of the audio sampling rate? Indeed, an audio system
governed by a 10 ppm XO, running at a nominal sampling frequency of
\qty{48}{\kilo\hertz} may run as slow as \(f_{s_{1}} =
\)\qty{47999.52}{\hertz} or as fast as \(f_{s_{2}} =
\)\qty{48000.48}{\hertz}. Is this sort of difference perceptible? By
way of context, that difference is analogous to having two A_{4} tuning
forks, one producing a frequency of \qty{439.9956}{\hertz} and another
at \qty{440.0044}{\hertz}, so a difference of less than one hundredth
of a cycle per second; this falls far, far below the /just noticeable
difference/ threshold for human pitch perception. The audio engineer
notes, however, that the devices running at \(f_{s_{1}}\) and \(f_{s_{2}}\)
will, after one second, be out of sync by roughly the duration of one
full audio sample; the sum two audio signals, \(x_{1}[n]\) and \(x_{2}[n]\),
where \(x_{2}[n] = x_{1}[n-1]\) is a one-zero low-pass filter.

** Network Protocols for Time Exchange

*** Network Time Protocol

*** Precision Time Protocol

** Media Clock Recovery

** Presentation Time Recovery

* Sound Field Synthesis
#+latex: \minitoc
#+latex: \newpage

** Psychoacoustics and Sound Localisation

*** Interaural Level Difference

*** Interaural Time Difference

** General Principles of Sound Field Synthesis

** Periphony

*** Stereo

*** Surround Sound

*** Binaural Reproduction

** Wave Field Synthesis

*** Virtual Sound Sources

*** Focused Sound Sources

*** Plane Waves

** Ambisonics

*** Higher Order Ambisonics

*** Spherical Microphone Arrays

*** Ambisonics Encoding and Decoding
** State of the Art

*** Economic and Financial Considerations

* Development
#+latex: \minitoc
#+latex: \newpage
** The Ananas Protocol
*** The Ananas Audio Protocol
*** The Ananas Authority Description Protocol
*** The Ananas Client Description Protocol
** Supporting Software Systems
*** Audio Plugins
**** The Ananas Audio Server Plugin
**** The Ananas WFS Plugin
**** The Ananas Ambisonics Plugin
*** DSP Algorithms
**** The Distributed WFS Algorithm
**** The Distributed Ambisonics Decoder

* Evaluation
#+latex: \minitoc
#+latex: \newpage
** Case Studies
* Conclusion
#+latex: \minitoc
#+latex: \newpage

#+print_bibliography:

* Local Variables                                                  :noexport:

- Add the /thesis/ document class.
- Don't output the title; that's handled by =frontmatter.tex=.
- Add some export headline filters (see =.dir-locals.el=). 

# Local Variables:
# org-latex-classes: (("thesis" "\\documentclass[a4paper, 12pt, table,
# twoside]{book}
# [NO-DEFAULT-PACKAGES]"
# ("\\chapter{%s}" . "\\chapter*{%s}")
# ("\\section{%s}" . "\\section*{%s}")
# ("\\subsection{%s}" . "\\subsection*{%s}")
# ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
# ("\\paragraph{%s}" . "\\paragraph*{%s}")
# ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# org-latex-title-command: nil
# org-export-filter-headline-functions: (tar/acks-as-section
# tar/abstract-as-section tar/intro-in-toc)
# End:

# LocalWords: transduced periphony ambisonics microcontroller datagram
