#+title: A Sample-Synchronous Distrisbuted Audio System for Spatial and Immersive Applications
#+author: Thomas Albert Rushton

#+options: toc:nil
#+export_file_name: out/thesis
#+latex_class: thesis
#+cite_export: biblatex
#+latex_header_extra: \RequirePackage[]{./out/thesis}

#+include: "frontmatter.tex" src latex

* About                                                            :noexport:

Org file describing my PhD thesis.

* LaTeX Setup                                                      :noexport:
:PROPERTIES:
:header-args: :tangle out/thesis.sty :results silent :noeval
:END:

** Provide the package

#+begin_src latex
\ProvidesPackage{thesis}
#+end_src

** Packages

*** Graphics

#+begin_src latex
\usepackage[dvipsnames]{xcolor}
\usepackage{geometry}
\usepackage{graphicx}
#+end_src

*** Colours

#+begin_src latex
\definecolor{tabED}{rgb}{0.90, 0.87, 0.93}
\definecolor{txtED}{rgb}{0.60, 0.28, 0.02}
\definecolor{siteED}{rgb}{0.04, 0.27, 0.47}
#+end_src

*** Typography

The main serif typeface.

#+begin_src latex
\usepackage[cmintegrals,cmbraces]{newtxmath}
\usepackage{ebgaramond-maths}
\usepackage[T1]{fontenc}
#+end_src

A nicer sans-serif typeface.

#+begin_src latex
\usepackage{helvet}
#+end_src

A nicer monospaced typeface.

#+begin_src latex
\usepackage{inconsolata}
#+end_src

Just all-round better typography.

#+begin_src latex
\usepackage{microtype}
#+end_src

Fancy characters (typically) at the beginning of chapters.

#+begin_src latex
\usepackage{lettrine}
#+end_src

**** Quotes

#+begin_src latex
\makeatletter
\newenvironment{chapquote}[2][2em]
{\setlength{\@tempdima}{#1}%
  \def\chapquote@author{#2}%
  \parshape 1 \@tempdima \dimexpr\textwidth-2\@tempdima\relax%
\itshape}
{\par\normalfont\hfill--\ \chapquote@author\hspace*{\@tempdima}\par\bigskip}
\makeatother
#+end_src

*** Tables

#+begin_src latex
\usepackage{booktabs}
#+end_src

*** Maths

#+begin_src latex
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{amsfonts}
#+end_src

*** Units

#+begin_src latex
\usepackage{siunitx}
\sisetup{
  mode=match,
  per-mode=symbol
}
#+end_src

*** References

#+begin_src latex
\usepackage[noabbrev,capitalise]{cleveref}
\usepackage{hyperref}
\hypersetup{
  colorlinks,
  linkcolor=black
}
#+end_src

* Export hooks                                                     :noexport:


#+bind: org-export-filter-headline-functions (tar/acks-as-section tar/abstract-as-section tar/intro-in-toc)

** Acknowledgements & Abstract as sections, not chapters

#+begin_src emacs-lisp :results none
(defun tar/acks-as-section (headline backend info)
  "Export Acknowledgements heading as \\section instead of \\chapter."
  (when (org-export-derived-backend-p backend 'latex)
    (replace-regexp-in-string
     "\\\\chapter\\*{\\(Acknowledgements\\)}"
     "\\\\section*{\\1}"
     headline)))
#+end_src

#+begin_src emacs-lisp :results none
(defun tar/abstract-as-section (headline backend info)
  "Export Abstract heading as \\section instead of \\chapter; put it on a new page too."
  (when (org-export-derived-backend-p backend 'latex)
    (replace-regexp-in-string
     "\\\\chapter\\*{\\(Abstract\\)}"
     "\\\\newpage
\\\\section*{\\1}"
     headline)))
#+end_src

** Add Introduction to contents

#+begin_src emacs-lisp :results none
(defun tar/intro-in-toc (headline backend info)
  "Add the Introduction to the table of contents."
  (when (org-export-derived-backend-p backend 'latex)
    (replace-regexp-in-string
     "\\(\\\\label{sec:intro}\\)"
     "\\1
\\\\addcontentsline{toc}{chapter}{\\\\nameref{sec:intro}}"
     headline)))
#+end_src

** Lettrine at the start of each chapter

# #+bind: org-export-before-parsing-functions (tar/lettrine-after-h1)
# #+begin_src emacs-lisp :results none
# (defun tar/lettrine-after-h1 (backend)
#   "Add lettrine to first paragraph after each level-1 headline."
#   (when (org-export-derived-backend-p backend 'latex)
#     (org-element-map (org-element-parse-buffer) 'headline
#       (lambda (headline)
#         (when (and (eq (org-element-property :level headline) 1)
#                    (not (org-element-property :UNNUMBERED headline)))
#           (let ((target-para
#                  (cl-loop for child in (org-element-contents
#                                         (car (org-element-contents headline)))
#                           when (eq (org-element-type child) 'paragraph)
#                           return child)))
#             (when target-para
#               (let* ((begin (org-element-property :contents-begin target-para))
#                      (end (org-element-property :contents-end target-para))
#                      (text (buffer-substring begin end))
#                      (first-char (substring text 0 1))
#                      (rest-of-word
#                       (and (string-match "^.\\([a-zA-Z]*\\)" text)
#                            (match-string 1 text)))
#                      (remainder
#                       (substring text (+ 1 (length rest-of-word)))))
#                 (goto-char begin)
#                 (delete-region begin end)
#                 (insert (format "@@latex:\\lettrine{%s}{%s}@@%s"
#                                 first-char
#                                 rest-of-word
#                                 remainder))))))))))
# #+end_src

* Acknowledgements
:PROPERTIES:
:UNNUMBERED: notoc
:END:

Thanks, y'all.

* Abstract
:PROPERTIES:
:UNNUMBERED: notoc
:END:

#+begin_abstract
This is what my work is about
#+end_abstract

* Introduction
:PROPERTIES:
:UNNUMBERED: t
:CUSTOM_ID: sec:intro
:END:

Hi there; let's go.

* Computer Networking

Computer networks are a thing\nbsp[cite:@metcalfeEthernet1976]

* Time

#+begin_quote
Time is an illusion; lunchtime doubly so.
#+end_quote

Consider a tuning fork, a steel, two-pronged resonator which, when
struck, vibrates at a reliable frequency. Just how reliable is this
frequency when all is said and done? Frequency, given in
\unit{\hertz}, can be said to describe the number of times a given
event occurs in one second. And how is a second defined? In terms of
the duration required for a caesium atom to vibrate a certain number
of times. So, frequency is defined in terms of time, and time in terms
of frequency; it appears that we have a tautology on our
hands. Indeed, this is an inescapable reality by which we are faced
when we wrestle intimately with time, that most illusory of concepts.

Returning to our tuning fork, each time it is struck, the steel from
which it is manufactured will deform ever so slightly. Some of the
physical energy imparted to it by the blow against a hard surface will
be transduced to heat, which changes the physical behaviour of its
material. Strike it on a cold day and it will vibrate more quickly
than on a hot day. And that is not even to mention the device against
which it was calibrated on the day it was manufactured. In short, a
tuning fork designed to produce a reliable \qty{440}{\hertz} frequency
/does not/, /has never/, and /will never/ produce precisely that
frequency. Indeed, given that atomic clocks are /only/ accurate to
parts per quadrillion, the very idea of the quantity \qty{440}{\hertz}
is far from perfectly-defined.

Time in computer systems is, of course, subject to the same
vagaries. It is in fact something like a tuning fork that describes
the idea of time in the vast majority of digital systems. A crystal
oscillator (XO), is a sliver of piezoelectric quartz mineral and, like
a tuning fork, on receiving some energy (in this case electrical) as
input, vibrates at a more-or-less reliable frequency. How accurate
this frequency is (setting aside the fallibility of the definition of
a second) is typically defined in /parts-per-million/ (ppm); a XO with a
tolerance of 10 ppm can reasonably be expected to vibrate up to 0.001
% faster or slower than the frequency to which it is rated. Thus a 10
ppm XO manufactured to vibrate at \qty{1}{\mega\hertz} my be expected
to produce a frequency, \(f\), in the range

#+NAME: eq:freq-range
\begin{equation}
999\,990 \leq f \leq 1\,000\,010
\end{equation}
If, to the (audio) engineer's eye, those figures suddenly doesn't look
so reliable after all, that is entirely understandable. What of the
purity, the /truth/ of the audio sampling rate? Indeed, an audio system
governed by a 10 ppm XO, running at a nominal sampling frequency of
\qty{48}{\kilo\hertz} may run as slow as \qty{47999.52}{\hertz} or as
fast as \qty{48000.48}{\hertz}.

** A Section

*** A Subsection

* Sound Field Synthesis

#+print_bibliography:

* Local Variables                                                  :noexport:

# Local Variables:
# org-latex-classes: (("thesis" "\\documentclass[a4paper, 12pt, table]{book}
# [NO-DEFAULT-PACKAGES]"
# ("\\chapter{%s}" . "\\chapter*{%s}")
# ("\\section{%s}" . "\\section*{%s}")
# ("\\subsection{%s}" . "\\subsection*{%s}")
# ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
# ("\\paragraph{%s}" . "\\paragraph*{%s}")
# ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# org-latex-title-command: nil
# org-export-allow-bind-keywords: t
# End:

# LocalWords transduced
