#+title: Emacs Config
#+property: header-args :tangle ~/.emacs.d/org-init.el :noeval

I aim to migrate my existing config, managed with [[https://www.chezmoi.io/][chezmoi]], to this
file. In the meantime, I tangle it to file that I then load from
=init.el=. For more config, see [[file:early-init.org][early init]].

* Inspo

- https://codeberg.org/mehrad/.emacs.d
- https://protesilaos.com/emacs/dotemacs

* Global modes

** Visual line mode

I work (or aim to) with buffers whose lines aren't so long that they
need to wrap, so I disable =visual-line-mode=.

#+begin_src emacs-lisp
(global-visual-line-mode -1)
#+end_src

* Emacs Itself

#+begin_src emacs-lisp
(use-package emacs
  :ensure nil
  :init
  (setq-default
#+end_src

** Default mode & scratch message

Use Org Mode by default.

#+begin_src emacs-lisp
   major-mode 'org-mode
   initial-major-mode 'org-mode
#+end_src

A cheery, informative message for the scratch buffer.

#+begin_src emacs-lisp
   initial-scratch-message "\
,#+begin_quote
This buffer is for notes that are not saved. it is in Org-mode so all
Org keybindings work. For example, to create a code block, use ~C-c
C-,~, and select a language. Enter ~C-c C-c~ and the result will be
inserted below the source block.
,#+end_quote

"
#+end_src

** Line truncation

I'm not a fan of continuation lines; if a line is longer than the
viewport allows, I'll move the cursor to the right.

#+begin_src emacs-lisp
    truncate-lines t
#+end_src

If necessary, I can toggle from truncation to continuation with =C-x x
t=.

** Shell

Make sure shell commands run interactively, so profile/config gets
loaded and thus the correct ~PATH~.

#+begin_src emacs-lisp
    shell-command-switch "-ic"
#+end_src

** Finish up

Close ~setq-default~ and ~use-package~.

#+begin_src emacs-lisp
))
#+end_src

* Org Mode

#+begin_src emacs-lisp
(use-package org
  :ensure nil
  :config
#+end_src

** Initial Folding State

I like to fold everything by default; this can be overridden with,
e.g., ~#+startup: nofold~.

#+begin_src emacs-lisp
(setq org-startup-folded 'fold)
#+end_src

** Finish up

#+begin_src emacs-lisp
)
#+end_src

* Window-switching

Let's try the =ace-window= package.

#+begin_src emacs-lisp
(use-package ace-window
  :ensure t
  :config
  (global-set-key (kbd "M-o") 'ace-window)
  (setq aw-dispatch-always t))
#+end_src

* Appearance

** Custom faces

#+begin_src emacs-lisp
(custom-set-faces
#+end_src

*** Org mode

Add some extra contrast to source blocks.

#+begin_src emacs-lisp
'(org-block-begin-line ((t (:inherit org-block-begin-line
                                     :extend t
                                     :underline nil))))
'(org-block-end-line ((t (:inherit org-block-end-line
                                   :extend t
                                   :overline nil
                                   :underline nil))))
#+end_src

*** Flyspell

Make spelling errors really pop.

#+begin_src emacs-lisp
'(flyspell-incorrect ((t (:inverse-video t))))
#+end_src

*** Finish up

Close ~custom-set-faces~.

#+begin_src emacs-lisp
)
#+end_src

* Org Mode

#+begin_src emacs-lisp
(use-package org
  :ensure nil
  :config
#+end_src

** Structure templates

*** Shell

#+begin_src emacs-lisp
(add-to-list 'org-structure-template-alist
             '("b" . "src shell :results output :exports both"))
(add-to-list 'org-structure-template-alist
             '("B" . "src shell :noeval"))
#+end_src

*** R

Feels like I'm very unlikely to use these...

#+begin_src emacs-lisp
(add-to-list 'org-structure-template-alist
             '("r" . "src R :results output :session *R* :exports both"))
(add-to-list 'org-structure-template-alist
             '("R" . "src R :results output graphics :file (org-babel-temp-file \"figure\" \".png\") :exports both :width 600 :height 400 :session *R*"))
(add-to-list 'org-structure-template-alist
             '("RR" . "src R :results output graphics :file  (org-babel-temp-file (concat (file-name-directory (or load-file-name buffer-file-name)) \"figure-\") \".png\") :exports both :width 600 :height 400 :session *R*"))
#+end_src

*** Python

#+begin_src emacs-lisp
(add-to-list 'org-structure-template-alist
             '("p" . "src python :results output :exports both"))
(add-to-list 'org-structure-template-alist
             '("P" . "src python :results output :session :exports both"))
(add-to-list 'org-structure-template-alist
             '("PP" . "src python :results file :session :var matplot_lib_filename=(org-babel-temp-file \"figure\" \".png\") :exports both
import matplotlib.pyplot as plt

import numpy
x=numpy.linspace(-15,15)
plt.figure(figsize=(10,5))
plt.plot(x,numpy.cos(x)/x)
plt.tight_layout()

plt.savefig(matplot_lib_filename)
matplot_lib_filename"))
#+end_src

*** Emacs Lisp

#+begin_src emacs-lisp
(add-to-list 'org-structure-template-alist
             '("m" . "src emacs-lisp"))
#+end_src

*** Graphviz

Do I really need this one? [[https://graphviz.org/gallery/][Graphviz]] is ghastly.

#+begin_src emacs-lisp
(add-to-list 'org-structure-template-alist
             '("g" . "src dot :results output graphics :file \"/tmp/graph.pdf\" :exports both
digraph G  {
node [color=black,fillcolor=white,shape=rectangle,style=filled,fontname=\"Helvetica\"];
A[label=\"A\"]
B[label=\"B\"]
A->B
}"))
#+end_src

*** Faust

#+begin_src emacs-lisp
(add-to-list 'org-structure-template-alist
	     '("f" . "src faust"))
(add-to-list 'org-structure-template-alist
	     '("fh" . "src faust :results html :exports both :tab svg :sizes 0,100"))
(add-to-list 'org-structure-template-alist
	     '("fs" . "src faust :results file svg :file process.svg :exports both"))
#+end_src

I really need to do something at some point (in =ob-faust=) about that
whole ~file svg~ situation.

*** Julia

#+begin_src emacs-lisp
(add-to-list 'org-structure-template-alist
	     '("j" . "src julia"))
(add-to-list 'org-structure-template-alist
	     '("J" . "src julia :session :results output"))
(add-to-list 'org-structure-template-alist
	     '("JJ" . "src julia :session :results file graphics :file plot.png :output-dir figs"))
#+end_src

*** typst

#+begin_src emacs-lisp
(add-to-list 'org-structure-template-alist '("t" . "export typst"))
#+end_src

** Conclude

Close ~use-package org~

#+begin_src emacs-lisp
)
#+end_src

** Export

*** Typst

#+begin_src emacs-lisp
(use-package ox-typst
  :ensure t
  :after org)
#+end_src

* TODO Use ~setopt~ for ~defcustom~ variables

...so any assigned callbacks are invoked ([[https://emacsredux.com/blog/2025/04/06/goodbye-setq-hello-setopt/][source]]).
